### ISSUE TITLE
vich_uploader_asset not rendering https

### ISSUE THREAD

**Issue by kcaporaso** [dustin10/VichUploaderBundle#1003]
|    Q        |   A
|------------ | -----
| Version     | 1.8.6

### Support Question

Hello,
I'm using the following to render an image in twig:

```<img class="img-responsive" src="{{ vich_uploader_asset(blog, 'imageFile') | imagine_filter('blog_footer_thumb') }}" />```

However, on a site using https the images are not being loaded over https, they seemed to be locked into http (non SSL).  Is there a configuration setting to force the https or at least load the images over what the current protocol is?  Obviously this is causing mixed content warnings in the browser.

I've not been able to find a solution on SO or a general Google search.
Thanks,
Kevin

**Comment by garak** [comment]
Please provide your version in `x.y.z` format

**Comment by kcaporaso** [comment]
@garak updated original post, but it's returning:  1.8.6

```
composer show vich/uploader-bundle
name     : vich/uploader-bundle
descrip. : Ease file uploads attached to entities
keywords : file uploads, upload
versions : * 1.8.6
type     : symfony-bundle
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/dustin10/VichUploaderBundle.git 5cd1b931a3acc2fcb5cf51e4a2ff4559b19ab0c6
dist     : [zip] https://api.github.com/repos/dustin10/VichUploaderBundle/zipball/5cd1b931a3acc2fcb5cf51e4a2ff4559b19ab0c6 5cd1b931a3acc2fcb5cf51e4a2ff4559b19ab0c6
path     : /private/var/www/www.vspdirect.com/vendor/vich/uploader-bundle
names    : vich/uploader-bundle
```

**Comment by garak** [comment]
What if you try to remove `imagine_filter`?

**Comment by kcaporaso** [comment]
@garak ah crud, it's that filter causing the issue.  When I remove imagine_filter vich_uploader_asset() does the right thing, sorry for the false alarm.  I guess I'll move the issue over to their github world.
