### ISSUE TITLE
[Cache] Directory does not exist

### ISSUE THREAD

**Issue by ahmed-bhs** [dustin10/VichUploaderBundle#1004]
I'm facing the following error message:

>  The directory "/home/codein/delabie-pp/ezplatform/var/cache/dev/vich_uploader" does not exist.

This error happens ONLY during new deployments (new releases are reachable only after cache:clear).

**Comment by garak** [comment]
Well, you're supposed to clear your cache every time you deploy

**Comment by ahmed-bhs** [comment]
I'm already getting the exception after cache:clearing, this my after deploy script:
```
php bin/console bazinga:js-translation:dump web/assets --merge-domains
php bin/console kaliop:migration:migrate -n
php bin/console doctrine:migration:migrate -n
php bin/console cache:clear
php bin/console cache:pool:clear cache.redis
php bin/console assets:install web --symlink --relative
php bin/console assetic:dump
```

Any help would be appreciated.

**Comment by garak** [comment]
Are you forcing `prod` environment? (You should)

**Comment by ahmed-bhs** [comment]
It's a dev environment. Actually.

**Comment by garak** [comment]
bundle version?

**Comment by ahmed-bhs** [comment]
v1.9.2

**Comment by garak** [comment]
Can you reproduce the same problem on your local dev environment?

**Comment by garak** [comment]
Closing for missing feedback

**Comment by digitaltim-de** [comment]
Same probem...

**Comment by remoteclient** [comment]
Same problem on Symfony 5.2. After `clear:cache` I get `  The directory "/var/www/html/devapi.bmoffice24.de/var/cache/dev/vich_uploader" does not exist. `

**Comment by garak** [comment]
See #1161
