### ISSUE TITLE
Event class causes Symfony 4.3 deprecation notices

### ISSUE THREAD

**Issue by nem75** [dustin10/VichUploaderBundle#1006]
Hi,

since Sf 4.3 arrived testing apps which use this bundle, e.g. with WebTestCase cases, leads to this deprecation notice which breaks the build:

```
  1x: The "Vich\UploaderBundle\Event\Event" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.
```

Will this be addressed in the near future?

**Comment by garak** [comment]
It will be fixed in the next days. Of course, you can propose a PR if you mind.
By the way: your build should **not** fail in case of deprecations due to vendors.

**Comment by garak** [comment]
As you can see in related commit, it looks like my solution is not working in some cases.
What do you think?
