### ISSUE TITLE
Bad dispatch in UploadHandler

### ISSUE THREAD

**Issue by ngilain** [dustin10/VichUploaderBundle#1018]
### Bug Report

Since the last tag, the upload on several of our projects are broken due to a mistake in the call of the Symfony dispatcher.

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.10.0

#### Summary

When trying to upload some file on a Symfony 3.4 project, this error message appears : 

`Type error: Argument 2 passed to Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event or null, string given, called in /home/wwwroot/scp/vendor/vich/uploader-bundle/Handler/UploadHandler.php on line 110`  

The fact is that the recently added test to manage both versions of Symfony dispatch is ok, but the dispatch themselves are inverted in the if/else.

For instance on my project in Symfony 3.4, the code go on line https://github.com/dustin10/VichUploaderBundle/blob/1.10.0/Handler/UploadHandler.php#L110 which generate the bug as the call should be 

```php
$this->dispatcher->dispatch($eventName, $event);
```

Best regards

**Comment by garak** [comment]
Do you have Symfony contracts in vendors?

**Comment by ngilain** [comment]
Yes in version 1.1.5

**Comment by garak** [comment]
Please try to require `^1.10@dev-fix-dispatcher` and see if it works

**Comment by ngilain** [comment]
Thank you for your quick answer.

The bundle looks operationnal again with these corrections.

Do you plan to tag it soon ?

**Comment by garak** [comment]
Immediately
