### ISSUE TITLE
Image won't upload in OneToOne relation?

### ISSUE THREAD

**Issue by kurokami98** [dustin10/VichUploaderBundle#1019]
I have two entity which is StudentAccount and StudentProfile and their relationship is One-To-One. Each of them have their own image property and name.

The problem is:

> When i fetch the StudentProfile through $studentAccount->getStudentProfile() method and use its set method to set image, the image won't upload. It show no error after submit.

My controller, entity and vich_uploader.yaml: [Press here](https://hackmd.io/@CMtVeFnOS_-T-2PoRppDdA/BJ1OrAVbB)

Any clue about this?

**Comment by garak** [comment]
This is just wrong:
```
$file = $request->files->get('studentProfileImage');
$user->setProfilePictureFile($file);
```
Please read documentation and follow it

**Comment by kurokami98** [comment]
> This is just wrong:
> 
> ```
> $file = $request->files->get('studentProfileImage');
> $user->setProfilePictureFile($file);
> ```
> 
> Please read documentation and follow it

Is there another way to use this instead of using Symfony Form Builder? I wonder how to use this for Restful API if i only can stick to the Form Builder?

Oh forgot to mention, i can upload image to StudentAccount, with same pattern:

```
$input = $request->request;
$file = $request->files->get('studentCardImage');
$em = $this->getDoctrine()->getManager();
$user = $em->getRepository(StudentAccount::class)->findOneBy(['id'=>1]);
$user->setStudentCardImage($file);
//...
$em->flush();
```
It works for StudentAccount but not StudentProfile...

**Comment by garak** [comment]
Inject UploadHandler and use `upload` method

**Comment by kurokami98** [comment]
> Inject UploadHandler and use `upload` method

I use the UploadHandler like this:

```
public function updateInfo(Request $request, UploadHandler $uploadHandler)
{
        $input = $request->request;
        $file = $request->files->get('studentCardImage');
        // ...
        $uploadHandler->upload($file, 'studentCardImage');
        //...
}
```

But it throw error after submit

> The class "Symfony\Component\HttpFoundation\File\UploadedFile" is not uploadable. If you use annotations to configure VichUploaderBundle, you probably just forgot to add `@Vich\Uploadable` on top of your entity. If you don't use annotations, check that the configuration files are in the right place. In both cases, clearing the cache can also solve the issue.

I am sure that my entity have the annotation @Vich\Uploadable but i have no clue about this error...

**Comment by garak** [comment]
You need to pass your uploadable object (StudentAccount I guess) as first argument

**Comment by kurokami98** [comment]
> You need to pass your uploadable object (StudentAccount I guess) as first argument

Sorry to ask, i couldn't find any documentation regard to the UploadHandler.. so i actually don't know how to use it in my code :(

Now the code look like this:
```
public function updateInfo(Request $request, UploadHandler $uploadHandler)
{
        $input = $request->request;
        $file = $request->files->get('studentCardImage');
        
        //Get Student Account Entity Object
        $user = $em->getRepository(StudentAccount::class)->findOneBy(['id'=>1]);

        $uploadHandler->upload($user, 'studentCardImage');
        //...
}
```

And now how should i upload my image? Put setStudentCardImage( ) / setImageFile( ) method after upload method? What did UploadHandler have done to my code here?

**Comment by kurokami98** [comment]
I think i had figure out some issue, i go try create a new symfony project and test it out first. Will update here.

**Comment by garak** [comment]
Indeed, we need to properly document such case.
Setting the file before `$uploadHandler->upload($user, 'studentCardImage');` should do the trick

**Comment by kurokami98** [comment]
After i recreate all the entity, now i can upload in both entity (OneToOne) without using UploadHandler.

**Upload image for StudentAccount:**
```
public function updateInfo(Request $request)
{
        $input = $request->request;
        $file = $request->files->get('studentCardImage');
        
        //Get Student Account Entity Object
        $user = $em->getRepository(StudentAccount::class)->findOneBy(['id'=>1]);
        
        // *** it works without using UploadHandler ***
        $user->setStudentCardFile($file);
        
        //...
}
```

**Upload image for StudentProfile:**
```
public function updateProfile(Request $request)
{
        $input = $request->request;
        $file = $request->files->get('studentProfileImage');
        $em = $this->getDoctrine()->getManager();

        $user = $em->getRepository(StudentAccount::class)->findOneBy(['id'=>1]);
        $user = $user->getStudentProfile();
        
        // *** it works without using UploadHandler ***
        $user->setProfilePictureFile($file);
        
       // ...
}
```
I'm not sure what condition trigger the issue but perhaps it is misconfigured at somewhere.


Last question to ask, is it a must to use UploadHandler each time i upload a file? Hope there will have a documentation about UploadHandler so we all can learn more about how it works and what it does.
