### ISSUE TITLE
Override UploaderHelper class

### ISSUE THREAD

**Issue by botjaeger** [dustin10/VichUploaderBundle#1023]
|    Q        |   A
|------------ | -----
| Version     | 1.8.8

### Support Question

Is it possible to override `UploadHelper` class to add some logic and stuffs??

If yes, how can I make it usable on forms? Like easyadminbundle?

Use it as default link generator.

**Comment by garak** [comment]
Try this https://symfony.com/doc/current/service_container/service_decoration.html

**Comment by botjaeger** [comment]
```
pablo.service.custom_uploader_helper:
        class: PabloBundle\Service\CustomUploaderHelper
        decorates: vich_uploader.templating.helper.uploader_helper
        arguments: ['@pablo.service.custom_uploader_helper.inner']
```

already did this, but I'm getting this TypeError on `UploaderExtension`

```
Type error: Argument 1 passed to Vich\UploaderBundle\Twig\Extension\UploaderExtension::__construct() must be an instance of Vich\UploaderBundle\Templating\Helper\UploaderHelper, instance of PabloBundle\Service\CustomUploaderHelper given
```

**Comment by garak** [comment]
Your custom helper should extends bundle's helper

**Comment by botjaeger** [comment]
Helper class? like `Symfony\Component\Templating\Helper\Helper`
or `Vich\UploaderBundle\Templating\Helper\UploaderHelper` class

**Comment by garak** [comment]
As written in your error message, **must be an instance of `Vich\UploaderBundle\Templating\Helper\UploaderHelper`**

**Comment by botjaeger** [comment]
I tried `Symfony\Component\Templating\Helper\Helper` still getting the same error,
but on `Vich\UploaderBundle\Templating\Helper\UploaderHelper` no error but my logic/changes does not show

**Comment by botjaeger** [comment]
```
class CustomUploaderHelper extends UploaderHelper
{
    private $helper;

    public function __construct(UploaderHelper $helper)
    {
        $this->helper = $helper;
        parent::__construct($helper->storage);
    }

    /**
     * Gets the public path for the file associated with the
     * object.
     *
     * @param object|array $obj       The object
     * @param string       $fieldName The field name
     * @param string       $className The object's class. Mandatory if $obj can't be used to determine it
     *
     * @return string|null The public asset path or null if file not stored
     */
    public function asset($obj, string $fieldName, ?string $className = null)
    {
        return 'asd' . $this->helper->asset($obj, $fieldName, $className);
    }

    /**
     * Returns the canonical name of this helper.
     *
     * @return string The canonical name
     */
    public function getName(): string
    {
        return 'vich_uploader';
    }
}
```

**Comment by botjaeger** [comment]
the code works via `DependencyInjection`

```
public function testAction(UrlHelperService $service)
    {
        $user = $this->getDoctrine()->getRepository(User::class)->find(1);

        $data = $service->generateUrl($user, 'profilePictureFile');
        return $this->json([$data]);
    }
```

returns 

```
[
    "asdhttps://s3-ap-southeast-1.amazonaws.com/propertypro/development/user_files/b0e34ae5bfcf98"
]
```

**Comment by botjaeger** [comment]
and on original `UploaderHelper`

```
use Vich\UploaderBundle\Templating\Helper\UploaderHelper;

class TestController extends BaseController
{
    public function testAction(UploaderHelper $service)
    {
        $user = $this->getDoctrine()->getRepository(User::class)->find(1);

        $data = $service->asset($user, 'profilePictureFile');
        return $this->json([$data]);
    }
}
```

**Comment by botjaeger** [comment]
![image](https://user-images.githubusercontent.com/17152065/62522995-76738280-b865-11e9-9f75-5c12875c3521.png)

but on forms it seems not working or not calling the decorated `UploaderHelper`


![image](https://user-images.githubusercontent.com/17152065/62523069-94d97e00-b865-11e9-892e-9b6cf4b006df.png)

**Comment by garak** [comment]
Try to remove call to parent's constructor in your constructor

**Comment by botjaeger** [comment]
still the same, still no `asd` prefix on generated url

**Comment by garak** [comment]
I'm trying to understand what you expect, since you didn't provide details: it looks like you're using `VichImageType` in your form and you want to customize your uploaded image path.
Is it correct?

**Comment by botjaeger** [comment]
this is what I want to achieve,

we have two kinds of files/images uploaded on our end, 

1. the one with `filename.ext`
2. the new one that saves the `mediaId` (as the one on the screenshot)

we are able to generate URL on files/images of those with `filename.ext`
but on `mediaID` we have another service for that, and that service is what I'm trying to implement/inject on vich's `UploaderHelper` class.

decorator seems working fine if called via DependencyInjection and via `$this->get('service_id')`

but on forms it doesn't

**Comment by garak** [comment]
`VichImageType` is not using `UploaderHelper`

**Comment by botjaeger** [comment]
ohhhh,

it uses `StorageInterface`

**Comment by botjaeger** [comment]
I think were using `GaufretteStorage` class so I just decorate it?

**Comment by botjaeger** [comment]
Alright.

I made it work so I'll share this for future googlers

```
class DecorateGaufretteStorage extends GaufretteStorage
{
    /** @var MediaService */
    protected $helper;

    public function __construct(PropertyMappingFactory $factory, FilesystemMap $filesystemMap, string $protocol, MediaService $mediaService)
    {
        $this->helper = $mediaService;

        parent::__construct($factory, $filesystemMap, $protocol);
    }

    public function resolveUri($obj, string $fieldName, ?string $className = null): ?string
    {
        $vichUrl = parent::resolveUri($obj, $fieldName, $className);

        if (empty($vichUrl)) return null;

        if ($this->helper->urlFound($vichUrl)) return $vichUrl;

        $temp = explode('/', $vichUrl);
        $mediaId = end($temp);

        return $this->helper->resolveImageUrl($mediaId, [2000, 2000]);
    }
}
```

service definition

```
pablo.service.decorate_gaufrette_storage:
        class: PabloBundle\Service\DecorateGaufretteStorage
        decorates: vich_uploader.storage.gaufrette
        arguments:
            - '@vich_uploader.property_mapping_factory'
            - '@knp_gaufrette.filesystem_map'
            - 'gaufrette'
            - '@pablo.service.media'
```

take note the `decorates` option, it should use the `service id` of the service you want to decorate 
for it to work.

and this will work on both `VichImageType` and `VichFileType`
also on `UploaderHelper` class for generating URLs

also note that my modification was done on `GaufretteStorage` class which I am using.
