### ISSUE TITLE
Customize display filename on forms

### ISSUE THREAD

**Issue by botjaeger** [dustin10/VichUploaderBundle#1025]
|    Q        |   A
|------------ | -----
| Version     | 1.8.8

### Support Question

Hi, I was looking for a way to customize the displayed filename on VichFileType forms like in this image below

![image](https://user-images.githubusercontent.com/17152065/63315173-c1e56080-c33c-11e9-8149-78bf0c9a16cb.png)

I am saving the filename as a `media_id` so when displayed to a form it looks like that, I was wondering if I can customize it by getting the owner's entity and get their property named `fullname` or `title`

(for example) 

`fullname-tax-card.ext`

served as a "virtual name" so that users will not get shocked why their filenames has some random characters displayed on their screens

**Comment by botjaeger** [comment]
I just learned that `easyadmin` uses different form for `vich_image` & `vich_file` types

https://symfony.com/doc/1.x/bundles/EasyAdminBundle/integration/vichuploaderbundle.html#customizing-form-fields-for-image-and-file-uploading

**Comment by garak** [comment]
You can [override bundle's template](https://symfony.com/doc/current/bundles/override.html#templates) or you can use a custom theme (just like easyadmin)

**Comment by botjaeger** [comment]
thank you.
