### ISSUE TITLE
VichUploaderBundle using Gaufrette and Mogilefs

### ISSUE THREAD

**Issue by ratasxy** [dustin10/VichUploaderBundle#103]
Hello.

I have a problem with the URL generated by the bundle, I'm using it to store files MogileFS but this gives me a path like 

http://111.111.111.111:7001/dev1/0/000/000/000/00000004.fid
but to do 
{{vich_uploader_asset (entity, 'file')}}
in twig

returns 345435343.jpg

**Comment by garak** [comment]
Did you configure your `uri_prefix`?

**Comment by garak** [comment]
Closing for missing feedback.
