### ISSUE TITLE
delete_on_remove: false does not work 

### ISSUE THREAD

**Issue by jeansebbaklouti** [dustin10/VichUploaderBundle#1036]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.6.2

#### Summary

Hello,

thanks for the wonderfull work! 
I use VichUploader 1.6.2, with gaufrette 0.5.3 ans S3 as storage (aws/aws-sdk-php": "3.87).

I use the options :  
- delete_on_update: false
- delete_on_remove: false

But when i delete or update a file , the file is deleted from S3.
I need to keep file on S3 and just delete it from database.
Any idea ? 

#### How to reproduce
Install dependency with composer adn create a form
Config:
- delete_on_update: false
- delete_on_remove: false

VichUploaderBundle 1.6.2, 
gaufrette 0.5.3 
aws/aws-sdk-php 3.87.

delete a file from form and check S3 file
-->

#### Expected behavior

The file is deleted from dabatabse and did not from S3.

**Comment by garak** [comment]
You should update at least to version 1.7.1

**Comment by jeansebbaklouti** [comment]
Thank you for the answer. unfortunately i work on a very old application and i cannot use this version.
I will try to find an another way.
