### ISSUE TITLE
Update with new ID

### ISSUE THREAD

**Issue by Kaaly** [dustin10/VichUploaderBundle#1046]
|    Q        |   A
|------------ | -----
| Version     | 1.10.1

### Support Question

I have an entity **Company** link to an **Image** entity which use VichUploader.
Everything is working fine.

The first time i had an image to the company, a new image with an id (e.g 40) is created.
When i update after that the image, that keep the same ID (e.g 40) and update information insteand of creating a new ID.

There is a way to able VichUploader to create a new Image entity on each update ?

**Comment by garak** [comment]
I'm not sure to understand the reason why you want a new object when updating an old one

**Comment by Kaaly** [comment]
Because the entity Image is also link to another entity and when image is update in company entity, it must not change on the other entity

**Comment by garak** [comment]
That's even less clear than your previous statement

**Comment by Kaaly** [comment]
Ok

The entity relationships is :

Company <-> Image <-> Offer

When i update image from company entity i don’t want to update image for the offer which should keep the previous image.

**Comment by garak** [comment]
You can simply avoid to update image: if you don't upload anything, VichUploaderBundle will do nothing

**Comment by Kaaly** [comment]
It's not really that.

I re-explain :
I have a company which can have an image.

I can also create offer. An offer is link to a company and use the same image as the company.
But the offer take the image of the company when it's create but then if i update the company image, it must not update the offer image.

In term of entity relationsihip, it would give that : 
**Create company link to an image :**
Company #1 <=> Image #1

**Create offer link to a company and an image :**
Offer #1 <=> Company #1
Offer #1 <=> Image #1

**Update image company :**
Company #1 <=> Image #2
Offer #1 <=> Image #1 (no change)

**Comment by garak** [comment]
Again, I can't see where this bundle can help with this scenario.
This bundle is just meant to make easier uploading/downloading files inside entities. 
**When** updating an entity is up to you, as well as the choice of updating an entity or not updating it, as well as the choice of which fields/relations update (or not update)

**Comment by Kaaly** [comment]
Ok, I think we can't understand each other. No problem, we'll find a solution on our side.

Thank for your time.
