### ISSUE TITLE
Improve phpunit configuration

### ISSUE THREAD

**Issue by garak** [dustin10/VichUploaderBundle#1050]
Configuration in `phpunit.xml.dist` contains some useless configurations (all the ones that match [default configuration](https://phpunit.readthedocs.io/en/8.4/configuration.html)).
For the sake of simplicity, we should remove them

**Comment by ClementGautier** [comment]
Tell me if you had something else in mind (also I'm quite glad to contribute as I've used the bundle in the past. Keep on the good work)
