### ISSUE TITLE
uri_prefix must be same as upload_destination

### ISSUE THREAD

**Issue by pajasry** [dustin10/VichUploaderBundle#1054]
### Bug Report
|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.10

#### Summary
I have been trying to configure vich_uploader for some pdfs and encountered this bug. Uri_prefix must be the same as upload_destination. Maybe I missed something in the documentation but when I set uri_prefix to upload_destination all thing works great.

#### Current behavior
The file isn't served properly ROUTE not found

#### How to reproduce
Set uri_prefix different from upload_destination

#### Expected behavior
uri_prefix address return desired file

**Comment by garak** [comment]
Documentation says exactly that: you need to configure both values and they need to match.
I'm not sure to understand why you even want different values on that
