### ISSUE TITLE
Allow Symfony 5

### ISSUE THREAD

**Issue by cobyl** [dustin10/VichUploaderBundle#1057]
now is locked in composer...

**Comment by yaroslavche** [comment]
@garak I can't install on clean Symfony 5 project.

```
composer require vich/uploader-bundle:dev-master
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for vich/uploader-bundle dev-master -> satisfiable by vich/uploader-bundle[dev-master].
    - vich/uploader-bundle dev-master requires symfony/form ^3.4.19 || ^4.0 -> no matching package found.
```
Seems that `"symfony/form"` in `composer.json` `require` should also be `"^4.4 || ^5.0"`

**Comment by garak** [comment]
@yaroslavche you're right, I did a search&replace without noticing the different constraint.... my bad

**Comment by garak** [comment]
Should be fixed in 5103c1716dcd50b351bce82a2c05ae22fbf34fbd

**Comment by yaroslavche** [comment]
Yes, I've installed succesfully. But after accept recipe `c:cl` failed and revert composer changes. At least now I can install, and will configure manually. If I'll notice some troubles, I'll let you know in issues.
Many thanks for so incredible quick support! =)

**Comment by tv78-coder** [comment]
So better stay in  <= 4.4 until support for SF5 is stable.

**Comment by garak** [comment]
@tv78-coder this bundle already supports SF5.
I can't speak for other bundles, of course
