### ISSUE TITLE
Symfony5 DataCollector\MappingCollector

### ISSUE THREAD

**Issue by yaroslavche** [dustin10/VichUploaderBundle#1061]
### Bug Report

`\Symfony\Component\HttpKernel\DataCollector\DataCollector` has changes: in \Vich\UploaderBundle\DataCollector\MappingCollector::collect third argument should by nullable Throwable instead Exception.

|    Q        |   A
|------------ | ------
| BC Break    | I think, yes
| Version     | dev-master

#### Summary && Current behavior

```
$ bin/console c:cl
PHP Fatal error:  Declaration of Vich\UploaderBundle\DataCollector\MappingCollector::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Exception $exception = NULL): void must be compatible with Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Throwable $exception = NULL) in /project/path/vendor/vich/uploader-bundle/src/DataCollector/MappingCollector.php on line 56
```

#### How to reproduce

Install clear Symfony5 website-skeleton and add https://github.com/dustin10/VichUploaderBundle/commit/5103c1716dcd50b351bce82a2c05ae22fbf34fbd

#### Expected behavior

Should work

#### Additional
I think this changes affetcts Symfony4 projects, that's why I created a [branch](https://github.com/yaroslavche/VichUploaderBundle/tree/symfony5_fixes) with [commit](https://github.com/yaroslavche/VichUploaderBundle/commit/fee6aff8f64bab73fcf999e3d977a0ab27a56dd1), but don't create a PR.

**Comment by garak** [comment]
Symfony 4 shouldn't be affected since in that version interface method misses third parameter (on purpose, I guess).
I tried with a 4.4 project and it works
So you can open your PR
