### ISSUE TITLE
ClassUtils getClass

### ISSUE THREAD

**Issue by simplyniceweb** [dustin10/VichUploaderBundle#1063]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | "1.10.2"

#### Summary

Argument 1 passed to Vich\UploaderBundle\Util\ClassUtils::getClass() must be an instance of Vich\UploaderBundle\Util\object, instance of App\Entity\Album given, called in /home3/neirb07/public_html/vendor/vich/uploader-bundle/EventListener/Doctrine/BaseListener.php on line 55

#### Current behavior

Argument 1 passed to Vich\UploaderBundle\Util\ClassUtils::getClass() must be an instance of Vich\UploaderBundle\Util\object, instance of App\Entity\Album given, called in /home3/neirb07/public_html/vendor/vich/uploader-bundle/EventListener/Doctrine/BaseListener.php on line 55

#### How to reproduce

I'm not sure how but its working on my local

#### Expected behavior

to work

**Comment by garak** [comment]
I'm afraid that we don't support version "x.y.z"...

**Comment by simplyniceweb** [comment]
> I'm afraid that we don't support version "x.y.z"...

sorry, edited it

**Comment by garak** [comment]
It's not enough: I need actual installed version, not your constraint

**Comment by simplyniceweb** [comment]
> It's not enough: I need actual installed version, not your constraint

done sir its 1.10.2

**Comment by garak** [comment]
I guess that you're using php 7.2 or 7.3

**Comment by simplyniceweb** [comment]
@garak I'm using 7.1 actually sir

http://www.bloomperfumes.net/phpinfo.php

**Comment by garak** [comment]
So I'm not sure how you managed to install that version.
If you use composer to install this bundle, you can't install any version above 1.8.8
Please refer to [docs](https://github.com/dustin10/VichUploaderBundle/blob/master/docs/symfony_support_policy.md)

**Comment by simplyniceweb** [comment]
@garak in my local i'm using 7.2 and hostgator shared host latest version is up to 7.1 only and i'm getting this error, should i downgrade to 1.8.8?

**Comment by garak** [comment]
See https://getcomposer.org/doc/06-config.md#platform
