### ISSUE TITLE
Using a Data Transfer Object

### ISSUE THREAD

**Issue by o-alquimista** [dustin10/VichUploaderBundle#1064]
|    Q        |   A
|------------ | -----
| Version     | 1.11.0

### Support Question

I use DTOs in Symfony Forms instead of Entity classes. I wasn't so sure how was I supposed to implement this bundle in this situation, but I gave it a try. This is how I did it:

Product.php, the Entity
```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $imageName;

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }
}

```

ProductFormModel.php, the DTO
```
<?php

namespace App\Form\Model;

use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use DateTimeImmutable;
use DateTime;

/**
 * A DTO (Data Transfer Object) for the product creation form.
 *
 * @Vich\Uploadable
 */
class ProductFormModel
{
    /**
     * @Assert\NotBlank
     */
    private $imageName;

    /**
     * @var File
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName")
     * @Assert\Image
     */
    private $imageFile;

    /**
     * @var DateTime
     */
    private $updatedAt;

    public function getImageName()
    {
        return $this->imageName;
    }

    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new DateTimeImmutable;
        }
    }
}
```

This is the configuration:
```
vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false

```

Then I create a form field like this:
```
->add('imageFile', VichImageType::class)
```

On the controller, I am retrieving the `$imageName` value from the DTO and setting it to the Entity, then persisting the changes.

I have one problem and one question.

**The problem:**
The property `$imageName` on the DTO is empty, which makes the form submission fail. A violation is being triggered after I submit the form. I have no idea why. I get no other errors. No file is being stored at the specified path.

**The question:**
The property `$updatedAt` is only present in the DTO, so it doesn't map to the database. Should it? I know `inject_on_load` is `false`, but I need to know if it would work if it were `true`.

**Comment by o-alquimista** [comment]
See? imageName is empty, but imageFile contains an `UploadedFile` instance.

![Captura de tela de 2019-11-29 16-16-26](https://user-images.githubusercontent.com/25424263/69887014-9ec73700-12c3-11ea-9709-b8eb81d93b5c.png)

**Comment by garak** [comment]
You need to map both DTO **and**entity
Your entity should contain a reference to a File object, not only to the name

**Comment by o-alquimista** [comment]
And so I changed the Entity to also contain the mapping, but imageName is still `null` when I submit an image.

```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use DateTimeImmutable;
use DateTime;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @Vich\Uploadable
 */
class Product
{
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $imageName;

    /**
     * @var File
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var DateTime
     */
    private $updatedAt;

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new DateTimeImmutable;
        }
    }
}
```

**Comment by garak** [comment]
To be clear: you need double mapping because the mapping for DTO is used in the form (so during upload) while the mapping in Entity is used when reading the entity itself.
So, you can't expect that `$imageName` in Entity is automagically set, you need to set it manually when you transfer informations from DTO to Entity

**Comment by o-alquimista** [comment]
But I did.

> On the controller, I am retrieving the `$imageName` value from the DTO and setting it to the Entity, then persisting the changes.

The problem is that, when I attempt to retrieve the `$imageName` from the DTO, it is `null`.

**Comment by garak** [comment]
I see. I usually get the name from `UploadedFile`, using `getFilename()` method

**Comment by o-alquimista** [comment]
I still don't understand this...

So, when I submit an image, the VichImageType will insert an `UploadedFile` instance in `$imageFile`, right? Does it contain the filename created with the namer I configured? So all I have to do is grab this name (in the controller) and store it in `$imageName` on the Entity? Is that it?

Because I tried this:
```
$product->setImageName($productModel->getImageFile()->getFilename());
```

But the `$imageName` property is still triggering a `NotBlank` violation.

**Comment by o-alquimista** [comment]
OK, I made some progress thanks to that `getFilename()` method. The `$imageName` is being stored now, but the image file itself is not being saved at the configured location.

Do I have to do that manually too, with the `move()` method?

By the way, I can't help but notice the amount of changes I had to make to get this far in configuring the bundle. In previous projects I used my own FileUploader service, and the changes to get that working were much less invasive and without duplication, even when using a DTO.

The thing is that I never handled multiple files on a single Entity. I'm hoping VichUploader makes that easier than writing it myself.

**Comment by garak** [comment]
If image is not saved, you're doing something wrong.
This bundle has to support multiple choices, as pure entity and DTO/entity combination, but if you have some proposal for simplification, feel free to open a PR

**Comment by o-alquimista** [comment]
I don't know what could be wrong this time, there's no error. I'll try this bundle again in the future. Thanks for your help so far.

**Comment by lemorragia** [comment]
@o-alquimista i'm trying the same thing with DTO's...digging up a little bit seems that the main logic about the file processing/field mapping is inside the Handler/*classes* which are called by EventListeners listening to DoctrineEvents.

The field can't be mapped on the object, because inside the DTO class Doctrine is not yet triggered. So if the field is correctly bound with an UplodedFIle instance, it can't be properly handled for upload. I'm looking for a way to make it work, i'll post it here if i find it for future use...maybe a custom EventSubscriber triggering the same flow, but at a Request/Form-submit level will do the job.

**Comment by garak** [comment]
@lemorragia there's nothing blocking from using this bundle with DTOs, I'm using it myself like so since years

**Comment by lemorragia** [comment]
@garak mmmh...could you provide an example? It seems, reading up above, that you manually map the fields in the dto, using UploadableFile functions(getSize, getMimeType) to fill the missing fields...is this correct?

**Comment by garak** [comment]
Define "manually"

**Comment by lemorragia** [comment]
instead of relying on UploadHandler->upload() of the bundle(which, as far as i can see, manages to move the file in the proper directory and fills the configured fields of the given object), do you set the fields in the dto using UploadedFile methods (eg. $this->fileSize = $this->uploadedFile->getSize(), inside the dto)? 

The other way i could see this working could be injecting the storage and handler services of the bundle inside the dto and calling their methods to handle the upload.

**Comment by garak** [comment]
You don't need to do anything manual as long as your object is mapped.
So, if your DTO is mapped, you'll get UploadedFile automatically.
Then, since your Entity is not directly tied to your form, you need to manually pass UploadedFile from DTO to Entity.
Last, your Entity needs to me mapped too, to be able to retrieve your File

**Comment by lemorragia** [comment]
i understand. This method should work, but probably i'm esperiencing something strange as the post author did. I'm probably experiencing some special case: 

the case is of a UserPicture Entity linked OneToOne with a User entity...where the vich-mapped entity is UserPicture, and i'm persisting the User entity, which cascading persists the UserPicture...(but even manually persisting the UserPicture doesn't change the result)

- the entity is properly mapped (the one containing the file)
- the dto is properly mapped
- the "file" field in the entity is properly filled with the UploadedFile instance
- the bundle is loaded and configured
- the bundle EventListener on Doctrine-PrePersist is NOT called (and this is probably where the problem is)...which is very strange

i'll do some digging and see if i find a solution...my bet is on the "isUploadable()" function that does not return true in this case because of the mapping-analysis

**Comment by MarlonAEC** [comment]
So? Could someone post an example (WORKIN EXAMPLE)? Or could they solve the problem in the end? I would really appreciate some example, I am a bit of a beginner in the field. Thanks in advance!!

**Comment by garak** [comment]
> So? Could someone post an example (WORKIN EXAMPLE)? Or could they solve the problem in the end? I would really appreciate some example, I am a bit of a beginner in the field. Thanks in advance!!

State your problem and we'll try to help you.

**Comment by sabat24** [comment]
I have just created new DTO from scratch because I needed to allow user to change his avatar and e-mail without changing rest of `Entity`. You can check your code with my working example.

```php
/**
 * @Vich\Uploadable
 */
final class ProfileDTO
{
    /**
     *
     */
    private $avatar = '';

    /**
     * @Vich\UploadableField(mapping="user_avatar", fileNameProperty="avatar")
     */
    private $avatarFile;

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function setAvatarFile(?File $avatarFile = null): void
    {
        $this->avatarFile = $avatarFile;
    }

    public function getAvatarFile(): ?File
    {
        return $this->avatarFile;
    }

    public static function fromEntity(User $user = null): self
    {
        $self = new self();
        if ($user === null) {
            return $self;
        }
        $self->id = $user->getId();
        $self->avatar = $user->getAvatar();
        $self->avatarFile = $user->getAvatarFile();
        return $self;
    }

    public function toEntity(User $user = null): User
    {
        if ($user === null) {
            $user = new User();
        }
        $user->setAvatar($this->avatar);
        $user->setAvatarFile($this->avatarFile);
        return $user;
    }
}
```

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @Vich\Uploadable
 */
class User implements UserInterface, \Serializable
{
     /**
     * @ORM\Column(type="string", length=50, options={"default": ""})
     */
    private $avatar = '';

    /**
     * @Vich\UploadableField(mapping="user_avatar", fileNameProperty="avatar")
     */
    private $avatarFile;
    
    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }
    
    public function setAvatarFile(?File $avatarFile = null): void
    {
        $this->avatarFile = $avatarFile;

        if (null !== $avatarFile) {
            $this->updatedAt = new DateTimeImmutable();
        }
    }

    public function getAvatarFile(): ?File
    {
        return $this->avatarFile;
    }
}
```

```php
// controller

$user = $this->getUser();
$form = $this->createForm(ProfileType::class, ProfileDTO::fromEntity($user), ['allow_extra_fields' => true]);
$form = $form->handleRequest($request);

if ($form->isSubmitted() && $form->isValid()) {
            /** @var ProfileDTO $dto */
            $dto = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($dto->toEntity($user));
}
```

```php
// profileType

public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => ProfileDTO::class,
            ]
        );
        parent::configureOptions($resolver);
    }
```

**Comment by garak** [comment]
> I have just created new DTO from scratch because I needed to allow user to change his avatar and e-mail without changing rest of `Entity`.

You don't need a DTO for that.
Just use setter methods on your User entity: it will change avatar without changing the rest of entity
