### ISSUE TITLE
How to install in Symfony 5?

### ISSUE THREAD

**Issue by mateuszmalecki** [dustin10/VichUploaderBundle#1065]
I try to start: 
composer require vich/uploader-bundle

I have an error:
Using version ^1.11 for vich/uploader-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vich/uploader-bundle ^1.11 -> satisfiable by vich/uploader-bundle[1.11.0].
    - vich/uploader-bundle 1.11.0 requires symfony/config ^3.4 || ^4.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

What can I do with this?

**Comment by garak** [comment]
As you can see in our releases, there's still no stable release supporting Symfony 5. For now, you need to point version to our branch alias (see our composer.json)

**Comment by garak** [comment]
Just released tag [1.12.0](https://github.com/dustin10/VichUploaderBundle/releases/tag/1.12.0)
