### ISSUE TITLE
Document not up to date with Symfony 5

### ISSUE THREAD

**Issue by gundamftw** [dustin10/VichUploaderBundle#1069]
I'm using Symfony 5 and Flex. After I installed the bundle, it doesn't add the bundle to app/config/bundles.php. I have to manual add it to the file.

In the document here, the bundles path is outdated.

https://github.com/dustin10/VichUploaderBundle/blob/master/docs/installation.md

**Comment by garak** [comment]
Document is already suggesting to use Flex. It doesn't mention that you need execute the recipe.
I guess that you fail to execute recipe you can expect that bundle is not enabled.
We keep the old, pre-Flex, way of enable bundle just for users of old projects

**Comment by garak** [comment]
I added a note about kernel class and made explicit that bundle is automatically enabled only if you execute a recipe.
Is that enough for you?

**Comment by gundamftw** [comment]
I don't know what a recipe is. The thing I did was I installed the bundle, ran a composer command, and then it complains about not being able to read the bundle's yaml file.

The document should also mention about manually adding this line if anything failed, to the app/config/bundles.php file, which format is different from the kernel class in earlier Symfony version.

```
return [
    Vich\UploaderBundle\VichUploaderBundle::class => ['all' => true],
]
```

**Comment by garak** [comment]
The point is that without Flex you need to manually enable any new bundle, while with Flex it's enough to execute the recipes, just like prompted. We can't replicate all Symfony documentation, and if you don't know what is a recipe you probably missed some parts of that.
