### ISSUE TITLE
no extension able to load the configuration for “mappings”

### ISSUE THREAD

**Issue by ag253617** [dustin10/VichUploaderBundle#1076]
Hello

I'm trying to use VichUploaderBundle to handle a file upload. I work with symfony 4. I have a problem in the first step (Step 1: configure an upload mapping).

in the app/config/config.yml file I have:
``
vich_uploader:
    db_driver: orm

mappings:
    property_image:
        uri_prefix: /images/properties
        upload_destination: '%kernel.project_dir%/public/images/properties'
``

But it creates an error:

``
(2/2) FileLoaderLoadException
There is no extension able to load the configuration for "mappings" (in C:\wamp64\www\MonAgence\config/packages/vich_uploader.yaml). 
Looked for namespace "mappings", found "framework", "sensio_framework_extra", "doctrine_cache", "doctrine", "doctrine_migrations", "security", "swiftmailer", "web_profiler", "twig", "monolog", "debug", "maker", "web_server", "doctrine_fixtures", "knp_paginator", "vich_uploader" 
in C:\wamp64\www\MonAgence\config/packages/vich_uploader.yaml (which is loaded in resource "C:\wamp64\www\MonAgence\config/packages/vich_uploader.yaml").
``

I searched the internet but I don't see how to fix it. Do you have an idea?

I added "Vich\UploaderBundle\VichUploaderBundle :: class => ['all' => true]," in config/bundles.php

I think that I see about the Enable the bundle part (https://github.com/dustin10/VichUploaderBundle/blob/master/docs/installation.md#enable-the-bundle). But I don't understand how to do it.

**Comment by garak** [comment]
If it's a new project, you should not use "app" directory

**Comment by ag253617** [comment]
Hello,
Thank you for your answer, but I don't think the problem is related to that.
It seems to be that part

``
    mappings:
        property_image:
            uri_prefix: /images/properties
            upload_destination: '%kernel.project_dir%/public/images/properties'
``

if I delete these lines, I no longer have the error, but it does not work.

**Comment by garak** [comment]
Is the bundle actually enabled? Check your profiler

**Comment by ag253617** [comment]
I added "Vich\UploaderBundle\VichUploaderBundle :: class => ['all' => true]," in config/bundles.php Are you talking about that?

I think that I see about what you are talking. That's why I skipped this part ( github.com/dustin10/VichUploaderBundle/blob/master/docs/… ).

**Comment by garak** [comment]
That's correct, but did you check it it worked?

**Comment by ag253617** [comment]
I followed the way of doing that I described (as in the lesson) and that's what doesn't work.
I try to do it the other way, but to be honest, I don't understand how to do it.

I already have 
``
// app/AppKernel.php 

    public function registerBundles()
    {
        if (!file_exists($filename = $this->getRootDir().'/'.$this->testCase.'/bundles.php')) {
            throw new \RuntimeException(sprintf('The bundles file "%s" does not exist.', $filename));
        }
        return include $filename;
    }
``
I don't know what to do with https://github.com/dustin10/VichUploaderBundle/blob/master/docs/installation.md#enable-the-bundle

would you know how to do it?

**Comment by garak** [comment]
There's something weird, AppKernel.php in not used anymore in Symfony 4 (nor the whole "app" directory").
I suggest you to look for an up-to-date guide (official docs are fine)

**Comment by ag253617** [comment]
sorry, I'm mixed with github documentation, my config is in
config/packages/vich_uploader.yaml. you are right.

but I have the file vendor/symfony/framework-bundle/Tests/Functional/app/AppKernel.php

**Comment by garak** [comment]
So, open any page of your application and click on the small Symfony logo in the bottom right corner.
Then look at "Enabled Bundles" and see if you spot VichUploaderBundle

**Comment by ag253617** [comment]
If I delete the mapping part of the file (otherwise I don't have the logo because of the error).
I have VichUploaderBundle in "Enabled Bundles" (VichUploaderBundle | "C:\wamp64\www\MonAgence\vendor\vich\uploader-bundle").

**Comment by garak** [comment]
Check indentation in your yaml file: it looks like "mappings" is not under "vich_uploader"

**Comment by ag253617** [comment]
thank you very much for your help, the problem came from the.
