### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Impossible to determine the class name. Either specify it explicitly or give an object").

### ISSUE THREAD

**Issue by kasali** [dustin10/VichUploaderBundle#1078]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | x.y.z

#### Summary

I want diplay the picture like this:
<img src="{{ vich_uploader_asset(property.picture,'imageFile')}}" alt="{{ property.filename }}" width="100%" height="98%">

#### Current behavior
An exception has been thrown during the rendering of a template ("Impossible to determine the class name. Either specify it explicitly or give an object").

**Comment by garak** [comment]
Feel free to re-open this issue with needed information
