### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Impossible to determine the class name. Either specify it explicitly or give an object").

### ISSUE THREAD

**Issue by kasali** [dustin10/VichUploaderBundle#1079]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | x.y.z

#### Summary

I want to link an image's entity(Picture) to another entity(Property) and diplay the image.
the entity Picture:
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PictureRepository")
 * @Vich\Uploadable()
 */
class Picture
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File|null
     * @Assert\Image(mimeTypes="image/jpeg")
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Property", inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $property;

    public function getId() : ? int
    {
        return $this->id;
    }

    public function getFilename() : ? string
    {
        return $this->filename;
    }

    public function setFilename(? string $filename) : self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getimageFile() : ? File
    {
        return $this->imageFile;
    }

    public function setImageFile(? File $imageFile) : self
    {
        $this->imageFile = $imageFile;
        return $this;
    }

    public function getProperty() : ? Property
    {
        return $this->property;
    }

    public function setProperty(? Property $property) : self
    {
        $this->property = $property;

        return $this;
    }
}
and Property:
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Cocur\Slugify\Slugify;
/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @Vich\Uploadable
 */
class Property
{
    const TYPE = [
        0 => ' à vendre',
        1 => ' à louer'
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=233,unique=true)
     * @Assert\NotBlank()
     * @Assert\Length(min=4)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Length(min=1)
     * @Assert\NotBlank()
     */
    private $price;
    /**
     * @ORM\Column(type="integer")
     */
    private $area;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $garage;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creat_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_At;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Type;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="property", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /** 
     * @var Array
     */
    private $pictureFiles;

    function __construct()
    {
        $this->creat_at=new \DateTime();
        $this->pictures = new ArrayCollection();
    }
   
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }
    public function getSlug() : ? string
    {
        return (new Slugify())->slugify($this->title);
    }
    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getArea(): ?int
    {
        return $this->area;
    }

    public function setArea(int $area): self
    {
        $this->area = $area;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getGarage(): ?string
    {
        return $this->garage;
    }

    public function setGarage(?string $garage): self
    {
        $this->garage = $garage;

        return $this;
    }

    public function getCreatAt(): ?\DateTimeInterface
    {
        return $this->creat_at;
    }

    public function setCreatAt(\DateTimeInterface $creat_at): self
    {
        $this->creat_at = $creat_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_At;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_At): self
    {
        $this->updated_At = $updated_At;

        return $this;
    }
     public function getFormatedPrice()
    {
        return number_format($this->price, 0, ' ', ' ');
    }

     public function getType(): ?string
     {
         return self::TYPE[$this->Type];
     }

     public function setType(string $Type): self
     {
         $this->Type = $Type;

         return $this;
     }
         /**
     * @return Collection|Picture[]
     */
    public function getPictures() : Collection
    {
        return $this->pictures;
    }

    public function getPicture() : ? Picture
    {
        if (empty($this->pictures)) {
            return null;
        }
        return $this->pictures[0];

    }
    public function addPicture(Picture $picture) : self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProperty($this);
        }

        return $this;
    }

    /** 
     * @return mixed
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * @param mixed mixed $pictureFiles
     * @return Property
     */
    public function setPictureFiles($pictureFiles) : self
    {
        foreach ($pictureFiles as $pictureFile) {
            $picture = new Picture();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFile;
        return $this;
    }

    public function removePicture(Picture $picture) : self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

}
where i display image i do that:
<img src="{{ vich_uploader_asset(property.picture,'imageFile')}}" alt="" width="100%" height="98%">

#### Current behavior

An exception has been thrown during the rendering of a template ("Impossible to determine the class name. Either specify it explicitly or give an object").

**Comment by garak** [comment]
Last try: you need to provide a readable issue, *following the instrucrions provided in comments*.
Please be sure your issue is both **readable** and informations (like version number) **properly filled** and possible images not broken
