### ISSUE TITLE
Using vich_uploader_asset leads to wrong url

### ISSUE THREAD

**Issue by MilesYM** [dustin10/VichUploaderBundle#1088]
|    Q        |   A
|------------ | -----
| Version     |  Lastest

### Support Question

I am trying to generate a link to my file uploaded on S3 with this bundle on a private bucket.

Looking at the doc I am using 

`vich_uploader_asset(user.deck, 'documentFile')`

this generates a link like this:

> https://console.aws.amazon.com/s3/buckets/myprivate-bucket/decks/mydoc.pdf?region=us-east-1

this link doesn't work. It should be :

> https://myprivate-bucket.s3.us-east-1.amazonaws.com/decks/mydock.pdf

Or alternatively:

> https://s3.console.aws.amazon.com/s3/object/myprivate-bucket/decks/mydoc.pdf?region=us-east-1&tab=overview

how do I change this ? Am i doing something wrong? I am using the basic configuration from this repo/doc

Thank you

**Comment by garak** [comment]
Please provide your configuration.
Also, "latest" is not a valid version, provide your actual installed version (not your requirement)

**Comment by garak** [comment]
Closing for missing feedback
