### ISSUE TITLE
How to display filename uploaded on the input ?

### ISSUE THREAD

**Issue by KevinArtus** [dustin10/VichUploaderBundle#1096]
|   Symfony        |
|------------ |
| 5.0   |

### Support Question
Hi

I've two entities Candidate -> OneToMany -> Attachment
Twig with a collection of Attachment like this :
(see my comment : https://github.com/dustin10/VichUploaderBundle/issues/1090#issuecomment-577209955)

I have uploaded 2 images for this candidate which have been inserted into the database.

The problem is that if I want to change the candidate profile, I don't see the files already added.
It simply displays a new download option.

If i add a new file on the input, it will delete one of those stored on the database :/

Is it possible to display the filename on the input for those uploaded ?
I mean, as i have 2 files on the databse, i'll would like to see 2 input with the filename.

In that case, the candidate will know that he already uploaded files and could delete them or replace or uploade new one.

**Comment by garak** [comment]
You just can't have a default value in an input file field, it's by design (design of HTML, not of this bundle)

**Comment by garak** [comment]
Because the file is replaced?

**Comment by KevinArtus** [comment]
No, it's not the same file.
It juste replace an existing file by a new one (it do not delete one sorry).

It's like if the input file field is linked to an existing file on the database.

**Comment by garak** [comment]
If you're able to reproduce such problem, feel free to open an issue for a bug.

**Comment by KevinArtus** [comment]
I have to create a new issue as bug ?
It's strange, it should not do this.

**Comment by garak** [comment]
You should first try to demonstrate that it's actually a bug.
Frankly, that's unlikely,you're probably doing something wrong.
But trying to reproduce it's a good way to spot your error.

**Comment by KevinArtus** [comment]
I'm still on the problem.
The input file field seems t o be linked to the uploaded file.
If i add a file on this input, it'll replace the existing one in the database.
