### ISSUE TITLE
DownloadHandler should set fallback filename in makeDisposition() call

### ISSUE THREAD

**Issue by TomaszGasior** [dustin10/VichUploaderBundle#1097]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.13.0 

#### Summary

This is my controller action:

```
    /**
     * @Route("/file/{id}", name="file.download")
     */
    public function download(File $file, DownloadHandler $downloadHandler): Response
    {
        return $downloadHandler->downloadObject($file, 'fileData', null, true);
    }
```
I set 4th argument of downloadObject() to `true` to enforce downloading using original filename. Inside DownloadHandler, here https://github.com/dustin10/VichUploaderBundle/blob/master/src/Handler/DownloadHandler.php#L71 makeDisposition() method is called without setting fallback filename as third argument. Fallback filename must contain **only** ASCII characters. When fallback filename is not defined, makeDisposition() uses its second argument as both filename and fallback filename, see here https://github.com/symfony/http-foundation/blob/master/HeaderUtils.php#L169

#### Current behavior

When original filename contains non-ASCII characters, HeaderUtils::makeDisposition() fails with "The filename fallback must only contain ASCII characters." exception.

#### How to reproduce

To reproduce please create file with original filename containing non-ASCII characters, for example "Zażółć gęślą jaźń.docx" which contains Polish-specific characters.

#### Expected behavior

IMHO your bundle should define some basic/automatic fallback filename, date&time for example.

**Comment by TomaszGasior** [comment]
@garak Could you please tell me when are you going to do new release with this fix?

**Comment by garak** [comment]
Next week at last. Meanwhile, you can use our branch alias

**Comment by TomaszGasior** [comment]
@garak Thanks.
