### ISSUE TITLE
Type error: Argument 1 passed to Vich\UploaderBundle\Util\ClassUtils::getClass() when save any entity in onAuthenticationSuccess

### ISSUE THREAD

**Issue by npmhieu** [dustin10/VichUploaderBundle#1102]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 1.8 || 1.10

#### Summary

Error when use with Symfony 3.4, after login, I have a LoginSuccessHandler which save some data and I got this error

#### Current behavior
Type error: Argument 1 passed to Vich\UploaderBundle\Util\ClassUtils::getClass() must be an instance of Vich\UploaderBundle\Util\object, instance of UserBundle\Entity\User given

#### How to reproduce

`class LoginSuccessHandler implements AuthenticationSuccessHandlerInterface
{
  protected $router;
  private $apiService;

  public function __construct(Router $router, ApiService $apiService)
  {
    $this->router = $router;
    $this->apiService = $apiService;
  }

  public function onAuthenticationSuccess(Request $request, TokenInterface $token)
  {
    /** @var User $user */
    $user = $token->getUser();
    $user->setFullname("Any value");
    $userAccessToken = $this->apiService->saveEntity($user);
    $response = new RedirectResponse($this->router->generate('homepage'));
    return $response;
  }
}`

**Comment by garak** [comment]
PHP version?

**Comment by npmhieu** [comment]
Hi Garak,
I use php 7.1.23

Thank you very much for your support.

**Comment by garak** [comment]
Can you check the line where the error occurs? it should be [this line](https://github.com/dustin10/VichUploaderBundle/blob/1.8/Util/ClassUtils.php#L23)
Is is the same in your code?

**Comment by npmhieu** [comment]
Hi Garak,
Yes, that's it :) 
Do you have any work around for it ?
Thank you very much!

**Comment by garak** [comment]
So, there's no "object" type in that method.
I'm afraid you're checking the wrong code or reporting something wrong
