### ISSUE TITLE
Do we still need updatedAt for upload?

### ISSUE THREAD

**Issue by fd6130** [dustin10/VichUploaderBundle#1103]
|    Q            |   A
|---------------- | ------
| Bundle version  | ^1.13 
| Symfony version | 5.0.5
| PHP version     | 7.3.15

### Support Question

The documentation said we need `updatedAt` because doctrine need at least one field changes
```
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }
```
I comment out the code `if(null !== $imageFile)` if-condition and upload a file. The file is saved without issue. 

Do we still need the `updatedAt` for the upload entity?

**Comment by garak** [comment]
That's a good question.
I don't use it myself since a while, so I'm inclined for an affirmative answer.
Anyway, we need to be sure and especially to detect the point where Doctrine changed behavior.
If we manage to do so, we can integrate documentation, e.g. telling "if you're using doctrine before version X.Y you need to set updatedAt property etc. etc."

**Comment by fd6130** [comment]
I'm not code expert but may i ask how this bundle work with doctrine? 

I come up with the thought: When we persist an entity, vich-bundle will get involved in the persist event and do those mapping (like mapping fileNameProperty to the given property) and handle file upload.  From my point of view, the `imageName` got value (consider as update), then the `updatedAt` is not really needed.   Maybe?

**Comment by garak** [comment]
The magic is [here](https://github.com/dustin10/VichUploaderBundle/blob/master/src/EventListener/Doctrine/UploadListener.php)
The point is that this is happening only when entity is changed

**Comment by fd6130** [comment]
Ok cool, it seems we still need updatedAt for update case. We need to make sure there is one field change otherwise the entity won't be updated.

**Comment by garak** [comment]
I just tried to create a simple project and I confirmed our suspicions: updatedAt is not needed anymore.
I'll update docs in next days.
Thanks

**Comment by fd6130** [comment]
> I just tried to create a simple project and I confirmed our suspicions: updatedAt is not needed anymore.
> I'll update docs in next days.
> Thanks
Have you tried update case? I just realize only updating the `imageFile` property won't make doctrine update the entity.

**Comment by garak** [comment]
Ah, you're right.
So we need it after all
