### ISSUE TITLE
Array of files

### ISSUE THREAD

**Issue by StephanGR** [dustin10/VichUploaderBundle#1104]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | don't know
| BC Break    | don't know

#### Summary

Would it be possible to add the fact of putting an array of images in place of a single image

**Comment by garak** [comment]
You need to better define your expectations

**Comment by StephanGR** [comment]
I wanted to know if you can add putting multiple files for one entity
Because if I understand the documentation correctly, you have to make several fields for several files
Therefore I wanted to know if it was possible to add several files for a single entity

**Comment by garak** [comment]
It depends on how you map your entities.
That's something related to Doctrine, more than to this bundle

**Comment by StephanGR** [comment]
Thanks for the response, but how can i do something like that ?

- UUID of my operation entity

  - Folder 1

  - Folder 2

  - Folder 3

  - Folder of documents entity of operation entity

    - Document 1

    - Document 2

    - etc...

  - Folder of pictures entity of documents entity of operation entity

    - Picture 1

    - Picture 2

    - etc...

**Comment by garak** [comment]
I guess you can define your entities and relevant [associations](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/association-mapping.html)

**Comment by StephanGR** [comment]
I've already define my entities with associations like Many To One, but does the architecture that i showed you is great

i can make the tree of folders when a new row is added to the db ? and store files in it ?

What do you think about this "solution" ?

**Comment by garak** [comment]
Is Folder an entity?
Anyway, you're not limited in creating instances of your entities

**Comment by StephanGR** [comment]
Nop operation, documents, and pictures are entity but i want to add files for operation, documents and pictures 

How can i do this ?

**Comment by garak** [comment]
You can:

1) read the docs
2) try to implement
3) ask questions on **specific** problems, not on architectural choices

**Comment by StephanGR** [comment]
Alright,

Thanks for your time
