### ISSUE TITLE
Required 

### ISSUE THREAD

**Issue by kl3sk** [dustin10/VichUploaderBundle#1105]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.3.1
| Symfony version | 5.0.5
| PHP version     | 7.2

### Support Question
Edit form with an ever uploaded file calls asserts errors.

See Stackoverflow  [question](https://stackoverflow.com/questions/60566464/vichuploader-required-upload)

**Comment by garak** [comment]
What is the location (in this bundle) where you expect to see a "required"?

**Comment by kl3sk** [comment]
I want my user to be required to upload a file, on new form this work because no file was provided.
But, if they need to update the form without providing an other file, my assertion `@assert\NotBlank` raise.


I want to be able to update my form with (new one) OR without (with current) changing file.

**Comment by garak** [comment]
What is restraining you from that?

**Comment by kl3sk** [comment]
When I edit my form without file, this append.

![image](https://user-images.githubusercontent.com/2953145/76098123-3033fc80-5fc9-11ea-98ad-55586b7d5782.png)

**Comment by garak** [comment]
So put field require when adding and non-required when editing. Too easy?

**Comment by kl3sk** [comment]
Hum this sound a good solution (why do I don't think about it 😅), but for some reasons I disable HTML5 validation, so when `required` is true, it doesn't validate.

**Comment by garak** [comment]
Of course, the same pattern applies to validation

**Comment by kl3sk** [comment]
Of course, but just don't know why it doesn't apply here. This is not due to this bundle I know.

I leave it open when I found a good solution and write it down here.

**Comment by garak** [comment]
Did you find a solution?

**Comment by kl3sk** [comment]
Unfortunately no, I have to use `Constraint` on the form for now.

**Comment by garak** [comment]
But you **always** have to.
Still, I don't get how your expectations are not met

**Comment by kl3sk** [comment]
You mean that no validation can be met with Entity annotations ?

**Comment by garak** [comment]
Well, you could also use annotations with groups

**Comment by kl3sk** [comment]
That what I want to to without success, maybe because input file is inside collection ?

**Comment by garak** [comment]
I don't know.
But, again, there's nothing about validation inside this bundle

**Comment by kl3sk** [comment]
Yes I never said this, because I know it.
Because I need to work on my project I leave this using Form Annotations, and I'll have a look after.

**Comment by garak** [comment]
fair enough
