### ISSUE TITLE
Obtain image Url using UploaderHelper

### ISSUE THREAD

**Issue by fd6130** [dustin10/VichUploaderBundle#1106]
|    Q            |   A
|---------------- | ------
| Bundle version  | ^1.13 
| Symfony version | 5.0.5
| PHP version     | 7.3.15

### Support Question

We can obtain the image url using `$helper->asset($entity, 'image');`  But what about results from Query Builder/DQL that are not hydrate as object but array?

------------------------------------------
For example, i have a product entity
```
//Uploadable Entity
class Product
{
   private $title;
   private $imageFile;
   private $imageName;
   // other property...
}
```
To obtain the url, we can use `$helper->asset($entity, 'imageFile');`

But if i fetch it using Query Builder/DQL:

```
public function getSomeProductInformation()
{
  return $this->createQueryBuilder('p')
      ->select('s.id, s.title, s.imageName')
      ->getQuery()
      ->getResult();
}
```

It give array as result so i can't get url using `UploaderHelper`.  Do we have alternative solution to obtain the url without entity only?

**Comment by garak** [comment]
You can pass entity class name as third parameter to helper method

**Comment by fd6130** [comment]
> You can pass entity class name as third parameter to helper method

But how about the first parameter? Pass the whole array?

**Comment by garak** [comment]
Yes, pass your array as first parameter

**Comment by fd6130** [comment]
Ok, thanks!
