### ISSUE TITLE
Image upload when persisting entity (before execute flush)

### ISSUE THREAD

**Issue by fd6130** [dustin10/VichUploaderBundle#1110]
|    Q            |   A
|---------------- | ------
| Bundle version  | ^1.13 
| Symfony version | 5.0.5
| PHP version     | 7.3.15

### Support Question

Hi, this is not really an issue but i would like to ask a question.

Somehow i realize that image is uploaded when uploadable entity is persisted.

```
// Controller action
public function upload(Request $request)
    {
        $image = new PostImage(); // uploadable entity
        $image->setImageFile($request->files->get('fileToUpload'));

        $this->entityManager->persist($image); // Note: not yet flush, but image already save to the folder
        // ...
    }
```

Somehow if there is a case that after flush and error occurs, the data won't save to database (that's great) but the file is still remain at the destination folder. Isn't that the file should be removed when a database transaction fail?

Thanks.

**Comment by garak** [comment]
I'm afraid this case is not currently handled
