### ISSUE TITLE
Generating a URL in a Twig Template using wamp

### ISSUE THREAD

**Issue by JeanValJeann** [dustin10/VichUploaderBundle#1113]
Bundle version  | 1.13
Symfony version | 5.0
PHP version     | 7.3.5

Hi,

I got question about generating an URL in a Twig template using Wamp and not internal PHP server. In Twig view, there is a src attribute generated using

`
<img src="{{ vich_uploader_asset(product, 'image') }}" alt="{{ product.name }}" />
`

But this src attribute is like '/images/products/my_product_image_name.jpg'. it works as described in Doc assuming that you run the internal PHP server, as well. That's not my case, I'm running Wamp server on Windows 10 via symfony/apache-pack and have an .htaccess in my /public folder.

How to generate an absolute URL using Twig template ?

Thanks

**Comment by garak** [comment]
Function is meant to work on any server

**Comment by garak** [comment]
Closing for missing feedback
