### ISSUE TITLE
Add option to display a link with target _blank instead of a download one.

### ISSUE THREAD

**Issue by VincentLanglet** [dustin10/VichUploaderBundle#1114]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | ?
| BC Break    | no

#### Summary

Instead of a link 
```
<a href="" download></a>
```
I would like a link 
```
<a href="" target="_blank"></a>
```

I think this could be an option in the form.

**Comment by garak** [comment]
target blank is [a bad idea](https://www.google.com/search?q=avoid+target+_blank)
Anyway, if you are aware of consequences, you can still use it by [overriding templates](https://symfony.com/doc/current/bundles/override.html#templates)

**Comment by VincentLanglet** [comment]
>target blank a bad idea

We can add `rel=”noopener noreferrer”`.

Or use `_self`, at least. Instead of downloading the file.
There is no way to see the file without downloading it when editing.

> Anyway, if you are aware of consequences, you can still use it by [overriding templates](https://symfony.com/doc/current/bundles/override.html#templates)

The issue with overriding template is that if the VichFile template is updated with new feature/new bugFix ; I don't take advantage of these features/bugFix.

That's not the case with an option to remove the `download` attribute.

**Comment by garak** [comment]
> The issue with overriding template is that if the VichFile template is updated with new feature/new bugFix ; I don't take advantage of these features/bugFix.

That's it. It's up to you.
Anyway, templates rarely changed in last years
