### ISSUE TITLE
Prevent non working upload due to typo

### ISSUE THREAD

**Issue by flohw** [dustin10/VichUploaderBundle#1115]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | maybe

#### Summary

It would be a nice addition to throw an exception when the mapping used in `@UploadableField` does not exist, as the `vich_uploader_assets` does. I just lost some time to figure out why the upload didn't work. It turns out I just make a typo on the mapping used in the annotation.

Thank you

**Comment by garak** [comment]
What is the point where you'd expect that?

**Comment by flohw** [comment]
Improve DX in order to know immediately why the upload won't work instead of searching for the typo we don't expect to make. :slightly_smiling_face: 

At the moment the method `MetadataReader::isUploadable` only return false if the mapping is not found. I think throwing an exception would help to know we've done a mistake.

**Comment by garak** [comment]
We're already throwing `MappingNotFoundException` and `NotUploadableException` in `PropertyMappingFactory::fromObject`

**Comment by flohw** [comment]
So it may have a bug as I annotate my entity and my property. The property had `announce_logo` where my configuration named `announcer_logo`.

Maybe it's due to some new SF5 behavior but I did not have any exception thrown.

I can try to make a small project to reproduce.

**Comment by garak** [comment]
Closing for missing feedback
