### ISSUE TITLE
How to check image sise before posting 

### ISSUE THREAD

**Issue by methodeprog** [dustin10/VichUploaderBundle#1123]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.13 
| Symfony version | 4.4.7
| PHP version     | 7.2.5

### Support Question

Dear value member, i try do check an image size before posting in Symfony controller
but it return null !!

```
        if ($form->isSubmitted() && $form->isValid()) {

            // imageSiz is null ???
            $imageSize = $form->getData();
         //   dump($imageSize);
        //    die();
```
Please help !!

Best regards !!

**Comment by garak** [comment]
What is $form?

**Comment by garak** [comment]
Closing for missing feedback
