### ISSUE TITLE
SmartUniqueNamer including ext of original filename

### ISSUE THREAD

**Issue by nuryagdym** [dustin10/VichUploaderBundle#1125]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.13 
| Symfony version | 4.4.7
| PHP version     | 7.3

In the documentation written if we use SmartUniqueNamer    a Strange name.jpg 
will be uploaded as something like a-strange-name-0eb3db03971550eb3b0371.jpg
But when I tried it uploads    a Strange name.jpg      as   a-strange-name.jpg-0eb3db03971550eb3b0371.jpg
Is it how it is supposed to work?

From the library code it seems that it this is expected result:
```
        $originalName = $file->getClientOriginalName();
        $originalExtension = \strtolower(\pathinfo($originalName, PATHINFO_EXTENSION));
        $originalBasename = \basename($originalName, '.'.$originalExtension);
        $originalBasename = $this->transliterator->transliterate($originalBasename);
        $uniqId = \str_replace('.', '', \uniqid('-', true));
        $uniqExtension = \sprintf('%s.%s', $uniqId, $originalExtension);
        $smartName = \sprintf('%s%s', $originalBasename, $uniqExtension);
```
Would not be it is better  if don't specify extension twice in the uploaded filename?

**Comment by garak** [comment]
I'm sorry but I can't see how library code could expect such result.
Anyway, I tried to upload a file named "a strange name.png" and I got a file named "a-strange-name-5eba625e2c2e4106358645.png"

**Comment by nuryagdym** [comment]
I found the problem, it is because of the case of extension. This problem occurs when I select a file with an upper case extension (image.PNG). If the extension is lower case then it works as you said

**Comment by garak** [comment]
It's a bug on our code. First, we lowecase the extension. Then, we basename the file using lowecased extension.
Can you provide a patch?

**Comment by nuryagdym** [comment]
Yes I will work on that, and will make a PR

**Comment by garak** [comment]
Great! Please remember to add a test.
