### ISSUE TITLE
`UploadHandler::clean()` attempts to remove the wrong file

### ISSUE THREAD

**Issue by soundlake** [dustin10/VichUploaderBundle#1130]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.11.0 
| Symfony version | 3.4.39
| PHP version     | 7.3.14

#### Summary

I set `delete_on_update` `true` explicitly however, the old file isn't removed.

#### Current behavior

Apparently, in `EventListener\Doctrine\CleanListener::preUpdate()`, the `$object` is passed to `Handler\UploadHandler::clean()` but it contains the new value. Thus, it ends up attempting to delete the new file.

Check out the [Doctrine's Doc for the `preUpdate` event](https://www.doctrine-project.org/projects/doctrine-orm/en/2.5/reference/events.html#preupdate). There's only a singly way to get the old value; calling `getOldValue($fieldName)`.

#### How to reproduce

The old file always remains. I'm a bit surprised that it is not reported yet.

#### Expected behavior

The old file should be removed on delete if it is configured so.

**Comment by garak** [comment]
@soundlake do you have an idea on how we can solve this?

**Comment by soundlake** [comment]
@garak I haven't tested yet, but using `onFlush` instead of `preUpdate` would work. https://www.doctrine-project.org/projects/doctrine-orm/en/2.5/reference/events.html#onflush
I don't have much time to test that, but I'll be back tomorrow. 😉

**Comment by garak** [comment]
Problem here is that chain of responsibilities delegate removal to inner classes, where events are not available anymore.
In the last step, it's a concrete instance of `AbstractStorage` that deletes file, but only basing on the mapping, without knowing anything about original event.
I guess that we should find a way to get the old value from the event (when still possible) and somehow pass it around.
