### ISSUE TITLE
Symfony - API Platform - Vich Uploader & vulnerability issues

### ISSUE THREAD

**Issue by Jogima-cyber** [dustin10/VichUploaderBundle#1136]
Good morning, I'm trying to develop a smartphone application connected to an API Platform API. I need the option to upload some files from the application. I cannot trust those who send files. I've followed the https://api-platform.com/docs/core/file-upload/ guidlines. Thus, I can't see how to prevent a CWE-434 vulnerability (Unrestricted Upload of File with Dangerous Type, https://cwe.mitre.org/data/definitions/434.html). I've done it myself on my system, so the vulnerability works with my configuration. I cannot believe that it was forgotten from the vichuploaderbundle. It must be something else, but I can't figure out what. Should I write my own image handler, or is there a way to use vichuploaderbundle with safety ?

**Comment by garak** [comment]
Symfony is offering a robust system of validation. Look there.
For example, see https://symfony.com/doc/master/reference/constraints/File.html

**Comment by Jogima-cyber** [comment]
@garak hi and thank you for your answer ! I've used [symfony image constraint](eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTE3ODU0MTUsImV4cCI6MTU5MTc4OTAxNSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiam9zZXBoLmFtaWdvQGhlYy5lZHUifQ.mM8q7cgNuWbASr39VbMlcaNsRMQKJWhzmaqh7jynPJb-SFSY07fMrsS_I5ne8y6TDG7QvnuaCpnnTjeeb4h6zjS2b5p3zrpjtGtbp5hkAKOtV28xx3052S1vYLARE9G6D3-OL1hl1mX9JX4yteT0_apKpRgY899x_ZxhBlrKZGFh294ZXsOQ6czgnMErcKRMKAz2DEhvYary7cFtw-e2i_HYW0CjNDS-tUM5UdwbVcwRqOi43saNdQ3aPjRc4QE1feIbgSP5jytmcb5Vi7AFtLz70WtVvlTDTXTi_NCwjdI3uN5IEm1Ic8q9ALpx8qW91ulCLsJH-T4WZ3SMCQpQDmESVB2K3kkk_inuzgAyzfGM9wdJkS_lmfv7VsVuBiMPveaffG419WDvtNPne9ua65M8MGEk1JnRxH4DdOKBkzjxiStsUZe_K8Lm_44uzdHX8bOKiG2phTKfItkcte9z4pejRgtDT_qj8DrO9Do7VlW3Ms5JEU7F73Lo87bRcu4U-WC-bRoyEPq882GfOxnPSBIbzd8EYZ4cN_F9G0pw_FwmaLRoNIo3haA5ubTMPzChLAvv9cHY5zqmgGjSnACoRRuQgYrZ2oO3MaocpaCsuTPbJTFubK0U5O0FJIqrijY5Log5W_azOF9QyId7Z8POa8TUFj26kgP46DGOc98UO3g), which detects if a file is a valid image. I trust symfony constraint to avoid images upload vulnerabilities.
I use the constraint like that :
`// src/Entity/Author.php
namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;

class Author
{
    /**
     * @Assert\Image()
     */
    protected $headshot;
}
`

**Comment by mbrodala** [comment]
https://symfony.com/doc/current/reference/constraints/Image.html
