### ISSUE TITLE
vich_file_label create missing translations 

### ISSUE THREAD

**Issue by VincentLanglet** [dustin10/VichUploaderBundle#1137]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.14.0 
| Symfony version | 4.4.9
| PHP version     | 7.4

#### Summary

Hi @garak, thanks for this useful bundle.

The way VichUploader translate the form label seems buggy to me and report missing translations.
```
{%- block vich_file_label -%}
    {%- set label = label|trans|default(label) -%}
    {{- block('form_label') -}}
{%- endblock -%}
```

Firstly, when using `'label' => false`, it use `trans` on `false` and report a missing translation for `''`. Same when providing no label, it use `trans` on `null`. This leads to an error with Symfony 5. (Cf https://github.com/dustin10/VichUploaderBundle/issues/1066)

Secondly, when using `'label' => 'myLabel'`, it use obviously `trans` on `myLabel`. But the block `form_label` try to translate the label too with the option `'translation_domain'`. This means that the profiler report a missing translation when trying the second translation.

Finally, when using  `'translation_domain' => false`, the label is still translated.

### Solutions

The difficulty would be to determine what is BC and what is BC-break

Currently, If I have the following translations
```
#messages.yaml
myLabel: foo
myLabel2: bar

#VichUploaderBundle.yaml 
myLabel3: baz
bar: hello
```

- `myLabel` will be translated to `foo` with the first trans. (and then foo will be a missing translation in VichUploaderBundle)
- `myLabel2` will be translated to `bar` with the first trans. And then it will be translated to `hello` by `form_label`.
- `myLabel3` will be reported as a missing translation and then will be translated to `baz`.

IMHO the best solution would be to
- add a `delete_translation_domain` option and use it instead of `translation_domain` for `delete_label`.
- add a `download_translation_domain` option and use it instead of `translation_domain` for `download_label`
- change the default value of `translation_domain` to `messages`.
- remove the `{%- set label = label|trans|default(label) -%}` code.
But this would need to release a new major version.

I didn't find a BC way to fix both the fact that `false/null` throw an error with Symfony 5 and the double translate calls which leads to missing translations.

**Comment by garak** [comment]
What about checking for `label` value inside block?

**Comment by VincentLanglet** [comment]
> What about checking for `label` value inside block?

You can do something like 
```
{%- block vich_file_label -%}
    {% if label is not same as(null) and is not same as(false) %}
        {%- set label = label|trans -%}
    {% endif %}
    {{- block('form_label') -}}
{%- endblock -%}
```
This avoid to trans the `false` and `null` value indeed. It could be a first step.

But it doesn't fix everything.

If I use 
```
'label' => 'myLabel`
`translation_domain` => `myTranslationDomain`
```

A call for `label|trans` is still called (with the `translation_domain` `messages`).
- Either it create a missing translation ; but at least it's then correctly translated thanks to `form_label`.
- Either it create the following non-expected behaviour with
```
# messages.yaml
myLabel: Generic label

# myTranslationDomain.yaml
myLabel: Specific label
```
The developer would expect to be translated to `Specific label`, but instead it will be translated to `Generic label` and then `Generic label` will be reported as a missing translation in `myTranslationDomain`.

**Comment by garak** [comment]
So, a solution could be avoid using custom domains, and using only domain provided by bundle.
I guess that this should need some emphasis in docs

**Comment by garak** [comment]
Anyway, I'm trying to get the reason for the presence of `vich_file_label` twig block, but I can't.
I found [this commit ](https://github.com/dustin10/VichUploaderBundle/commit/9e55a6e1929c6345ebc7e3bd6272682264fe247a) to be the culprit.
Honestly, I think we could get rid of it and solve this issue

**Comment by VincentLanglet** [comment]
The reason was explained here: https://github.com/dustin10/VichUploaderBundle/pull/902

When writing
```
$builder->add('file', VichUploadType::class, ['label' => 'app.product_file']
```
Developers are expecting the label to be translated with the `messages` domain.

When writing
```
$builder->add('file', VichUploadType::class, ['label' => 'app.product_file', 'translation_domain` => 'customDomain`]
```
They expects the label to be translated with the `customDomain` domain.

If you remove the `vich_file_label`, it default to `form_label`, and the label gonna be translated with the `VichUploaderBundle` translation domain since you override the `translation_domain` option.
IMHO, it would be better to not override the `translation_domain`

Then you have others option for the `download` and the `form.label.delete` translations:
- You can add another option like `'action_translation_domain' => 'VichUploaderBundle'` which does not conflict with the `translation_domain` for the label.
- You can pass `VichUploaderBundle` as a translation domain for the download and the delete directly in the `fields.html.twig` because you consider that the translation are not often changed, and if they want to change it they should use your domain.

**Comment by garak** [comment]
Well, I tried on a local project to remove `vich_file_label` from bundle.
Normal translation is working, using messages provided in my `VichUploaderBundle.en.yaml` file.
Custom translation is working too, using messages provided in my `custom.en.yaml` file (and passing `translation_domain` option).

So, for what I see, my previous proposal stands: we remove the block and we add a note in docs recommending to add translations for widget in  VichUploaderBundle domain

**Comment by VincentLanglet** [comment]
> So, for what I see, my previous proposal stands: we remove the block and we add a note in docs recommending to add translations for widget in VichUploaderBundle domain

I agree it works but it won't be usual for developers. As said, when writing
```
$builder->add('file', VichUploadType::class, ['label' => 'app.product_file'])
```
We expects to use the `messages` domain, not `VichUploaderBundle` one.

And if I write 
```
$builder->add('file', VichUploadType::class, ['label' => 'app.product_file', 'translation_domain` => `custom`])
```
I would usually prefer to still use VichUploaderBundle domain for the `download` and `delete` label.

Since you proposal is a BC-break and need a new major, why not also changing the current `translation_domain` option to something like `action_translation_domain` (or splitting to `download_translation_domain` and `delete_translation_domain`) in order to not override the  'translation_domain` value. This will allow this form to translate the label with the `messages` domain by default.

**Comment by garak** [comment]
Why do you think my proposal is a BC break?

**Comment by VincentLanglet** [comment]
Currently
```
$builder->add('file', VichUploadType::class, ['label' => 'app.product_file'])
```
is translated with the `messages` domain and then with the `translation_domain` option.

So with the translations file
```
#messages.yaml 
app.product_file: Product File
```
It will display `Product file` (and of course report a missing translation for Product File in VichUploaderBundle domain).

The use of the `messages` domain was introduced in `1.8.5`. A lot of developers can be used to it. With your proposal, it will display `app.product_file` instead (and report a missing translation for `app.product_file` in VichUploaderBundle domain). I consider this as a BC break.

The current behavior is buggy since it translates two times the label. But since the developer could have used one or the others, I see no solution to translate only one time the label without a BC-break.

**Comment by garak** [comment]
Well, this is a little mess.
I think we need to simplify, so I'd avoid adding further parameters.

The current situation is that, even if you're using a translation in messages domain, you need an additional translation in VichUploaderBundle domain. Furthermore, you're often in a situation where you put the same translation in both domains (since it happens that you need to translate the same term inside the form and elsewhere).

Considering this, I'm still for the removal of the block. This will be marked as potential BC break and released in next minor.
Documentation will be updated to clarify the need of translating labels in VichUploaderBundle domain.

**Comment by VincentLanglet** [comment]
> Well, this is a little mess.
> I think we need to simplify, so I'd avoid adding further parameters.

It's not adding another parameters. It's renaming the existent one. From
```
$resolver->setDefaults([
            'allow_delete' => true,
            'asset_helper' => false,
            'download_link' => null,
            'download_uri' => true,
            'download_label' => 'download',
            'delete_label' => 'form.label.delete',
            'error_bubbling' => false,
            'translation_domain' => 'VichUploaderBundle',
        ]);
```
To
```
$resolver->setDefaults([
            'allow_delete' => true,
            'asset_helper' => false,
            'download_link' => null,
            'download_uri' => true,
            'download_label' => 'download',
            'delete_label' => 'form.label.delete',
            'error_bubbling' => false,
            'action_translation_domain' => 'VichUploaderBundle',
        ]);
```

You won't override `translation_domain` and you won't use it. Symfony will use it for you.

Every other form I know are using the `messages` domain by default. And this is certainly for this reason that people added [this commit](https://github.com/dustin10/VichUploaderBundle/commit/9e55a6e1929c6345ebc7e3bd6272682264fe247a).

I won't see as messy the fact that
- Symfony option as label, translation_domain have the default behavior of symfony
- VichUploader option as download_label, delete_label, have a custom behavior with a custom action_translation_domain.

> The current situation is that, even if you're using a translation in messages domain, you need an additional translation in VichUploaderBundle domain. 

It reports indeed a missing translation, but I assume that most of the developper are ignoring this. I can bet that the majority of the developers are using the `messages` domain rather than the `VichUploaderBundle` domain, so it will a BC-break for the majority.

> Furthermore, you're often in a situation where you put the same translation in both domains (since it happens that you need to translate the same term inside the form and elsewhere).
> 
> Considering this, I'm still for the removal of the block.

I'm not following you on this point.
Since you often want the same translation, you don't want to add the translation in two differents domains. Just one, the `messages` one.

But if I want to provide my domain (with the current `translation_domain` option), I'll need to also add translations for `download` and `form.label.delete`, but most of the time nobody wants to changes this.

**Comment by VincentLanglet** [comment]
> This will be marked as potential BC break and released in next minor.
> Documentation will be updated to clarify the need of translating labels in VichUploaderBundle domain.

If you want to be more simple, you could
- Remove the override of `translation_domain`.
- Stop passing the option to the delete and use `'VichUploaderBundle'`.
```
$form->add('delete', Type\CheckboxType::class, [
    'label' => $options['delete_label'],
    'mapped' => false,
    'translation_domain' => 'VichUploaderBundle',
    'required' => false,
]);
```
- Stop passing the option to the download label and use `'VichUploaderBundle'`.

**Comment by garak** [comment]
What if we move all bundle translations to messages domain?
Then, we can remove the current block from template and remove `translation_domain` default from VichFileType

**Comment by VincentLanglet** [comment]
> What if we move all bundle translations to messages domain?
> Then, we can remove the current block from template and remove `translation_domain` default from VichFileType

You could have a conflict with the developper if he use the same key somewhere else.

You could change your key to something specific like `vich_uploader.label.delete`. But, I don't know it's recommended.

Symfony use his own domains for his own translations: 
https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Form/Resources/translations
https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Security/Core/Resources/translations
And I don't think there is a way to override this.

So I won't be surprised if the translation_domain for the `delete_label` and the `download_label` can't be overriden and was always VichUploaderBundle.

**Comment by garak** [comment]
I don't see any problem in using a prefix in messages, I think it's much unlikely someone is already using it.
Something like:
```yaml
# translations/messages.en.yaml
vich_uploader:
    form_label:
         delete_confirm: Delete?
    link:
         download: Download
```

**Comment by VincentLanglet** [comment]
Yes indeed. 

I was just considering that was the purpose of the translation domains. Create a prefix for the `download_label` and the `delete_label` is similar to adding a `action_translation_domain`.

But the prefix solution could fix everything too, if it's the solution you prefer.

**Comment by garak** [comment]
@VincentLanglet can you please take a look to linked PR?
(It's still missing docs part and some translations)
