### ISSUE TITLE
Automatically put the filename on input file on update

### ISSUE THREAD

**Issue by bastien70** [dustin10/VichUploaderBundle#1147]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | no

#### Summary

When I create an instance of an object, saved in a database, and I want to modify it, I would like the name of the uploaded files to appear in the inputs in order to find my way around it better.

Before, I did this manually each time, in my Twig template, I put a data-attribute to my input in case a file was attached to it.
Then in javascript, I got the data-attribute, and I inserted it in the label of the input.

But it would be nice to implement something automatic so you don't have to do it yourself.

For this, in the form_theme **fields.html.twig** : 

```twig
{%- block vich_file_widget -%}
    <div class="vich-file">
        <div class="vich-file">

            {% if(form.vars.object) %}
                {{- form_widget(form.file, {'attr': {"data-filename": form.vars.object.filename}}) -}} // set data-filename
            {% else %}
                {{- form_widget(form.file) -}}
            {% endif %}

            {% if form.delete is defined %}
                {{ form_row(form.delete) }}
            {% endif %}

            {% if download_uri %}
                <a download href="{{ download_uri }}">Télécharger le fichier</a>
            {% endif %}
        </div>
    </div>
{%- endblock -%}

......
```

And if your javascript file : 

```js
$(document).ready(function() {
            $("input[type=file]").each(function (index, inputFile) {
                if($(inputFile).data("filename"))
                {
                    var label = $("label[for='" + $(inputFile).attr('id') + "']")[0];
                    label.innerHTML = $(inputFile).data("filename");
                }
            })
        });
```

But I wonder if we can do even better?

**Comment by garak** [comment]
What about putting name inside label?

**Comment by bastien70** [comment]
> What about putting name inside label?

Like this ?

```twig
{%- block vich_file_label -%}
    {%- set label = label|trans|default(label) -%}

    {% if form.vars.object %}
        {%- set label_html = form.vars.object.filename-%}
    {% endif %}

    {{- block('form_label') -}}
{%- endblock -%}
```

**Comment by garak** [comment]
I meant using `label` option when you build your form. No need to alter template.

**Comment by bastien70** [comment]
> I meant using `label` option when you build your form. No need to alter template.

Mmmmh... I'm not sure, or I don't understand... because in my formBuilder, I've : 

```php
->add('colorPalet', ProjectColorPaletType::class, [
                "required" => $requiredFile,
                "label" => false
            ])
```

And the **ProjectColorPaletType** class : 

```php
        $builder
        ->add('imageFile', VichImageType::class, [
            'label' => 'Palette de couleurs',
            'attr' => [
                'placeholder' => 'Choisir un fichier',
            ],
            'constraints' => [
                new File([
                    'maxSize' => '1M',
                    'mimeTypes' => [
                        'image/jpeg',
                        'image/png',
                    ],
                    'mimeTypesMessage' => 'Veuillez choisir un fichier ayant le bon format (jpg, png)',
                    'maxSizeMessage' => 'Votre fichier est trop volumineux {{ size }} {{ suffix }}. La taille maximale autorisée est {{ limit }} {{ suffix }}',
                ]),
            ],
            'help' => 'Formats valides : jpeg, png',
        ]);
        ;
```

Result : 
![image](https://user-images.githubusercontent.com/53140475/91641996-221ae200-ea28-11ea-87f8-e5cf15313cee.png)

Which `label` option are you talking about?

**Comment by garak** [comment]
"Palette de couleurs" is your label

**Comment by bastien70** [comment]
> "Palette de couleurs" is your label

Mmh yeah but it is showing on the top on my input. I want the filename in my input fil.

"Palette de couleurs" is just the signification of my field part

**Comment by garak** [comment]
Well, you can't get a pre-filled value inside an input file.
This is a limit of HTML specs, not of this bundle.

**Comment by bastien70** [comment]
> Eh bien, vous ne pouvez pas obtenir une valeur pré-remplie dans un fichier d'entrée.
> Il s'agit d'une limite de spécifications HTML, pas de cet ensemble.

I want this : 
![image](https://user-images.githubusercontent.com/53140475/91642124-0b28bf80-ea29-11ea-9f21-56356ca10ffe.png)

So, when I update my entity, if there is some file input which have already a value, I want set the filename on the input. 

I want to pre-fill the field with the name of the already existing file, to let me know that I already have a file (although the image is also displayed).

I join you on the limit of HTML.

This is why I opened this ticket, in order to create something that can automatically manage all this and put in each file type field, the name of the file already present.

Hence the above piece of code that works, and hence my question "is there a better solution or something the bundle already allows to do to achieve the same result?"

**Comment by garak** [comment]
I understand your target.
Unfortunately, being something opposed to the current standard, it could be a behavior that users can find unexpected.
My advice is to avoid it.
There's no way to accomplish it in this bundle, and it will never be.

**Comment by bastien70** [comment]
Okay I see!
Thanks for your answer ! :)
