### ISSUE TITLE
Remove files async

### ISSUE THREAD

**Issue by chapterjason** [dustin10/VichUploaderBundle#1155]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.15.0
| Symfony version | 5.1.5
| PHP version     | 7.4.9

### Support Question

I currently use the bundle in combination with the `league/flysystem-bundle`. It works great, but I want to delete the files async, a solution would be to use the messenger which I already use, but if I use the `PRE_REMOVE` event, how can I stop the vich uploader from doing his job?

Could also be a Feature request ;)

**Comment by garak** [comment]
Maybe we could add some logic to our Event class, allowing user to set a flag.
Then, after `PRE_REMOVE` is dispatched, we could check for such flag and stop removing accordingly.
