### ISSUE TITLE
Entity updateAt datetime field returns current date instead of database.

### ISSUE THREAD

**Issue by ahmed-bhs** [dustin10/VichUploaderBundle#1159]
**Entity updateAt datetime field returns current date instead of database.**<br><br>
I have an Entity image that stores the date of update in a field called updatedAt. 

        <?php /** @noinspection PhpFullyQualifiedNameUsageInspection */
    
    namespace App\Entity;
    
    use Doctrine\Common\Collections\ArrayCollection;
    use Doctrine\Common\Collections\Collection;
    use Doctrine\ORM\Mapping as ORM;
    use Symfony\Component\HttpFoundation\File\File;
    use Vich\UploaderBundle\Mapping\Annotation as Vich;
    
    /**
     * @ORM\Entity(repositoryClass="App\Repository\ImageRepository")
     * @Vich\Uploadable
     */
    class Image
    {
        /**
         * @ORM\Id()
         * @ORM\GeneratedValue()
         * @ORM\Column(type="integer")
         */
        private $id;
    
        /**
         * @var File
         * @Vich\UploadableField(mapping="images", fileNameProperty="name")
         */
        private $file;
    
        /**
         * @var string
         * @ORM\Column(type="string", length=255)"
         */
        private $name;
    
        /**
         * @var \DateTime
         * @ORM\Column(type="datetime")
         */
        private $updatedAt;
    
        /**
         * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="images", cascade={"persist"})
         */
        private $tags;
    
        public function __construct()
        {
            $this->updatedAt = new \DateTime();
            $this->tags = new ArrayCollection();
        }
    
        public function getId(): ?int
        {
            return $this->id;
        }
    
        public function getFile(): ?File
        {
            return $this->file;
        }
    
        public function setFile(?File $file = null): void
        {
            $this->file = $file;
            if ($file !== null) {
                // It is required that at least one field changes if you are using doctrine
                // otherwise the event listeners won't be called and the file is lost
                $this->updatedAt = new \DateTime();
            }
        }
    
        public function getName(): ?string
        {
            return $this->name;
        }
    
        public function setName(?string $name): self
        {
            $this->name = $name;
    
            return $this;
        }
    
        public function getUpdatedAt(): ?\DateTimeInterface
        {
            return $this->updatedAt;
        }
    
        public function setUpdatedAt(\DateTimeInterface $updatedAt): self
        {
            $this->updatedAt = $updatedAt;
    
            return $this;
        }
    
        
    }

But when I retrieve it from the database, the updatedAt field shows the current datatime as bellow:

    Image {#646 ▼
      -id: 27
      -file: File {#698 ▶}
      -name: "kPRHHeCVrT.jpg"
      -updatedAt: DateTime @1558609804 {#706 ▼
        date: 2019-05-23 11:10:04.486082 UTC (+00:00)
      }
      -tags: PersistentCollection {#686 ▶}
    }
and a `var_dump($this->updatedAt)` in the getUpdatedAt method shows this: 

    object(DateTime)#626 (3) { ["date"]=> string(26) "2019-05-19 21:17:48.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(3) "UTC" } 

    object(DateTime)#680 (3) { ["date"]=> string(26) "2019-05-23 11:24:12.746548" ["timezone_type"]=> int(3) ["timezone"]=> string(3) "UTC" } 

note the 2 different objects. This is caused by the inject on load linstner whish call the setFile() functionand tben updating the updateAt field.
Is there a way to stop updating the updateAt field when we retrieve the data from database ?

**Comment by garak** [comment]
Please create a repository with a minimal Symfony project where it's possible to replicate your problem.

**Comment by ahmed-bhs** [comment]
@garak Thank you very much for your consideration, I just created a minimal <a href="https://github.com/ahmed-bhs/vich-demo">demo project</a>, where you can reproduce the problem. You can simply follow the steps is explained at the readme.md level. Cheers!

**Comment by garak** [comment]
Thank you, demo project is perfect.
I played with it a bit and found that adding `nullable=true` to imageName doctrine mapping fixes the problem.

**Comment by garak** [comment]
I have to amend my previous comment: after reverting my change to doctrine mapping, everything is working again.
At this point, really, I don't know how this could be possible, but I can exclude that is something that depends on this bundle (rather it should depend on Doctrine)

**Comment by ahmed-bhs** [comment]
Thank you so mush for your time, In fact changing the `nullablle` property to true didn't solve the problem for me. 
I can say that the `FileInjector` is calling `setFile()` function with a non-null argument so this line `$this->updatedAt = new \DateTime(); `gonna always executed that's why the updatedAt field is updated with the current new datetime.

Just one last question, If we change the setFile() function like this, do you think will there be kind of regressions :
```
   public function setImageFile(?File $imageFile = null): void
    {
        if (null !== $this->imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTime();
        }
        $this->imageFile = $imageFile;
    } 
```
Cheers!

**Comment by garak** [comment]
First, let me say that `setFile()` method is *your* method. You can avoid it completely (if you can) or you can change it to suit your needs.
Then, I fail to see how checking for previous version of `$this->imageFile` can help you here, it would imply that if image is changing (e.g. is not new) you don't update time and so change is not triggered.

**Comment by garak** [comment]
@ahmed-bhs would you mind to share how did you manage to solve?
