### ISSUE TITLE
"[ErrorException] Trying to access array offset on value of type null" when "composer recipes  vich/uploader-bundle"

### ISSUE THREAD

**Issue by Whiax** [dustin10/VichUploaderBundle#1164]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.15
| Symfony version | 5.1
| PHP version     | 7.4.0

#### Summary

I launch "composer recipes  vich/uploader-bundle". I get " [ErrorException] Trying to access array offset on value of type null".

#### Current behavior

I get " [ErrorException] Trying to access array offset on value of type null".

#### How to reproduce

I just tried installing VichUploaderBundle with all things updated

#### Expected behavior

The installation should proceed correctly and create the configuration file.

**Comment by garak** [comment]
Sorry, I can't reproduce

**Comment by Whiax** [comment]
> Sorry, I can't reproduce

It seems to be an error with PHP 7.4. I managed to use / update multiple recipes but VichUploaderBundle and symfony/apache-pack both give me the same ErrorException. Are you trying to reproduce with PHP7.4?

**Comment by garak** [comment]
Tried with: PHP 7.4, VichUploaderBundle 1.15, Symfony 5.2-rc1

**Comment by garak** [comment]
> How could I try to debug it myself? (I don't have a traceback to see where it fails)

You can try with `-vvv` flag

**Comment by Whiax** [comment]
Ok here is the trace, I'll try to look into it

```
Exception trace:
 () at wamp64\www\XXX\vendor\symfony\flex\src\Command\RecipesCommand.php:186
 Composer\Util\ErrorHandler::handle() at wamp64\www\XXX\vendor\symfony\flex\src\Command\RecipesCommand.php:186
 Symfony\Flex\Command\RecipesCommand->displayPackageInformation() at wamp64\www\XXX\vendor\symfony\flex\src\Command\RecipesCommand.php:96
 Symfony\Flex\Command\RecipesCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:310
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:122
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:63
 require() at ComposerSetup\bin\composer.phar:24
```

**Comment by garak** [comment]
I see a reference to `$recipeLock['version']` in RecipesCommand.php:186.
You can try to debug there.

**Comment by Whiax** [comment]
It's on a line with "$recipeLock['version']". When I var_dump $recipeLock I get "NULL"

**Comment by Whiax** [comment]
The name is ok: "vich/uploader-bundle" in var_dump. But after "$recipeLock = $this->symfonyLock->get($recipe->getName());"
$recipeLock is NULL.

**Comment by Whiax** [comment]
I guess this is more a problem coming from flex, but some packages worked.

If I do "$version = $recipeLock['version'] ?? null;" and replaces $recipeLock['version'] where it was used before. The command "composer recipes vich/uploader-bundle" works.
But the command "composer recipes:install symfony/apache-pack --force -v" doesn't.
It shows
```
    Do you want to execute this recipe?
    [y] Yes
    [n] No
    [a] Yes for all packages, only for the current installation session
    [p] Yes permanently, never ask again for this project
    (defaults to n):

  [Symfony\Component\Console\Exception\RuntimeException]
  Aborted

```
With the final trace at:
C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Helper/QuestionHelper.php:148

But I don't really get how to solve it this time

**Comment by Whiax** [comment]
Ok fixed it.

(1) set
`$version = $recipeLock['version'] ?? null;`
in RecipesCommand.php

(2) replace $recipeLock['version'] with $version wherever it appears in RecipesCommand.php

(3) replace $answer = $this->io->askAndValidate([....ETC....]); by $answer = 'y'; in Flex.php.

Now the config file for VichUploaderBundle creates correctly.
This was more a flex problem I guess.
Thanks for the indication for debugging composer.
