### ISSUE TITLE
Add a way to avoid upload in tests.

### ISSUE THREAD

**Issue by VincentLanglet** [dustin10/VichUploaderBundle#1165]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes (?) 
| BC Break    | no

#### Summary

I'm using VichUploader with KnpGaufrette and Amazon AWS S3.

I recently got an error in my tests functional because the `putObject` request couldn't be done on Amazon.
Of course, I didn't add the Amazon User/Pass in my env.test file.
But I don't want to make request during these tests.

So I trying to avoid this by overriding the `storage` in my test config.
I tried `storage: flysystem` but I still get some errors.

So I was wondering if a `storage: mock` could be added ?
This storage would do nothing ! This allow to use
```
vich_uploader:
    storage: gaufrette
```
in the config and override this in config.test to
```
vich_uploader:
    storage: mock
```

I assume it would be hard, and need a basic implementation of the interface StorageInterface

WDYT @garak ?

**Comment by garak** [comment]
Usually, during tests you configure storage to save files to filesystem

**Comment by VincentLanglet** [comment]
> Usually, during tests you configure storage to save files to filesystem

Filesystem wasn't working because I sometime create my own `UploadedFile` like in this issue.
https://github.com/dustin10/VichUploaderBundle/issues/735

Seems like it works well with gaufrette but not with filesystem.
I'll try `new Uploaded(..., ..., null, null, true)`.
