### ISSUE TITLE
Vich\UploaderBundle\Form\Type\VichImageType

### ISSUE THREAD

**Issue by endidev** [dustin10/VichUploaderBundle#1166]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.15.0 
| Symfony version | 5.1.8  
| PHP version     | 7.4.12

### Support Question

My project work with easy admin 3.1, on my local works great, I can upload, delete, edit images, but when I pass the project to production won't let me enter to the 'Create/Edit' option on any entity with images on my dashboard

Throw me the next error, 
An error has occurred resolving the options of the form "Vich\UploaderBundle\Form\Type\VichImageType": The options "upload_dir", "upload_filename" do not exist. 
But that file is on vendor, I don't know how to fix it.

Some people ask me if I edit my services.yaml or my easy_admin.yaml, the answer is no. I manage my CRUD from the dashboard, and each entity has his own crud. 
I pass the last 2 days trying to fix it, but i can't, so I add my StackOverflow question, so u can see more in detail, https://stackoverflow.com/questions/64934444/vichuploaderbundle-form-type-vichimagetype-error-produccion?noredirect=1#comment114806235_64934444
My apologize if this should not be here.

**Comment by garak** [comment]
It looks like easyadmin is trying to pass invalid options to VichImageType.

**Comment by arandapablodamian** [comment]
I fix this problem downgrading the version of easyadmin 3.1 to the version 3.0 with al its dependencies with the composer. I execute composer require easycorp/easyadmin-bundle 3 --with-all-dependencies

**Comment by endidev** [comment]
> 
> 
> I fix this problem downgrading the version of easyadmin 3.1 to the version 3.0 with all its dependencies with composer. I execute composer require easycorp/easyadmin-bundle 3 --with-all-dependencies

Yup, the error was on easyAdmin version, I fix it a few moments ago, I close this issue, thx for your help.
