### ISSUE TITLE
Support for league/flysystem v2.0

### ISSUE THREAD

**Issue by WolfgangDrescher** [dustin10/VichUploaderBundle#1177]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | probably yes

#### Summary

As `league/flysystem` and the corresponding symfony bundle `league/flysystem-bundle` released recently version 2.0. It would be nice if the VichUploaderBundle would support these new version as well. What I experienced so far is that the `League\Flysystem\FilesystemInterface` does no longer exist in `Vich\UploaderBundle\Storage\FlysystemStorage`.

**Comment by mewebstudio** [comment]
I have the same problem.

**Comment by digitaltim-de** [comment]
Same Issue here

**Comment by fullbl** [comment]
How should it be done?

It's possible to create another storage (FlysystemV2Storage), but I see a set of problems:
- version 2 of FilesystemOperator (the old FilesystemInterface) doesn't allow to get the adapter, so don't know how to find the full path in doResolvePath method
- how can we test them? It's not possible to require two versions of the same package!
- is it possible to check which version of the bundle the user have to automatically load the right storage?

**Comment by garak** [comment]
@fullbl the idea is to drop v1 and support only v2 from next minor version

**Comment by digitaltim-de** [comment]
Any fix here in WIP?
