### ISSUE TITLE
How to get the "upload_destination" variable from a service ?

### ISSUE THREAD

**Issue by GaylordP** [dustin10/VichUploaderBundle#1181]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.16
| Symfony version | 5.2
| PHP version     | 7.4

I'm sorry for the simplicity of the question, I searched a lot without getting an answer.

How to get the `upload_destination` variable from a service on Symfony? I can't find the VichUploaderBundle service to get this data.

**Comment by garak** [comment]
You can use `Vich\UploaderBundle\Mapping\PropertyMappingFactory` service.
Example:
```php
/** @var Vich\UploaderBundle\Mapping\PropertyMappingFactory $factory */
$mappings = $factory->fromObject($myUploadableObject);
$destination = $mappings[0]>getUploadDestination()
```
