### ISSUE TITLE
Cannot store records to database while using CollectionType form type

### ISSUE THREAD

**Issue by msrumon** [dustin10/VichUploaderBundle#1183]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.16.1
| Symfony version | 5.2.3
| PHP version     | 7.4.14

### Support Question

I am having problem uploading and storing multiple files while each file related to one entity. I have created [this repository](https://github.com/msrumon/vich-issue) and explained almost everything about it there.

**Comment by garak** [comment]
Try this patch
```diff
diff --git a/src/Controller/HomeController.php b/src/Controller/HomeController.php
index 6436131..3c12463 100644
--- a/src/Controller/HomeController.php
+++ b/src/Controller/HomeController.php
@@ -23,7 +23,6 @@ class HomeController extends AbstractController
         for ($i = 0; $i < 3; $i++) {
             $bar = new Bar();
             $foo->addBar($bar);
-            $em->persist($bar);
         }
 
         $form = $this->createForm(FooType::class, $foo);
diff --git a/src/Entity/Foo.php b/src/Entity/Foo.php
index 788141e..3ce2a08 100644
--- a/src/Entity/Foo.php
+++ b/src/Entity/Foo.php
@@ -21,8 +21,11 @@ class Foo
     private $id;
 
     /**
-     * @ORM\OneToMany(targetEntity=Bar::class, mappedBy="foo", orphanRemoval=true)
+     * @ORM\OneToMany(targetEntity=Bar::class, mappedBy="foo", orphanRemoval=true, cascade={"persist"})
      * @Assert\Valid
+     * @Assert\All({
+     *     @Assert\NotNull
+     * })
      */
     private $bars;

```

**Comment by msrumon** [comment]
Don't know why, but my problem went away at msrumon/vich-issue@35c1418ee1caa4e3d0bf4d3a4ea32166a680fd3e. Do you know the reason? Because I thought both the following means the same thing:

- Add `cascade={"persist"}` with `@OneToMany` annotation.
- Call `persist()` with non-persisted entity.

Thanks and best regards.
