### ISSUE TITLE
Entity Updated in UnitOfWork because of file injection

### ISSUE THREAD

**Issue by cjprinse** [dustin10/VichUploaderBundle#1195]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.11.0
| Symfony version | 4.4
| PHP version     | 7.4.12

### Support Question

Our entities are getting updated, after loading the entity.
this is because of we set the updated_at field of the entity when setting the file, as stated as best practise.

```php
public function setFile(?File $file = null): void
    {
        $this->file = $file;
        if ($file !== null) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTime();
        }
    }
```

This method is called in the injectListener

```php
foreach ($this->getUploadableFields($object) as $field) {
            $this->handler->inject($object, $field);
}
```

Which will eventually go to Vich\UploaderBundle\Mapping\PropertyMapping::setFile

```php
public function setFileName($obj, string $value): void
{
    $this->writeProperty($obj, 'name', $value);
}

```

Because of this uses the PropertyAccessor, the Entity method will be called. This will trigger the change in updatedAt, and the entity will be part of the unit of work

**Comment by garak** [comment]
What is the question?

**Comment by cjprinse** [comment]
The issue is that the entity is changed due to a initial load from the database. I think this is an unwanted side effect.
Is there any workaround?

**Comment by garak** [comment]
> The issue is that the entity is changed due to a initial load from the database. I think this is an unwanted side effect.
> Is there any workaround?

Please provide a way to reproduce your problem.

**Comment by garak** [comment]
Closing for missing feedback
