### ISSUE TITLE
 Transfer record from one entity to another without deleting uploaded file

### ISSUE THREAD

**Issue by abrahamsomx** [dustin10/VichUploaderBundle#1196]
I have a problem, I need to transfer a record from one entity to another which is like the history of the first. In that record there is the link to a file uploaded to the server and I use the delete_on_remove property. When I copy the info to the new entity and delete the record the file is deleted (as it should) is there a way to momentarily avoid this?

|    Q            |   A
|---------------- | ------
| Bundle version  | 1.17
| Symfony version | 5.2
| PHP version     | 7.3.21

**Comment by garak** [comment]
I guess you can get the file from original entity and then set it in the new one.
Something like:
1) get entity A
2) get file from A
3) copy A to B
4) delete A
5) set file into B

**Comment by abrahamsomx** [comment]
Thanks !!!
