### ISSUE TITLE
How can I delete the files from filesystem and entity when the entity has a certain status?

### ISSUE THREAD

**Issue by parijke** [dustin10/VichUploaderBundle#1200]
I cannot seem to find how I can delete a phisical file when an entity has a certain status. I want to delete attached files from entities that has status 'xyz'. So I retrieve them trough the repository, then loop over them.

Then how do I delete the file from the entity (setting the file property to null I guess). That removes the connection between the entity and the file, but not the file itself.

How to appropiate delete the actual file?

**Comment by garak** [comment]
You can use `vich_uploader.upload_handler` service.

**Comment by parijke** [comment]
Thanks that worked
