### ISSUE TITLE
image display problem in the front-end part

### ISSUE THREAD

**Issue by beedigital2019** [dustin10/VichUploaderBundle#1203]
i have trouble displaying the image in the angular framework part while it works in the symfony part. it only displays iri example: / api / media_object/1

**Comment by garak** [comment]
Please provide a concrete use case

**Comment by fd6130** [comment]
You should append the hostname by your own. Either append it using `$request->getSchemeAndHttpHost() ` or hard code url.

**Comment by garak** [comment]
Closing for missing feedback
