### ISSUE TITLE
Namer for VichUploader with EasyAdmin 3 not working

### ISSUE THREAD

**Issue by Cyberzip** [dustin10/VichUploaderBundle#1208]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.17.1
| EasyAdmin version | 3.3
| Symfony version | 4.4
| PHP version     | 7.4.18

### Support Question

After following every instructions on Symfony Docs [https://symfony.com/doc/2.x/bundles/EasyAdminBundle/integration/vichuploaderbundle.html], the images could be uploaded, deleted and edited, but they cannot be renamed. So Namer found on
[https://github.com/dustin10/VichUploaderBundle/blob/master/docs/namers.md] doesn't work either. Without renaming files, uploading them is pointless, when naming conflicts arise. Should I downgrade to Easy Admin 2 or to a previous VichUploader version for that to work? 

![image](https://user-images.githubusercontent.com/72373550/120285764-a27bb580-c2ce-11eb-861b-996a7a0b81fc.png)
![image](https://user-images.githubusercontent.com/72373550/120285995-deaf1600-c2ce-11eb-8df0-02e065ced4fd.png)
![image](https://user-images.githubusercontent.com/72373550/120286207-0b632d80-c2cf-11eb-81b5-fc973bdb76f1.png)

**Comment by garak** [comment]
Try to clear your cache

**Comment by Cyberzip** [comment]
![cache](https://user-images.githubusercontent.com/72373550/120294097-ec689980-c2d6-11eb-955c-9145624c47cb.png)
Done that. No effect.
Should I downgrade to a EasyAdmin version on which Namer was still working, should anyone know which?

**Comment by garak** [comment]
I don't know EasyAdminBundle, but I can't imagine a way it can disable the namer. If you see that your configuration is applied (via `console debug:conf`, the namer must work.

**Comment by scuben** [comment]
I currently face the same problem. An active namer makes the listener not working. I do not know why (yet) but keep you posted.

**Comment by Cyberzip** [comment]
![namer1](https://user-images.githubusercontent.com/72373550/121694297-0a09e000-cadb-11eb-82ec-8d84648ec351.png)
![namer2](https://user-images.githubusercontent.com/72373550/121694301-0b3b0d00-cadb-11eb-956c-d186c5748923.png)
![namer3](https://user-images.githubusercontent.com/72373550/121694307-0d04d080-cadb-11eb-97ac-8f4f706668e7.png)

For those who still cannot rename their uploaded files, I stumbled across setUploadedFileNamePattern() on this [blog](https://symfonyquestions.com/2020/12/14/symfony-5-easyadmin3-field-imagefield-how-not-to-delete/). It is weirdly absent yet from the official EasyAdmin Docs. However, it works and evidently is present in the EasyAdmin vendor files, (../vendor/easycorp/easyadmin-bundle/src/Field/ImageField.php). I thank [Garak](https://github.com/garak) though for responding.
