### ISSUE TITLE
UniqueEntity does not work on file name

### ISSUE THREAD

**Issue by ahmed-bhs** [dustin10/VichUploaderBundle#1211]
### Support Question

Is it normal that validation via `@UniqueEntity("imageName")` constraint does not work
 when uploading an image ! Any hint!

**Comment by garak** [comment]
If that property contains the name of your uploaded file, you should rely on a namer instead

**Comment by ahmed-bhs** [comment]
@garak thank you, for you answer, so I need to process validation of the unique imageName inside a namer ? does there any example !

**Comment by garak** [comment]
You simply needs to ensure unique names. Using one of provided namers should be enough
