### ISSUE TITLE
Packagist is not updated with last modification (php8 attributes support)

### ISSUE THREAD

**Issue by davidnurdin** [dustin10/VichUploaderBundle#1224]
Hi,

The last version on packagist is 1.18.0 released on 04 jun 2021 and doesn't include the php8 attributes fixes added on github on 25 jun 2021 (commit : 09bf36d).

Can you update packagist please?

Thanks

**Comment by garak** [comment]
Indeed, 1.18.0 is the latest tag we released.
I'm afraid packagist can't publish versions before we do.

**Comment by guilliamxavier** [comment]
@davidnurdin:

> The last version on packagist is 1.18.0 released on 04 jun 2021 and doesn't include the php8 attributes fixes added on github on 25 jun 2021 (commit : https://github.com/dustin10/VichUploaderBundle/commit/09bf36df903a779ca1ccf43f44857e3a10193798).

Actually it doesn't include php8 attributes support at all (commit: https://github.com/dustin10/VichUploaderBundle/commit/6d65be2d6f07294bbe7f5ef900876d0ef1159690).

@garak:

> I'm afraid packagist can't publish versions before we do.

I guess the question intent was more like "Can you release a new version (with php8 attributes support) please?"

(Personally I'm more looking forward to https://github.com/dustin10/VichUploaderBundle/commit/437407b2d53a9cca931da8433a5e4bc9e2fc073b)

**Comment by garak** [comment]
> I guess the question intent was more like "Can you release a new version (with php8 attributes support) please?"

Just use `-dev` alias and you'll get it. No need to wait for a new release.
