### ISSUE TITLE
The file upload is not picked up, if the file is the only field that has changed

### ISSUE THREAD

**Issue by WishCow** [dustin10/VichUploaderBundle#123]
If you have a user model, that has 4 attributes:
- id
- name
- picture
- picturePath

Id, name, and picturePath are persisted through Doctrine, the picture attribute is the one with the @Vich/UploadableField annotation, and has "picturePath" as its fileNameProperty attribute.

Create a form for this entity, then upload a new file, and modify nothing else on the form. The change will not be picked up. This is because the UploaderListener is listening on the prePersist and preUpdate events, which are never fired, since the only field that is modified by the form is the "picture" field, which is not mapped by Doctrine.

**Comment by DavidM974** [comment]
Hi, i'm testing your bundle and when i save my Image entity the file is lost. My conf is like the exemple. Is it possible that my event listener is not call? even if my updatedAt is update in my database?

**Comment by K-Phoen** [comment]
@DavidM974 Can you open a new issue for your problem? Giving us your configuration would be nice too :)

**Comment by DavidM974** [comment]
Thanks for your quick answer my bad! 
i forgot  the annotation on the class ...  
 ` * @Vich\Uploadable
 */
class Image
{`

Now it works!
