### ISSUE TITLE
"Mapping not found for field" after update to doctrine bundle 2.5.0

### ISSUE THREAD

**Issue by janwebdev** [dustin10/VichUploaderBundle#1236]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | yes
| Bundle version  | 1.18.0
| Symfony version | 4.4.33
| PHP version     | 8.0.13

#### Summary

after update of project to doctrine bundle 2.5.0 all Vich mappings raise an exception "Mapping not found for field"
#### Current behavior

all Vich mappings raise an exception "Mapping not found for field".
this happens only after the cache of project has been generated

#### How to reproduce

```
/**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @Assert\NotBlank(groups={"UserAvatar"}, message="You haven't uploaded new image")
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * @Vich\UploadableField(mapping="users", fileNameProperty="image")
     * @var File
     */
    private $imageFile;
```

#### Expected behavior

no exception as before update

**Comment by bobvandevijver** [comment]
I think you also updated `jms/metadata` to 2.6.0, which is breaks BC. See https://github.com/schmittjoh/metadata/issues/108.

**Comment by janwebdev** [comment]
> I think you also updated `jms/metadata` to 2.6.0, which is breaking BC. See [schmittjoh/metadata#108](https://github.com/schmittjoh/metadata/issues/108).

Thank for your reply. No, not using JMS at all in project

**Comment by bobvandevijver** [comment]
@janwebdev That would be impossible as this bundle requires it ;)

https://github.com/dustin10/VichUploaderBundle/blob/dbfe95c7cbe04def86b2e64a5c5ff6c9bb9f515d/composer.json#L20

Anyways, I have the exact same error, but the fix is inbound @ jms.

**Comment by janwebdev** [comment]
@bobvandevijver Thatnks a lot for your help. It is fixed now ))
