### ISSUE TITLE
Support PHP 8.1

### ISSUE THREAD

**Issue by tacman** [dustin10/VichUploaderBundle#1239]
FILTER_SANITIZE_STRING is deprecated, it is used in createDownloadResponse() in DownloadHandler.php

https://stackoverflow.com/questions/69207368/constant-filter-sanitize-string-is-deprecated

Is there another way to handle that?  I don't completely follow what this method does, and am wondering if the string manipulation is still needed.

**Comment by garak** [comment]
Fixed in latest version
