### ISSUE TITLE
[php][phan][PhanAccessMethodInternal]

### ISSUE THREAD

**Issue by guelosuperstart** [dustin10/VichUploaderBundle#1241]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | dev-master 7116d1b
| Symfony version | 5.4
| PHP version     | x8.0.13

#### Summary

Problem with php pahn

#### Current behavior

When i run phan, i get these errors   :

`PhanAccessMethodInternal Cannot access internal method \Vich\UploaderBundle\Mapping\Annotation\Uploadable::__construct() of namespace \Vich\UploaderBundle\Mapping\Annotation defined at vendor/vich/uploader-bundle/src/Mapping/Annotation/Uploadable.php:21 from namespace \App\Entity`

`PhanAccessMethodInternal Cannot access internal method \Vich\UploaderBundle\Mapping\Annotation\UploadableField::__construct() of namespace \Vich\UploaderBundle\Mapping\Annotation defined at vendor/vich/uploader-bundle/src/Mapping/Annotation/UploadableField.php:58 from namespace \App\Entity\Customer`

#### How to reproduce

```php
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Doctrine\ORM\Mapping as ORM;
use App\Validator\Constraints\ImagesProperties;

#[ORM\Entity]
#[Vich\Uploadable]
class MediaObject
{
    #[ORM\Id, ORM\Column(options: ['unsigned' => true]), ORM\GeneratedValue]
    #[Groups(['default', 'id'])]
    protected int $id;

    public ?string $contentUrl = null;

    #[ImagesProperties]
    #[Vich\UploadableField(mapping: 'media_object', fileNameProperty: 'filePath')]
    public File $file;

    #[ORM\Column]
    public ?string $filePath = null;
}
```

**Comment by garak** [comment]
What do you expect?

**Comment by guelosuperstart** [comment]
I would like that #[Vich\Uploadable] and #[Vich\UploadableField] not to generate errors :p with phan analyzer (https://github.com/phan/phan)

Thank you.

**Comment by garak** [comment]
We're using phpstan here, and it doesn't complain.
Feel free to open a PR to solve your problem.

**Comment by guelosuperstart** [comment]
I think the problem is caused by the annotation `@internal`. Normally we dont have to use / access a method with `@internal`.
it's so why PHAN isn't happy ... :p 

`PhanAccessMethodInternal Cannot access internal method`

```php
/**
 * Uploadable.
 *
 * @Annotation
 * @Target({"CLASS"})
 * @NamedArgumentConstructor
 *
 * @author Dustin Dobervich <ddobervich@gmail.com>
 * @final
 *
 * @internal
 */
#[\Attribute(\Attribute::TARGET_CLASS)]
class Uploadable implements AnnotationInterface
{
}
```

**Comment by garak** [comment]
It looks like it's more a problem with phan than VichUploaderBundle

**Comment by kappaj** [comment]
I think @guelosuperstart is right. `@internal` marks the annotation for internal use only and not for public. But it is needed to be public. My IDE (Intellij/PHPStorm) also marks this as a problem.

![internal](https://user-images.githubusercontent.com/11064439/146333616-952fc89b-03a5-4b97-95c1-41fbc5aaff87.PNG)

**Comment by garak** [comment]
I see.
This needs to be removed, so.
A pull request is welcome

**Comment by garak** [comment]
Can you please check if related PR works for you?
