### ISSUE TITLE
Symfony 6 compatible version

### ISSUE THREAD

**Issue by phiphou** [dustin10/VichUploaderBundle#1245]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

What about a Symfony 6 compatible version ? Tried to update my project but failed because Vich's not compatible.

**Comment by garak** [comment]
Just use our alias for dev

**Comment by garak** [comment]
Sorry, I thought we already merged related PR, but I didn't remember correctly.
See #1237

**Comment by phiphou** [comment]
Any update on this ? 

Composer says me : vich/uploader-bundle 1.18.0 requires symfony/config ^4.4 || ^5.0

**Comment by qdequippe** [comment]
+1 to publish a new release for Symfony 6 support :)

**Comment by garak** [comment]
https://github.com/dustin10/VichUploaderBundle/releases/tag/1.19.0
