### ISSUE TITLE
Vich\UploaderBundle\Mapping\PropertyMapping marked as @internal

### ISSUE THREAD

**Issue by nspyke** [dustin10/VichUploaderBundle#1253]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.19.0
| Symfony version | 4.4
| PHP version     | 8.0

#### Summary

The class \Vich\UploaderBundle\Mapping\PropertyMapping has been marked as `@internal` but it is referenced as an argument in 
both namer interfaces 
- \Vich\UploaderBundle\Naming\DirectoryNamerInterface
- \Vich\UploaderBundle\Naming\NamerInterface

PHPStorm is now showing these types with a strike through and a warning.

I feel that anything that has been used in a public interface should not be marked as internal.

#### Expected behavior
No longer marked as `@internal`

**Comment by garak** [comment]
Thanks for reporting.
Do you mind opening a PR?

**Comment by nspyke** [comment]
#1254
