### ISSUE TITLE
Add dimensions helper functions

### ISSUE THREAD

**Issue by Jupi007** [dustin10/VichUploaderBundle#1255]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I'd like to embedded `Vich\UploaderBundle\Entity\File` in a new project but there's something that holds me back from doing it.
I always like to add some helper functions for the `dimensions` field, to avoid to directly deal with raw array data, like this:

```php
    public function getWidth(): ?int
    {
        if ($this->getDimensions()) {
            return $this->getDimensions()[0];
        }

        return null;
    }

    public function getHeight(): ?int
    {
        if ($this->getDimensions()) {
            return $this->getDimensions()[1];
        }

        return null;
    }
    
    // This one is just a "plus" because I always put image dimensions on each <img> tag to avoid layout shifting
    public function getRenderedHtmlDimensions(): ?string
    {
        if ($this->getDimensions()) {
            return 'width="' . $this->getWidth() . '" height="' . $this->getHeight() . '"';
        }

        return null;
    }
```

Actually, if I want to implement those functions, I need to create my own `Embeddable` class and duplicate all the mapping inside it, and it annoy me a bit.

If you like the idea of those helpers functions, are you open to a PR?

**Comment by garak** [comment]
Yes, please.
