### ISSUE TITLE
Symfony\Bridge\Twig\Extension\AssetExtension Bug

### ISSUE THREAD

**Issue by alichoo** [dustin10/VichUploaderBundle#1269]
|    Q            |   A
|---------------- | ------
 
| Symfony version | 5.3
| PHP version     | 7.3.24

### Support Question

I havegot this error on dev env please help:
Argument 1 passed to Symfony\Bridge\Twig\Extension\AssetExtension::getAssetUrl() must be of the type string, null given

**Comment by garak** [comment]
AssetExtension is not part of this bundle, why you're looking for help here?

**Comment by alichoo** [comment]
hello, because it s such a global extension an error is bothering me and i found good answers here :D

**Comment by garak** [comment]
Don't get me wrong, but this is not a general-purpose Symfony support system.
You can refer to https://symfony.com/support
