### ISSUE TITLE
[RFC] OrignameNamer altering Original Name

### ISSUE THREAD

**Issue by oleg-andreyev** [dustin10/VichUploaderBundle#1274]
#### Summary

Solely based on Namer name, I expect it to use Original Name, but actually it's adding "unique" prefix to the name

#### Current behavior

Namer is adding "unique" prefix

#### Expected behavior

OrignameNamer should not append anything to the original name of a file.

**Comment by garak** [comment]
This is the expected (and documented) behaviour. If you need a different one, you can implement your custom file namer
