### ISSUE TITLE
property_path is not respected

### ISSUE THREAD

**Issue by oleg-andreyev** [dustin10/VichUploaderBundle#1279]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.19.0
| Symfony version | v6.0.6
| PHP version     | 8.1.3

#### Summary

We have following relations - Product 1:* ProductImageMedia *:1 MediaObject
Building for where data_class is ProductImageMedia because it contains fields that do not belong to Media Object
Image preview like this:

```php
->add(
    'file',
    VichImageType::class,
    [
        'property_path' => 'media.file',
        'label' => 'Image',
        'disabled' => true,
        'allow_delete' => false,
    ]
)
```

#### Current behavior

When building an URI for image, VichImageType is validating that "entity" is uploadable, but ProductImageMedia is not uploadable, so using property_path to point to "uploadable" entity.

#### Expected behavior

FormType should respect property_path

**Comment by garak** [comment]
Duplicated of #1273
