### ISSUE TITLE
Make PropertyMapping not as internal.

### ISSUE THREAD

**Issue by laurentmuller** [dustin10/VichUploaderBundle#1287]
The `PropertyMapping` class is marked as `@internal`. When we create a custom file or directory namer, PhpStorm complain about that.:

![PropertyMapping](https://user-images.githubusercontent.com/4330059/166250702-7e061c9f-5822-4ccb-8ac4-dd4c3c7e215f.png)

It is not possible to remove this attribute ?

NB: This is the same for `Transliterator` class.

**Comment by garak** [comment]
Already fixed in e3a612b

**Comment by laurentmuller** [comment]
Sorry. I have not see this PR.

What about `Transliterator` class ?

**Comment by garak** [comment]
> What about `Transliterator` class ?

That should be fixed, too
