### ISSUE TITLE
Migrate existing files into Vich columns?

### ISSUE THREAD

**Issue by UlrichThomasGabor** [dustin10/VichUploaderBundle#1296]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.19.1 
| Symfony version | 6.1
| PHP version     | 8.1

### Support Question

I have to import existing files into newly created columns for Vich via batch processing. This seems to be impossible?

https://github.com/dustin10/VichUploaderBundle/blob/master/src/Handler/UploadHandler.php#L125
Here the `preUpdate` listener just does nothing if the attribute is `File` instead of `UploadedFile`. (I would have expected it to notice that the `File` object of an attribute changed and updated its information with the new `File` object.)

If I try to fake an `UploadedFile`, the validation fails, because Symfony checks if the file really was uploaded:
https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpFoundation/File/UploadedFile.php#L153

Leaving only modifying the columns and moving the files manually?

**Comment by garak** [comment]
I guess you can use your namer, and then update the field accordingly

**Comment by UlrichThomasGabor** [comment]
Well, there are also the other columns, `size`, `dimensions`, `mimeType`, and we also had multiple use-cases in the past that files "uploaded" via other means should be saved into an entry. It's basically not even possible now to write a CLI script `curl`ing images from somewhere and inserting them into an entity without further ado.

I'm unsure how to proceed, but circumventing that regularly feels like a lot of work down the road.

**Comment by UlrichThomasGabor** [comment]
Would it be possible to add an interface `ReplacingFile` (or something like that), which could have concrete classes like `StoredFileForCopy` or `StreamedContent`, and which is being recognized by Vich the same as `UploadedFile` when updating entities?

**Comment by garak** [comment]
Feel free to propose an implementation
