### ISSUE TITLE
Directory namer property based on new entity

### ISSUE THREAD

**Issue by ofeugret** [dustin10/VichUploaderBundle#1297]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.18.0 
| Symfony version | 5.3.3
| PHP version     | 7.4.27

### Support Question

Hello,

I have a form for my entity Company containing file input. I create a subfolder for each company based on its ID.
File upload is working when company already exists.

Is it possible to upload file on **new** company form?
I have the following error and it's normal:

> Directory name could not be generated: property id is empty.

Is there a way to delay file upload after getting the ID of the new company?

Thanks for your help.

**Comment by garak** [comment]
Just avoid having objects with an empty ID

**Comment by fico7489** [comment]
same here
