### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by garak** [dustin10/VichUploaderBundle#1298]
It looks like it's a problem with composer and plugin handing.
See https://github.com/dustin10/VichUploaderBundle/runs/7387753776?check_suite_focus=true#step:5:23

**Comment by endelwar** [comment]
As per CI error:
```
You can run "composer config --no-plugins allow-plugins.symfony/flex [true|false]" to enable it (true) or disable it explicitly and suppress this exception (false)
See https://getcomposer.org/allow-plugins
```

I can prepare a PR to fix this, just tell me if you||VichUploaderBundle trust or not symfony/flex composer plugin (I do) and PR will follow this direction.

**Comment by garak** [comment]
Yes please
