### ISSUE TITLE
Target directory is not created

### ISSUE THREAD

**Issue by Flower7C3** [dustin10/VichUploaderBundle#1316]
In 
https://github.com/dustin10/VichUploaderBundle/blob/6b428642694cbfeb1be6e956ba59382d89ae1ee6/src/Storage/FileSystemStorage.php#L25 the target directory is not created when I use `ReplacingFile` (like described in https://github.com/dustin10/VichUploaderBundle/blob/master/docs/other_usages/replacing_file.md#inject-files-from-other-sources)

**Comment by gdbonino** [comment]
The same for me

**Comment by garak** [comment]
@UlrichThomasGabor do you have an idea about this?

**Comment by UlrichThomasGabor** [comment]
According to a php comment `move_uploaded_file` won't create a directory also, therefore I guess this is not related to the new `ReplacingFile` functionality, but should be a general problem.

What is your `vich_uploader.yaml` content and what is the existing directory structure? I guess you tried to use one of the [directory namers](https://github.com/dustin10/VichUploaderBundle/blob/master/docs/namers.md#directory-namer)?

**Comment by UlrichThomasGabor** [comment]
Should be fixed via #1318
