### ISSUE TITLE
Null error when deleting an uploaded file (removing the corresponding entity object)

### ISSUE THREAD

**Issue by TheoSrz69** [dustin10/VichUploaderBundle#1319]
Hi,

I'm currently trying to use VicheUploaderBundle into a Symfony 6 webapp. And I've something weird when I delete an uploaded file, by removing the matching entity in my repository...

Here is my entity definition (not the methods, only the properties) : 
```
#[ORM\Entity(repositoryClass: InputFileRepository::class)]
#[Vich\Uploadable]
class InputFile
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $filename = null;

    #[ORM\OneToMany(mappedBy: 'inputFile', targetEntity: Log::class)]
    private Collection $logs;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $uploadedAt = null;

    #[Vich\UploadableField(mapping: 'gselector', fileNameProperty: 'filename', size: 'size', mimeType: 'mimeType', originalName: 'originalName')]
    private ?File $file = null;

    #[ORM\Column(length: 255)]
    private ?string $originalName = null;

    #[ORM\Column]
    private ?int $size = null;

    #[ORM\Column(length: 255)]
    private ?string $mimeType = null;
```

I strictly followed all the documentation instructions... And here is my controller : 
```
#[Route('/delete/{id}', name: 'app_delete_file')]
    public function delete_inputFile(InputFile $inputFile): Response
    {
        //try {
            $this->entityManager->remove($inputFile);
            $this->entityManager->flush();
        /*}
        catch (Exception $e)
        {
            dd($e);
        }*/

        return $this->redirectToRoute('app_import_file');
    }
```

Nothing very complex isn't it?  And yet, during execution, there is an error when calling the flush() method : 
![image](https://user-images.githubusercontent.com/8304429/189541163-3a140213-dfd4-42ac-8552-e949bf643141.png)

I don't understand why I got this error on the filename property. Do you think there is an issue with the bundle ?

Thanks for your help.
Regards,

--
Sylvain

**Comment by garak** [comment]
Try adding `nullable` option in the mapping of `$originalName` property.

**Comment by TheoSrz69** [comment]
Hello garak,

Thank you for your answer. I will give a try tonight. 
But, before that, why do you think "originalName" property would be to modify ? Symfony error talk about the "filename" property... As a workaround, I thought this morning that I can only set the delete_on_remove to "false" et delete by myself the file in the folder after removing the entity. Maybe it will work...

**Comment by garak** [comment]
You're right, sorry: try to add it in the `$filename` property

**Comment by TheoSrz69** [comment]
Hello garak !

It's great. I added "?" before all field types into all setter methods. I had to put this nullable for all entity property (because same error occured after "filename" property on "size" property, and so on...). At the moment, it's okay.
Thank you for pointing me in the right direction.

Have a nice day !

**Comment by garak** [comment]
Great.
If you feel the docs can be improved, feel free to open a PR.
Otherwise, I guess we can close this issue.

**Comment by TheoSrz69** [comment]
Yes, good idea ! It would be more clear for other developers.
I have never yet open a PR (not sure to be competent enough for that). But for docs, I will give a try (however, my english is not very good....).

**Comment by TheoSrz69** [comment]
Hi !
I sent a PR (first one !!! yeah !!!). I close this issue now. Very thank you garak !
