### ISSUE TITLE
 Invalid service "vich_uploader.form.type.file"

### ISSUE THREAD

**Issue by Sophikitis** [dustin10/VichUploaderBundle#1323]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.21.1
| Symfony version | 6.1.7
| PHP version     | 8.1

#### Summary

I installed this bundle on my project but when I run `php bin/console lint:container` command it return :

![image](https://user-images.githubusercontent.com/33518344/198883427-0d7f2c41-b463-4a88-9800-ebcfe0176dd6.png)

**Comment by garak** [comment]
Did you install symfony/form as well?

**Comment by Sophikitis** [comment]
oooh I am so stupid ! you are right, I forgot to install the form component.  Sorry for the waste of time.
