### ISSUE TITLE
How to use upload file as email attachment

### ISSUE THREAD

**Issue by zeldystern** [dustin10/VichUploaderBundle#1325]
Hello,

Thank you for your great product!
We used it to upload files to our s3 server and we display the files as needed using the DownloadHandler.
The problem we are having is attaching the uploaded file to an email being sent from the server.
It looks like we need the full path to the file but I don't see how to get that.
What would you recommend as the best way to accomplish this?

**Comment by garak** [comment]
To me this is a subject [for the Mailer](https://symfony.com/doc/current/mailer.html#file-attachments), not for this bundle

**Comment by zeldystern** [comment]
The issue is happening before the Mailer related code. 
The trouble is getting either raw file or path to file locally when using S3 Adaptor, even when inject_on_load is set to true.

**Comment by garak** [comment]
I don't know... if you're able to "display the files", can't you just use the same path with which files are displayed to retrieve them?

**Comment by garak** [comment]
Hello @zeldystern did you solve your problem?

**Comment by zeldystern** [comment]
Thanks for following up! We resolved this by sending the files as links
instead.

Zeldy Stern
***@***.***

Testing and Training International

[image: tti.png]
