### ISSUE TITLE
Vichuploader Background-image 

### ISSUE THREAD

**Issue by juani0824** [dustin10/VichUploaderBundle#1326]
I would like to know how I can retrieve an image from the css, I would like to add the image using the background-image.
I don't know if this is possible.
I appreciate your help.

Thanks.

![image](https://user-images.githubusercontent.com/56587915/200192107-0616bb89-8471-4a50-8c8e-dfa761a66289.png)
 
This is my code : 
Entity Category
![image](https://user-images.githubusercontent.com/56587915/206904063-514145f2-dffa-4cd0-84bd-56f7eb11deac.png)

VichUploader
![image](https://user-images.githubusercontent.com/56587915/206904103-f938de29-60cd-455f-9567-38710b14e247.png)

Services 
![image](https://user-images.githubusercontent.com/56587915/206904114-c57e1969-3e92-41fd-a8f4-7c8213781fa7.png)

Thanks you

**Comment by garak** [comment]
I see HTML in your screenshot, not CSS.
You can use the usual helper provided also in our [documentation](https://github.com/dustin10/VichUploaderBundle/blob/master/docs/generating_urls.md#generating-a-url-in-a-twig-template)

**Comment by garak** [comment]
Hello @juani0824 does my response solve your problem? If so, please close this issue.

**Comment by juani0824** [comment]
No, no he podido resolver el problema todavía, es código html pero la foto quiero recuperarla desde background-image y no sé cómo hacerlo .

**Comment by garak** [comment]
Try this (assuming that `foo` variable contains a reference to your entity)

```twig
<div class="img prix" style="background-image: url({{ vich_uploader_asset(foo) }})"></div>
```

**Comment by juani0824** [comment]
thanks for your answer, but I still have an error.
![image](https://user-images.githubusercontent.com/56587915/206903943-e8570173-7082-4a72-95a7-a7a75fe02278.png)

![image](https://user-images.githubusercontent.com/56587915/206903991-7420effa-f57d-4734-8012-86fa8bf2021e.png)

**Comment by garak** [comment]
I guess that "image" is not the name of your mapped field

**Comment by garak** [comment]
Closing for missing feedback
