### ISSUE TITLE
Manually trigger upload handlers?

### ISSUE THREAD

**Issue by craigh** [dustin10/VichUploaderBundle#1335]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.21.1
| Symfony version | 5.4.x
| PHP version     | 8.1.9

### Support Question

I am using a DTO in _multiple passes_ to fill out a form like a job application. The form is reloaded multiple times via JS. On one of these 'middle' passes, a have the opportunity to upload files (like resume, etc). But on form submission, the DTO doesn't _hydrate_ an `Entity` until the form is fully completed.

It appears that this bundle triggers the upload and mapping procedures with Doctrine event listeners and since I am not hydrating the Entity in the middle steps, the file is not uploaded and mapped. Is there a way to manually trigger the process? And since I will be eventually hydrating an entity and files will already be uploaded, is there a way to disable such triggers at that time?

**Comment by garak** [comment]
I suggest saving the files into a dedicated, temporary entity and then moving them to the desired entity when the process is completed.
Then you'll need to programmatically clear the temporary entity, removing the rows/files, in case someone left the process before finishing it.

**Comment by craigh** [comment]
@garak thank you for the suggestion. I hadn't considered that idea yet, and it may be the easiest solution. However, I am stuck on this part of your idea:
> moving them to the desired entity when the process is completed.

I assume I cannot just copy the filename over from temp entity to desired entity. So, will I need to construct a new `UploadedFile` and pass it to the new entity? (somewhere in my mind I remember this is impossible). Additionally, the temp entity will store files in a different location than the final, so can this bundle handle the move?

**Comment by craigh** [comment]
🙇  Thank you for your suggestions, I was able to make this work with your idea of a dedicated, temporary entity.
