### ISSUE TITLE
Unable to post pictures

### ISSUE THREAD

**Issue by Jsobkowiak** [dustin10/VichUploaderBundle#1340]
|    Q            |   A
|---------------- | ------
| Bundle version  | 2.0.z 
| Symfony version | 6.2.*
| PHP version     | 8.1.z

### Support Question

![image](https://user-images.githubusercontent.com/96530451/207160387-dcdd0175-44ee-4e94-9788-43a5493fe92b.png)

it gives me the code there when I try to send an image

**Comment by garak** [comment]
Please provide the code you're using

**Comment by garak** [comment]
Closing for missing feedback
