### ISSUE TITLE
Final classes not mockable by phpunit

### ISSUE THREAD

**Issue by GCth** [dustin10/VichUploaderBundle#1342]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.0.1

#### Summary

Marking many classes as `final` caused the phpunit to be unable to mock them - which makes some of our tests to fail.

#### Previous behavior

With 1.x bundle version, it was possible to mock UploadHandler

#### Current behavior

```
PHPUnit\Framework\MockObject\ClassIsFinalException: Class "Vich\UploaderBundle\Handler\UploadHandler" is declared "final" and cannot be doubled
```

#### How to reproduce

```
$uh = $this->createMock(UploadHandler::class);
```

It doesn't matter what mappings I use.

**Comment by garak** [comment]
You can use https://packagist.org/packages/dg/bypass-finals
