### ISSUE TITLE
Failing bin/console lint:container without symfony/form component

### ISSUE THREAD

**Issue by Nijusan** [dustin10/VichUploaderBundle#1345]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 2.0.1 
| Symfony version | 6.2.3
| PHP version     | 8.1.11

#### Current behavior

`» bin/console lint:container

In AbstractRecursivePass.php line 173:

  Invalid service "vich_uploader.form.type.file": class "Symfony\Component\Form\AbstractType" not found while loading "Vich\UploaderBundle\Form\Type\VichFileType".

lint:container`

#### How to reproduce

I've installed the minimum project setup of symfony via installer and api platform to build a small api. i installed this bundle as recommended in the api platform docs. and now the lint:container is failing. i think it is because of the missing symfony form component, which i do not need for my project. the component is added to the req-dev section, maybe it should be put to the required section because your implementation is build on top?

**Comment by garak** [comment]
It was changed in ff7a8e8dc5eef061b5a780df511cc62f1988fa62
Do you have any idea @mbrodala ?

**Comment by Nijusan** [comment]
Ok, i've read your changes and disabling form via configuration solves the problem. but then, as mentioned in the PR, the form default setting should be set to false

**Comment by garak** [comment]
> Ok, i've read your changes and disabling form via configuration solves the problem. but then, as mentioned in the PR, the form default setting should be set to false

I'm afraid that having a `false` default is not the best solution: the probability that a user is using forms (i.e. using the full framework) is 95% to me. Moreover, even if the probability would be 50%, we can change that default only in a major version.

I guess that the best solution is a change in the documentation, to highlight the problem you just hit, along with its solution.
You can propose a PR in which you add a note in the index.md ("forms-related" section)

**Comment by Nijusan** [comment]
ok, thanks for your support. i'll try to do a PR this weekend with your suggestion

**Comment by mbrodala** [comment]
Interesting issue, we also use a similar setup and run container lint in our CI without issues. But we have also set `form: false` exactly because we don't use `symfony/form`. Maybe you missed that? If you **do** use `symfony/form`, then you should `require` it and **not** set `form: false` here.

**Comment by garak** [comment]
I think this solves the question.
It's up to the user disabling forms when not in use.

**Comment by veloxy** [comment]
For anyone else landing here:

Lint error is caused when not using symfony forms (eg in an API), vich uploader has optional requiredment on `symfony/form` but because `vich_uploader.form` defaults to `true` it still tries to register form types which causes errors when `symfony/form` is not in your composer packages.

To fix this issue either install `symfony/form` or add this to your config if you're not using the form types at all:

```yaml
vich_uploader:
    form: false
```
