### ISSUE TITLE
  Uncaught Error: Attribute class "ApiPlatform\Core\Annotation\ApiResource" not found

### ISSUE THREAD

**Issue by BossSidi** [dustin10/VichUploaderBundle#1358]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | yes/no
| Bundle version  | 2.0.1 
| Symfony version | 6.2.*
| PHP version     | 8.1

#### Summary

there is a problem with vich, the bundle does not recognize ApiResource in vich/uploader-bundle/src/Metadata/Driver/AttributeReader.php.
Can you help me for this problem?

**Comment by garak** [comment]
Please provide error stack

**Comment by BossSidi** [comment]
Error:
Attribute class "App\Domain\Auth\File\Vich\Uploadable" not found

  at /Users/ousmanesidibe/nabhorelan/vendor/vich/uploader-bundle/src/Metadata/Driver/AttributeReader.php:61
  at ReflectionAttribute->newInstance()
     (/Users/ousmanesidibe/nabhorelan/vendor/vich/uploader-bundle/src/Metadata/Driver/AttributeReader.php:61)
  at Vich\UploaderBundle\Metadata\Driver\AttributeReader->convertToAttributeInstances(array(object(ReflectionAttribute), object(ReflectionAttribute), object(ReflectionAttribute)))
     (/Users/ousmanesidibe/nabhorelan/vendor/vich/uploader-bundle/src/Metadata/Driver/AttributeReader.php:20)
  at Vich\UploaderBundle\Metadata\Driver\AttributeReader->getClassAnnotations(object(ReflectionClass))
     (/Users/ousmanesidibe/nabhorelan/vendor/vich/uploader-bundle/src/Metadata/Driver/AttributeReader.php:25)
  at Vich\UploaderBundle\Metadata\Driver\AttributeReader->getClassAnnotation(object(ReflectionClass), 'Vich\\UploaderBundle\\Mapping\\Annotation\\Uploadable')
     (/Users/ousmanesidibe/nabhorelan/vendor/vich/uploader-bundle/src/Metadata/Driver/AnnotationDriver.php:98)
  at Vich\UploaderBundle\Metadata\Driver\AnnotationDriver->isUploadable(object(ReflectionClass))
     (/Users/ousmanesidibe/nabhorelan/vendor/vich/uploader-bundle/src/Metadata/Driver/AnnotationDriver.php:88)
  at Vich\UploaderBundle\Metadata\Driver\AnnotationDriver->getAllClassNames()
     (/Users/ousmanesidibe/nabhorelan/vendor/jms/metadata/src/Driver/DriverChain.php:57)
  at Metadata\Driver\DriverChain->getAllClassNames()
     (/Users/ousmanesidibe/nabhorelan/vendor/jms/metadata/src/MetadataFactory.php:145)
  at Metadata\MetadataFactory->getAllClassNames()
     (/Users/ousmanesidibe/nabhorelan/vendor/vich/uploader-bundle/src/Metadata/MetadataReader.php:66)
  at Vich\UploaderBundle\Metadata\MetadataReader->getUploadableClasses()
     (/Users/ousmanesidibe/nabhorelan/vendor/vich/uploader-bundle/src/DataCollector/MappingCollector.php:22)
  at Vich\UploaderBundle\DataCollector\MappingCollector->collect(object(Request), object(Response), object(Error))
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/http-kernel/Profiler/Profiler.php:156)
  at Symfony\Component\HttpKernel\Profiler\Profiler->collect(object(Request), object(Response), object(Error))
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/http-kernel/EventListener/ProfilerListener.php:108)
  at Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelResponse(object(ResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:115)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/event-dispatcher/EventDispatcher.php:206)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.response', object(ResponseEvent))
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ResponseEvent), 'kernel.response')
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:127)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ResponseEvent), 'kernel.response')
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/http-kernel/HttpKernel.php:196)
  at Symfony\Component\HttpKernel\HttpKernel->filterResponse(object(Response), object(Request), 2)
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/http-kernel/HttpKernel.php:184)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 2)
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 2, false)
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/http-kernel/EventListener/ErrorListener.php:90)
  at Symfony\Component\HttpKernel\EventListener\ErrorListener->onKernelException(object(ExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:115)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/event-dispatcher/EventDispatcher.php:206)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(ExceptionEvent))
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:127)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/http-kernel/HttpKernel.php:221)
  at Symfony\Component\HttpKernel\HttpKernel->handleThrowable(object(Error), object(Request), 1)
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/http-kernel/HttpKernel.php:114)
  at Symfony\Component\HttpKernel\HttpKernel->terminateWithException(object(Error), object(Request))
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php:125)
  at Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::Symfony\Component\HttpKernel\EventListener\{closure}(object(Error))
     (/Users/ousmanesidibe/nabhorelan/vendor/symfony/error-handler/ErrorHandler.php:538)
  at Symfony\Component\ErrorHandler\ErrorHandler->handleException(object(Error))

**Comment by garak** [comment]
Did you add the use for the Uploadable class?

**Comment by BossSidi** [comment]
Yes I added it at the class level

**Comment by garak** [comment]
Please provide a relevant part of code, and your configuration

**Comment by BossSidi** [comment]
Configuratuon file : vich_uploader.yml
vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    mappings:
        avatars:
            uri_prefix: /upload/user/avatars
            upload_destination: '%kernel.project_dir%/public/upload/user/avatars'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        attachments:
            uri_prefix: /upload/attachements/file
            upload_destination: '%kernel.project_dir%/public/upload/attachements/file'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        conv_cover:
            uri_prefix: /upload/conv_cover/file
            upload_destination: '%kernel.project_dir%/public/conv_cover/file'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        profil_permis:
            uri_prefix: /upload/profil_permis/file
            upload_destination: '%kernel.project_dir%/public/upload/profil_permis/file'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        profil_identity:
            uri_prefix: /upload/profil_identity/file
            upload_destination: '%kernel.project_dir%/public/upload/profil_identity/file'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        media_object:
            uri_prefix: /upload/media
            upload_destination: '%kernel.project_dir%/public/upload/media'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

**Comment by BossSidi** [comment]
<?php

namespace App\Domain\Auth\File;

use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Post;

use App\Domain\Auth\Entity\Profil\Profil;
use App\Domain\Shared\Timestamp;
use App\Http\Controller\MediaObject\CreateMediaObjectAction;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[Vich\Uploadable]
#[ORM\Entity]
#[ApiResource(
    types: ['https://schema.org/MediaObject'],
    operations: [
        new Get(),
        new GetCollection(),
        new Post(
            controller: CreateMediaObjectAction::class,
            openapiContext: [
                'requestBody' => [
                    'content' => [
                        'multipart/form-data' => [
                            'schema' => [
                                'type' => 'object',
                                'properties' => [
                                    'file' => [
                                        'type' => 'string',
                                        'format' => 'binary'
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ],
            validationContext: ['groups' => ['Default', 'media_object_create']],
            deserialize: false
        )
    ],
    normalizationContext: ['groups' => ['media_object:read']],
    paginationClientEnabled: true,
    paginationClientItemsPerPage: 10,
    paginationClientPartial: true,
    paginationEnabled: true,
    paginationItemsPerPage: 10
)]
class MediaObject
{
    #[ORM\Id, ORM\Column, ORM\GeneratedValue]
    private ?int $id = null;

    #[ApiProperty(types: ['https://schema.org/contentUrl'])]
    #[Groups(['media_object:read', 'profil:read', 'user:read'])]
    private ?string $contentUrl = null;

    #[Vich\UploadableField(mapping: "media_object", fileNameProperty: "filePath")]
    #[Assert\NotNull(groups: ['media_object_create', 'profil:write', 'user:read', 'user:write',])]
    private ?File $file = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['media_object:read', 'profil:read', 'user:read'])]
    private ?string $filePath = null;

    #[ORM\OneToOne(mappedBy: "identity", targetEntity: Profil::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    #[Groups(['media_object:read'])]
    private ?Profil $identity = null;

    #[ORM\OneToOne(mappedBy: "identityVerso", targetEntity: Profil::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    #[Groups(['media_object:read'])]
    private ?Profil $identityVerso = null;

    #[ORM\OneToOne(mappedBy: "permis", targetEntity: Profil::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    #[Groups(['media_object:read'])]
    private ?Profil $permis = null;


    #[ORM\OneToOne(mappedBy: "permisVerso", targetEntity: Profil::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    #[Groups(['media_object:read'])]
    private ?Profil $permisVerso = null;

    #[ORM\OneToOne(mappedBy: "carteGrise", targetEntity: Profil::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    #[Groups(['media_object:read'])]
    private ?Profil $carteGrise = null;

    #[ORM\OneToOne(mappedBy: "carteGriseVerso", targetEntity: Profil::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    #[Groups(['media_object:read'])]
    private ?Profil $carteGriseVerso = null;

**Comment by BossSidi** [comment]
#[Vich\Uploadable]
#[ORM\Entity]
#[ApiResource(
    types: ['https://schema.org/MediaObject'],
    operations: [
        new Get(),
        new GetCollection(),
        new Post(
            controller: CreateMediaObjectAction::class,
            openapiContext: [
                'requestBody' => [
                    'content' => [
                        'multipart/form-data' => [
                            'schema' => [
                                'type' => 'object',
                                'properties' => [
                                    'file' => [
                                        'type' => 'string',
                                        'format' => 'binary'
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ],
            validationContext: ['groups' => ['Default', 'media_object_create']],
            deserialize: false
        )
    ],
    normalizationContext: ['groups' => ['media_object:read']],
    paginationClientEnabled: true,
    paginationClientItemsPerPage: 10,
    paginationClientPartial: true,
    paginationEnabled: true,
    paginationItemsPerPage: 10
)]
class MediaObject
{
    #[ORM\Id, ORM\Column, ORM\GeneratedValue]
    private ?int $id = null;

    #[ApiProperty(types: ['https://schema.org/contentUrl'])]
    #[Groups(['media_object:read', 'profil:read', 'user:read'])]
    private ?string $contentUrl = null;

    #[Vich\UploadableField(mapping: "media_object", fileNameProperty: "filePath")]
    #[Assert\NotNull(groups: ['media_object_create', 'profil:write', 'user:read', 'user:write',])]
    private ?File $file = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['media_object:read', 'profil:read', 'user:read'])]
    private ?string $filePath = null;

**Comment by garak** [comment]
Please provide the "use" section as well

**Comment by BossSidi** [comment]
use App\Domain\Auth\Entity\Profil\Profil;
use App\Domain\Shared\Timestamp;
use App\Http\Controller\MediaObject\CreateMediaObjectAction;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
