### ISSUE TITLE
displaying images with VichUploaderBundle in Symfony app prod

### ISSUE THREAD

**Issue by kasali** [dustin10/VichUploaderBundle#1374]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.19.0
| Symfony version | 6.2.7
| PHP version     | 8.2.0

### Support Question

I am having trouble displaying images on different pages in my Symfony app using VichUploaderBundle. The images are stored in the /public/images/annonces directory, and I am able to access them using the URL nomdomaine/symfonyapp/public when I set the url_prefix configuration to ./images/annonces.

However, when I try to access images on a specific page using the URL nomdomaine/symfonyapp/public/annonces/auto, the images do not appear. When I set the url_prefix to ../images/annonces, the images on the specific page appear, but the images in the root directory do not.

I have checked the file permissions and they seem to be correct. Here is the relevant configuration from my config.yaml file:
```
vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        annonce_image:
           uri_prefix: /images/annonces
           upload_destination: '%kernel.project_dir%/public/images/annonces'
           namer: Vich\UploaderBundle\Naming\UniqidNamer 
```

I have also tried adding the following rule to my .htaccess file, but it did not fix the issue:

```
<IfModule mod_rewrite.c>
    # This Option needs to be enabled for RewriteRule, otherwise it will show an error like
    # 'Options FollowSymLinks or SymLinksIfOwnerMatch is off which implies that RewriteRule directive is forbidden'
    Options +FollowSymlinks

    RewriteEngine On

    # Determine the RewriteBase automatically and set it as environment variable.
    # If you are using Apache aliases to do mass virtual hosting or installed the
    # project in a subdirectory, the base path will be prepended to allow proper
    # resolution of the index.php file and to redirect to the correct URI. It will
    # work in environments without path prefix as well, providing a safe, one-size
    # fits all solution. But as you do not need it in this case, you can comment
    # the following 2 lines to eliminate the overhead.
    #comment2
    RewriteBase /topautosntest/public/
    RewriteCond %{REQUEST_URI}::$0 ^(/.+)/(.*)::\2$
    RewriteRule .* - [E=BASE:%1]
    # RewriteCond %{REQUEST_URI} !^/public/
    #RewriteRule ^(.*)$ public/$1 [L]
   # RewriteRule ^images/annonces/(.*)$ public/images/annonces/$1 [L]
    #RewriteRule ^images/annonces/(.*)$ /public/images/annonces/$1 [L]
    #RewriteCond %{DOCUMENT_ROOT}public%{REQUEST_URI} -f
    #RewriteRule !^public/ public%{REQUEST_URI} [L]
    # Sets the HTTP_AUTHORIZATION header removed by Apache
    RewriteCond %{HTTP:Authorization} .+
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%0]

    # Redirect to URI without front controller to prevent duplicate content
    # (with and without `/index.php`). Only do this redirect on the initial
    # rewrite by Apache and not on subsequent cycles. Otherwise we would get an
    # endless redirect loop (request -> rewrite to front controller ->
    # redirect -> request -> ...).
    # So in case you get a "too many redirects" error or you always get redirected
    # to the start page because your Apache does not expose the REDIRECT_STATUS
    # environment variable, you have 2 choices:
    # - disable this feature by commenting the following 2 lines or
    # - use Apache >= 2.3.9 and replace all L flags by END flags and remove the
    #   following RewriteCond (best solution)
    #comment 2
    RewriteCond %{ENV:REDIRECT_STATUS} =""
    RewriteRule ^index\.php(?:/(.*)|$) %{ENV:BASE}/$1 [R=301,L]

    # If the requested filename exists, simply serve it.
    # We only want to let Apache serve files and not directories.
    # Rewrite all other queries to the front controller.
    #comment1
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    #RewriteRule ^ %{ENV:BASE}/index.php [L]
    RewriteRule ^(.*)$ index.php [QSA,L]
    RewriteRule ^images/annonces/(.*)$ public/images/annonces/$1 [L]
</IfModule>
```

What am I doing wrong? How can I fix this issue so that I can display images on all pages in my Symfony app? Any help would be greatly appreciated.

**Comment by garak** [comment]
Please clarify this sentence: "try to access images on a specific page"

**Comment by kasali** [comment]
if the uri_prefix in vich config is : ./images/annonces. All images are displayed when I go domainename/symfonyapp/public but this doesn't work if I go another page like domainename/symfonyapp/public/annonces/auto except i do ../images/annonces in the uri_prefix.

**Comment by garak** [comment]
You're supposing that everyone can understand the meaning of "images are displayed" or "this doesn't work".
If you want help, you need to give a way to understand your situation

**Comment by kasali** [comment]
If you set the uri_prefix configuration in your VichUploaderBundle config file to ./images/annonces, all of the images stored in the /public/images/annonces directory will be displayed correctly when you access your Symfony app using the URL domainename/symfonyapp/public. However, this configuration will not work when you try to access a specific page within your Symfony app, such as domainename/symfonyapp/public/annonces/auto.

To make the images display correctly on this specific page, you need to modify the uri_prefix configuration to ../images/annonces. This will tell Symfony to look for the images one level up from the current directory, which will allow the images to display correctly on the specific page. However, if you go back to the root directory, the images may not display correctly because Symfony will be looking for them in a directory that does not exist.

**Comment by garak** [comment]
Could you please specify how you "make images display"?

**Comment by kasali** [comment]
yeah  i make it this way  ;  ` ` ` {% if annonce.pictures %}
                                                                            {% set picture = annonce.pictures[0] %}
                                                                                <img src="{{ vich_uploader_asset(picture,'imageFile') }}"
                                                                                    class="img-responsive img-thumbnail rounded" width="100%" height="210"
                                                                                    style="height: 210px; width: 100%;" alt="carplaceholder" />
                                                                                 
                                                                        {% endif %}```

**Comment by kasali** [comment]
with this way :  `<img src="{{ vich_uploader_asset(picture,'imageFile') }}"/>`

**Comment by garak** [comment]
The "public" string should not be part of your URL

**Comment by kasali** [comment]
public is a symfony public directory. It's not a string.

**Comment by garak** [comment]
"public" is a string. The name of a directory is a string.
I can only guess (since you don't provide info) that you didn't configure properly your virtual host.

**Comment by kasali** [comment]
Yeah but even I do uri_prefix :/images/annonces. I have the issue. I have no issue in my computer.

**Comment by garak** [comment]
Let's make it short: do you have the same problem if you try to generate the URL for any of your static files, directly with the `asset` helper?

**Comment by kasali** [comment]
i have that only for the images with vichuploder bundle config. The problem comes from the uri_prefix.

**Comment by garak** [comment]
You said you only have this issue only in a specific environment, so the problem Is not with uri_prefix configuration.
Every Symfony request passes from the same front controllers, so there's no match between URL paths and directories.
I suggest you to re-check the way you're using your routes and, again, to properly configure your virtual host, following official Symfony documentation.

**Comment by kasali** [comment]
thanks, i resolved it
