### ISSUE TITLE
MappingNotFound Exception issue

### ISSUE THREAD

**Issue by guizmo51** [dustin10/VichUploaderBundle#1375]
My settings : 
Symfony 6
PHP 8.2
Api-Platform 3
I have that issue with the last V1 (1.22) of VichUploader but also V2. (2.11).

I have an issue (MappingNotFound Exception) when I'm on my prod (Symfony with prod env)
I have two entities with Uploadable PHP attribute. "Map" and "Space". 
Everything is OK on my computer (in DEV and PROD env)
When I release on prod I have a MappingNotFound Exception about the Map entity. I don't know why, I can't reproduce locally.
PHP version are the same...

I can't figure out where is the issue...
Thanks :)

**Comment by garak** [comment]
If the production logs are not enough, you need a way to get the full error stack.
A quick dirty way could be enabling the profiler in prod.

A more clean, and permanent, solution involves the use of https://github.com/getsentry/sentry-symfony package.

**Comment by guizmo51** [comment]
Thanks for your help @garak  I can' provide error stack because that issue is triggered during cache/clear during automatic deployment.
I only have the following trace : 
Run composer recipes at any time to see the status of your Symfony recipes.
> post-install-cmd: @auto-scripts
> auto-scripts: Symfony\Flex\Flex->executeAutoScripts
Executing script cache:clear
Executed script cache:clear  [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!   // Clearing the cache for the prod environment with debug                      
!!   // false                                                                       
!!  
!!   // Cache is fresh.                                                             
!!  
!!   // Warming up optional cache...                                                
!!  
!!  
!!  In MappingNotFoundException.php line 17:
!!                                                                                 
!!    [Vich\UploaderBundle\Exception\MappingNotFoundException]                     
!!    Mapping not found. The configuration for the class "App\Entity\Map" is prob  
!!    ably incorrect.                                                              
!!                                                                                 
!!  
!!  Exception trace:
!!    at /home/deployer/[PROJECT]/releases/43/vendor/vich/uploader-bundle/src/Exception/MappingNotFoundException.php:17
!!   Vich\UploaderBundle\Exception\MappingNotFoundException::createNotFoundForClass() at /home/deployer/[PROJECT]/releases/43/vendor/vich/uploader-bundle/src/Metadata/MetadataReader.php:82
!!   Vich\UploaderBundle\Metadata\MetadataReader->getUploadableFields() at /home/deployer/[PROJECT]/releases/43/vendor/vich/uploader-bundle/src/Metadata/CacheWarmer.php:29
!!   Vich\UploaderBundle\Metadata\CacheWarmer->warmUp() at /home/deployer/[PROJECT]/releases/43/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:99
!!   Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /home/deployer/[PROJECT]/releases/43/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:141
!!   Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /home/deployer/[PROJECT]/releases/43/vendor/symfony/console/Command/Command.php:308
!!   Symfony\Component\Console\Command\Command->run() at /home/deployer/[PROJECT]/releases/43/vendor/symfony/console/Application.php:1032
!!   Symfony\Component\Console\Application->doRunCommand() at /home/deployer/[PROJECT]/releases/43/vendor/symfony/framework-bundle/Console/Application.php:94
!!   Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /home/deployer/[PROJECT]/releases/43/vendor/symfony/console/Application.php:301
!!   Symfony\Component\Console\Application->doRun() at /home/deployer/[PROJECT]/releases/43/vendor/symfony/framework-bundle/Console/Application.php:80
!!   Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/deployer/[PROJECT]/releases/43/vendor/symfony/console/Application.php:171
!!   Symfony\Component\Console\Application->run() at /home/deployer/[PROJECT]/releases/43/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54
!!   Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /home/deployer/[PROJECT]/releases/43/vendor/autoload_runtime.php:29
!!   require_once() at /home/deployer/[PROJECT]/releases/43/bin/console:11
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers]

**Comment by guizmo51** [comment]
Ok, I have updates : on my prod server (I forked in an other directory I reproduced it...) I change the name of the entity "Map" as Carte (Map in French) and now everything is Ok.
I don't know why the word is triggering this kind of thing : (I'm aware about the reserved words but Map as class name is not a reserved words) is it a php settings and in this cas i'm not 100% iso with my prod env ?

**Comment by garak** [comment]
Finally, this seems a problem not related to VichUploaderBundle. Can we close this issue?

**Comment by guizmo51** [comment]
Yes we can close. It was triggered by VichUploader configuration and server sides issues.
