### ISSUE TITLE
Allow not null/uniq mapped fields

### ISSUE THREAD

**Issue by mysterty** [dustin10/VichUploaderBundle#1380]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Actually, vichuploader needs entity's mapped field "filename" to be nullable.

I guess that vichuploader delete file, clean the entity, save it, then set the new file's name in entity's mapped "filename", then save it again.

Maybe it could be more efficient / powerfull to delete file, clean, update, then save only once...

**Comment by garak** [comment]
The nullability is by design. The bundle listen to the Doctrine pre-persist event, so the filename property can't be set before.
