### ISSUE TITLE
Enable error bunbbling in the embebbed file field

### ISSUE THREAD

**Issue by Safranil** [dustin10/VichUploaderBundle#1384]
*This issue refer #1381*

Without the `error_bubbling` in the embedded file field, any error from the field doesn't get displayed in the form.

In my case, I get a size limit by `upload_max_filesize` set in `php.ini` that is hidden by VichUploader in the form but the field is marked as invalid by Symfony Form component.

I'm using the Symfony backed Bootstrap theme and i also got the same behavior without any theme.

The error appear when the file size is greater than `upload_max_filesize`.

![image](https://user-images.githubusercontent.com/4648342/230141738-f54c309b-53fe-426a-9b79-bacbfe7c7ac7.png)
![image](https://user-images.githubusercontent.com/4648342/230142200-d395c998-5b20-4596-8308-725aa444d478.png)

About my environment:
- Symfony 5.4.18
- PHP 8.1.17
- vich/uploader-bundle 2.1.1

Here a simple project similar to mine with the problem:
https://cloud.safranil.fr/s/eLkNj8YXPTS7T4f

### Steps to reproduce

1. Set `upload_max_filesize` to `2M`
2. Set `post_max_size` to a value greater than `8M`
3. Upload the file `33771058105_af4685ee0e_5k.jpg` from the linked archive
4. The error is then added to the file field but not displayed in the page until the bubbling is enabled.

**Comment by Safranil** [comment]
Are you able to reproduce this issue ?\
Do you need more informations about my configuration or my environment ?

**Comment by garak** [comment]
Sorry for the delay, I finally found the time to check your code.
Indeed, if you hit the maximum file size set in php.ini, the error is not bubbled.
But you can easily fix it by adding your constraint (which, by the way, you should always do).

So, I just changed your S class:

```
    #[Vich\UploadableField(mapping: "st", fileNameProperty: "logo")]
    #[Assert\Image(maxSize: '2M')]
    public $logoFile;
```

and the error was properly shown.

**Comment by Safranil** [comment]
Ok, thanks for your advice, this indeed was planned for the next release.

I think my PR is still valid as the constraint can be higher than PHP config permit.

**Comment by garak** [comment]
I can't think of a valid case in which you want to have a constraint which doesn't take into account your php configuration.
Even in that case, you can simply add the bubbling yourself. It's clearly an edge case, so it won't be included in this bundle.

**Comment by Safranil** [comment]
I understand, thank you for your help 😄.
