### ISSUE TITLE
Custom delete checkbox in VichFileType

### ISSUE THREAD

**Issue by laurentmuller** [dustin10/VichUploaderBundle#1386]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I use a custom form type to edit an image. This will be nice if the delete checkbox type in the `VichFileType` can be customized.

In my case, I want to replace the   `CheckboxType` by an `HiddenType` form type. Unfortunately, the addition of the check box type is included in the `buildDeleteField `function.

It is simply matter of creating a new protected function like code below:

```php
protected function addDeleteField(FormInterface $form): void
{
    $form->add('delete', Type\CheckboxType::class, [
        'label' => $options['delete_label'],
        'mapped' => false,
        'translation_domain' => $options['translation_domain'],
        'required' => false,
    ]);
}
```

And call this function:
```php
protected function buildDeleteField(FormBuilderInterface $builder, array $options): void
{
    $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($options): void {
        $form = $event->getForm();
        ...
        $this->addDeleteField($form);
    }
}
```

**Comment by garak** [comment]
Fortunately, you can override bundle templates, no need to wait for a new feature

**Comment by laurentmuller** [comment]
You are right. I already hide the checkbox in the template with the following code:

```twig
{% block vich_image_widget -%}
    ...
    {% if form.delete is defined -%}
        <div class="d-none">{{ form_widget(form.delete) }}</div>
    {%- endif %}
{%- endblock %}
```
But this render the `delete` field as checkbox type; not as hiddent type.

**Comment by garak** [comment]
But is not displayed anyway, right? So, in the end, it's hidden.

**Comment by laurentmuller** [comment]
OK, This is was just to not render a full checkbox and label.

**Comment by garak** [comment]
> OK, This is was just to not render a full checkbox and label.

I see. I think it's not worth adding this feature: after all, it's customization.
