### ISSUE TITLE
Uploading image after checking delete checkbox is not working

### ISSUE THREAD

**Issue by Guervyl** [dustin10/VichUploaderBundle#1387]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  |2.1
| Symfony version | 6.2
| PHP version     | 8.1

#### Summary

After checking the delete checkbox from VichFileType, uploading new image in the form dos not upload the image and does not save the image in the form if no change have made in other fields. In other word, Only upload the image does not save the image.

#### Current behavior

Only uploading the image in the form without changing other fields does not save the image after checking the delete button.

#### How to reproduce

In your update form, only upload a new image without editing any other fields.

#### Expected behavior

It should change the image with the new uploaded one.

**Comment by garak** [comment]
Please check https://github.com/dustin10/VichUploaderBundle/blob/master/docs/known_issues.md

**Comment by Guervyl** [comment]
Thanks.
