### ISSUE TITLE
LifecycleEventArgs getEntityManager() is deprecated.

### ISSUE THREAD

**Issue by laurentmuller** [dustin10/VichUploaderBundle#1393]
### Feature Request

With Symfony 6.3, the method `getEntity()` from the class `LifecycleEventArgs` is deprecated.

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Summary

The `DoctrineORMAdapter` class use the  `getEntity()` function from the `LifecycleEventArgs` class. This must be replaced by the `getObject()` function.

Maybe the adapter must replace the class `\Doctrine\ORM\Event\LifecycleEventArgs` by the `Doctrine\Persistence\Event\LifecycleEventArgs` class. This class have suppressed the `getObject()` function.

**Comment by laurentmuller** [comment]
I see that the last code is already using the `getObject()` function. 

But the function use the `getEntityManager()`. This must be replaced by the `getObjectManager()` function.

**Comment by garak** [comment]
It should be fixed now, right?

**Comment by laurentmuller** [comment]
For me it's OK.

Any release ?

**Comment by mdriessen** [comment]
Looks good to me. Would appreciate a new tagged release, thanks.
