### ISSUE TITLE
Custom VichImageType

### ISSUE THREAD

**Issue by florent6001** [dustin10/VichUploaderBundle#1394]
|---------------- | ------
| Bundle version  | "vich/uploader-bundle": "^2.1"
| Symfony version | 6.3.0
| PHP version     | 8.2.7

### Support Question

Hi, actually i'm trying to implement a logo features in a form, all is working pretty good after some little issue with serialization. But now, i'm facing a problem with VichImageType, actually. If we upload a big image, the image will take all the screen and dont fit to the div. I tryied to add a custom class w-100 on my FormType but it didn't do the trick.

Someone have maybe an idea how to change it ? Here is my current code: 

```
->add('imageFile', VichImageType::class, [
                'label' => $this->translator->trans('Company logo'),
                'required' => false,
            ])
```

```
<div class="col-md-6">
            {{ form_row(form.imageFile) }}
        </div>
```

Here is a screenshot of the result:
<img width="1121" alt="Capture d’écran 2023-06-28 à 04 28 10" src="https://github.com/dustin10/VichUploaderBundle/assets/16673235/445b76ef-9be7-41b9-9904-6a2cda59d1d4">

**Comment by garak** [comment]
You can use a CSS rule with max-width and max-heigth

**Comment by florent6001** [comment]
I don't want to use CSS in that case, i would like to change the html structure.

**Comment by garak** [comment]
So, you can override the template
