### ISSUE TITLE
namer is not optional any more

### ISSUE THREAD

**Issue by oleg-andreyev** [dustin10/VichUploaderBundle#1403]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 2.2.0
| Symfony version | 6.3.x
| PHP version     | 8.1.x

#### Summary

Done upgrade from 1.23.1 to 2.2.0. 
We're getting `A namer must be configured.`

After searching the code found that `\Vich\UploaderBundle\Mapping\PropertyMapping::getUploadName` is now throwing exception if namer is not configured.
Based on diff 
![image](https://github.com/dustin10/VichUploaderBundle/assets/1244112/16dad07d-80c1-4c7e-96c7-110be1fffabd)

There was a warning but for some reason it was not tracked.
But anyway `namer` should be a `required` field so that Symfony Cache won't build.

#### Current behavior

`namer` is optional in configs.

#### Expected behavior

`namer` is not optional in configs and container complications failes.

**Comment by garak** [comment]
It seems that we're missing a call to `isRequired` inside our `Configuration` class.
Do you mind opening a PR to fix it?
