### ISSUE TITLE
updatedAt problem after install vich on a crud

### ISSUE THREAD

**Issue by SamuelVauloup** [dustin10/VichUploaderBundle#1408]
|    Q            |   A
|---------------- | ------
| Bundle version  | 2.2
| Symfony version |  6.3
| PHP version     | 8.2

i try  to use  vich  but i  have an error message on my all crud page who have the vich component : 

Neither the property "updatedAt" nor one of the methods "updatedAt()", "getupdatedAt()"/"isupdatedAt()"/"hasupdatedAt()" or "__call()" exist and have public access in class "App\Entity\Categorie".

i put the .yarl , entity and the form file in a zip
[vich problem.zip](https://github.com/dustin10/VichUploaderBundle/files/13278626/vich.problem.zip)

i started  symfony since 1 week , and don't know how resolve the problem.

`
`

`

**Comment by garak** [comment]
Try to add a method called `getCreatedAt` in your entity, and make it return a value from a mapped property (probably $createdAt)

**Comment by SamuelVauloup** [comment]
i put  a
`    public function getCreatedAt() :?DateTime
    {
        return $this->createdAt;
    }
    
    public function setCreatedAt(DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt() :?DateTime
    {
        return $this->updatedAt;
    }
    
    public function setUpdatedAt(DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }`


 now i have a  new error :

`App\Entity\Categorie::getUpdatedAt(): Return value must be of type ?App\Entity\DateTime, DateTimeImmutable returned`

**Comment by garak** [comment]
So change the return type

**Comment by SamuelVauloup** [comment]
i change the type and add  
"use DateTimeImmutable;" 
on my  entity,  and  now  its work
thanks for help
