### ISSUE TITLE
Support for Symfony 7

### ISSUE THREAD

**Issue by oliveradria** [dustin10/VichUploaderBundle#1413]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

Symfony 7.0.0 with minimum PHP 8.2 has been released. It would be great to see VichUploaderBundle installable in a Symfony 7 setup.

**Comment by RobinDev** [comment]
VichUploader bundle rely on Gauffrette wich is not actively maintained https://github.com/KnpLabs/KnpGaufretteBundle/pulls

**Comment by jcglombard** [comment]
> VichUploader bundle rely on Gauffrette wich is not actively maintained https://github.com/KnpLabs/KnpGaufretteBundle/pulls

You can easily switch to  [league/flysystem-bundle](https://github.com/thephpleague/flysystem-bundle) which is actively maintained ;-)

**Comment by samir-ah** [comment]
I think it would be simpler if you drop support of gaufrette in the next major version

**Comment by garak** [comment]
This PR is meant for the next minor version, so dropping Gaufrette won't help here

**Comment by shambhu384** [comment]
Waiting for release thank you @garak
