### ISSUE TITLE
download_uri should use publicUrl when using FlysytemStorage

### ISSUE THREAD

**Issue by erichard** [dustin10/VichUploaderBundle#1418]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

When using the flysystem storage adapter, we could use the publicUrlGenerator defined on the storage. This way we can get direct url to S3 files or others storage provider.

#### Possible implementation 

From my tests, I think we only need to implement `resolveUri()` method in the `Vich\UploaderBundle\Storage\FlysystemStorage`

**Comment by sovetski** [comment]
Any update on it please?

Also related: https://github.com/dustin10/VichUploaderBundle/issues/1434#issuecomment-2041172155
