### ISSUE TITLE
Removing a file from within the message queue handler

### ISSUE THREAD

**Issue by Jayohhtchen** [dustin10/VichUploaderBundle#1422]
I'm really struggling to delete a file using the message queue as outlined in the docs: https://github.com/dustin10/VichUploaderBundle/blob/master/docs/events/howto/remove_files_asynchronously.md

I don't understand how to delete the file in the handler. What does this mean?
 // delete your file according to your mapping configuration

The entity is removed by this point and all I have is the filename from the message queue. Can someobody help my newb self out. Might be good if there was an example in the docs?

I've tried looking in closed issues, the docs and around the web but not found any examples.

**Comment by Jayohhtchen** [comment]
Thanks Garak. Would that allow me then to use the remove function in the upload Handler?

**Comment by garak** [comment]
> Thanks Garak. Would that allow me then to use the remove function in the upload Handler?

Yep, that's the intended way

**Comment by Jayohhtchen** [comment]
I'm not having much luck with this. I tried the new entity approach but not working for me and the file won't delete. 
I think this is because the remove function triggers off another PRE_REMOVE event and is set to not delete the file, so i'm stuck in an infinite loop of adding new messages to the handler.

It seems like the async method as described in the docs won't actually ever work with the current setup?

With the liipimaginefilters i can just call $this->cacheManager->remove($filename, 'original');  
Is there any plan to implement anything like this to just remove by filename and the mapping you wan't to use?

**Comment by Jayohhtchen** [comment]
Scrap the above, I'm an idiot. I was using the wrong remove function.

Have got it to work using the below:

```

$filename = $message->getFilename();

$photo = new Photos();
$photo->setImage($filename);

$mapping = $this->PropertyMappingFactory->fromField($photo, 'imageFile');
$this->StorageInterface->remove($photo, $mapping);
```

Thank you for your help on this @garak

**Comment by garak** [comment]
Glad you made it.
Can we close this?

**Comment by Jayohhtchen** [comment]
Closing as resolved. Thanks for your help again :)
