### ISSUE TITLE
Installation instructions are outdated

### ISSUE THREAD

**Issue by tacman** [dustin10/VichUploaderBundle#1431]
https://github.com/dustin10/VichUploaderBundle/blob/master/docs/installation.md#enable-the-bundle

These installation instructions are for old, unmaintained versions of Symfony:

```php
// app/AppKernel.php (your kernel class may be defined in a different class/path)
class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = [
            // ...
            new Vich\UploaderBundle\VichUploaderBundle(),
            // ...
        ];
    }
}
```

**Comment by garak** [comment]
Instructions are provided exactly for users of old versions.
If you use a maintained version of Symfony, you're using Flex as well, and the bundle is enabled for you

**Comment by tacman** [comment]
Hmm.  I was following the best practices suggestions here: https://symfony.com/doc/current/bundles/best_practices.html#installation-instructions

Since the bundle only works with Symfony 5.4+, I didn't think those old instructions applied.
