### ISSUE TITLE
Install dose not register in bundle.php

### ISSUE THREAD

**Issue by Adi-18** [dustin10/VichUploaderBundle#1436]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 2.3.1
| Symfony version | 7.0.2
| PHP version     | 8.2.15

#### Summary
After "composer require vich/uploader-bundle" there is no entry in bundle.php like "Vich\UploaderBundle\VichUploaderBundle::class => ['all' => true]"

**Comment by garak** [comment]
This is not a responsibility of this bundle.
Check if your flex is working or enable the bundle manually.
