### ISSUE TITLE
Using pure Annotation Does not Upload the actual file. @Vich\UploadableField

### ISSUE THREAD

**Issue by l0r3nc335** [dustin10/VichUploaderBundle#1438]
### Bug Report

|    Q            |   A
|---------------- | ------
| Bundle version  | 2.3.1
| Symfony version | 5.4^
| PHP version     | 8.1.2

#### Current behavior

Using pure @Vich\Uploadable and @Vich\UploadableField(mapping="images", fileNameProperty="url") Does not upload the temp file to the public/images directory.

And works if I add #[Vich\Uploadable] and #[Vich\UploadableField(mapping: 'images', fileNameProperty: 'url')] the annotation above

**Comment by garak** [comment]
Use the attributes then

**Comment by julienmiclo** [comment]
Since 2.0, you need to do this : the new default type for mapping is "attribute". You can still use annotations, but you need an explicit definition (set "annotation" as value for "vich_uploader.metadata.type" config key)
