### ISSUE TITLE
Files ALWAYS gets downloaded even if `Content-Disposition` is set to `inline`

### ISSUE THREAD

**Issue by DenuxPlays** [dustin10/VichUploaderBundle#1456]
This is due to the unnecessary download attribute in the <a> tag here:
```twig
        {%- if download_uri -%}
            <a href="{{ asset_helper is same as(true) ? asset(download_uri) : download_uri }}" download>
                {{ translation_domain is same as(false) ? download_label : download_label|trans({}, translation_domain) }}
            </a>
        {%- endif -%}
```

It should be
```twig
        {%- if download_uri -%}
            <a href="{{ asset_helper is same as(true) ? asset(download_uri) : download_uri }}">
                {{ translation_domain is same as(false) ? download_label : download_label|trans({}, translation_domain) }}
            </a>
        {%- endif -%}
```

Files still get downloaded but now the `Content-Disposition` gets respected.

**Comment by garak** [comment]
What's the case when Content-Disposition is online?

**Comment by DenuxPlays** [comment]
> What's the case when Content-Disposition is online?

It simply means that the browser tries to open the file inside the browser and if he can't he is still going to download it.

I overwrote your form template and simply removed the download attribute and it works as expected (even when not setting the header/ direct download link)

**Comment by garak** [comment]
So, it seems that the default template works fine with the default headers. If you want something different, overwriting the template is enough.
I don't see any issue here.

**Comment by DenuxPlays** [comment]
> So, it seems that the default template works fine with the default headers. If you want something different, overwriting the template is enough.
> 
> I don't see any issue here.

My issue is that the download Attribute is unnecessary.
It works as expected without it and without it the standard header gets actually respected as expected.

**Comment by garak** [comment]
You already solved it with the custom template. Is there anything else you need?

**Comment by DenuxPlays** [comment]
> You already solved it with the custom template. Is there anything else you need?

I thought this change can be applied directly in the soruce repository.
As I think this is a general improvement/"bug" fix

**Comment by garak** [comment]
The whole point is about what the average user expects to get. The current implementation suits it.
A custom implementation is still possible.
So, I don't see the need for improvements or fixes.

**Comment by DenuxPlays** [comment]
The current experiene does not change.
The user would still get what they expected but okay if you are not open to this change this disscussion is pointless
