### ISSUE TITLE
The object is not uploadable.

### ISSUE THREAD

**Issue by papvan** [dustin10/VichUploaderBundle#147]
Hi,
I have used VichUploaderBundle
I have this error when i'm using field image of my object.
Entity:
<pre>
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Base
 *
 * @Vich\Uploadable
 * @ORM\Entity(repositoryClass="Portal\CoreBundle\Repository\CatalogRepository")
 * @ORM\Table(name="catalog")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *     "category"       = "Category",
 *     "item"           = "Item",
 * })
 */
class Base
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

...

/**
     * @Assert\File(
     *     maxSize="3M",
     *     mimeTypes={"image/png", "image/jpeg", "image/pjpeg"}
     * )
     * @Vich\UploadableField(mapping="catalog_image", fileNameProperty="imageName")
     */
    protected $image;

    /**
     * @ORM\Column(name="image_name", type="string", length=255, nullable=true)
     */
    protected $imageName;

...
</pre>

When i try upload image: The object is not uploadable.

**Comment by K-Phoen** [comment]
Should be fixed now.

**Comment by barbu110** [comment]
Hello! According to [this](https://blog.theodo.fr/2018/06/upload-symfony-aws-s3/), adding the `image` field (as the case is here) should work, but I get the same error no matter what.
