### ISSUE TITLE
Double extension with OrignameNamer

### ISSUE THREAD

**Issue by neufman** [dustin10/VichUploaderBundle#1472]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 2.4.2
| Symfony version | 7.1.6
| PHP version     | 8.3.7

#### Summary

I use Vich\UploaderBundle\Naming\OrignameNamer for my uploads. 
Since the last version, the behavior has changed. 
Indeed, the `name` method returns the name of the file with twice the extensions.
(Maybe add a `$' in regular expressions for unit tests).
I haven't tested the other namers.

#### Current behavior

For this uploaded file, the `name` method returns `6720bd4f7e964_test.png.png`

```php
[Symfony\Component\HttpFoundation\File\UploadedFile](file:///var/www/html/vendor/symfony/http-foundation/File/UploadedFile.php#L32) {#66 ▼
  -test: false
  -originalName: "test.png"
  -mimeType: "image/png"
  -error: 0
  -originalPath: "test.png"
  path: "/tmp"
  filename: "phpnIdgMC"
  basename: "phpnIdgMC"
  pathname: "/tmp/phpnIdgMC"
  extension: ""
  realPath: "[/tmp/phpnIdgMC](file:///tmp/phpnIdgMC#L0)"
  aTime: 2024-10-29 11:47:43
  mTime: 2024-10-29 11:47:43
  cTime: 2024-10-29 11:47:43
  inode: 22118283
  size: 9879
  perms: 0100600
  owner: 33
  group: 33
  type: "file"
  writable: true
  readable: true
  executable: false
  file: true
  dir: false
  link: false
}
```

A file `image_test.jpeg` will be named `6720bfe33f6aa_image_test.jpeg.jpg`.

#### How to reproduce

Upload a file with an extension in its name using OrignameNamer. The resulting name has two extensions.

#### Expected behavior

Get a file name with only one extension.

**Comment by garak** [comment]
Applying the following diff (according to your suggestion), the test still passes

```
diff --git a/tests/Naming/OrignameNamerTest.php b/tests/Naming/OrignameNamerTest.php
index c0f586d..9d91402 100644
--- a/tests/Naming/OrignameNamerTest.php
+++ b/tests/Naming/OrignameNamerTest.php
@@ -15,9 +15,9 @@ final class OrignameNamerTest extends TestCase
     public static function fileDataProvider(): array
     {
         return [
-            ['file.jpeg', '/[a-z0-9]{13}_file.jpeg/', false],
-            ['file',      '/[a-z0-9]{13}_file/',      false],
-            ['Yéöù.jpeg', '/[a-z0-9]{13}_yeou.jpeg/', true],
+            ['file.jpeg', '/[a-z0-9]{13}_file.jpeg$/', false],
+            ['file',      '/[a-z0-9]{13}_file$/',      false],
+            ['Yéöù.jpeg', '/[a-z0-9]{13}_yeou.jpeg$/', true],
         ];
     }
 ```

**Comment by azazels79** [comment]
Hi!
The same thing happens to me.

When using "Vich\UploaderBundle\Naming\OrignameNamer" when uploading an image, it uses a double extension:

file upload -> sorteobombo.jpg
save -> 672df884f0284_sorteobombo.jpg.jpg

**Comment by BA-JBI** [comment]
Hi,
Can confirm this issue.

Problem seems to be in
https://github.com/dustin10/VichUploaderBundle/blob/10e7e01c486956012bc0bc624197ea807092f78d/src/Naming/OrignameNamer.php#L44-L50

There should be a check if $name ends with $extension

**Comment by garak** [comment]
The test itself was buggy.
I proposed a fix in the attached PR, please check if it works for you.
Please notice that when a file has an extension that does not match the guessed one, the name will still apply another extension. For example, a `foo.jpeg` with a guessed `jpg` extension will be named `foo.jpeg.jpg`

**Comment by BA-JBI** [comment]
Thanks @garak
Have tested the pull request and my filenames now are correct again.

> Please notice that when a file has an extension that does not match the guessed one, the name will still apply another extension.
This behavior seems reasonable to me as it does keep the "origname" as much as possible

**Comment by garak** [comment]
Merged and released: https://github.com/dustin10/VichUploaderBundle/releases/tag/v2.4.3
