### ISSUE TITLE
Sometimes Images are uploaded with broken pixels.

### ISSUE THREAD

**Issue by agaktr** [dustin10/VichUploaderBundle#1475]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | v2.4.2
| Symfony version | v6.4.13
| PHP version     | v8.3.13

#### Summary

Sometimes randomly, uploaded images are broken. The user reuploads the image again and again, it breaks on different places, until eventually it shows correctly.
![image](https://github.com/user-attachments/assets/39955600-35a7-4221-a3e4-4655a4c0b2ae)
![image](https://github.com/user-attachments/assets/433a2fe0-2b9b-49f0-a656-68a63e1f85e9)

https://github.com/user-attachments/assets/f5b61476-9240-4d1d-b1de-11ce0cd5f61d (client video)

#### Current behavior

Randomly, Images are uploaded broken on the website.

#### How to reproduce

There is no obvious pattern on the images that are uploaded as broken. On those images, eventually, after 3-5-10 retries they are uploaded correctly. I use almost the default configuration of the bundle with nothing added in it.

The vich_uploader.yaml file:
````
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        uploads:
            # uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads/%current_date%'
            namer: App\Namer\VichUploadWithDatedPathNamer
````
The namer class I created:
````
class VichUploadWithDatedPathNamer implements NamerInterface
{
    public function name($object, PropertyMapping $mapping): string
    {
        /* @var $file UploadedFile */
        $file = $mapping->getFile($object);

        // create path with filename
        $filepath = implode('/', [
            // $mapping->getUriPrefix(),
            date('Y', time()),
            date('m', time()),
            date('d', time()),
            $file->getClientOriginalName()
        ]);

        return $filepath;
    }
}
````

The fields I use inside entities:
````
// NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'uploads', fileNameProperty: 'featuredImage')]
    private ?File $featuredImageFile = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $featuredImage = null;
    
    
    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setFeaturedImageFile(?File $featuredImageFile = null): void
    {
        $this->featuredImageFile = $featuredImageFile;

        if (null !== $featuredImageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updated = new \DateTimeImmutable();
        }
    }

    public function getFeaturedImageFile(): ?File
    {
        return $this->featuredImageFile;
    }
    
````
#### Expected behavior

Images should be uploaded correctly without being broken.

**Comment by garak** [comment]
This bundle saves information about the uploaded files to your entities (and then retrieves the same information). It doesn't handle the actual upload, which is handled by Symfony.

Probably you should try to investigate the problem elsewhere.

**Comment by agaktr** [comment]
I just updated everything to latest version and wait for the client to upload things.

Maybe a Symfony issue?

**Comment by agaktr** [comment]
Thanks for your time :)
