### ISSUE TITLE
File naming (file extensions) changed between 2.4.1 and 2.4.2

### ISSUE THREAD

**Issue by jxmallett** [dustin10/VichUploaderBundle#1479]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.4.2

#### Summary

The handling of file extensions changed in 2.4.2 with this commit https://github.com/dustin10/VichUploaderBundle/commit/4962a3e5ff2c3eb37831a3964c65cb99a2b8d700 (Specifically the changes to the FileExtensionTrait)

#### Previous behavior

Previously the file extension was based on the extension of the original name of the uploaded file.

#### Current behavior

The original file extension is now ignored and the extension is 'guessed' based on the mime type.

#### How to reproduce

* Create a zip file (of any file) and name it `zip-file.txt`.
* Check the mime type in bash with `file -i zip-file.txt`. It should return `application/zip`.
* Upload `zip-file.txt` using vich uploader. I am using the UniqidNamer, but any namer that uses `FileExtensionTrait` is affected.
* Observe the .txt extension is removed and replaced with .zip

---

I know the commit was made to address a potential security issue, but I thought the behaviour change was worth reporting.

**Comment by ServerExe** [comment]
I have the same issues with CSV files now. They result in .txt files which is not acceptable for us

**Comment by garak** [comment]
> I have the same issues with CSV files now. They result in .txt files which is not acceptable for us

This is either a problem with symfony/mime component or with your file having the wrong mime type

**Comment by ServerExe** [comment]
> This is either a problem with symfony/mime component or with your file having the wrong mime type

Simple CSV files are always considered `text/plain`. At least when you export an Excel file to an UTF-8 CSV File. Symfony's MimeTypes class maps `text/plain` to .txt.

I guess I will need to write a custom Namer since I need the uploaded files to keep their extension.

**Comment by garak** [comment]
> I guess I will need to write a custom Namer since I need the uploaded files to keep their extension.

A possible improvement to the bundle could be adding a new option, something like `namer_keep_extension`: if `true`, it would behave like the old one, if `false` like the current one. The default should be `false`.

PRs are welcome.

**Comment by garak** [comment]
About a possible alternate solution: we could add a map of extensions allowed for reach mime type, and then keep the original extension when it belongs to that list. Probably easier.

**Comment by garak** [comment]
The change in the proposed PR should fix the problem with the CSV extension. If you have more cases to add, feel free to suggest them.
The same PR also adds a few documentation notes about the upgrade process.

**Comment by mathiiii-dev** [comment]
Hello, I'm reopening this issue because I think I have the same problem with XLSB files.
When I upload one it become a XLSX file.

**Comment by garak** [comment]
Please open another issue, then you can propose a PR to fix it
