### ISSUE TITLE
I can't clone it via composer.json

### ISSUE THREAD

**Issue by tom10271** [dustin10/VichUploaderBundle#149]
D:\WAMP\www>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for knplabs/knp-gaufrette-bundle dev-master -> satisf
iable by knplabs/knp-gaufrette-bundle[dev-master].
    - knplabs/knp-gaufrette-bundle dev-master requires knplabs/gaufrette 0.2.*@d
ev -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common
 problems.

This is the message I got on CMD. Why cloning it can be that frustrating?

**Comment by saifrehman15** [comment]
Not worked for me . 

$ composer require vich/uploader-bundle
Using version ^1.8 for vich/uploader-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v2.8.16
    - Conclusion: don't install symfony/symfony v2.8.16
    - vich/uploader-bundle 1.8.0 requires symfony/form ^3.4|^4.0 -> satisfiable by symfony/form[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1].
    - vich/uploader-bundle 1.8.1 requires symfony/form ^3.4|^4.0 -> satisfiable by symfony/form[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1].
    - vich/uploader-bundle 1.8.2 requires symfony/form ^3.4|^4.0 -> satisfiable by symfony/form[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1].
    - vich/uploader-bundle 1.8.3 requires symfony/form ^3.4|^4.0 -> satisfiable by symfony/form[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1].
    - symfony/form v3.4.0 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.1 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.10 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.11 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.12 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.2 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.3 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.4 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.5 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.6 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.7 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.8 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.9 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.0 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.1 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.10 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.11 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.12 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.2 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.3 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.4 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.5 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.6 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.7 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.8 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.9 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.1.0 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.1.1 conflicts with symfony/symfony[v2.8.16].
    - Installation request for symfony/symfony (locked at v2.8.16, required as 2.8.*) -> satisfiable by symfony/symfony[v2.8.16].
    - Installation request for vich/uploader-bundle ^1.8 -> satisfiable by vich/uploader-bundle[1.8.0, 1.8.1, 1.8.2, 1.8.3].


Installation failed, reverting ./composer.json to its original content.
