### ISSUE TITLE
delete_on_update don't works.

### ISSUE THREAD

**Issue by bruli** [dustin10/VichUploaderBundle#154]
Hi.

I started using the bundle but don't delete old image when i change it with edit form.

I don't know if it's my mistake or a bug.

This is my config.yml.

<code><pre>
knp_gaufrette:
    stream_wrapper: ~
    adapters:
        brand_adapter:
            local:
                directory: %kernel.root_dir%/../web/images/brand
    filesystems:
        brand_image_fs:
            adapter:    brand_adapter
            alias:      brand_filesystem
        product_image_fs:
            adapter:    product_adapter
            alias:      product_filesystem
vich_uploader:
    db_driver:  orm
    gaufrette:  true
    storage:    vich_uploader.storage.gaufrette
    mappings:
        brand_image:
            uri_prefix:         /images/brand
            upload_destination: brand_image_fs
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            inject_on_load:     true
            delete_on_update:   true
</pre></code>

Any idea?

**Comment by RuSS-B** [comment]
Guys if you had the same problem as @Kevlys @smilesrg @pbowyer make sure that you aren't assigning filename manually

    public function setFile(File $file)
    {
        $this->file = $file;

        if ($file instanceof UploadedFile) {
            if ($filename = $file->getFilename()) {
                $this->setSomeFileName($filename);
            }
        }
    }

In this case you can have problems with auto delete. Just use the trick with updatedAt field or something like that

Example:

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $contractFile
     */
    public function setContractFile(File $file)
    {
        $this->file = $file;

        if ($file instanceof UploadedFile) {
            $this->setUpdatedAt(new \DateTime());
        }
    }
