### ISSUE TITLE
how to use custom namer

### ISSUE THREAD

**Issue by floranM** [dustin10/VichUploaderBundle#20]
hi, i'm try your bundle, but i don't understand how to use custom namer.

Can you explain how to implement  a custom namer , or show an example for a custom namer.

thanks for help.

Sorry for my english,

**Comment by sokphea-chea** [comment]
hi.. I follow @doncandid said and get this error.. any suggestion? thanks 
Compile Error: Declaration of AdminBundle\Service\Namer\Namer::name() must be compatible with Vich\UploaderBundle\Naming\NamerInterface::name($object, Vich\UploaderBundle\Mapping\PropertyMapping $mapping)

**Comment by andela-tolotin** [comment]
@sokphea-chea. I think what you're missing is the propertymapping.

```
use Vich\UploaderBundle\Naming\NamerInterface;
use Vich\UploaderBundle\Mapping\PropertyMapping;

class FileNamer implements NamerInterface
{
    /**
     * Creates a name for the file being uploaded
     *
     * @param object $obj The object the upload is attached to
     * @param string $field The name of the uploadable field to generate a name for
     *
     * @return string The file name
     */
    public function name($object, PropertyMapping $mapping)
    {
        $file = $object->file;
        $extension = $file->getExtension();

        return uniqid('', true).'.'.$extension;
    }
```

**Comment by jesusmartinez** [comment]
You guys should put all this useful info into the documentation. It took me through many posts to get here and find proper configuration.

**Comment by michael-rision** [comment]
OK - solved the previous one by looking at the existing code - I was missing the  ': string' after the function definition.... hope this helps someone else.

**Comment by frvaillant** [comment]
This saved me
`/**
     * @inheritDoc
     */
    public function name($object, PropertyMapping $mapping): string
    {
        $fileType = ucfirst($mapping->getFilePropertyName());
        $functionName = 'get' . $fileType;
        list($type, $extension) = explode('/', $object->{$functionName}()->getMimeType());
        return uniqid('', true).'.'.$extension;
    }`
