### ISSUE TITLE
File is not saved

### ISSUE THREAD

**Issue by petrjirasek** [dustin10/VichUploaderBundle#203]
Hi,

I would like to ask you if someone doesn't know where is the problem. I followed the configuration tutorial in doc and try to create a photo entity with the similar configuration.

Here is gist https://gist.github.com/Jirda/8901323

I have created a directory upload in the web directory but when I run the load code in a data fixture to create Photo entity, then the image is not saved and the upload directory is empty. Also, imageName is null.

Thank you for your notes.

**Comment by chriwup** [comment]
Actually setting the parameter `test`=`true` to the UploadedFile constructor does allow you to "upload" a local file:

```
new UploadedFile($filePath, "image1.png", 'image/png', filesize($filePath), null, true);
```

This fixes the "not uploaded due to an unknown error" issue @petrjirasek described.

**Comment by gorvelyfab** [comment]
Thank @chriwup this is works for me
