### ISSUE TITLE
Symfony2 file upload in a OneToMany relationship

### ISSUE THREAD

**Issue by achrafff** [dustin10/VichUploaderBundle#219]
Hi
I have an entity User and other Image, what i want is that a User can upload images for hos profile (even without multi-upload at the same time), but i couldn't do that as i'm new in symfony2 and doctrine2 :(

PS: i'm using fosuserbundle for handling users

**Comment by famas23** [comment]
can u exaplin how to use form collection ? please

**Comment by Dragnucs** [comment]
@famas23 https://symfony.com/doc/3.1/form/form_collections.html
