### ISSUE TITLE
Set image by URL

### ISSUE THREAD

**Issue by tricki** [dustin10/VichUploaderBundle#231]
I want to allow the user to use his Facebook profile picture (or indeed an image from any external URL) instead of uploading his own.
I'm not sure how to do it. I see two options:
1. Download the profile picture.
   I know how to download it but I don't know how to save it in the configured directory and using the namer configured by the VichUploaderBundle.
   Also this has the disadvantage of not updating when the user changes his facebook picture.
2. Directly link to his Facebook picture
   I could do this by setting the absolute URL as the imageName property but this doesn't work well with the `vich_uploader_asset` twig function.

I'm willing to use any of those two or any other option but I'm not sure which would be best. Can anyone give me a hint?
If there's no way to do it I'll simply download the picture and manually move and rename it which will work fine as long as I don't change the configuration.

Thanks
Thomas

**Comment by jernejpangersic** [comment]
I know this is closed but is there a way to achieve this?
I was thinking something along the lines of: you download the image, and use your bundle to upload it (I'm using AWS S3 as my storage). 
So is there a way to programmatically upload a file?

Thanks
