### ISSUE TITLE
"The object is not uploadable"

### ISSUE THREAD

**Issue by BobbySix** [dustin10/VichUploaderBundle#24]
Hi,

I have used VichUploaderBundle with MongoDB

The upload worked fine but when i wanna use this : 

in my Document :

```
 /**
 * @MongoDB\File
 *
 * @Vich\UploadableField(mapping="template_file", fileNameProperty="name")
 *
 * @var File $file
 */
public $file;
```

in my controller : 

$helper = $this->container->get('vich_uploader.templating.helper.uploader_helper');
$path = $helper->asset($template, 'file');

And i get a "The object is not uploadable" any idea why the ReflectionClass is not accepted as uploadable ?

Thanks

**Comment by ajankowski** [comment]
Clearing the cache fixed this issue for me.

**Comment by gusdecool** [comment]
try clearing the cache first as @ajankowski suggested.
change on annotation usually not detected by symfony :sob:

**Comment by ewertoncode** [comment]
Good! I clear the cache and works!

Thank's

**Comment by Kid-Binary** [comment]
Works for me as well, thank you.

**Comment by stingbo** [comment]
Works for me as well, thank you. @ajankowski
