### ISSUE TITLE
Propel, 1:n relations and delete_on_remove

### ISSUE THREAD

**Issue by K-Phoen** [dustin10/VichUploaderBundle#245]
Because of how Propel works, files are not deleted when the "1 side object" is deleted. The delete event isn't fired, preventing the bundle to do its work.
Fixing the event cascade in [willdurand/EventDispatcherBehavior](https://github.com/willdurand/EventDispatcherBehavior) could be an option (if it's possible).

**Comment by garak** [comment]
Hey, since this is a very OLD issue and we had to remove Propel support in latest version, I'd like to know if this issue is still relevant, and especially if you're able to propose a fix for an older branch.
Otherwise, this issue will be closed without resolution.
