### ISSUE TITLE
Is there is simple way to get `upload_destination` directory config from the DIC ?

### ISSUE THREAD

**Issue by gido** [dustin10/VichUploaderBundle#251]

**Comment by webdevilopers** [comment]
Same scenario here.

In my service I have to manually add files to the same folder where the uploaded files are stored. The content is generated with the `KnpSnappyBundle`. The files don't have to be added to the Entity itself.
The just need to be in the same folder.

So far I tried:
```php

```

**Comment by st0at** [comment]
I found such solution for this issue:
```
$property_mapping_factory = $this->container->get('vich_uploader.property_mapping_factory');
$upload_destination = $property_mapping_factory->fromField($entity, 'file_property_name')->getUploadDestination();
```
