### ISSUE TITLE
Filesize in twig

### ISSUE THREAD

**Issue by markitosgv** [dustin10/VichUploaderBundle#271]
Is any simply way to get filesize in twig? I make my own twig extension for this purpose... Will be interesting include in vichuploader twig extensions this method to get a fliesize in twig? or maybe attach a new extension for this purpose.

**Comment by hubgit** [comment]
Here's [an example of an event subscriber that stores extra file details with the entity](https://gist.github.com/hubgit/0cdf96c296f20017fe91).
