### ISSUE TITLE
Can I use another Document class?

### ISSUE THREAD

**Issue by mlaptas** [dustin10/VichUploaderBundle#282]
Hi. 

I have defined my own document classes, f.e. ImageFile, PdfFile - they extend AbstractFile class. How can I use my own classes in User document (it has inside such definition:
- @ODM\ReferenceOne(targetDocument="MyOwnBundle\Document\File\AbstractFile")
  protected $avatar;

Regards, Marek

**Comment by garak** [comment]
You can use a listener and do whatever you want with the uploaded file.
See docs about [events](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/events.md).
