### ISSUE TITLE
couldn't save the uploaded files

### ISSUE THREAD

**Issue by symfonyluxury** [dustin10/VichUploaderBundle#29]
I just got a huge confusion that I fully followed the instruction, and there is none error during the form submission.
However as a result, there is none files lies in related configured destination, but  the tmp path has been saved into
db field, like "tmp\php96F6.tmp",why?

**Comment by adrielwerlich** [comment]
hello I am uploading images and the path being recorded is

C:\xampp_\tmp\phpF148.tmp

Any idea why this would be happening?
