### ISSUE TITLE
File upload through AJAX call

### ISSUE THREAD

**Issue by reypm** [dustin10/VichUploaderBundle#311]
I'm asking if it's possible to upload a file using this Bundle but using a AJAX call instead of the common way. I've tried this code:

```
$.ajax({
    async: false,
    type: "POST",
    cache: false,
    url: '{{ path('save-product') }}',
    data: $('.smart-form').serializeArray(),
    success: function (data) {
        // Something
        } 
    }
});
```

But it's not working since image is saved as blank value in DB and it's not uploaded at all, any advice around this?

**Comment by Dragnucs** [comment]
@K-Phoen Will it be possible to have a premade view that supports Drag'n'Drop?

**Comment by haithemkdous** [comment]
@reypm did you find the solution Ajax upload with VichUploaderBundle??

**Comment by reypm** [comment]
@haithemkdous is being a while since I work on this but as far as I can remember I didn't found by then
