### ISSUE TITLE
How to delete a file (not delete entity object and not overwrite with another file)?

### ISSUE THREAD

**Issue by archie18** [dustin10/VichUploaderBundle#323]
Hello,

I'm trying to figure out how to simply delete a file attached to an entity. I do not want to delete the entire entity object and neither do I want to replace the file with another file. Just delete the file. I searched the documentation and tried Google but didn't find anything useful. I also tried to set the file variable of the entity object to NULL and persist the entity. But this did not remove the physical file.

Any hints are highly appreciated.

Best,
Andreas

**Comment by RowanReid** [comment]
This should be mentioned in the documentation somewhere :-)

**Comment by K-Phoen** [comment]
The bundled evolved and the correct way to remove a file "manually" is now: `$this->get('vich_uploader.upload_handler')->remove($entity, 'fieldName');`

**Comment by danaki** [comment]
Injection of `vich_uploader.upload_handler` breaks the abstraction. Please consider implementing this:

> setting the variable to null should be captured by the listener and the file should be deleted automatically.

**Comment by vbarrier** [comment]
> Injection of `vich_uploader.upload_handler` breaks the abstraction. Please consider implementing this:
> 
> > setting the variable to null should be captured by the listener and the file should be deleted automatically.

Does it work like that in 2023? (It seems not)

**Comment by falves97** [comment]
> Injection of `vich_uploader.upload_handler` breaks the abstraction. Please consider implementing this:
> 
> > setting the variable to null should be captured by the listener and the file should be deleted automatically.

Any updates on this point?

**Comment by garak** [comment]
> > Injection of `vich_uploader.upload_handler` breaks the abstraction. Please consider implementing this:
> > > setting the variable to null should be captured by the listener and the file should be deleted automatically.
> 
> Any updates on this point?

This issue is closed, what kind of update do you expect?

**Comment by falves97** [comment]
I'm sorry if I did something I shouldn't have @garak. I'm starting to use this Bundle in a personal project and found myself in the same situation.
I just found the colleague's suggestion of functionality so as not to break the abstraction valid.

If I misunderstood that it wasn't a feature suggestion, I'm sorry for the inconvenience.

**Comment by garak** [comment]
@falves97 no need to apologize.
The current implementation of this bundle makes impossible the file removal after setting the value to null, because the information about the file name is lost.
But you can easily implement your own cleaner command, checking for the files of all your entities and performing the related cleaning when needed.

**Comment by falves97** [comment]
I see, it's a very interesting alternative.
Thanks for your attention @garak.
