### ISSUE TITLE
Uploaded file disappears on form if form validation fails

### ISSUE THREAD

**Issue by ghost** [dustin10/VichUploaderBundle#343]
Hi,

I have a form where I upload a file. Everything is ok if form validation succeds. If it fails the form has every field populated execpt for the uploaded file field which hasn't anymore the previously uploaded way.

I want the form to mantain the uploaded file if the form validation fails. 

How can I achieve that? 

Thanks

Matteo

**Comment by aosmialowski** [comment]
@matteomoretti you simply can't solve the issue. Files have to bee re-selected by user once again.
