### ISSUE TITLE
I can't see the uploaded image after submitting form

### ISSUE THREAD

**Issue by ThomasDeudon** [dustin10/VichUploaderBundle#344]
Hi, I'm using VichUploaderBundle for an user profile image.
##### In my profile edit form I added the image into the form builder :

```
public function buildForm(FormBuilderInterface $builder, array $options)
{
    // add your custom field
    $builder->add('username')
            ->add('email')
            ->add('imageFile');
}
```
##### In the User entity I correctly put the annotation for upload and setFile is with another change for the listener

```
/**
  *
  * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
  */
 public function setImageFile(File $image = null)
 {
     $this->imageFile = $image; 

     if ($image) {
         $this->imageName = $image->getFileName();
     }
 }
```
##### my config :

```
vich_uploader:
    db_driver: orm
    mappings:
         user_image:
            uri_prefix:         /upload/images/users
            upload_destination: %kernel.root_dir%/../web/upload/images/users
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
```

But when I submit my form, the imageName in my user change to something like : php7ZRE04 but I can't find any image...

**Comment by sonjadeissenboeck** [comment]
@ThomasDeudon I would also be interested in the information that fixed your problem

**Comment by ThomasDeudon** [comment]
Hello,

To be honest, I can't remember what was done. I simply know from my answer that I had an issue with my mapping.

Double check your entities ?

**Comment by nourelhoudamiled** [comment]
hello,
tu a utiliser vichuploader avec fosUser ? 
si oui tu me montrer ton view et merci
