### ISSUE TITLE
Embeddable object

### ISSUE THREAD

**Issue by garak** [dustin10/VichUploaderBundle#350]
Is there any way to get this bundle working on an embeddable object?
E.g. main entity with Uploadable annotation, Embedded sub-entity with UploadableField annotation

**Comment by K-Phoen** [comment]
In fact, I think it should work.

Embeddable objects will need to have the Uploadable annotation and be configured as usual, the only thing to do is properly create the form (ie: use an embedded form type). It should work as expected since it's conceptually the same as using relations.

**Comment by foaly-nr1** [comment]
@K-Phoen That's what I thought, but can't get it to work with Doctrine Embeddable and embedded form type.

**Comment by skhattane** [comment]
Hi, 1.4 is still unable to work on an embeddable object ?

I have recipeEntity (main entity) with recipeStepEntity (sub entity). 
recipeEntity have uploadable annotation (onetoone with recipeImageEntity) and recipeStepEntity have uploadable annotation (onetoone with recipeStepImageEntity)

Create an update recipe Form with recipeSteps (embedded collection) give me this error :
**"Expected argument of type "AppBundle\Entity\RecipeStepImage or null", "AppBundle\Entity\RecipeImage" given"**

**Comment by garak** [comment]
@skhattane your case is involving relationships, not [embedding](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/embeddables.html).
Anyway it looks like you're doing something wrong.

**Comment by skhattane** [comment]
@garak my bad. you're right.
Can you just confirm that my usecase is possible with this bundle ?

**Comment by garak** [comment]
Of course it is

**Comment by skhattane** [comment]
Shame on me ! I used "RecipeImageType" instead "RecipeStepImageType" in my RecipeStepType...
Everything work perfectly now. Awesome Bundle !

For my knowledge : Is there a way to add Ajax Image Upload to work with this bundle or the approach have to be completely different ?

**Comment by TrogWarZ** [comment]
Hello!

Don't understand why bundle not working with ORM\Embeddable entity (but works without). Can anyone share some examples of code (didn't see them in manual)?

My codes are here (config, enitites, controller): https://gist.github.com/TrogWarZ/a134123a61867d42b26f7e56ea2a6255

There is no errors but pdf file is not uploaded. If i move anything about upload to MainEntity – works great. But this is not what i need.

**Comment by garak** [comment]
What about your form?

**Comment by TrogWarZ** [comment]
I don't have form for this route. Uploaded file is grabbed from `$paramFetcher->get('pdf')`.

**Comment by garak** [comment]
If you provide an example of code, with your config, that is reproducible with a classic form, I can help you.

**Comment by TrogWarZ** [comment]
Which code do you need in addition to my snippet (link in my first comment)? There is part of my `config.yml` too. But i don't have forms – how do i provide them?

With regular entities without embeddable (when `emb_file` and `emb_name` is moved to `MainEntity`) – everything is working okay. Without forms.

**Comment by garak** [comment]
I just a reproducible code. Your current code is a bit "out of normal", e.g. it's not clear what ParamFetcher is nor why you use merge instead of persist.

**Comment by TrogWarZ** [comment]
> what ParamFetcher is

ParamFetcher is from [Symfony](http://symfony.com/doc/current/bundles/FOSRestBundle/param_fetcher_listener.html). It just validates params from request. In my case, it gets UploadedFile instance. See `var_dump($pf->geT('pdf'))` example:

```
/var/www/myproject/api/src/AcmeBundle/Controller/OrderController.php:767:
class Symfony\Component\HttpFoundation\File\UploadedFile#14 (7) {
  private $test =>
  bool(false)
  private $originalName =>
  string(26) "test_pdf_valid.pdf"
  private $mimeType =>
  string(15) "application/pdf"
  private $size =>
  int(1036)
  private $error =>
  int(0)
  private $pathName =>
  string(14) "/tmp/phpxDUJwT"
  private $fileName =>
  string(9) "phpxDUJwT"
}
```

> why you use merge instead of persist

There is `merge` because i'm updating entity that already exists in database (i get it from repository in line 26). If i need to create new entity, i will use `persist`.

Here is second gist: https://gist.github.com/TrogWarZ/eef344bf91f69756d7d9a3e374966227 The difference is in location of `emb_file` parameter – when it not in embedded entity, pdf file uploades good.

**Comment by garak** [comment]
But you don't need to merge an existing entity, unless you changed default Doctrine behaviour. Anyway, I can only help you if you provide a more standard use case

**Comment by TrogWarZ** [comment]
Got it. Can you provide example of standard use with upload to doctrine embeddable entity? In docs i see just regular entity upload (which works for me too).

**Comment by garak** [comment]
OK, I just tried with a minimal code, and embedded is working if:
* you annotate with `@Vich\Uploadable` both embedding and embedded objects
* you provide proxy setters and getters for the UploadableField and for its related string column

**Comment by ama3ing** [comment]
@garak Could you point me out how you made this work?

**Comment by garak** [comment]
See https://gist.github.com/garak/9c7240a05d6fbe1f30b674c6bc31bec3

**Comment by TrogWarZ** [comment]
Sorry for waiting – i'm very busy right now to post minimal project with this – can post on the next week, i think. Just tested ideas from your comment and they're not working )-:

Thanks for gist – will try it!

**Comment by BoShurik** [comment]
This gist is not working. You should copy uploadable field, and its getter/setter, and getter/setter for fileNameProperty to parent object

```php
/**
 * @Vich\Uploadable
 */
class User
{
    /**
     * @Vich\UploadableField(mapping="image", fileNameProperty="imageName")
     *
     * @var File
     */
    private $imageFile; // Not used
    
    /**
     * @param string $imageName
     *
     */
    public function setImageName($imageName)
    {
        $this->foo->setImageName($imageName);
    }
    /**
     * @return string|null
     */
    public function getImageName()
    {
        return $this->foo->getImageName();
    }

    /**
     * @param File $image
     */
    public function setImageFile(File $image = null)
    {
        $this->foo->setImageFile($image);
    }
    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->foo->getImageFile();
    }
}
```

**Comment by ama3ing** [comment]
I've thought about what I was trying to achieve by using Embeddable object and decided that it's not good approach after that. What we are trying to do here is have an abstraction for uploads and better way would be to create a mapped superclass for that (which works as expected)

```php
/**
 * @Vich\Uploadable
 * @ORM\MappedSuperclass
 */
abstract class AbstractImage
{
    /**
     * @var File
     * @Vich\UploadableField(mapping="upload", fileNameProperty="path")
     * @ORM\Column(type="string")
     */
    protected $file;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    protected $path;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    protected $uploadedAt;
```

**Comment by BoShurik** [comment]
Is there any way this feature will be implemented? Now it's too redundant to use this bundle with embeddables.

BTW, there is bundle which support embeddables - `atom-php/uploader-bundle` (unfortunately without documentation in english)

**Comment by garak** [comment]
It is implemented

**Comment by BoShurik** [comment]
I think it's little bit tricky, as I need to proxy every fields and methods related to file from embeddable to parent object

**Comment by garak** [comment]
If you find a better solution, feel free to propose it

**Comment by tinpansoul** [comment]
Stumbled across the exact same problem again even after 8-9 years – embedded just doesn't work: https://github.com/dustin10/VichUploaderBundle/blob/master/docs/usage.md

Found the solution by diggin into the library code and it was not in the documentation – you need to create an embeddable object before any upload will happen:
```php
class Product
{
    // ... class parameters from the official documentation

    public function __construct()
    {
        $this->image = new EmbeddedFile();
    }

    // ... class methods from the official documentation
}
```

**Comment by garak** [comment]
@tinpansoul what happens if you don't create the embedded object?
