### ISSUE TITLE
After upgrade I get MappingNotFoundException

### ISSUE THREAD

**Issue by flopp26** [dustin10/VichUploaderBundle#358]
Hi, I'm not sure to understand, what I need to change, now I get this error :

```
Mapping not found for field "" 
```

**Comment by gabiudrescu** [comment]
I'm getting the same error - MappingNotFoundException and I'm pulling my hair for a couple of hours because of it. Please find below my configuration.

I would remain grateful if you could hint me in solving this problem - am I doing something wrong?

composer.json:

```json
(...)
"symfony/symfony": "2.6.*"
(...)
"vich/uploader-bundle": "0.14.*"
```

app/config/config.yaml
```yaml
vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix:         /images/products
            upload_destination: %kernel.root_dir%/../web/images/products
```

Project entity

```php

<?php

namespace GabiU\CVBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Project
 * @Vich\Uploadable
 */
class Project
{
 (...)
    /**
     * @var string
     */
    protected $logo;

(...)

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="logo")
     *
     * @var File $imageFile
     */
    protected $imageFile;

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;
    }

    /**
     * @return File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

(...)

    /**
     * Set logo
     *
     * @param string $logo
     * @return Project
     */
    public function setLogo($logo)
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * Get logo
     *
     * @return string 
     */
    public function getLogo()
    {
        return $this->logo;
    }
(...)
```

Project FormType buildForm method

```php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description', 'ckeditor')
            ->add('url', 'url')
            ->add('logo', 'vich_image')
            ->add('isMain', 'checkbox', array(
                'data' => false,
            ))
        ;
    }
```

Stack trace
```
[1] Vich\UploaderBundle\Exception\MappingNotFoundException: Mapping not found for field "logo"
    at n/a
        in /home/gabiudrescu/PhpstormProjects/CV/vendor/vich/uploader-bundle/Storage/AbstractStorage.php line 147

    at Vich\UploaderBundle\Storage\AbstractStorage->getFilename(object(Project), 'logo', null)
        in /home/gabiudrescu/PhpstormProjects/CV/vendor/vich/uploader-bundle/Storage/AbstractStorage.php line 113

    at Vich\UploaderBundle\Storage\AbstractStorage->resolvePath(object(Project), 'logo')
        in /home/gabiudrescu/PhpstormProjects/CV/vendor/vich/uploader-bundle/Form/Type/VichFileType.php line 67

    at Vich\UploaderBundle\Form\Type\VichFileType->Vich\UploaderBundle\Form\Type\{closure}(object(FormEvent), 'form.pre_set_data', object(EventDispatcher))
        in  line 
```

**Comment by gabiudrescu** [comment]
According to Murphy laws, once you cry for help on a public form, 5 minutes later you managed to solve the issue: it was the damned formtype - it was pointing to logo, instead of imageFile, the property ment to hold the uploadfile.

it works now.

```php

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description', 'ckeditor')
            ->add('url', 'url')
            ->add('imageFile', 'vich_image', array(
                'required'      => false,
                'allow_delete'  => true,
                'download_link' => true,
            ))
            ->add('isMain', 'checkbox', array(
                'data' => false,
                'required' => false
            ))
        ;
    }
```

**Comment by mustaphajamel** [comment]
i have the same problem i corrected the form type with imageFile attribute didn't work (.tmp file in data base) i replaced the attribute with imageName ("Mapping not found for field "imageName")
this is my entity 

`
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
  
 /**
     *
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return Product
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image) {
            $this->updatedAt = new DateTime("2014-06-20 11:45 Europe/London");
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param string $imageName
     *
     * @return Product
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getImageName()
    {
        return $this->imageName;
    }
`
formType : 
 `    ->add('prixProduit',NumberType::class)
            ->add('quantiteStock')
            ->add('pourcentagePromotion')
            ->add('imageName', VichImageType::class, array(
                'required'      => false,
                'allow_delete'  => true,
                'download_link' => true,
            ))
        ;`
controller : (i didn't change anything)
![1528466_1495811207311148_857298037_n - copy](https://cloud.githubusercontent.com/assets/18304952/23093178/3f500c04-f5dc-11e6-9ff0-85b2584a98e9.jpg)


`public function newAction(Request $request)
    {
        $product = new Product();
        $form = $this->createForm('ProductBundle\Form\ProductType', $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $id_user = $this->get('security.token_storage')->getToken()->getUser();

            $em = $this->getDoctrine()->getManager();
            $em->persist($product);
            $em->flush($product);


            return $this->redirectToRoute('product_show', array('id' => $product->getId()));
        }

        return $this->render('product/new.html.twig', array(
            'product' => $product,
            'form' => $form->createView(),
        ));
    }
`


Any help please
