### ISSUE TITLE
Mapping not recognized anymore after update

### ISSUE THREAD

**Issue by amdiakhate** [dustin10/VichUploaderBundle#361]
Hello
Since the last update, my mappings are not recognized anymore.
I get this error in my twig : 

```

[1/2] MappingNotFoundException: Mapping not found for field "profile_image"   +
```

This is my entity : 

```

 /**
     * @Assert\File(
     *     maxSize="3M",
     *     mimeTypes={"image/png", "image/jpeg", "image/pjpeg"}
     * )
     * @Vich\UploadableField(mapping="profile_image", fileNameProperty="imageName")
     *
     * @var File $image
     */
    protected $image;

    /**
     * @ORM\Column(type="string", length=255, name="image_name",nullable=true)
     * @Expose
     * @var string $imageName
     */
    protected $imageName;

```

and this is the config.yml

```

mappings : 
    profile_image:
            uri_prefix:                 /uploads/profiles
            upload_destination:         %kernel.root_dir%/../web/uploads/profiles
            inject_on_load :            true
            delete_on_remove :          true
            delete_on_update :          true


```

**Comment by rasanga-byng** [comment]
@ruscon 
Did you use @Vich\Uploadable annotation in your object class?

**Comment by rasanga** [comment]
@ruscon 
Did you use @Vich\Uploadable annotation in your object class?

**Comment by ruscon** [comment]
@rasanga yes

**Comment by monsefoster** [comment]
@ruscon did you fix it? I'm having the same problem

**Comment by ruscon** [comment]
nope

**Comment by mdhheydari** [comment]
@ruscon @monsefoster 
I had the same problem. Using a bunch of `dump` I got that the `ClassMetadata` is not filled by the reflector. So I guess it's because of cache, cleared it and it worked like a charm. ;)

**Comment by ajankowski** [comment]
@mdhheydari 
Clearing the cache worked for me too!

**Comment by Zuhayer** [comment]
Same here, after hours of head smashing 'cache clearing' was the issue :)
