### ISSUE TITLE
File handling on form validation fail

### ISSUE THREAD

**Issue by matejvelikonja** [dustin10/VichUploaderBundle#367]
I could not found anything about file handling when form validation fails. 

The problem that I have is that I would like to keep uploaded file if the form validation fails. I'm aware of that, that you can not set this to file input tag, because of HTML restrictions. But it would be nice, if the uploaded file would be kept in entity, even when the form validation fails (on different fields).

It's really not a good user experience, if the user uploads file and forgets some other field, and than on form validation failure has to select file again.

Is this possible to do with the bundle?

**Comment by K-Phoen** [comment]
Nothing is done in this bundle to address this kind of concern. You could play with the `UploadHandler` and try to implement your own logic (a service exists to access it).
