### ISSUE TITLE
VichUploaderBundle + SonataAdminBundle

### ISSUE THREAD

**Issue by vittore** [dustin10/VichUploaderBundle#372]
Hi,

I have a simple entity and a sonataAdmin backend to manage it.

Here relevant files:

config.yml: https://gist.github.com/vittore/ea15bcefaf225423842d
Entity: https://gist.github.com/vittore/d7873a9db2cf63eacbec
EntityAdmin: https://gist.github.com/vittore/29b4947cd0d1e5396684

The error appears when upload a file (on create or edit an event entity): Attempted to call method "upload" on class "MyBundle\Entity\Event".

```
public function saveFile($event)
    {
        $basepath = $this->getRequest()->getBasePath();
        $event->upload($basepath);   <---- here
    }
```

Any ideas?

Thanks in advance.
v.

**Comment by K-Phoen** [comment]
You don't need the `saveFile` method, this is done auto-magically by VichUploaderBundle.
