### ISSUE TITLE
Unable to get file path relative to storage system

### ISSUE THREAD

**Issue by nibynool** [dustin10/VichUploaderBundle#373]
I originally posed this as a secondary question in https://github.com/dustin10/VichUploaderBundle/issues/368

I am passing a reference to an object via a queue to another server. On the second server I want to do some post-processing to uploaded files. I already know which file-system I am using (in my case Gaufrette connecting to S3) but I need to know the directory and filename.

The suggestion from @K-Phoen was to use something like:
```
Vich\UploaderBundle\Storage\StorageInterface::resolvePath($obj, $mappingName)
```

This seems to return the full path to the file, not just the path relative to the storage system.  For example, the path returned by gaufrette is `gaufrette://%upload_destination%/%relativePath%`

It would be optimal if the StorageInterfaces had a method along the lines of `resolveStorageSystemPath`

At present I have the following code to convert the resolved path to the storage system path:
```
$fileLocation = $storage->resolvePath($object, 'file');
$fileLocation = preg_replace('#^gaufrette://uploadDestination/#', '', $fileLocation);

```

**Comment by K-Phoen** [comment]
You can now retrieve the relative path for an object using the Storage.

```php
$fileLocation = $storage->resolvePath($object, 'file', $className = null, $relative = true);
```

This should solve your issue in a more elegant way :)

**Comment by nibynool** [comment]
Excellent... Thanks for the nice solution!

**Comment by nibynool** [comment]
Just a quick note (it would be quicker for you to update than for me to create a PR)... You didn't update the PHPDoc on abstract protected function doResolvePath in AbstractStorage.

Obviously not a major issue, but thought you might want it for completeness.

**Comment by K-Phoen** [comment]
Yup, forgot that. I'll update it tomorrow :)
