### ISSUE TITLE
How upload multiple image?

### ISSUE THREAD

**Issue by sergioplaza** [dustin10/VichUploaderBundle#375]
Hello, how I can upload multiple images ?, I'm new using this bundle. regards

**Comment by K-Phoen** [comment]
Same as issue #276

**Comment by sergioplaza** [comment]
Hello, thank you very much for your answer, but what I really want is upload in the same imageName several images as array. Is this possible ?. Greetings (excuse my English)

**Comment by K-Phoen** [comment]
Don't think so, nop.
