### ISSUE TITLE
docx and xlsx as zip when upload

### ISSUE THREAD

**Issue by Chensienyong** [dustin10/VichUploaderBundle#376]
Hi guys, is this the right place to ask..
I'm using this and here my code for file entity :
<pre>
/** @Assert\File(
     *   maxSize="20M",
     *   mimeTypes={"application/vnd.ms-office","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.openxmlformats-officedocument.wordprocessingml.document"}
     *  )
     *  @Vich\UploadableField(mapping="soal_nilai_ujian" , fileNameProperty="namaDiServer")
     */
    private $file;
</pre>
If i upload doc or xls extension it seems fine, but when upload docx or xlsx, it recognize it as zip.. Any solution? I had search and got no clue.. Thanks before

**Comment by Chensienyong** [comment]
okay, it seems that my question is MimeTypes problem not related to this bundle. But any help is appreciated!
another question;
How can i handle the error if i upload different file outside of the mime? It seems always insert list before input.
I want to change the text and put it on header.. Thanks :)

**Comment by K-Phoen** [comment]
As you said, not related to this bundle :)
