### ISSUE TITLE
Entity inheritance fails / Request new release

### ISSUE THREAD

**Issue by gnat42** [dustin10/VichUploaderBundle#377]
So recently I refactored a project using this bundle. It involved having a MappedSuperclass handle the document pieces and a couple other entities extending it. This resulted in some failures due to the old code in MetadataReader.php
```
public function getUploadableFields($class)
{
    $metadata = $this->reader->getMetadataForClass($class);
    $classMetadata = $metadata->classMetadata[$class];

    return $classMetadata->fields;
}
```
I was about to submit a patch where I tried to find the uploadable fields based on is_subclass_of(). Then I noticed that the code in master is quite different. When I copied it over it works just as well as my solution. Therefore it would be great if you could release another point release. I have in the meantime changed my requirement from 0.14.0 to dev-master.

**Comment by K-Phoen** [comment]
Inheritance should be working since 1.0.0-beta2. You can update your requirements to required at least this version.

**Comment by gnat42** [comment]
Ah thanks I didn't scroll that far down the tag list to see that version. Thanks!

**Comment by mathieu-axiocode** [comment]
Hi! My version is 1.0.0 beta5 but I get this error when flushing my entity : 

`The annotation "@MappedSuperClass" in class ... was never imported. Did you maybe forget to add             a "use" statement for this annotation?`

If I remove the vich annotations, my entity is successfully flushed, any idea? 
Thanks in advance...
