### ISSUE TITLE
How to get values for each uploaded file?

### ISSUE THREAD

**Issue by paquitodev** [dustin10/VichUploaderBundle#379]
I have a multiple files upload field and I'm manage it at controller as follow:

    foreach ($request->files as $uploadedFile) {
        $entRecaudosTramitesProductoSolicitud = new Entity\RecaudosTramitesProductoSolicitud();
        $entRecaudosTramitesProductoSolicitud->setProductoSolicitud(
            $em->getReference('AppBundle:ProductoSolicitud', $productoSolicitud)
        );
        $entRecaudosTramitesProductoSolicitud->setRecaudosTramite(
            $request->request->get( 'tipoRecaudoId' )
        );
        $entRecaudosTramitesProductoSolicitud->setRecaudoFile($uploadedFile);
        $em->persist($entRecaudosTramitesProductoSolicitud);

        $response['file_name'][] = ''; // here should go  the current uploaded fileName
        $response['file_url'][] = ''; // here should go  the current uploaded fileURL
        $response['file_delete'][] = ''; // here should go  the current uploaded fileDeleteURL
    }

    try {
        $em->flush();
        $response['success']   = true;
        $response['id']      = $request->request->get( 'tipoRecaudoId' );
        $status              = 200;
    } catch (\Exception $e) {
        $status              = 400;
    }

I need some advice|help here since I don't know how to get the values `fileName`, `fileURL` and `fileDeleteURL` for each uploaded file, for send it in as JSON to the view, can any give me some help?

Thanks in advance

**Comment by K-Phoen** [comment]
The file name is stored in your entity?
The documentation already explains [how to generate URLs](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/generating_urls.md).
And there is no URL exposed by this bundle to delete a file (why should there be one?)

**Comment by paquitodev** [comment]
Ok, thanks I've this working now
