### ISSUE TITLE
Can I get the path from the entity id

### ISSUE THREAD

**Issue by waltercruz** [dustin10/VichUploaderBundle#380]
I'm working with a very specificy query builder that it's returning my a array, not entities.

I would like to have some... vich_uploader_asset(field.id,'mymapping').

There's some alternative?

**Comment by K-Phoen** [comment]
```vich_uploader_asset(field.id, 'mymapping', 'My\Class\Name')```

As explained in the "[Generating URL](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/generating_urls.md)" section of the documentation.

**Comment by waltercruz** [comment]
ouch! thanks!

**Comment by K-Phoen** [comment]
:)

**Comment by waltercruz** [comment]
{{ vich_uploader_asset(entity, 'fileAgreement', 'Dialog\\ActionBundle\\Entity\\Action') }}"

My Action entity has various uploads fields..

{{ vich_uploader_asset(entity, 'fileAgreement', 'Dialog\\ActionBundle\\Entity\\Action') }}" is returning empty

An example from the data:

    array (size=12)
      'convocation_name' => string 'teste 1  ConvocatÃ³ria' (length=22)
      'id' => int 11
      'dialog_name' => string 'Mobilidade Urbana' (length=17)
      'name' => string 'teste sol!!' (length=11)
      'code' => string 'MOBI0001' (length=8)
      'status' => string 'D' (length=1)
      'type' => string 'P' (length=1)
      'pathAgreement' => string 'a5NBOmg_700b_v1.jpg' (length=19)
      'pathGreenlight' => null
      'pathNonObjection' => null
      'locais' => string 'MCid' (length=4)
      'externals' => string 'DG MOVE' (length=7)
  
the path that should be considerer is pathAgreement.

Any hints on this?

**Comment by K-Phoen** [comment]
I'll try to reproduce your issue this week-end.

**Comment by waltercruz** [comment]
I found it! I was returning my doctrine property name pathAgreement but vich search for the nas as it's on database, path_agreement.

**Comment by waltercruz** [comment]
thanks for listening my monologue!

**Comment by K-Phoen** [comment]
No problem, glad you could solve your issue :)
