### ISSUE TITLE
label:support Error while implementing Notice: Trying to get property of non-object

### ISSUE THREAD

**Issue by mufi** [dustin10/VichUploaderBundle#381]
Hi there please I'm seeking help. I'm trying to implement your bundle into my website I followed your documentation and sandbox but when I add this file:
```
# Resources/config/vich_uploader/coffee.yml
INB\ManageBundle\Entity\Coffee:
    imageMain:
        mapping: coffee
        filename_property: imageMainName
```
my site crashes at this error 

ContextErrorException in MetadataReader.php line 78:
Notice: Trying to get property of non-object

ErrorHandler->handleError('8', 'Trying to get property of non-object', '/Users/tomaskissik/Sites/ineedbeans/vendor/vich/uploader-bundle/Metadata/MetadataReader.php', '78', array('class' => 'INB\ManageBundle\Entity\Coffee', 'metadata' => null)) in MetadataReader.php line 78
at MetadataReader->getUploadableFields('INB\ManageBundle\Entity\Coffee') in RegisterPropelModelsPass.php line 32

Can you please see where I'm making mistake? Thank you very much!

```
# entity/coffee.php
namespace INB\ManageBundle\Entity;
use Symfony\Component\HttpFoundation\File\File;


class Coffee
{
    private $id;
    private $imageMain;
    private $imageMainName;
//....
public function setImageMain(File $imageMain = null)
    {
        $this->imageMain = $imageMain;
        return $this;
    }

    public function getImageMain()
    {
        return $this->imageMain;
    }

    public function setImageMainName($imageMainName)
    {
        $this->imageMainName = $imageMainName;
        return $this;
    }

    public function getImageMainName()
    {
        return $this->imageMainName;
    }

}

# Resources/config/doctrine/coffee.orm.yml
  type: entity
  repositoryClass: INB\ManageBundle\Entity\RepositoryCoffee
  table: coffee
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    imageMainName:
      type: string
      length: 255
      nullable: true
      column: image_main_name



# Resources/config/config.yml
vich_uploader:
    db_driver: orm
    mappings:
        coffee:
            uri_prefix: /images/coffee
            upload_destination: %kernel.root_dir%/../web/uploads/coffee/
```

**Comment by K-Phoen** [comment]
Closed in favour of #385

**Comment by hamerub** [comment]
Did you find a fix for this problem? I ran into the same thing.

**Comment by briantjuhh007** [comment]
Anyone found a fix...?

**Comment by MrNicodemuz** [comment]
Clearing the cache seemed to solve the issue for me.
