### ISSUE TITLE
Rename file when filename property is changed

### ISSUE THREAD

**Issue by debach** [dustin10/VichUploaderBundle#382]
Is there a way to rename the uploaded file when the filename property is changed? I actually want to make the filename property editable and, of course, the file should be renamed accordingly. Do I have to roll my own Doctrine callbacks? I was hoping that VichUploaderBundle can handle this.

**Comment by K-Phoen** [comment]
The bundle does not provide this kind of functionality. You'll have to use your own doctrine listeners and access the storage layer by yourself.
