### ISSUE TITLE
vich_image form type

### ISSUE THREAD

**Issue by fender-hm** [dustin10/VichUploaderBundle#383]
Thanks for your work!
I'm using <code>vich_image</code> form type, but I have a problem because on edit form original uploaded image is too big. Is there some opportunity to overwrite <code>vich_image_widget</code> block? I would like to use LiipImagineBundle for thumbnail.
Thanks!

**Comment by K-Phoen** [comment]
Hi!

If you just want to customize the template, you can [write your own form theme](http://symfony.com/doc/current/cookbook/form/form_customization.html#what-are-form-themes) and override vich_image_widget.

If you want to build thumbnails on the fly and display them instead, you'll need to use the [events triggered by the bundle](https://github.com/dustin10/VichUploaderBundle/blob/master/Event/Events.php).

**Comment by fender-hm** [comment]
Thank you very much! I used <a href='http://symfony.com/doc/current/cookbook/form/form_customization.html#method-2-inside-a-separate-template'>this one</a> method. Thanks for help.
