### ISSUE TITLE
Out of memory when uploading large files and using Gaufrette

### ISSUE THREAD

**Issue by RowanReid** [dustin10/VichUploaderBundle#384]
Line 57 of Storage/GaufretteStorage.php is making a call to file_get_contents() on the uploaded file.  This means that if we upload files larger in size than the available memory, then we get an error.  Is there a more efficient way that this code can be re-written?

**Comment by K-Phoen** [comment]
The problem here lies in Gaufrette: there is no clean (or even dirty) way to handle large files.
I suggest you considerate [Flysystem](https://github.com/thephpleague/flysystem) as an alternative.

**Comment by RowanReid** [comment]
Thanks!

**Comment by sela** [comment]
@K-Phoen is FlySystem support uploading files in chunks? I couldn't find it is.

**Comment by K-Phoen** [comment]
@sela I've not worked on this bundle for years, but here is a portion of code that you might find relevant: https://github.com/dustin10/VichUploaderBundle/blob/5b5a792d1dfbe5c89cd1720567a2a76c44617f98/Storage/FlysystemStorage.php#L38
