### ISSUE TITLE
Force downloading uploaded images

### ISSUE THREAD

**Issue by bocharsky-bw** [dustin10/VichUploaderBundle#389]
Uploaded images opening in a browser tab when click on **Download** link.

Can we force downloading for any files?

**Comment by K-Phoen** [comment]
Images are directly served by the web server so I'd say no.

**Comment by bocharsky-bw** [comment]
What about if we make download link via controller? We can add forcing headers in this case

**Comment by K-Phoen** [comment]
This would work (despite being a bit heavy).

If you want to submit a PR I'd be happy to review it :)

**Comment by bocharsky-bw** [comment]
Ok, I think about that :) Maybe later I'll have a time

**Comment by K-Phoen** [comment]
I kind of forgot about this issue, sorry!

There is - at last - some documentation about the download helper. You can find it here: https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/downloads/serving_files_with_a_controller.md

Sorry again.

**Comment by bocharsky-bw** [comment]
Oh, nice! Thanks for docs!
