### ISSUE TITLE
How to get url without entity

### ISSUE THREAD

**Issue by meron1122** [dustin10/VichUploaderBundle#391]
I have a row name,id etc but i dont have entity, how to generate link without get entity?

**Comment by K-Phoen** [comment]
You can do something like this:

```php
$entityData = [
    'id' => 42,
    'imageName' => 'foo.png',
];
$helper = $this->container->get('vich_uploader.templating.helper.uploader_helper');
$path = $helper->asset($entityData, 'image', 'Acme\DemoBundle\Entity\Image');
```

As long as you have access to the `imageName` and you specify the right class name in the `asset()` call, you can generate the path.
The same syntax works with the `vich_uploader_asset` twig function.
