### ISSUE TITLE
Upload does not perform if manually injecting file into the entity

### ISSUE THREAD

**Issue by smilesrg** [dustin10/VichUploaderBundle#397]
I'm injecting file in the form event listener:

```php
        $builder->addEventListener(
            FormEvents::PRE_SUBMIT,
            function (FormEvent $event) use ($container) {

                $form = $event->getForm();
                $data = $event->getData();

                $uploadsDir = $container->getParameter('uploads_dir');
                if (isset($data['file'])) {
                    $filename = sprintf('%s.%s', uniqid('tmp_'), $data['file']->getClientOriginalExtension());
                    copy($data['file']->getRealPath(), $uploadsDir . '/tmp/' . $filename);
                    $form->add('file_hidden', 'hidden', array(
                        'mapped' => false,
                        'required' => false,
                        'empty_data' => $filename,
                    ));
                } else if (!isset($data['file']) && isset($data['file_hidden'])) {
                    $fileInfo = new \SplFileInfo($uploadsDir . '/tmp/' . $data['file_hidden']);

                    $uploadedFile = new File($fileInfo->getRealPath());

                    $form->add('file_hidden', 'hidden', array(
                        'mapped' => false,
                        'required' => false,
                        'empty_data' => $data['file_hidden'],
                    ));

                    $form->get('file')->setData($uploadedFile);
                    $data['file'] = $uploadedFile;
                    $event->setData($data);
                }
            }
        );
```

Here are File object created:
```php $uploadedFile = new File($fileInfo->getRealPath());```

and is set as the submitted data:
```php
                    $form->get('file')->setData($uploadedFile);
                    $data['file'] = $uploadedFile;
                    $event->setData($data);
```

But if the insance is File type (not UploadedFile because it wouldn't work - validation will fail), the file wouldn't be uploaded.

**Comment by K-Phoen** [comment]
This is a [known issue](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/known_issues.md#no-upload-is-triggered-when-manually-injecting-an-instance-of-symfonycomponenthttpfoundationfilefile).

**Comment by smilesrg** [comment]
@K-Phoen but if create UploadedFile manually, any validation will fail. Take a look into isValid method of UploadedFile:

```php
    public function isValid()
    {
        $isOk = $this->error === UPLOAD_ERR_OK;

        return $this->test ? $isOk : $isOk && is_uploaded_file($this->getPathname());
    }
```

**Comment by K-Phoen** [comment]
This bundle is meant to be used in conjunction with forms and uploaded files. If you don't use them, you defeat its purpose and I can not really help you.

**Comment by smilesrg** [comment]
@K-Phoen there is such case: when user upload files and form is invalid, the files are lost. I am trying to manually re-populate files using tricks with hidden field. So, when hidden field with the file name is present, I am picking up file in event listener and adding it to the form field as data. If VichUploader would trigger if the File instance is set, that would help me so much!

**Comment by smilesrg** [comment]
Hey! I've just solved issue by setting up parameter "test" (the last parameter in the constructor) to "true" in UploadedFile instance! This means:
>Local files are used in test mode hence the code should not enforce HTTP uploads.

```php
                    $fileInfo = new \SplFileInfo($uploadsDir . '/tmp/' . $data['file_hidden']);

                    $mimeTypeGuesser = MimeTypeGuesser::getInstance();
                    $uploadedFile = new UploadedFile(
                        $fileInfo->getRealPath(),
                        $fileInfo->getBasename(),
                        $mimeTypeGuesser->guess($fileInfo->getRealPath()),
                        $fileInfo->getSize(),
                        null,
                        true
                    );
```

@K-Phoen Could you please add information about "test" parameter to the manual?

**Comment by K-Phoen** [comment]
Done, thanks! :)
