### ISSUE TITLE
Models outside bundle not working for XML mapping

### ISSUE THREAD

**Issue by meskis** [dustin10/VichUploaderBundle#399]
Hey,

I use XML for markup and my models are places outside the bundles.
I bunped into strange behavior as my models (entities) are completely decoupled. I found that FileLocator::findFileForClass uses model namespace to locate the mapping file which is wrong (I think).
I should be able to place my models outside bundles (use best practices) and still get this working.

Any ideas about that?

**Comment by K-Phoen** [comment]
You should be able to configure mapping locations. It's almost an hidden feature but [it can be configured](https://github.com/dustin10/VichUploaderBundle/blob/master/DependencyInjection/Configuration.php#L85-90).

**Comment by meskis** [comment]
Works :)
