### ISSUE TITLE
upload with multi field

### ISSUE THREAD

**Issue by thmohd** [dustin10/VichUploaderBundle#400]
I am trying to upload two files with 2 fields , and I see the first file but the second one is not exist, what I trying do is upload one file on AWS and the other locally , I am using knp_gaufrette.

I don't think there is any problem with config file as I tried both of the adapters and they both upload well but one file only to one destination only, whichever the first one..

Here is my config file :  

----------------------------------------
services:
    amazonS3:
        class: AmazonS3
        arguments:
            options:
                key:      '%aws_key%'
                secret:   '%aws_secret_key%'

knp_gaufrette:
    stream_wrapper: ~

    adapters:
        zip_uploads:
            amazon_s3:
                amazon_s3_id:   amazonS3
                bucket_name:    my_bucket
                options:
                    directory:  files/zip

        pdf_uploads:
            local:
                directory: "%pdf_directory%"

    filesystems:
            amazon_s3:
                adapter:    zip_uploads
            local_pdf:
                adapter:    pdf_uploads

vich_uploader:
    db_driver: orm
    storage: gaufrette

    mappings:
           zip_file:
                   uri_prefix:         https://s3.amazonaws.com/my_bucket
                   upload_destination: amazon_s3
                   namer:              vich_uploader.namer_uniqid
                   inject_on_load:     true
                   delete_on_update:   true
                   delete_on_remove:   true

           document_file:
                   uri_prefix:         /documents/files
                   upload_destination: local_pdf
                   namer:              vich_uploader.namer_uniqid
                   inject_on_load:     true
                   delete_on_update:   true
                   delete_on_remove:   true

--------------------------------

and here is part of my entity :::

   /**
     * @Vich\UploadableField(mapping="document_file",fileNameProperty="filename")
     * @var File
     */
    private $file;

    /**
     * @Vich\UploadableField(mapping="zip_file",fileNameProperty="filename")
     * @var File
     */
    private $zipfile;

    /**
     * @var string
     *
     * @ORM\Column(name="filename", type="string", length=255)
     */
    private $filename;

**Comment by K-Phoen** [comment]
Looks like you only defined one "filename" column. If you want two files to be uploaded, you need two columns to store their filenames.

**Comment by thmohd** [comment]
@K-Phoen Can't I have same name for both files? my files are always  One zip and one pdf

**Comment by K-Phoen** [comment]
Nop, you must have two columns otherwise the bundle won't be able to work as expected.

**Comment by thmohd** [comment]
@K-Phoen I did change that but I am still having same problem , the second file is not exist and no errors or anything from the application.

**Comment by K-Phoen** [comment]
can you paste your new entity?
Also, did you update the database and clear the cache?

**Comment by thmohd** [comment]
@K-Phoen Thank you so much , I did update the database and the problem was not solve because I didn't clear the cache , I just did as you reminded me and everything is working well.

Thank you :)

**Comment by K-Phoen** [comment]
Glad I could help you :)
