### ISSUE TITLE
why that can not determine change in debug mode?

### ISSUE THREAD

**Issue by ghanbari** [dustin10/VichUploaderBundle#402]
I use doctrine for my project and yaml for mapping of vich uploader & my entity,
when i change vich uploader mapping in yml file(change filename_property value), my form raise `Mapping not found for field "imageFile"` untill that i clear cache manual.
why that can not determine change when i was in development environment and debug was true?

**Comment by K-Phoen** [comment]
Metadata are cached (for obvious performance reasons). And as always when there is a cache layer somewhere, there needs to be another layer to invalidate it.
In this bundle, this invalidation must be done manually using the cache:clear command.
