### ISSUE TITLE
Can't upload file when create new object with form

### ISSUE THREAD

**Issue by maciejmigas** [dustin10/VichUploaderBundle#403]
Hello,
have any1 idea hot to resolve my problem what I described here http://stackoverflow.com/questions/30688375/symfony-2-vichuploader-cant-handle-file ?

**Comment by fundup** [comment]
USing Symfony 2.7 and VichUploaderBundle 0.14.
I think I have the sale problem. When I submit my form I don't have a file but a string : 
<code>
public function setImage( File $image = null)  {
        $this->image = $image;
        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->imageUpdatedAt = new \DateTime('now');
       </code>

$image parameter is equal to the filename.

**Comment by garak** [comment]
See #297
