### ISSUE TITLE
Vich can't handle annotations from extended classes

### ISSUE THREAD

**Issue by thomas-koch-comsolit** [dustin10/VichUploaderBundle#404]
I've two entity classes which extend a common abstract entity. I tried to put the Uploadable and UploadableField annotations in the abstract entity but it seems Vich does not see them there. It only worked to copy the annotations in the concrete entities and also to define the fields there instead of once in the abstract entity.

That's a pity. Doctrine can handle inheritance. What about traits?

does not work:
```PHP
/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
abstract class BaseEntity {
  /**
   * @Vich\UploadableField(mapping="event_document", fileNameProperty="document")
   */
  private $file;
}

/**
 * @ORM\Entity
 */
class ConcreteEntity extends BaseEntity {
  // nothing here
}
```

does work:
```PHP
/**
 * @ORM\Entity
 */
abstract class BaseEntity {
  // just the getters/setters here
}

/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
class ConcreteEntity extends BaseEntity {
  /**
   * @Vich\UploadableField(mapping="event_document", fileNameProperty="document")
   */
  protected $file;
}
```

**Comment by vlcekmi3** [comment]
Try to make $file field visible for inherited entities - put it protected.

**Comment by ivanbarlog** [comment]
I have tried to make property of base class `protected` plus I have add annotation `@Vich\Uploadable` to all my child classes and it worked.

Example:

```
/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
abstract class BaseEntity {
  /**
   * @Vich\UploadableField(mapping="event_document", fileNameProperty="document")
   */
  protected $file;
}

/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
class ConcreteEntity extends BaseEntity {
  // nothing here
}
```

**Comment by K-Phoen** [comment]
@thomas-koch-comsolit I've tested your inheritance schema with the latest release and it works. I remember having worked on this sort of issues a few months ago, inheritance seems to work now so I close this issue.
