### ISSUE TITLE
can't find many files

### ISSUE THREAD

**Issue by MoslemCherif** [dustin10/VichUploaderBundle#409]
Hello,
When using this bundle, i faced many problems as some files not found, such as AdvancedFileLocatorInterface, DriverInterface
Any solution?
Thanks

**Comment by K-Phoen** [comment]
It's probably an "install-related" issue. Did you try to delete the `vendor/*` directory and install again?

**Comment by MoslemCherif** [comment]
Hello,I will try again,and i will seeThanks a lot!Best Regards,

Date: Tue, 7 Jul 2015 13:46:01 -0700

**Comment by K-Phoen** [comment]
Since there have been no reply since almost two months, I close this issue.
