### ISSUE TITLE
Merge functionality from IphpFileStoreBundle

### ISSUE THREAD

**Issue by Mondane** [dustin10/VichUploaderBundle#413]
Have a look at https://github.com/vitiko/IphpFileStoreBundle .

I implemented that bundle first, but I like the way VichUploaderBundle handles the entity by using Symfony\Component\HttpFoundation\File\File better. There is some functionality thought that I appreciated:

- Annotated field data, the field in the database contains an array with usefull information:
 - path — full path to file in web dir, including web path to upload dir
 - size — file size in bytes
 - fileName — path to file , relative to web path of upload dir
 - originalName — original file name before upload
 - mimeType — file mime type
 - width — image width
 - height — image height
- File Namers
 - Transliteration - replace cyrillic and other chars to ascii
 - File name by value of entity field ( eg. the id)
- Directory Namers
 - Create subdirectory by date
 - Using entity field value
 - Using entity field name
 - Using entity class name

The best one, I think, is the array in the database which makes it possible to get back the original name when using a unique file namer.

Could these be implemented?

**Comment by hubgit** [comment]
Some of this is possible with [an event subscriber that adds extra file details to the entity](https://gist.github.com/hubgit/0cdf96c296f20017fe91).

**Comment by K-Phoen** [comment]
As @hubgit said, some of these features are implementable with event subscribers. I'd add that all "annotated field data"-related features can not be implemented directly by the bundle: the relevant data to collect depends too much on the application and the context.

However, features like transliteration and *File name by value of entity field* can and will be implemented in this bundle. In fact these two features landed on master today ;)
