### ISSUE TITLE
Saved entity without changing file looses file object

### ISSUE THREAD

**Issue by Mondane** [dustin10/VichUploaderBundle#416]
When I start editting an entity to which already a file is linked, the entity dump shows:

``` ObjDump
Nourishment {#828
  -id: 45
  #imageFile: File {#853}
  -imageName: "5592eaeb5110e.jpg"
  #createdAt: DateTime {#825
    +"date": "2015-06-30 21:15:55.000000"
    +"timezone_type": 3
    +"timezone": "Europe/Amsterdam"
  }
  #updatedAt: DateTime {#826
    +"date": "2015-06-30 21:15:55.000000"
    +"timezone_type": 3
    +"timezone": "Europe/Amsterdam"
  }
  #translations: PersistentCollection {#845
    -snapshot: array:1 [ …1]
    -owner: Nourishment {#828}
    -association: array:16 [ …16]
    -em: EntityManager {#787 …10}
    -backRefFieldName: "translatable"
    -typeClass: ClassMetadata {#829 …}
    -isDirty: false
    -initialized: true
    -coll: ArrayCollection {#846
      -elements: array:1 [
        "nl" => NourishmentTranslation {#889
          -name: "blab"
          -description: "bbbbwefw"
          #id: 51
          #locale: "nl"
          #translatable: Nourishment {#828}
        }
      ]
    }
  }
  #newTranslations: ArrayCollection {#895
    -elements: []
  }
  #currentLocale: "nl_NL"
  #defaultLocale: "nl"
}
```

If I select a new file in the upload, it looks as expected:

``` ObjDump
Nourishment {#416
  -id: 45
  #imageFile: File {#801}
  -imageName: "559c28fdb7f6c.JPG"
  #createdAt: DateTime {#413
    +"date": "2015-06-30 21:15:55.000000"
    +"timezone_type": 3
    +"timezone": "Europe/Amsterdam"
  }
  #updatedAt: DateTime {#514
    +"date": "2015-07-07 21:31:09.000000"
    +"timezone_type": 3
    +"timezone": "Europe/Amsterdam"
  }
  #translations: PersistentCollection {#433
    -snapshot: array:1 [ …1]
    -owner: Nourishment {#416}
    -association: array:16 [ …16]
    -em: EntityManager {#375 …10}
    -backRefFieldName: "translatable"
    -typeClass: ClassMetadata {#417 …}
    -isDirty: false
    -initialized: true
    -coll: ArrayCollection {#434
      -elements: array:1 [
        "nl" => NourishmentTranslation {#477
          -name: "blabsss"
          -description: "bbbbwefw"
          #id: 51
          #locale: "nl"
          #translatable: Nourishment {#416}
        }
      ]
    }
  }
  #newTranslations: ArrayCollection {#482
    -elements: []
  }
  #currentLocale: "nl_NL"
  #defaultLocale: "nl"
}
```

But if I don't select a new image, ie. I don't want to change the image. The entity dumps looks like:

``` ObjDump
Nourishment {#828
  -id: 45
  #imageFile: null
  -imageName: "5592eaeb5110e.jpg"
  #createdAt: DateTime {#825
    +"date": "2015-06-30 21:15:55.000000"
    +"timezone_type": 3
    +"timezone": "Europe/Amsterdam"
  }
  #updatedAt: DateTime {#826
    +"date": "2015-06-30 21:15:55.000000"
    +"timezone_type": 3
    +"timezone": "Europe/Amsterdam"
  }
  #translations: PersistentCollection {#845
    -snapshot: array:1 [ …1]
    -owner: Nourishment {#828}
    -association: array:16 [ …16]
    -em: EntityManager {#787 …10}
    -backRefFieldName: "translatable"
    -typeClass: ClassMetadata {#829 …}
    -isDirty: false
    -initialized: true
    -coll: ArrayCollection {#846
      -elements: array:1 [
        "nl" => NourishmentTranslation {#889
          -name: "blabs"
          -description: "bbbbwefw"
          #id: 51
          #locale: "nl"
          #translatable: Nourishment {#828}
        }
      ]
    }
  }
  #newTranslations: ArrayCollection {#895
    -elements: []
  }
  #currentLocale: "nl_NL"
  #defaultLocale: "nl"
}
```

After saving, I show the new entity on the screen. It looks ok when changing the image. But when I don't select an new image, the entity 'looses' the old image so nothing is shown. If I reload the entity, the old image is still there.

Is reloading the entity after I've persisted and flushed it the way to 'fix' this, or am I doing something wrong?

**Comment by Mondane** [comment]
@K-Phoen , I was looking through the code for this.

In file `https://github.com/dustin10/VichUploaderBundle/blob/HEAD/Handler/UploadHandler.php`, the `upload` function handles the upload. As I see it, it does this:

- It checks if the user has selected a file to upload in `hasUploadedFile`
- If there is a file uploaded, the storage and injector are called to handle it.
- Is no file uploaded, or $file is not of instance UploadedFile, nothing is done.

If I'm correct, it's symfony that updates the imageFile property of the entity when symfony validates the form. If a file is selected by the user, that one will be in the entity. But, if the user doesn't upload a new file, the exsisting file is overwritten with `null`.

Since the user explicitly has to check 'delete' to remove the file, I suggest adding code in the upload function I was talking about in this part of that function:

```php
        // nothing to upload
        if (!$this->hasUploadedFile($obj, $mapping)) {
            return;
        }
```

So it could do something like this:

```php
        // nothing to upload, inject the original file again but only if the delete isn't checked.
        if (!$this->hasUploadedFile($obj, $mapping)) {
            if ($delete_is_not_checked_for_this_mapping) {
                $this->injector->injectFile($obj, $mapping)
            }
            return;
        }
```

This way, the object that's available after:

```php
$form->handleRequest($request);
```

and after

```php
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($nourishment);
            $em->flush();

            $this->get('session')->getFlashBag()->add('success', 'Nourishment has been added.');

            // If the object can be saved, reload the form so a new item can be added.
            return $this->redirect($this->generateUrl('vaarties_dweh_admin_addnourishment'));
        }
```

Is complete as in, it is populated with the data from the form and can have one of these:

- no image since the delete checkbox was checked
- an uploaded image because the user selected a new one
- the original image since delete wasn't checked and no new image was selected.

What do you think?

**Comment by h3llr4iser** [comment]
I have the same problem

**Comment by garak** [comment]
Being this issue a bit old: did you try with a more recent version of VichUploaderBundle?

**Comment by garak** [comment]
Closing for missing feedback.

**Comment by Mondane** [comment]
@garak sorry for the late response. I just tested this with v1.4.0 and must confirm the problem still exists. Perhaps a new problem is now present; when editing an entity which already had an image, that image isn't shown anymore. After saving that entity and reloading the page, the old image is shown again.

Could you reopen this issue?

**Comment by h3llr4iser** [comment]
I confirm the problem too, My problem is when I have an association form example to save a file for each translation, when I update the entity The file is deleted from database but the file keep present in server. I have to do this before persisting entity to solve the problem:

`$fileEditTranslationPatch->asignTranslations($entity->getTranslations());`
`$em->persist($entity);`
`$em->flush();`

`public function asignTranslations($translations)
    {
        $accessor = PropertyAccess::createPropertyAccessor();
        if($translations->count() > 0){
            foreach ($translations as $locale => $translation){
                $translation->setUpdatedAt(new \DateTime('now'));
                $fields = $this->metadataReader->getUploadableFields(get_class($translation));
                foreach ($fields as $field){
                    $item = $field['fileNameProperty'];
                    if($accessor->getValue($translations[$locale], $item) == null){
                        if(array_key_exists($locale,$this->names) !== false) {
                            if (file_exists($this->names[$locale][$item]['path'])) {
                                $accessor->setValue($translations[$locale], $item, $this->names[$locale][$item]['name']);
                            }
                        }
                    }
                }
           }
       }
    }`

**Comment by garak** [comment]
Just to recap, the flow is the following:
- you get an entity with a file, shown in a form to edit
- you submit the form without submitting a new file. At this point, file is null
- when you load again the entity, the file is there

If it's like so, I don't see the problem. You didn't lose the file.

**Comment by h3llr4iser** [comment]
Not exactly, The file is not deleted, but the database field is null.

**Comment by Mondane** [comment]
For me, the problem is exactly that, you have to reload the entity to get the file when no new file was selected in the form. This shouldn't be necessary since the entity is already in memory in the handler for the post and it properly adds the file if a new one is selected.

The reason why I don't want to reload the entity, is because I let the posthandler send a new rendered template to the browser with the just saved entity. Reloading the entity is a performance penalty.

In my comment, https://github.com/dustin10/VichUploaderBundle/issues/416#issuecomment-119703464 , I gave a possible solution when checking if a new file is uploaded.

**Comment by garak** [comment]
Can you paste here your setter for the file object?

**Comment by Mondane** [comment]
Here is the Nourishment entity from my comment:

```php
<?php

namespace Vaarties\DwehBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Nourishment
 *
 * @Vich\Uploadable
 * @ORM\Table()
 * @ORM\Entity()
 */
class Nourishment
{
    use ORMBehaviors\Blameable\Blameable;
    use ORMBehaviors\Timestampable\Timestampable;

    /**
     * Get a string representation of this object to be used in form selects added
     * in a custom form type. Also used in symfony error messages to give a readable
     * object.
     * @return string
     */
    public function __toString() {
        return (string) $this->__call('name', array());
    }

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * NB This is not an ORM mapped field of this entity metadata, just a simple
     * property. A file saved in this property will automatically be put in the
     * correct storage location and the name will be put in property imageName.
     *
     * @var File $imageFile
     *
     * @Vich\UploadableField(mapping="nourishment", fileNameProperty="imageName")
     */
    protected $imageFile;

    /**
     * @var string
     *
     * @ORM\Column(name="image_name", type="string", length=255)
     * */
    private $imageName;

    public function __construct()
    {
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param File $imageFile
     *
     * @return Nourishment
     */
    public function setImageFile(File $imageFile = null)
    {
        $this->imageFile = $imageFile;

        if ($imageFile instanceof UploadedFile) {
            // It is required that at least one field changes if you are using
            // doctrine otherwise the event listeners won't be called and the file
            // is lost. To do so, the method to update the timestamps from Timestampable
            // is called.
            $this->updateTimestamps();
        }

        return $this;
    }

    /**
     * @return File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param string $imageName
     *
     * @return Nourishment
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;
        return $this;
    }

    /**
     * @return string
     */
    public function getImageName()
    {
        return $this->imageName;
    }

}
```

**Comment by garak** [comment]
Try to move `$this->imageFile = $imageFile;` inside `if`

**Comment by Mondane** [comment]
@garak that solves the problem not having an image after saving the entity with no image changed. But it introduces the problem where the image isn't set at all when just loading the entity.

I have this config:

```yaml
vich_uploader:
    db_driver: orm
    mappings:
        nourishment:
            uri_prefix: /uploads/nourishment
            upload_destination: %kernel.root_dir%/../web/uploads/nourishment
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid
```

**Comment by garak** [comment]
What problem?

**Comment by Mondane** [comment]
That,  when I load entities for display in a page, none of them have the
image set.  This because it's not an instance of UploadedFile.

Op 7 feb. 2017 21:09 schreef "Massimiliano Arione" <notifications@github.com
>:

What problem?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dustin10/VichUploaderBundle/issues/416#issuecomment-278124910>,
or mute the thread

**Comment by garak** [comment]
Wait, are we talking about getter or setter? The check for UploadedFile is done in the setter, while the getter is simply getting what is stored (a File or null).
So, if you avoid setting null (with the check mentioned above in the setter), you should not getting null from the getter.

**Comment by Mondane** [comment]
I'll test it with this setter

If $file instance of file
   $this->file = $file

If $file instance of uploadedfile
  $this->setUpdatedAt

Will have to test too if it works properly when deleting the file.

Gr.  Mondane

Op 8 feb. 2017 08:56 schreef "Massimiliano Arione" <notifications@github.com
>:

Wait, are we talking about getter or setter? The check for UploadedFile is
done in the setter, while the getter is simply getting what is stored (a
File or null).
So, if you avoid setting null (with the check mentioned above in the
setter), you should not getting null from the getter.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dustin10/VichUploaderBundle/issues/416#issuecomment-278255895>,
or mute the thread

**Comment by garak** [comment]
Any news? Can we close this issue?

**Comment by Mondane** [comment]
I've just tested it with the setter mentioned and the behavior is now almost as expected. Testcases:

NB Where I mention file, it's in fact an image which I render with the provided renderer that shows a thumbnail for the image.

1. Add a new entity without choosing a file.
Expected result: After saving, the new entity is shown without a file.
_Test OK_

2. Add a new entity with choosing a file.
Expected result: After saving, the new entity is shown with the file.
_Test OK_

3. Edit an entity without a file.
Expected result: In the edit form, no current file is shown.
_Test OK_

4. Edit an entity with a file.
Expected result: In the edit form, the current file is shown.
**Test Not OK**: The edit form doesn't show the file, in case of an image, there is no IMG tag.

5. Edit an entity without a file and select one.
Expected result: After saving, the new entity is shown with the file.
_Test OK_

6. Edit an entity with a file and select another one.
Expected result: After saving, the new entity is shown with the new file.
_Test OK_

7. Edit an entity with a file and delete the existing one.
Expected result: After saving, the new entity is shown without a file.
_Test OK_: In case of an image, there was indeed an IMG tag rendered, with a value in the ALT attribute but an empty SRC attribute. I could fix this by overwriting _vich_image_widget_ and check if _download_uri_ isn't empty before rendering the IMG tag.

8. Edit an entity with a file and delete the existing one and also select another one.
Expected result: After saving, the new entity is shown with the new file.
_Test OK_: albeit that the interface might be a little confusing allowing deleting and selecting at the same time when there is an existing file.

This are all testcase I can think of now. Do you have an idea how to solve nr. 4 and perhaps make the interface less confusing in nr. 8?

PS To render the image, I have overridden your template so _vich_image_widget_ does not add an IMG tag. Instead, I've moved that logic to a custom _file_widget_:

```twig
{% block file_widget %}
{% spaceless %}
    <div class="fileinput fileinput-new" data-provides="fileinput">
        <span class="image">
            <span class="fileinput-preview">
            </span>
            {% if form.parent.vars.download_uri is defined and form.parent.vars.download_uri %}
            <img src="{{ form.parent.vars.download_uri }}" alt="{{ 'form.fileinput.original-image'|trans({}, form.parent.vars.translation_domain) }}" /></a>
            {% endif %}
            <a href="#" class="fileinput-exists" data-dismiss="fileinput">
                <span class="icon icon-remove-small"></span>
            </a>
        </span>
        <span class="button">
            <span class="fileinput-new">{{ 'form.label.select'|trans({}, form.parent.vars.translation_domain) }}</span>
            <span class="fileinput-exists">{{ 'form.label.change'|trans({}, form.parent.vars.translation_domain) }}</span>
            {{ block('form_widget') }}
        </span>
        <span class="fileinput-filename">
        </span>
    </div>
{% endspaceless %}
{% endblock file_widget %}

{# Overwrites vendor/vich/uploader-bundle/Resources/views/Form/fields.html.twig
   Purpose: remove the DIV tag.
#}
{% block vich_file_widget %}
{% spaceless %}
        {{ form_widget(form.file) }}
        {% if form.delete is defined %}
        {{ form_row(form.delete) }}
        {% endif %}

        {% if download_uri is defined and download_uri is not empty %}
        <a href="{{ download_uri }}">{{ 'download'|trans({}, 'VichUploaderBundle') }}</a>
        {% endif %}
{% endspaceless %}
{% endblock %}

{# Overwrites vendor/vich/uploader-bundle/Resources/views/Form/fields.html.twig
   Purpose: remove the IMG tag which is added to the above defined file_widget
            and remove the DIV tag.
#}
{% block vich_image_widget %}
{% spaceless %}
        {{ form_widget(form.file) }}
        {% if form.delete is defined %}
        {{ form_row(form.delete) }}
        {% endif %}

        {% if show_download_link and download_uri is defined and download_uri is not empty %}
        <a href="{{ download_uri }}">{{ 'download'|trans({}, 'VichUploaderBundle') }}</a>
        {% endif %}
{% endspaceless %}
{% endblock %}
```

**Comment by garak** [comment]
You need to clarify point 4. Did you add vich template to `form_themes` in config? If you don't override the template, is the image displayed?

**Comment by Mondane** [comment]
The bundle theme is added to `form_themes` in my config. If I don't override the template, no image is shown in the form, only the delete checkbox.

**Comment by Mondane** [comment]
Was just looking at the documentation and noticed https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/form/vich_image_type.md . Turns out I was using the vich_file_type instead for images. After switching to vich_image_type, when editing an entity with an image associated, it's now shown.

Issue resolved :) Thank you for your patience and help.

**Comment by Mondane** [comment]
Extra note, the changed setter as written in https://github.com/dustin10/VichUploaderBundle/issues/416#issuecomment-278448481 isn't needed anymore now I'm using the correct form type.

This works:

```php
    /**
     * @param File $imageFile
     *
     * @return Nourishment
     */
    public function setImageFile(File $imageFile = null)
    {
        $this->imageFile = $imageFile;

        if ($imageFile instanceof UploadedFile) {
            // It is required that at least one field changes if you are using
            // doctrine otherwise the event listeners won't be called and the file
            // is lost. To do so, the method to update the timestamps from Timestampable
            // is called.
            $this->updateTimestamps();
        }

        return $this;
    }
```

**Comment by tlarsonlgdor** [comment]
I'm still having this problem with version 1.8. I fixed it by only including the file field (using VichFileType class) in the formbuilder. Any mappings for the properties in the UploadableField annotation like fileNameProperty or size, for example:
`@Vich\UploadableField(mapping="file_image", fileNameProperty="filePath", size="fileSize")`
are generated automatically by the plugin. However, it only calculates them properly when an actual file is uploaded or deleted. Therefore, if you include the automatically calculated fields in the form, even if you don't allow them to be accessed, the event listeners will still be triggered on every form submit and they make the fields null causing errors on future submissions. If you need the automatically calculated fields in your template as read only, send them using abstract controller's render function instead of using the form and formbuilder. If necessary, you might be able to make them editable if you don't include the non-required fields (like size) in the UploadableField annotation. However, I didn't check that.

**Comment by garak** [comment]
@tlarsonlgdor try with 1.10
