### ISSUE TITLE
GridFS and asset url

### ISSUE THREAD

**Issue by lsv** [dustin10/VichUploaderBundle#419]
Is it possible to use GridFS?

The upload is fine, and its uploaded to my mongodb with chunks and so on.

But how do we display the image?

``` php
<?php
use Vich\UploaderBundle\Templating\Helper\UploaderHelper;

public function getProfileImage(User $user, $size = 40)
{
          return $this->helper->asset($user->getProfileImage(), 'image_upload');
}
```

This gives a url of ```/user/images/55a55297c9090.png``` which is what i defined in ```uri_prefix``` but it just gives me a 404, and there is no image in web/user/images folder.

**Comment by yaK2manD** [comment]
You can use the twig helper 
`<img src="{{ vich_uploader_asset(product, 'image') }}" alt="{{ product.name }}" />`

You can also configure the bundle with inject_on_load: true 
Then, the image will be available in your entity. 

Hope it will help you

**Comment by lsv** [comment]
Eller bare nederst i FAQ'en

https://blackfire.io/doc/faq



    What does the time represent?

Time is probably the most interesting dimension you need to look at when 
trying to optimize the performance of an application. But time comes in 
several flavors.

All times displayed in the Blackfire interface can be more accurately 
referred to as*wall-clock times*or just*wall times*.

The wall time for a function call (represented as a node in the 
interface) is the measure of the*real time*it took for PHP to execute 
the code, the difference between the time at which PHP entered the 
function and the time at which PHP left the function.

Blackfire actually gives you two wall times:

  *

    The*inclusive time*, when the time includes the wall time for the
    function call*including*the inclusive time for all its children
    (the*inclusive wall-time*);

  *

    The*exclusive time*is the time spent in the function
    itself,*excluding*time spent in children.

The wall time is actually made of two parts:

  *

    The*CPU time*is the amount of time for which the CPU was*used*for
    processing instructions;

  *

    The*I/O time*is the time the CPU*waited*for input/output (I/O)
    operations (network, disk, ...)

How can you interpret those times?

The*inclusive time*allows you to determine the critical path of your 
application.

The*exclusive time*tells you which nodes consumed the most time by 
themselves; those are probably the ones you might want to optimize first.

The*I/O time*is a great way to spot nodes where some intensive I/O 
activities took place: some code waited for the network (database calls, 
Redis calls, HTTP calls, ...) or for the disks (file inclusions, ...) 
Keep in mind that the I/O is almost never 0 as it also includes 
non-significant activities like memory access.

**Comment by K-Phoen** [comment]
I never used GridFS myself but if I remember correctly, files are stored in mongo. It means that they aren't present on the filesystem, that's why the helper can't generate a valid URL and you're seeing a 404.

The solution for your issue would be to serve yourself the files through a controller as explained in [this blog post](http://php-and-symfony.matthiasnoback.nl/2012/10/uploading-files-to-mongodb-gridfs-2/).

I close this issue as it's not really one but feel free to keep posting if you need :)
