### ISSUE TITLE
The file upload errors aren't attached to the file upload field with vich_image 

### ISSUE THREAD

**Issue by daften** [dustin10/VichUploaderBundle#422]
Instead the error is shown at the top of the form.

**Comment by ddmaster** [comment]
what with it? how I can place errors to field?

**Comment by Atyz** [comment]
Same probleme here...
Does someone have a solution ?

**Comment by jcrombez** [comment]
You can set 'error_bubbling' => false in your field but it shouldn't be needed...

**Comment by garak** [comment]
This was fixed in a5fd360a841102cab769f0b544aa648226200327
