### ISSUE TITLE
Change Doctrine event order

### ISSUE THREAD

**Issue by fredcido** [dustin10/VichUploaderBundle#424]
Is it possible to change the Doctrine prePersist event order?
I'm using a slug bundle (https://github.com/samjarrett/DoctrineSluggableBundle) and when the upload is performed I still don't have the slug and I need to use it in order to generate the custom namer.

**Comment by K-Phoen** [comment]
Hum, I don't think it's a good idea for this bundle to adjust this kind of setting based on such a "small" bundle. I don't want to risk breaking things for a bundle with *only* 1300+ installs.

Sorry.

**Comment by paul-mesnilgrente** [comment]
Did you find a solution ? I thought to call manually `setSlug` in the controller before the `prePersist` but I don't know how to generate it.
