### ISSUE TITLE
Correct way to delete a file attached to an entity without deleting the entity?

### ISSUE THREAD

**Issue by novocainer** [dustin10/VichUploaderBundle#425]
The solution in #323 does not work since the remove() method expects the second parameter to be a PropertyMapping object and not a string. 

Could someone please clarify the correct way in which to delete a file attached to an entry and/or update the example in #323 ?

**Comment by K-Phoen** [comment]
Hum, looks like `remove` signature still expects a string and not a property mapping: `public function remove($obj, $fieldName)`.

This doesn't work?

**Comment by novocainer** [comment]
K-Phoen it does not work because we are using FlySystem as our storage and vich_uploader.storage returns a FlySystem instance which uses [public function remove($obj, PropertyMapping $mapping)](https://github.com/dustin10/VichUploaderBundle/blob/ed88af73ab04a5c4908baffad009bc1e47631a01/Storage/AbstractStorage.php#L84)

**Comment by K-Phoen** [comment]
Yup, all storage implementations work with  `PropertyMapping` objects. That's why my previous comment has a link to the `UploadHandler`, which abstracts that and allows you to work with objects and field names.
You should use the `vich_uploader.upload_handler` service instead of directly using the storage.

**Comment by novocainer** [comment]
Thank's Kevin. It worked. Perhaps issue #323 should be updated since the following code is incorrect: $this->get('vich_uploader.storage')->remove($entity, 'file_mapping');

**Comment by K-Phoen** [comment]
Done.

I close this issue then :)
