### ISSUE TITLE
What about v1.0.0 and tagging a new release?

### ISSUE THREAD

**Issue by robertfausk** [dustin10/VichUploaderBundle#429]
@K-Phoen At the moment there are 46 commits to master since release 1.0.0-beta3 from January.

**Comment by robertfausk** [comment]
At least 1.0.0-beta4 would be fine ;)

**Comment by robertfausk** [comment]
@K-Phoen  ping:)
Could you at least tag a new beta version?

**Comment by K-Phoen** [comment]
I guess I can at least do that ;)

**Comment by robertfausk** [comment]
Thank you.
