### ISSUE TITLE
Handling events

### ISSUE THREAD

**Issue by totechess** [dustin10/VichUploaderBundle#437]
I have been unsuccessfully trying to implement some events described in Vich\UploaderBundle\Event. I would like to implement PRE_INJECT and POST_UPLOAD.

I have an entity called Picture and it has a field "picture" and "thumbnail", I have configured the bundle to map those fields. My form has only the input to add one file and what I am trying to do is to clone in some way the request for picture to thumbnail and let VichUploader to do the work of uploading the file. Once done that, to resize the image is easy

**Comment by K-Phoen** [comment]
This bundle uses the event dispatcher provided by Symfony to basically you just have to follow [their documentation on creating event listeners](http://symfony.com/doc/current/cookbook/event_dispatcher/event_listener.html).
You can find all the events triggered by this bundle [here](https://github.com/dustin10/VichUploaderBundle/blob/master/Event/Events.php).

**Comment by K-Phoen** [comment]
Feel free to reopen the issue if you need more help.

**Comment by rasanga** [comment]
@K-Phoen which event did you use?
