### ISSUE TITLE
Multiple files for one entity not working

### ISSUE THREAD

**Issue by Symphomaniac** [dustin10/VichUploaderBundle#438]
I got the one file per entity to work rather peacefully but when trying to implement a one-to-many approach, it doesn't seem to work.

I don't get any actual errors but the files are simply not uploaded...!

The idea is that my Project entity has a one-to-many relationship with the ProjectFile entity.

Code looks like this:
https://gist.github.com/Symphomaniac/61185e309184b9cdccc7

I have tried again and again to look at the Sandbox examples but i can't seem to find my error(s)...!

**Comment by Symphomaniac** [comment]
Also, this is a snippet from my ProjectType.php file, the part defining the multi-upload input field in the  form:

....
            ->add('files', 'collection', array(
                    'type' => new ProjectFileType(),
                        'allow_add' => true,
                        'allow_delete' => true,
                        'by_reference' => false,
                    )
            )
...

Perhaps this is where the error is?

**Comment by garak** [comment]
As mentioned in [docs](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/form/vich_file_type.md), you must use Vich type instead of file type.
