### ISSUE TITLE
VichUploaderBundle (Column 'image_name' cannot be null) !

### ISSUE THREAD

**Issue by 01sup** [dustin10/VichUploaderBundle#439]
I have in my project an entity "Article", and i followed all the steps to add a file selector to this entity form but I get this error I dont know why : 

An exception occurred while executing 'INSERT INTO article (titre, contenu, date, image_name, updated_at, professeur_id) VALUES (?, ?, ?, ?, ?, ?)' with params ["sdfsd", "sdfdsfdsvsd dsfds fsd", "2015-08-28", null, "2015-08-28 02:56:57", 70]: 

 SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'image_name' cannot be null

**Comment by K-Phoen** [comment]
There is probably an error in your mapping or in the form definition. Could you paste these two classes here?

**Comment by 01sup** [comment]
<?php

namespace ENSA\PortailWebLaboratoireBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Article
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="ENSA\PortailWebLaboratoireBundle\Entity\ArticleRepository")
 */
class Article
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;




    ///////////////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////////////////////////
    /////// THIS IS WHAT I ADDED (VichUploaderBundle)///////////////////////
    ////////////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////////////////////

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTime('now');
        }
    }

    /**
     * @return File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param string $imageName
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;
    }

    /**
     * @return string
     */
    public function getImageName()
    {
        return $this->imageName;
    }



    ///////////////////////////////////////////////////////////////////////////
    //////////////////OTHER ATTRIBUTES THAT BELONGS TO ARTICLE ENTITY//////////
    ///////////////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////////////////////////

    /**
     * @var string
     *
     * @ORM\Column(name="titre", type="text")
     */
    private $titre;

    /**
     * @var string
     *
     * @ORM\Column(name="contenu", type="text")
     */
    private $contenu;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="date")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="ENSA\PortailWebLaboratoireBundle\Entity\Professeur")
     * @ORM\JoinColumn(nullable=false)
     */
    private $professeur;

    /**
     * @ORM\OneToMany(targetEntity="ENSA\PortailWebLaboratoireBundle\Entity\Commentaire", mappedBy="article", cascade={"remove"})
     */
    private $commentaires;


    /**
     * @ORM\OneToMany(targetEntity="ENSA\PortailWebLaboratoireBundle\Entity\Fichier", mappedBy="article", cascade={"remove"})
     */
    private $fichiers;


    //CONSTRUCTEUR PAR DEFAUT
    public function __construct(){

        $this->date = new \DateTime("now");
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set titre
     *
     * @param string $titre
     * @return Article
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;

        return $this;
    }

    /**
     * Get titre
     *
     * @return string 
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * Set contenu
     *
     * @param string $contenu
     * @return Article
     */
    public function setContenu($contenu)
    {
        $this->contenu = $contenu;

        return $this;
    }

    /**
     * Get contenu
     *
     * @return string 
     */
    public function getContenu()
    {
        return $this->contenu;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Article
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set professeur
     *
     * @param string $professeur
     * @return Article
     */
    public function setProfesseur($professeur)
    {
        $this->professeur = $professeur;

        return $this;
    }

    /**
     * Get professeur
     *
     * @return string 
     */
    public function getProfesseur()
    {
        return $this->professeur;
    }


    /**
     * Add commentaires
     *
     * @param \ENSA\PortailWebLaboratoireBundle\Entity\Commentaire $commentaires
     * @return Article
     */
    public function addCommentaire(\ENSA\PortailWebLaboratoireBundle\Entity\Commentaire $commentaires)
    {
        $this->commentaires[] = $commentaires;

        return $this;
    }

    /**
     * Remove commentaires
     *
     * @param \ENSA\PortailWebLaboratoireBundle\Entity\Commentaire $commentaires
     */
    public function removeCommentaire(\ENSA\PortailWebLaboratoireBundle\Entity\Commentaire $commentaires)
    {
        $this->commentaires->removeElement($commentaires);
    }

    /**
     * Get commentaires
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCommentaires()
    {
        return $this->commentaires;
    }

    /**
     * Add fichiers
     *
     * @param \ENSA\PortailWebLaboratoireBundle\Entity\Fichier $fichiers
     * @return Article
     */
    public function addFichier(\ENSA\PortailWebLaboratoireBundle\Entity\Fichier $fichiers)
    {
        $this->fichiers[] = $fichiers;

        return $this;
    }

    /**
     * Remove fichiers
     *
     * @param \ENSA\PortailWebLaboratoireBundle\Entity\Fichier $fichiers
     */
    public function removeFichier(\ENSA\PortailWebLaboratoireBundle\Entity\Fichier $fichiers)
    {
        $this->fichiers->removeElement($fichiers);
    }

    /**
     * Get fichiers
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getFichiers()
    {
        return $this->fichiers;
    }



}

**Comment by K-Phoen** [comment]
It seems that you forgot to add the `@Vich\Uploadable` annotation to your class, as specified in [the documentation](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/usage.md#step-2-link-the-upload-mapping-to-an-entity).

**Comment by 01sup** [comment]
nn actually I dont forget it I deleted the entity yesterday and I forget to add this annoation today
so this is not the problem, I'm getting the same error even with the annotation !

**Comment by K-Phoen** [comment]
Probably a cache issue then. Once the entity is properly configured, you have to clear the cache.

**Comment by 01sup** [comment]
I cleared the cache also (cache:clear) so this is not the problem !

**Comment by 01sup** [comment]
should i use 2 entities one for the Article and the other for storing the file !!!

Or there is somthing wrong with this line of code : 
@Vich\UploadableField(mapping="product_image", fileNameProperty="imageName") *

because I dont know what mapping="product_image" mean and what it's relation with my article entity !!!

**Comment by 01sup** [comment]
And this my config.yml configuration : 

# app/config/config.yml
vich_uploader:
    db_driver: orm

    mappings:
        espace_partage:
            uri_prefix:         /documents
            upload_destination: %kernel.root_dir%/../web/documents
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

I created a folder named documents in the web folder of symfony !

**Comment by 01sup** [comment]
update : 
 I changed the attribute mapping to "espace_partage" and the error is not shwon anymore but nothing is added to the database !!!

**Comment by 01sup** [comment]
UPDATE : 
I figure out that this issue have a relation with the size of the file (I think around 3Mo), so now I want to allow anay size of files !

**Comment by yaK2manD** [comment]
maybe related to #442

**Comment by 01sup** [comment]
YAA I foget to close this issue; tnx again :)
