### ISSUE TITLE
@Vich\Uploadable on a @MappedSuperclass

### ISSUE THREAD

**Issue by Yoshix** [dustin10/VichUploaderBundle#440]
When using `@Vich\Uploadable` on a `@MappedSuperclass` I get the following error:

    Notice: Undefined index: %FQCN%
    in: vendor/vich/uploader-bundle/Metadata/MetadataReader.php at line 78

The `%FQCN%` above is the class name of the entity class not the base class. And as such the index is undefined, because the meta data used the FQCN of the base class.

Changing:

    $classMetadata = $metadata->classMetadata[$class];

in line 78 to:
  
    $classMetadata = $metadata->getRootClassMetadata();

fixes the issue.

Is this the right approach?

**Comment by K-Phoen** [comment]
When I look at the line 78 of the same file I don't have the same code. Are you sure that you use the latest version of the bundle?

**Comment by Yoshix** [comment]
I'm not really sure. When using:

    composer require vich/uploader-bundle

composer adds:

    "vich/uploader-bundle": "^0.14.0"

to my `composer.json`. Which seems far older than what is currently available here.

**Comment by K-Phoen** [comment]
Yep, that's because the latest releases are all beta.

Try requiring `"vich/uploader-bundle": "~1.0@beta"`

**Comment by Yoshix** [comment]
That did the trick! Thanks a lot! ;D
