### ISSUE TITLE
VichUploaderBundle (Files size) !

### ISSUE THREAD

**Issue by 01sup** [dustin10/VichUploaderBundle#442]
I'm now working with this bundle, but if I chose to upload a file that have a size bigger than 3Mo, the file is not uploaded !!!

 is there a configuration to change related with the size !!

It tried the annotation @Assert\File(maxSize="XXXXX") but with no result !

**Comment by yaK2manD** [comment]
What is your php.ini configuration ?

**Comment by 01sup** [comment]
I dont know what is a php.ini configuration :(

**Comment by yaK2manD** [comment]
Ok. Which OS are you working on?

You should take a look here : http://php.net/manual/en/configuration.file.php
And http://stackoverflow.com/questions/2184513/php-change-the-maximum-upload-file-size

In other words, if you use Apache with php (WampServer for windows for example), by default, you can upload up to 2M files. So you have to edit your server config file (php.ini) to increase this value (ie. 2nd link) and then reload it.

**Comment by 01sup** [comment]
Thanks a lot, you're a genius :)
