### ISSUE TITLE
Overwriting of vich_image_widget doesn't work properly

### ISSUE THREAD

**Issue by decebaldecebal** [dustin10/VichUploaderBundle#443]
Hello,
So I tried overwriting the vich_image_widget as below because of a current problem in Vich Uploader Bundle that even if I render the field using form_widget, it still puts 2 <div> and the the input field instead of just rendering the input field like with other Symfony form elements, and I needed to add a class to the input field itself and this was the only solution I have found. 

```
{% block vich_image_widget %}
    {% spaceless %}
    {% set type = type|default('file') %}
    <input class="imgUpload" type="{{ type }}" {{ block('widget_attributes') }} />
    {% endspaceless %}
{% endblock %}
```

So then I encountered another problem.The block('widget_attributes') actually doesn't render the correct "id" and "name" on the input.When I render it with form_widget, the "id" has "_file" appended to the end of the string that block('widget_attributes') id renders, and the "name" has "[file]" appended to it and block('widget_attributes') doesn't.

So when I tried overwriting the template, I kept getting validation errors.As a workaround, I edited the DOM using javascript and added the appropriate string to the "id" and "name" of the input field until this gets fixed.

**Comment by joaoalves89** [comment]
You can overwrite the widgets like this:

```yml
twig:
    form_themes:
        - 'Form/vich_fields.html.twig' # path for your template
```

```twig
{% extends 'VichUploaderBundle:Form:fields.html.twig' %}

{% block vich_file_widget %}
    {{ parent() }}
    {{ block('field_help') }}
{% endblock %}

{% block vich_image_widget %}
    {{ parent() }}
    {{ block('field_help') }}
{% endblock %}
```

**Comment by decebaldecebal** [comment]
I know how to overwrite templates, the problem is that the code
block('widget_attributes')
doesn't render the proper attributes that are rendered when you use the default template.

**Comment by crmpicco** [comment]
@joaoalves89 Great answer! :+1:

**Comment by garak** [comment]
This should be fixed since some versions ago. Feel free to re-open, if not.
