### ISSUE TITLE
Can't use VichImageType

### ISSUE THREAD

**Issue by picks44** [dustin10/VichUploaderBundle#444]
I get this error 
> The object is not uploadable.

If I go back to using "file" in my FormType, it's OK...
I've also added the Twig like this 
```
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes: ['bootstrap_3_layout.html.twig', 'VichUploaderBundle:Form:fields.html.twig']
```

**Comment by zhaocunyang** [comment]
if use file can not update this record file
