### ISSUE TITLE
Use Assert validation

### ISSUE THREAD

**Issue by picks44** [dustin10/VichUploaderBundle#450]
hello there, 

great bundle, but is there a way to user @Assert() validation for maxHight / maxWidth / maxSize etc... ?
This feature is pretty important in my projet.

Thanks a lot for your answer.

**Comment by K-Phoen** [comment]
You can use the validation [as documented by Symfony](http://symfony.com/doc/current/book/validation.html). Just define your constraints on the attribute containing the `File` instance and it should work.

**Comment by picks44** [comment]
Thks !
