### ISSUE TITLE
DEPRECATED - FormTypeInterface::setDefaultOptions()

### ISSUE THREAD

**Issue by patie** [dustin10/VichUploaderBundle#453]
DEPRECATED - Vich\UploaderBundle\Form\Type\VichFileType: The FormTypeInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead. This method will be added to the FormTypeInterface with Symfony 3.0.

**Comment by K-Phoen** [comment]
If you want to write a PR for that, I'd be happy to review it :)

**Comment by belendel** [comment]
Made a PR for it.

**Comment by K-Phoen** [comment]
Should be fixed in master.
