### ISSUE TITLE
Attachment class called twice (first UploadedFile then File instance)

### ISSUE THREAD

**Issue by fleskalebas** [dustin10/VichUploaderBundle#456]
I am trying to get the `GetClientOriginalName()` of an uploaded file but when I dump the `$image->getClientOriginalName()` I get an error that the file instance is not `UploadedFile`, but `File`. However, the original file name dumps fine.

It turns out that the class is called twice. When I dump `$image`, I get an `UploadFile` first, then I get a `File`. So when I dump `getClientOriginalName()`, it dumps the correct name first and because of the second time (when it's a `File` instance) I get a Symfony error.

So I have a check:

```
if(!$this->fileorigname) {
            $this->fileorigname = $image->getClientOriginalName();
        }
        dump($this->fileorigname);
```

This works fine, but I am curious why the class is called twice (first `UploadedFile`, then `File`). How can I get to only call it once with a `UploadedFile` so I can use the 'Client' Functions?

I use multiple file uploading with a Document class with an Attachment form collection. Maybe that's the culprit?

**Comment by garak** [comment]
It's likely like so: when you upload the file, you get an `UploadedFile`; when you use your object outside the uploading process, you get a `File`.
Just check if your property is an instance of `UploadedFile`.

**Comment by garak** [comment]
Closing for missing feedback
