### ISSUE TITLE
Problem with generated relative/absolute url to the file

### ISSUE THREAD

**Issue by memorydeveloper** [dustin10/VichUploaderBundle#457]
The problem I want to expose is this:

In a dedicated web hosting like http://mysite.com publishing the web folder, the uploaded file generated url is like this:

/uploads/myfile.zip

But in a service like this:

http://mysite.com/my_project/web/app.php

the url generated is the same and it does not work. It resolve to something like this:

http://mysite.com/uploads.zip

This is an incorrect path to the file.

What can I do?

Thanks

Raibel

**Comment by K-Phoen** [comment]
The [`uri_prefix` configuration option of the mappings](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/usage.md#step-1-configure-an-upload-mapping) should be what you are looking for.

You could use "/my_project/web/" as value and it should do what you want.
