### ISSUE TITLE
form_errors with form theme

### ISSUE THREAD

**Issue by Tetdoss** [dustin10/VichUploaderBundle#460]
Hello i have an issue using your form theme

I'm using an assert on my imageFile : * @Assert\Image(maxSize="300k", mimeTypes={"image/jpeg", "image/png"}, allowLandscape=true, allowPortrait=false)

But when I validate the form, the imageFile errors are considered as global error and not as field error :/

It's not a global error when I'm not using your form theme.

Thank you !

**Comment by garak** [comment]
This is not related to theme. Indeed, even without vich form theme, the error is global, since Symfony defaults ``error_bubbling`` option to ``true`` for compound elements.

**Comment by K-Phoen** [comment]
Should be fixed in master.
