### ISSUE TITLE
Change filename for download

### ISSUE THREAD

**Issue by Noxalus** [dustin10/VichUploaderBundle#461]
Hello everyone.

I browsed the entire documentation and I didn't find the solution for this problem. I know it's possible to name the uploaded files as we want using namers, but I want to keep my files with unique id as filename on my server. But I also want to give them a more representative name for users that will download them.

If I remember correctly, we can do that sending some additional data into HTTP header like that:

```
header('Content-Disposition: attachment; filename=' . $customFilename);
```

Is it something handled by VichUploaderBundle?

**Comment by K-Phoen** [comment]
The bundle provides a `DownloadHelper` that can help you to do that. I just wrote a bit a documentation for it, you can find it here: https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/downloads/serving_files_with_a_controller.md

Feel free to comment here if you need anything :)
