### ISSUE TITLE
How to remove/disable the delete checkbox

### ISSUE THREAD

**Issue by mrvudo** [dustin10/VichUploaderBundle#467]
There is a delete checkbox next to the upload field.

Is there a way to remove this field from displaying?

**Comment by K-Phoen** [comment]
You can use the `allow_delete` option [described in the documentation](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/form/vich_file_type.md). Setting it to false should do the trick.

**Comment by mrvudo** [comment]
Thanks, that worked
