### ISSUE TITLE
Deprecated: Accessing type "file" by its string name is deprecated since version 2.8 and will be removed in 3.0

### ISSUE THREAD

**Issue by sc0rp10** [dustin10/VichUploaderBundle#477]
Accessing type "file" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\FileType" instead

vich/uploader-bundle/Form/Type/VichFileType.php:44
vich/uploader-bundle/Form/Type/VichFileType.php:71

This warning should be fixed with replacing 'file' with `FileType::class`.
I can PR this, but it will break BC with symfony/symfony < 2.8

**Comment by K-Phoen** [comment]
Hi!

I'm more than okay to fix deprecation notices (we've already fixed a few in this bundle) but I really want to preserve BC.

Is there a way to achieve this in regard of this notice?

**Comment by sc0rp10** [comment]
Regarding to https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#form I don't know how to preserve BC. With 3.0 VichUploaderBundle will not work, but if these notices will be fixed, will not work with 2.x.
Only (very ugly) way is it detecting versions like:
```php
if (is_symfony3()) {
        $builder->add('file', FileType::class', array(
            'required' => $options['required'],
            'label'    => $options['label'],
            'attr'     => $options['attr'],
        ));
} else {
        $builder->add('file', 'file', array(
            'required' => $options['required'],
            'label'    => $options['label'],
            'attr'     => $options['attr'],
        ));
}
```
Maybe is there another solutions, but i don't see them.

**Comment by sc0rp10** [comment]
@K-Phoen any ideas? Because of this users can't update symfony to 3.0.

**Comment by K-Phoen** [comment]
I didn't have time to investigate this issue. I'll try this week-end but I can't promise.

Help is appreciated though ;)

**Comment by sc0rp10** [comment]
I can do it, but I need your decision about BC with 2.8.
Variants:
- drop 2.8 support (bad idea because of 2.8 is LTS release)
- create separated branches (double support)
- create polyfill (ugly code and may be impossible)
- ignore 3.0 (bad idea too)

**Comment by K-Phoen** [comment]
I think there is a way to support both 2.x and 3.x in the same codebase. At least, that's what I want and will try to do.

I tried something like this and it seems to work:

```diff
diff --git a/Form/Type/VichFileType.php b/Form/Type/VichFileType.php
index c27c145..8780e0b 100644
--- a/Form/Type/VichFileType.php
+++ b/Form/Type/VichFileType.php
@@ -11,6 +11,8 @@ use Symfony\Component\Form\FormView;
 use Symfony\Component\OptionsResolver\OptionsResolver;
 use Symfony\Component\OptionsResolver\OptionsResolverInterface;
 use Symfony\Component\Translation\TranslatorInterface;
+use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
+use Symfony\Component\Form\Extension\Core\Type\FileType;
 
 use Vich\UploaderBundle\Form\DataTransformer\FileTransformer;
 use Vich\UploaderBundle\Handler\UploadHandler;
@@ -48,7 +50,7 @@ class VichFileType extends AbstractType
      */
     public function buildForm(FormBuilderInterface $builder, array $options)
     {
-        $builder->add('file', 'file', array(
+        $builder->add('file', new FileType(), array(
             'required' => $options['required'],
             'label'    => $options['label'],
             'attr'     => $options['attr'],
@@ -75,7 +77,7 @@ class VichFileType extends AbstractType
                 return;
             }
 
-            $form->add('delete', 'checkbox', array(
+            $form->add('delete', new CheckboxType(), array(
                 'label'     => $translator->trans('form.label.delete', array(), 'VichUploaderBundle'),
                 'required'  => false,
                 'mapped'    => false,
@@ -108,10 +110,16 @@ class VichFileType extends AbstractType
         }
     }
 
+    // BC for SF < 2.8
+    public function getName()
+    {
+        return $this->getBlockPrefix();
+    }
+
     /**
      * {@inheritdoc}
      */
-    public function getName()
+    public function getBlockPrefix()
     {
         return 'vich_file';
     }
̀```

We should confirm that it really works against all the Symfony versions supported by the bundle, that it does not trigger deprecation notices and that it follows the best practices.

It's just a start, I'm sure that there is more needed to achieve a real compatibility.

**Comment by sc0rp10** [comment]
https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#form says
> Passing type instances to Form::add(), FormBuilder::add() and the FormFactory::create*() methods is deprecated and will not be supported anymore in Symfony 3.0. Pass the fully-qualified class name of the type instead.

>Before:

> `$form = $this->createForm(new MyType());`
>After:

> `$form = $this->createForm(MyType::class);`

**Comment by K-Phoen** [comment]
Well, if we need to pass the FQCN, we can. The `::class` syntax not being available in PHP 5.4 (the minimal version supported by the bundle), we'll need to write it ourselves.

Here is what I want to achieve : a single branch supporting both 2.x and 3.x.
If you feel like it, you can draft a PR. If not, I'll try to work on it this weekend.

I'm at work right now and I don't have much time for this, sorry.

**Comment by sc0rp10** [comment]
symfony 3.0 requires php >= 5.5.9 https://github.com/symfony/symfony/blob/master/composer.json#L19

**Comment by K-Phoen** [comment]
I know. But this bundle supports symfony ~2.3 and requires PHP >= 5.4

**Comment by K-Phoen** [comment]
A fix landed in master :)
