### ISSUE TITLE
Is Symfony 3 support planned ?

### ISSUE THREAD

**Issue by Booteille** [dustin10/VichUploaderBundle#483]
Hi.

I just wanted to know if the support for Symfony 3 is planned.

Thanks.

**Comment by K-Phoen** [comment]
Symfony 3 should already be supported. Did you notice a bug?

**Comment by Booteille** [comment]
Just I wasn't able to download it without asking for "dev-master". Composer told me version 3.0.0 where not supported, only versions until 2.8.0.

I didn't notice any bug since I installed it though.

**Comment by garak** [comment]
Indeed, there is no stable tag with Symfony 3 support.

**Comment by Booteille** [comment]
Okay.

**Comment by milan74sk** [comment]
Same to me:
Install Symfony 2.7.? (don't remember exact number) | Don't install Symfony 3.0.0

**Comment by javiereguiluz** [comment]
Same for me:

![vich_symfony_3](https://cloud.githubusercontent.com/assets/73419/12024486/b6d50468-ada4-11e5-8b0d-d2b7ed15461f.png)

Any updates about this issue?

**Comment by fkrauthan** [comment]
@K-Phoen Any plans to release a stable version soon with symfony 3.0 support?

**Comment by K-Phoen** [comment]
A stable release, I honestly don't know. There are some issues to fix and I don't know when I will have enough time.

But I tagged a new beta version with Symfony 3.0 support (1.0.0-beta7).

**Comment by garak** [comment]
@K-Phoen is there a way to help? I'm looking into issues and I can't see a milestone nor labels to find blocking issues

**Comment by K-Phoen** [comment]
I just created a milestone for the 1.0.0 release.

My main concerns are Symfony 2.3 to 3.0 compatibility and form themes integration. There seem to be issues with YAML mappings in Symfony 3.0 apps and somme issues related to the form themes (duplicated labels, errors displayed in the wrong place, …).
If you want to help you can provide a way to reproduce these issues or draft a PR to solve them if you want. Any help is appreciated :)
