### ISSUE TITLE
Symfony3 - impossible to install / use

### ISSUE THREAD

**Issue by milan74sk** [dustin10/VichUploaderBundle#486]
what means this and how to fix ?

...

composer require vich/uploader-bundle

Using version ^0.14.0 for vich/uploader-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vich/uploader-bundle ^0.14.0 -> satisfiable by vich/uploader-bundle[v0.14.0].
    - Conclusion: remove symfony/symfony v3.0.0
    - Conclusion: don't install symfony/symfony v3.0.0
    - vich/uploader-bundle v0.14.0 requires symfony/property-access ~2.3 -> satisfiable by symfony/property-access[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
    - don't install symfony/property-access v2.3.0|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.1|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.10|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.11|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.12|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.13|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.14|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.15|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.16|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.17|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.18|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.19|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.2|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.20|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.21|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.22|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.23|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.24|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.25|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.26|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.27|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.28|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.29|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.3|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.30|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.31|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.32|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.33|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.34|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.35|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.4|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.5|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.6|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.7|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.8|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.3.9|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.4.0|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.4.1|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.4.10|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.4.2|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.4.3|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.4.4|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.4.5|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.4.6|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.4.7|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.4.8|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.4.9|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.0|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.1|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.10|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.11|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.12|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.2|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.3|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.4|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.5|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.6|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.7|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.8|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.5.9|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.0|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.1|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.10|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.11|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.12|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.2|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.3|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.4|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.5|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.6|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.7|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.8|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.6.9|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.7.0|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.7.1|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.7.2|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.7.3|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.7.4|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.7.5|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.7.6|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.7.7|don't install symfony/symfony v3.0.0
    - don't install symfony/property-access v2.8.0|don't install symfony/symfony v3.0.0
    - Installation request for symfony/symfony 3.0.* -> satisfiable by symfony/symfony[v3.0.0].

Installation failed, reverting ./composer.json to its original content.

...

**Comment by mbiert** [comment]
@milan74sk try ```composer require vich/uploader-bundle dev-master``` there hasn't been a tag added yet for v3

**Comment by milan74sk** [comment]
I see ... 
now it has been downloaded corectly
thank you very much for the info

**Comment by saifrehman15** [comment]
symfon2 unable to install .

$ composer require vich/uploader-bundle
Using version ^1.8 for vich/uploader-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v2.8.16
    - Conclusion: don't install symfony/symfony v2.8.16
    - vich/uploader-bundle 1.8.0 requires symfony/form ^3.4|^4.0 -> satisfiable by symfony/form[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1].
    - vich/uploader-bundle 1.8.1 requires symfony/form ^3.4|^4.0 -> satisfiable by symfony/form[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1].
    - vich/uploader-bundle 1.8.2 requires symfony/form ^3.4|^4.0 -> satisfiable by symfony/form[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1].
    - vich/uploader-bundle 1.8.3 requires symfony/form ^3.4|^4.0 -> satisfiable by symfony/form[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1].
    - symfony/form v3.4.0 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.1 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.10 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.11 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.12 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.2 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.3 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.4 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.5 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.6 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.7 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.8 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v3.4.9 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.0 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.1 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.10 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.11 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.12 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.2 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.3 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.4 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.5 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.6 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.7 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.8 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.0.9 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.1.0 conflicts with symfony/symfony[v2.8.16].
    - symfony/form v4.1.1 conflicts with symfony/symfony[v2.8.16].
    - Installation request for symfony/symfony (locked at v2.8.16, required as 2.8.*) -> satisfiable by symfony/symfony[v2.8.16].
    - Installation request for vich/uploader-bundle ^1.8 -> satisfiable by vich/uploader-bundle[1.8.0, 1.8.1, 1.8.2, 1.8.3].


Installation failed, reverting ./composer.json to its original content.

**Comment by garak** [comment]
@saifrehman15 you need to try with an older version

**Comment by saifrehman15** [comment]
kindly share the version name.

**Comment by garak** [comment]
`^1.7`

**Comment by saifrehman15** [comment]
Thanks

**Comment by saifrehman15** [comment]
Also try to install ^1.4 but did't work.

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonata-project/user-bundle 3.x-dev requires sonata-project/core-bundle ^3.2 -> satisfiable by sonata-project/core-bundle[3.10.0, 3.2.0, 3.3.0, 3.4.0, 3.5.0, 3.5.1, 3.6.0, 3.7.0, 3.7.1, 3.8.0, 3.9.0, 3.9.1, 3.x-dev] but these conflict with your requirements or minimum-stability.
    - sonata-project/user-bundle 3.x-dev requires sonata-project/core-bundle ^3.2 -> satisfiable by sonata-project/core-bundle[3.10.0, 3.2.0, 3.3.0, 3.4.0, 3.5.0, 3.5.1, 3.6.0, 3.7.0, 3.7.1, 3.8.0, 3.9.0, 3.9.1, 3.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for sonata-project/user-bundle 3.x-dev -> satisfiable by sonata-project/user-bundle[3.x-dev].

**Comment by garak** [comment]
Ask Sonata
