### ISSUE TITLE
formType use VichFileType::class and form_themes use bootstrap_3_layout.html.twig has problem

### ISSUE THREAD

**Issue by zhaocunyang** [dustin10/VichUploaderBundle#487]
when I use bootstrap form themes and formType use VichFileType::class has a problem
![image](https://cloud.githubusercontent.com/assets/10735017/11970629/88bc61aa-a969-11e5-8fbc-9acaf0398256.png)

**Comment by K-Phoen** [comment]
Can you explain the problem?

**Comment by zhaocunyang** [comment]
if  I use bootstrap form themes and formType use VichFileType::class when will see add to a layer '<div>'and '<label>'  so will see two label

**Comment by garak** [comment]
This issue is with bootstrap theme, not with this bundle. The bundle is just using ``{{ form_row(form.file) }}``.
My personal workaround is hiding one of labels using CSS.

**Comment by garak** [comment]
Anyway, it should be fixed in 3d091a43b8d90e1e71933ac32e2d94885356625a

**Comment by K-Phoen** [comment]
I close this issue then.
