### ISSUE TITLE
update file has a problem

### ISSUE THREAD

**Issue by zhaocunyang** [dustin10/VichUploaderBundle#488]
use this bundle if i create entity not upload file then update this record upload file, cannot upload file for this record ! if i delete one entity record file and save , then update this record and upload new file , can not save file

**Comment by themao** [comment]
I can confirm, updating an entity by uploading a new file does not upload that file at all

**Comment by themao** [comment]
After doing some investigations I discovered that the file does not get uploaded if it was the only change in the entity. If, for example, a name was changed, too - then the file is also uploaded

**Comment by themao** [comment]
@zhaocunyang there is a thread (and a solution) already related to this problem https://github.com/dustin10/VichUploaderBundle/issues/8#issuecomment-3780172

**Comment by K-Phoen** [comment]
Yep, that's a [known issue](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/known_issues.md#the-file-is-not-updated-if-there-are-not-other-changes-in-the-entity).

**Comment by zhaocunyang** [comment]
I know thanks
