### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lunetics** [dustin10/VichUploaderBundle#489]
Isn't it time after a year to release a new stable version?

**Comment by K-Phoen** [comment]
Time, maybe. But there are some issues that need to be fixed before releasing a new stable version.

Any help I can get is welcome though :)

**Comment by geekdevs** [comment]
@K-Phoen Which issues do you want to get solved before release? I might be able to help

**Comment by K-Phoen** [comment]
@geekdevs It would be awesome! You can have a look at the [1.0.0 milestone](https://github.com/dustin10/VichUploaderBundle/milestones/1.0.0) :)

**Comment by geekdevs** [comment]
@K-Phoen ok. trying to dig into it.
Is `runTests.sh` script up-to-date? I get a lot of BC breaks (travis looks good though)

```
2.3.0 = OK

2.5.0 
Vich\UploaderBundle\Tests\Functional\UploadTest::testFileIsUploadedWithFileType
Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("You have requested a non-existent service "request_stack".") in "form_div_layout.html.twig" at line 208.

2.6.0
Vich\UploaderBundle\Tests\Functional\UploadTest::testFileIsUploadedWithFileType
Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The parameter "debug.error_handler.throw_at" must be defined.

2.7.0 = OK

2.8.0
1) Vich\UploaderBundle\Tests\Functional\UploadTest::testFileIsUploadedWithFileType
Failed asserting that false is true.

/var/www/VichUploaderBundle/Tests/Functional/UploadTest.php:13

2) Vich\UploaderBundle\Tests\Functional\UploadTest::testFileIsUploadedWithImageType
Failed asserting that false is true.

/var/www/VichUploaderBundle/Tests/Functional/UploadTest.php:51

3.0.0 = OK
```

**Comment by JHGitty** [comment]
The Symfony documentation links to the VichUploaderBundle. That because I want to integrate it. But then I saw that Symfony 3 is not compatible with the current stable version.

Because the Symfony 3 documentation suggests this bundle it should be get a stable version which is compatible with Symfony 3 as fast as possible.

**Comment by K-Phoen** [comment]
Actively working on this bundle isn't my priority right now (unfortunately). But I have enough time to review and merge pull-requests :)

**Comment by JHGitty** [comment]
@K-Phoen Could you add a label to all issues which should be resolved for a stable release?

**Comment by K-Phoen** [comment]
There already is a milestone for that.

**Comment by JHGitty** [comment]
@K-Phoen But there is currently one single issue in it which is not fully reproducible yet. Please add all needed issues to the milestone.

**Comment by geekdevs** [comment]
@K-Phoen if you have time to review, maybe you could answer my question form 1 week ago? ;) 
Cannot run tests, am I missing something?

**Comment by K-Phoen** [comment]
Tests should obviously be green (they are on Travis). I don't know what could go wrong with this script (maybe a cache-related issue?)

Sorry for the late and unhelpful answer…

**Comment by geekdevs** [comment]
@K-Phoen ok, at least I now know that you're not aware of the issue. Will take a deeper look into it.
For me it seems that the problem is that it does not update symfony dependencies correctly

**Comment by JHGitty** [comment]
@geekdevs Please create a new issue for this.

**Comment by garak** [comment]
So, the milestone is done. Can you release v1.0.0?

**Comment by K-Phoen** [comment]
@garak there is still a [PR](https://github.com/dustin10/VichUploaderBundle/pull/401) to review before v1.0.0 (and honestly, I don't know if the PR is correct or not)

Want to have a look at it?

**Comment by spacetraveller** [comment]
Symfony 3.x is out - since most new projects will be built in Symfony 3.x, and plenty of documentation points to 3.x and this file upload plugin, there is a huge expectation that this plugin would work with it.

Is there anyone that can help with integrating this into Symfony 3 ?

Attempting to install it displays a long list of requirement issues.

**Comment by achristodoulou** [comment]
:+1:

**Comment by gbelmm** [comment]
+1

**Comment by K-Phoen** [comment]
1.0.0 has just been tagged :)
