### ISSUE TITLE
Handling file uploads when there is a ManyToOne relationship

### ISSUE THREAD

**Issue by reypm** [dustin10/VichUploaderBundle#491]
I have a `ManyToOne` relationship between `Identifier` and `Downloads` entities as shown in the following code:

    class Identifier
    {
        ...

        /**
         * @ORM\ManyToOne(targetEntity="Downloads")
         * @ORM\JoinColumn(name="downloads_id", referencedColumnName="id")
         */
        protected $downloads;
    }

    class Downloads
    {
        use IdentifierAutogeneratedTrait;
        use TimestampableEntity;
        use ActiveTrait;

        /**
         * @ORM\Column(type="string", length=150)
         * @Assert\NotBlank()
         */
        protected $name;

        public function setName($name)
        {
            $this->name = $name;
            return $this;
        }

        public function getName()
        {
            return $this->name;
        }

        public function __toString()
        {
            return $this->name;
        }
    }

How do I link the upload mapping to entities in this edge case? I think that `imageName` and `imageFile` (both coming from [this docs][1]) should be at `Downloads` entity but I am not sure if I am in the right path any advice here? Should be `Downloads` the linked entity?

 [1]: https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/usage.md#step-2-link-the-upload-mapping-to-an-entity

**Comment by a2xchip** [comment]
Create ```DownloadType``` then ```IdentifierType``` and include DownloadType as a ```collection``` form see Symfony documentation http://symfony.com/doc/current/cookbook/form/form_collections.html
