### ISSUE TITLE
Problem when creating a new entity

### ISSUE THREAD

**Issue by totechess** [dustin10/VichUploaderBundle#495]
I am trying to create a table to store images which will lately display in a slideshow in a specific order

Entity: https://gist.github.com/totechess/ed10ae3a9b9e49eeacae
Controller: https://gist.github.com/totechess/98a209d46a5043043f9c
Form: https://gist.github.com/totechess/b58e927f8f68d4708053

When I submit the form I got this error

An exception occurred while executing 'INSERT INTO slide_image (image, order, created) VALUES (?, ?, ?)' with params ["5691b60e864b6_chess-board-rules-chess_00418821jpg-awesome.jpg", 1, "2016-01-10 02:38:22"]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order, created) VALUES ('5691b60e864b6_chess-board-rules-chess_00418821jpg-aweso' at line 1

I don't know what's happening or how can I fix it

**Comment by jkabat** [comment]
My guess is that 'order' column must use backtics as it is reserved word. You either change the column name or try to find out which bundle is failing - it doesn't even have to be VichUploaderBundle.

**Comment by sasy-lingo** [comment]
@totechess Check this SO thread: http://stackoverflow.com/a/10483663
@jkabat Found the problem ;)

**Comment by K-Phoen** [comment]
Agreed, does not look like a VichUploaderBundle issue.
