### ISSUE TITLE
Form field vich_image does not reiqure file to be an image

### ISSUE THREAD

**Issue by JarJak** [dustin10/VichUploaderBundle#497]
You can upload any file through this form field.

**Comment by K-Phoen** [comment]
Validation should be handle by the application, through validation rules.

**Comment by JarJak** [comment]
Shouldn't in be mentioned in documentation?

**Comment by K-Phoen** [comment]
It's the common way to do validation in Symfony apps so I don't think that we need to duplicate the this knowledge in our doc.
