### ISSUE TITLE
Upload Files outside web folder

### ISSUE THREAD

**Issue by crash21** [dustin10/VichUploaderBundle#500]
Hello,

If I want to upload files outside web folder then how should I serve them?
Should i create a handler and what action name this handler should have? (i want to server files not download them, it img src="images/foo.png""  but this file is not under web folder but in app/data

Thanks a lot.

**Comment by K-Phoen** [comment]
I don't understand why you want to store your files outside the web folder if you still want to be able to serve them.
One of the reason to move the files in the `app/` directory (for instance) is to prevent the webserver from accidentally serving them to unauthorized users.

**Comment by crash21** [comment]
I need because I use watermarks.

So the idea is to upload them in app/data/uploads
and in the /web/uploads folder have only the watermarks (which are generated from LiipImagineBundle)

Otherwise I will expose original images in the web folder,
Also I don't need to save them initially to web folder with watermark because if i decide to change watermark text, font size or position I wont have original images to process the new watermark.

By the way I made this working with the help of LiipImagineBundle (using loaders) but was wondering if its also possible to do this only with Vich.

Thanks,
Nick

**Comment by JHGitty** [comment]
There is already a discussion about the best directory for storage of persistent data: https://github.com/symfony/symfony-docs/issues/6095

As described by @andrerom we should use the directory ``/var/public/`` or ``/var/data`` or ``/var/storage``.

The ``/app`` directory should be read-only for the webserver - please DO NOT store such data there because the ``/app`` directory should not be writeable.

**Comment by K-Phoen** [comment]
The point here isn't about `/app` vs `/var`, it's more about `/web` vs anything else ;)

**Comment by JHGitty** [comment]
@K-Phoen Sure. I want just to notify people about wrong usage of the ``/app`` directory.

We should mainly discuss about a subfolder in ``/var``. This question is a basic question in the Symfony community which is not fully resolved yet. The default Symfony structure results in something in ``/web/`` but I also think it is not nice to write data directly into it.

**Comment by hackzilla** [comment]
I'm using a controller to server files outside of the web directory.

See: [serving_files_with_a_controller.md](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/downloads/serving_files_with_a_controller.md)

**Comment by garak** [comment]
Closing, since it's supported via documentation.

**Comment by seddighi78** [comment]
I see [serving_files_with_a_controller.md](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/downloads/serving_files_with_a_controller.md) but how to render the image in twig I will upload my files to `/var/uploads/...` directory

**Comment by hackzilla** [comment]
@seddighi78 I'd personally use a symlink.
