### ISSUE TITLE
How to upload file to the dynamic subdirectory?

### ISSUE THREAD

**Issue by bocharsky-bw** [dustin10/VichUploaderBundle#501]
How can I create a custom namer which could generate some hash like `d74a1cb2f57966565d735c6332b77474.jpg` and then split it to the few subdirectories like `/d7/4a/1cb2f57966565d735c6332b77474.jpg`, so the resulting file `1cb2f57966565d735c6332b77474.jpg` uploads to the '%upload_destination%/d7/4a/' directory. 

Can I do it with VichUploadBundle?

**Comment by bocharsky-bw** [comment]
I think the main problem I faced with this issue is that `directory namers MUST be stateless`.

**Comment by JHGitty** [comment]
Could you explain us some benefits why there should be subfolders used? I saw similar in the Twig cache storage but as I understood it only results in better performance if you use 1000 or 10000 files in a folder, right?

It would be nice to understand this more - maybe there are some benchmarks about that.

**Comment by bocharsky-bw** [comment]
@JHGitty I don't have any performance benchmarks personally, but you're right! I consider it with a performance point. And yes, I try to implement something what Twig do for all my uploads.

**Comment by JHGitty** [comment]
Should we support that a namer is allowed to return a path (directory + filename) instead of only a filename? I have not checked it but I think it is not supported currently?

**Comment by JHGitty** [comment]
I found that there is already a "directory namer" interface: https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/directory_namer/howto/create_a_custom_directory_namer.md

I think the directory namer is made for your requirements, isn't it?

**Comment by bocharsky-bw** [comment]
@JHGitty I think, the main problem is that:
> directory namers MUST be stateless

See notes in [namers.md](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/namers.md#directory-namer). I tried to use my custom directory namer to resolve this but I failed. Seems directory namer is independent of file namer. Maybe one of the possible solutions is to make directory and file namers aware about each other.

**Comment by JHGitty** [comment]
@K-Phoen I think this issue should get the ``Enhancement`` label.

**Comment by K-Phoen** [comment]
I think that what @bocharsky-bw wants to do is already feasible. The directory namers are [called after the file namers](https://github.com/dustin10/VichUploaderBundle/blob/de4006e73e3bd14ac3d784f72971ddf5cf112b97/Storage/AbstractStorage.php#L55-L62) and have access to both the object and the [mapping](https://github.com/dustin10/VichUploaderBundle/blob/de4006e73e3bd14ac3d784f72971ddf5cf112b97/Naming/DirectoryNamerInterface.php#L22).

So using the filename to generate a directory name should already work :)

**Comment by bocharsky-bw** [comment]
@K-Phoen Yeah, looks like it works already but with some bugs on update/remove. I guess it happens because file namer only calls for uploading files, but directory namer also calls for updating and deleting. Actually, directory namer is called even to display already uploaded image, always. I think this is a strange usage of directory namer. As a file namer, directory namer should be triggered only on uploading, I think.

**Comment by Koc** [comment]
@bocharsky-bw see related PR

**Comment by c33s** [comment]
@Koc very nice PR maybe you want to add a few features to it...

currently i work on a project, which uploads everything into one directoy, a simple directory listing `ls -lsa` needs ages to execute. about 1024 files per directory is a good value to go for.

php can also split up files for sessions: https://secure.php.net/manual/en/session.configuration.php#ini.session.save-path 

> For example, setting to `'5;/tmp'` may end up creating a session file and location like `/tmp/4/b/1/e/3/sess_4b1e384ad74619bd212e236e52a5a174If `. 

my two cents: it would be quite important do keep the full filename, this would make it to handle the file when moving it, putting it to a cdn, ...

also for better handling file content changes and caching, it would be good to have the option to calculate the hash content based [`sha1_file()`](https://secure.php.net/manual/en/function.sha1-file.php)
