### ISSUE TITLE
Generate URL for Amazon S3

### ISSUE THREAD

**Issue by fcpauldiaz** [dustin10/VichUploaderBundle#502]
I'm using Gaufrette as a layer to make uploads to Amazon S3 servers. It works like expected but I don't know how to make the URL'S. I can't find any documentation about this.

The way I did it was: first make the folder public in my Amazon server and the following hack:
```twig
<a  target="_blank" href="https://s3.amazonaws.com/plataformavirtual/parcialesyhdt/{{doc.documentName}}">Descargar</a>
```
Is there another way to do this?

When I didn't have the Amazon server I did it this way:
```twig
<a  target="_blank" href="{{ vich_uploader_asset(doc, 'documentFile') }}">Descargar</a>
````

**Comment by GWillmann** [comment]
Hi @fcpauldiaz,

Just adding :

    uri_prefix:         https://name-of-your-bucket.s3.amazonaws.com

to your mappings in your config.yml will make it possible for you to use ‘vich_uploader_asset‘!

**Comment by fcpauldiaz** [comment]
Thank you @GWillmann !
