### ISSUE TITLE
Doesn't uploads file and doesn't save it if CSRF tag is not included inside form without any exception.

### ISSUE THREAD

**Issue by a2xchip** [dustin10/VichUploaderBundle#511]
I found undocumented scenario, losed 3 hours to understand why it happens and it think that it should be documented some how and new exception might be created somewhere in the bundle insides. Let me reproduce it.

When your security settings are low and you use `{{ form_end(form, {'render_rest': false}) }}` tag to close form without rendering parts you don't need and `{{ form_row(form._token) }}` tag is not included in your form: your form is working fine and is able to save all data but file will not be uploaded and saved, the most important part no exception would be thrown about it.
If i dump `$file` varialble in my entity file setter it shows file, it means that the validation rejects happens inside VichUploaderBundle.

**Comment by K-Phoen** [comment]
If the form is not valid, the behavior is correct and the file should indeed NOT be uploaded nor persisted.

Concerning the validation part, I'm a bit skeptical as this bundle does not define anything related to the validation.

**Comment by a2xchip** [comment]
@K-Phoen May be we may rethink the task. I'm not sure about it. But symfony itself were persisting entity as always without ```{{ form_row(form._token) }}``` but VichUploader didn't. 

May be this case must be documented somewhere in usage part of documentation. I losed hours trying to determine what is wrong and simply don't want others to hit the same cause starting using bundle. It is all.

**Comment by garak** [comment]
I can't see any valid reason for your scenario: simply DO NOT close form without rendering remaining fields.
