### ISSUE TITLE
How to use downloadObject function

### ISSUE THREAD

**Issue by mkalisz77** [dustin10/VichUploaderBundle#515]
Can this function be used to display images using 
render(controller(...)) in Twig, when I have only image file name ?

How it can be done ?

My image files are outside web root and I try to display them, is it possible using this function

**Comment by zerubeus** [comment]
You have to use this function instead 
```php
vich_uploader_asset(page, 'imageFile')
```

**Comment by garak** [comment]
You need to retrieve your object. Then you can follow [docs](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/downloads/serving_files_with_a_controller.md)
