### ISSUE TITLE
Symfony 3.0.1: Could not load type "vich_image"

### ISSUE THREAD

**Issue by MichalMajer** [dustin10/VichUploaderBundle#520]
Hi, I've done everything according to the installation manual and tryed the example from "basic usage" in 1.0.0-beta7 and Symfony 3.0.1.

However, when adding a new form field like this:
```
->add('imageFile', 'vich_file', array(
                'required'      => false,
                'allow_delete'  => true, // not mandatory, default is true
                'download_link' => true, // not mandatory, default is true
            ));
```
I get an error:
> Could not load type "vich_image"
> 500 Internal Server Error - InvalidArgumentException

Any ideas if this is a bug or am I supposed to do something differently in Symfony 3.0.1 what might not be in the manual?

Thanks, Mike.

**Comment by javiereguiluz** [comment]
In Symfony 3 forms no longer accept short type names (e.g. `vich_file`) and you must pass the fully qualified class name:

```php
->add('imageFile', 'Vich\UploaderBundle\Form\Type\VichFileType', array(
    ...
)
```

If you are lucky and use PHP 5.5 or higher, you can use this:

 ```php
use Vich\UploaderBundle\Form\Type\VichFileType;

// ...

->add('imageFile', VichFileType::class, array(
    ...
)
```

**Comment by MichalMajer** [comment]
Thanks, that was indeed the problem!

**Comment by juanitourquiza** [comment]
Hi,

I use this:

```
use Vich\UploaderBundle\Form\Type\VichFileType;

// ...

->add('ruta', VichFileType::class, array(
    ...
)
```

However this is my error:


> The class "BackendBundle\Entity\Documentos" is not uploadable. If you use annotations to configure VichUploaderBundle, you probably just forgot to add `@Vich\Uploadable` on top of your entity. If you don't use annotations, check that the configuration files are in the right place. In both cases, clearing the cache can also solve the issue.

My configuration is with yml

Regards

**Comment by Koc** [comment]
@juanitourquiza see #728

**Comment by juanitourquiza** [comment]
Maybe:
I think this in config.yml:

```
//app/config/config.yml
vich_uploader:
    db_driver: orm

    mappings:
        documentos_ruta:
            uri_prefix:         /uploads/documentos
            upload_destination: %kernel.root_dir%/../web/uploads/documentos
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

```
Inside folder vich_uploader:

```
//Entity.Documentos.orm.yml
BackBundle\Entity\Documentos:
    ruta:
        mapping: documentos_ruta
        filename_property: nombre
```
```


```
And Entity :
```
```
//Resources/config/doctrine
BackendBundle\Entity\Documentos:
    type: entity
    table: documentos
    indexes:
        fk_documentos_proceso1_idx:
            columns:
                - proceso_id
    
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        ruta:
            mapping: documentos_ruta
            filename_property: nombre

        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        proceso:
            targetEntity: Procesos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                proceso_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
```

```

Where is the error?
