### ISSUE TITLE
Forms-related documentation && symfony 3

### ISSUE THREAD

**Issue by m1m1m1** [dustin10/VichUploaderBundle#524]
Hello,
Is it possible that: https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/form/vich_file_type.md is outdated and it will not work with symfony 3? 

After implementing the code we have an error:

> Could not load type "vich_file"

**Comment by m1m1m1** [comment]
It seems to me that you should use:

` 
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

           ->add('imageFile', VichFileType::class, array(
                'required'      => false,
                'allow_delete'  => true, // not mandatory, default is true
                'download_link' => true, // not mandatory, default is true
            ))
`

**Comment by K-Phoen** [comment]
There are indeed a few differences between Symfony 3.0 and the older versions. A PR to update the documentation would be welcome, are you interested? :)

**Comment by m1m1m1** [comment]
I can try to update folder: https://github.com/dustin10/VichUploaderBundle/tree/master/Resources/doc/form

**Comment by K-Phoen** [comment]
That would be great :)

**Comment by mangelsnc** [comment]
Hi!

I had not read this issue before, but I had the same issue a few days ago and I sent a PR fixing this:

https://github.com/dustin10/VichUploaderBundle/pull/529

**Comment by K-Phoen** [comment]
@mangelsnc Awesome, thanks! :+1:
