### ISSUE TITLE
Prevent delete some files selected

### ISSUE THREAD

**Issue by anacona16** [dustin10/VichUploaderBundle#525]
Hi, thank for this bundle.

What is the best way for no delete some files selected?

Explain me, I need keep a default image for the user, but I need maintain this options _delete_on_update_, _delete_on_remove_ activated.

Thanks

**Comment by K-Phoen** [comment]
I don't see a clean solution for that right now.

But if what you really want is having default images for your users, then they really should be default images. Meaning that your user entity should NOT have the default image persisted in it and you should use it or display it when needed.

**Comment by K-Phoen** [comment]
I close this issue but feel free to ask more questions if you need :)
