### ISSUE TITLE
Uploading new file does not work, when no persisted fields are modified

### ISSUE THREAD

**Issue by akomm** [dustin10/VichUploaderBundle#527]
Files will not be replaced, when updating an entity without any modification on persisted fields. Since the file property used to handle uploads is not persisted, only changing this file does not trigger the lifecycle event preUpdate and so the filehandler is unaware of the changes.

Before I'v found this bundle, I'v written a upload handler and run into exact same issue. I did not want to mess around and make a quick solution, so I'v looked for a bundle and found this one, with exact same issue. At least I can not find any clue in docs or source to fix this problem.

When I first encoutered this problem with my upload handler, I had an approach using onLoad event, but it seems like an overkill. Alternative would be to add a persisted field which has no other purpose then to be changed to trigger the event.

**Comment by K-Phoen** [comment]
This is a known (and [documented](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/known_issues.md#the-file-is-not-updated-if-there-are-not-other-changes-in-the-entity)) issue.
