### ISSUE TITLE
Same name file upload issues

### ISSUE THREAD

**Issue by Dragnucs** [dustin10/VichUploaderBundle#531]
**Issue 1:**
If a new file is uploaded and there exists one with the same name yet different data, the old one gets overridden.

**Issue 2:**
If two objects or more share the same file name, because of the issue above, deleting one of the objects makes the others point to non-existent files.

**How to reproduce:**
Issue one:
  1. Have two different files sharing the same name
  2. Upload the first one
  3. Upload the second

Issue two:
  1. Delete one of the object created above
  2. Visit the remaining one
  3. Verify it is broken because it points to an non-existing file

**Expected results:**
- Uploading a new file should *not* override another one if they are different.
- Files owned by more than one objects should not be removed if only one object is dropped.

**Comment by K-Phoen** [comment]
These problems can be solved by using [file namers](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/namers.md#provided-file-namers). You probably want to have a look to the `vich_uploader.namer_origname` namer :)

**Comment by Dragnucs** [comment]
Thank you, I skipped reading that part and it solves the issue indeed. Why is `vich_uploader.namer_origname` or `vich_uploader.namer_uniqid` not the default?

**Comment by K-Phoen** [comment]
Because changing that would break a lot of apps :)
