### ISSUE TITLE
Requires symfony dependency injection 2.8.

### ISSUE THREAD

**Issue by CaredduMattia** [dustin10/VichUploaderBundle#532]
I think that this is a problem with Symfony 3.x and others dependencies because require symfony/dependency-injection ~2.8 instead of 3.0.

**Comment by K-Phoen** [comment]
I don't see were we require symfony/dependency-injection ~2.8.

What version of the bundle are you using? Could you paste the error generated by composer?

**Comment by CaredduMattia** [comment]
Yes, i'm wrong, the problem isn't about dependency injection but about symfony version that requires dependency injection 2.8.
I'm trying to use version 0.14.
This is the error 

> - symfony/framework-bundle v2.8.2 requires symfony/dependency-injection ~2.8 -> no matching package found.

**Comment by K-Phoen** [comment]
v0.14 does not support Symfony 3.0, see #503 :)
