### ISSUE TITLE
Invalid type for path "vich_uploader.mappings.user_avatar.namer"

### ISSUE THREAD

**Issue by sirion89** [dustin10/VichUploaderBundle#533]
This is the part of my config.yml:

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
      user_avatar:
        uri_prefix:         /uploads/user/profilepics
        upload_destination: %kernel.root_dir%/../web/uploads/user/profilepics
        inject_on_load:     false
        delete_on_update:   true
        delete_on_remove:   true
        namer:
          service: vich_uploader.namer_property
          options: { property: 'profileSlug'}

Fails with:
InvalidTypeException in ScalarNode.php line 36:
Invalid type for path "vich_uploader.mappings.user_avatar.namer". Expected scalar, but got array.

**Comment by K-Phoen** [comment]
What version of the bundle are you using?

**Comment by sirion89** [comment]
My composer selected this: "vich/uploader-bundle": "^0.14.0" running the composer require vich/uploader-bundle. Looks like the github version is more updated, infact i didn't have the vich_uploader.namer_property inside the namer.xml at all. How can i fix this?

**Comment by K-Phoen** [comment]
You have to use the beta versions if you want this feature :)

The latest beta is 1.0.0-beta7
