### ISSUE TITLE
How to store MimeType ?

### ISSUE THREAD

**Issue by picks44** [dustin10/VichUploaderBundle#534]
Is there an option to store or get the MimeType of uploaded files ?

**Comment by ismailbaskin** [comment]
http://api.symfony.com/3.0/Symfony/Component/HttpFoundation/File/File.html#method_getMimeType

**Comment by K-Phoen** [comment]
There is no option for that but you can use [the events triggered by the bundle](https://github.com/dustin10/VichUploaderBundle/blob/master/Event/Events.php) to know when a file is uploaded and then store its mime-type.

**Comment by Koc** [comment]
@K-Phoen using events for this are too boilerplate. We are having a lot of different entities which support different numbers of upload fields. Proper way would be add something like `@UploadableField.preUpload("myMethod")` to call `MyEntity::myMethod()` before moving file. And we can store mime-type, file size or file original name.

Is my proposed sollution acceptable? If yes - I can work on PR for it.

**Comment by Koc** [comment]
Another way - add `@UploadableField({..., originalName="propertyPath", mimeType="propertyPath", size="propertyPath"})`

**Comment by Koc** [comment]
relates to #413
