### ISSUE TITLE
DownloadHandler filename

### ISSUE THREAD

**Issue by poissob** [dustin10/VichUploaderBundle#535]
Hi,
It seems that the last commit broke the DownloadHandler.
The files I'm getting through my controller are now named "file-pdf" instead of "file.pdf".

I'm using the same code as the doc says in "Serving files with a controller", but the transliterate step replaces the "." with "-".

Is there another step to give the correct name to the extension ?

**Comment by K-Phoen** [comment]
Should be fixed in master, sorry for that :)

Thanks for reporting the issue! :+1:
