### ISSUE TITLE
UploaderHelper not resolving absolute URL to flysystem assets

### ISSUE THREAD

**Issue by luispabon** [dustin10/VichUploaderBundle#539]
When trying to resolveUri, a relative path based on uriPrefix, uploadDir and filename is generated. This does not work with flysystem + s3 (or any other remote storage adapter) as an absolute path to the remote object should be generated.

I am aware that I can set uriPrefix to the bucket URL and this would work; however, this means we need to know how to construct these URLs and hardcode them on config. Flysystem is able to generate this for us as it already knows everything it needs to know.

I reckon we should leverage this mechanism, and for the flysystem storage driver entirely do away with uriPrefix, uploadDir and filename and instead request the absolute URL to the asset from flysystem itself.

**Comment by luispabon** [comment]
Closing as actually I was looking at implementing this, and flysystem doesn't offer a direct way of doing this for every adapter, which is annoying.

**Comment by sovetski** [comment]
I don't know why it is closed but 8 years later the issue still there: https://github.com/dustin10/VichUploaderBundle/issues/1434#issuecomment-2041172155
