### ISSUE TITLE
The composer install won't work with Symfony 3.0.3

### ISSUE THREAD

**Issue by nicolas-lesage** [dustin10/VichUploaderBundle#540]
Hello everyone :)

I am new to Symfony and working on a project with v3.0.3. I tried to install the VichUploaderBundle using composer, as described in the installation guide, but it does not work. I get the following error:

vich/uploader-bundle v0.14.0 requires symfony/framework-bundle ~2.3 -> satisfiable by symfony/framework-bundle [v2.3.0, v2.3.1, [...], v2.8.3]

Is it possible to allow this bundle to work with Symfony 3.0.*?

Thanks for your help and feedback, have a good day!!

**Comment by K-Phoen** [comment]
See #538 :)
