### ISSUE TITLE
Please create new tag with fixed factory.xml

### ISSUE THREAD

**Issue by Flower7C3** [dustin10/VichUploaderBundle#547]
There is wrong service definition `vich_uploader.storage_factory` in file `./Resources/config/factory.xml` from tag **v0.14.0**. Please create new tag, so I can get this project via composer in specified tag instead _dev-master_.

**Comment by K-Phoen** [comment]
You can already use contraints like `~1.0@beta`

1.0.0 will be tagged when the PR #401 is either merged or closed.
