### ISSUE TITLE
uploading image to entity with EAV structure

### ISSUE THREAD

**Issue by jrobeson** [dustin10/VichUploaderBundle#550]
This is most likely a support question.  I'd like to be able to use this bundle with an entity where the structure is like:

```
 setting_name | setting_value | setting_type
```

I'm not sure what trouble I'd be getting into when adapting to this structure.

If it is possible, then I'd write a basic example to add to the documentation.

**Comment by Koc** [comment]
Interesting question, but can you describe your entities and relationship a little bit more?

**Comment by jrobeson** [comment]
I wrote this issue so long ago that I can't remember what stopped me from implementing this. Perhaps it'd be a lot clearer to me now.

I'm not sure what more I can provide other than saying that I wanted to the setting_value to the information of the uploaded file, and the setting_type is a hint on how to render the input/output.

**Comment by garak** [comment]
Unfortunately, EAV is an anti-pattern, so we won't support it, not even suggesting a solution in docs.

**Comment by Koc** [comment]
relates to https://github.com/symfony/symfony/issues/7530

**Comment by Koc** [comment]
@jrobeson you can create class wich linked to your eav one2many with indexed association http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/working-with-indexed-associations.html and then do something like this:

```php
class File
{
    public function setFileName($fileName)
    {
        $this->eav->set('file_name', $fileName);
    }

    public function setFileSize($fileSize)
    {
        $this->eav->set('file_size', $fileSize);
    }
}
```
