### ISSUE TITLE
How can I checked if the delete checkbox is checked in the controller?

### ISSUE THREAD

**Issue by RodolVelasco** [dustin10/VichUploaderBundle#552]
Hi, I have the vich_file as false for some requirements. I want to check in the controller if checkbox is checked and if there's a file being upload in the submit action.

**Comment by garak** [comment]
You should be able to get all relevant informations by calling `$form->getData()` (assuming that your form is named `$form`)

**Comment by garak** [comment]
Closing for missing feedback
