### ISSUE TITLE
how vich works with simple html form 

### ISSUE THREAD

**Issue by pato17** [dustin10/VichUploaderBundle#555]
<  input type="file" name="image[]" class="file" multiple data-show-upload="false" data-show-caption="false" data-show-remove="true" accept="image/jpeg,image/png" data-browse-class="btn btn-o btn-default" data-browse-label="Selectionner des images " required        >
- # 
  
  and in the controller : 
  foreach ($photos as $photo) {
              $media = new Image();
              $media->setIdProduit($produit);
              $media->setImageFile($photo);
  
  ```
           var_dump($media);
          $em = $this->getDoctrine()->getEntityManager();
          $em->persist($media);
          $em->flush();
      }
  ```

and then error msg:----------------------------------------------->

Catchable Fatal Error: Argument 1 passed to Pidev\AllForDealBundle\Entity\Image::setImageFile() must be an instance of Symfony\Component\HttpFoundation\File\File, string given, called in C:\wamp\www\web\src\Pidev\AllForDealBundle\Controller\ProduitsController.php on line 170 and defined

**Comment by Dragnucs** [comment]
Don't do that, even if you want to use a simple HTML form, please use the tools provide by Symfony-Twig like `form_row()` and `form_wdiget()`.

Then the issue you are having is not really related to a *simple HTML form* but rather to `setImageFile()' method which needs a File and not a string.

Finally, please review the logic of your foreach loop. Going your way will only make thing more complex but if you strictly follow the procedure as described in docs if this bundle, it will be as easy as pie.
