### ISSUE TITLE
Handling files with same name

### ISSUE THREAD

**Issue by clytemnestra** [dustin10/VichUploaderBundle#558]
Upon uploading a file named 'test.png', and then another different one, but still named 'test.png', the old file gets overwritten, but in the database a new entry is being created.

Does VichUploader have a way to prevent this? Or another bundle? Or what's a common solution to this problem?

**Comment by Dragnucs** [comment]
You have to use a [namer](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/namers.md) like namer_orignamer.

**Comment by clytemnestra** [comment]
Thanks. Don't know how I missed that.
