### ISSUE TITLE
Missing upgrade docs

### ISSUE THREAD

**Issue by Nyholm** [dustin10/VichUploaderBundle#562]
Im currently using version 0.14.0 and I'm really exited to upgrade to 1.0. Is the 1.0 version backwards compatible with 0.14.0. I cant find any information in the upgrade docs: 
https://github.com/dustin10/VichUploaderBundle/blob/master/UPGRADE.md

**Comment by K-Phoen** [comment]
Unless I forgot to mention it in the UPGRADE.md document, 1.0 should not introduce bc-breaks :)
