### ISSUE TITLE
Error using Symfony 3.0 + PHP 7.0.5

### ISSUE THREAD

**Issue by Noxalus** [dustin10/VichUploaderBundle#567]
Hello everyone!

I'm using **VichUploaderBundle** with _Symfony 3.0_ and _PHP 7.0.5_ and I have this error when I try to run my server:

```
[Symfony\Component\Debug\Exception\ContextErrorException] Notice: Undefined offset: 1
```

It's not explicitly said in the documentation, but from the [travis file](https://github.com/dustin10/VichUploaderBundle/blob/9d481b0b734ca1c832be9e8da572e69650bdf1bb/.travis.yml), I suppose that this project should work with PHP 7, isn't it?

Do you know what happens?

**Comment by Dragnucs** [comment]
Does it not necessarily related to VichUploader. On my end, it works with  PHP version `7.0.6-1+donate.sury.org~xenial+1` and Symfony `3.0.5`.

**Comment by K-Phoen** [comment]
+1, probably unrelated to this bundle.

Anyway, without a proper stack-trace it's hard to be certain.

**Comment by Noxalus** [comment]
It's related to this bundle, because if I disable it (remove the entry in `AppKernel.php` + `config.yml` files), there is no error. But if this bundle works for you with PHP 7, there is definitely something wrong with my project. Maybe it's related to one of the dependencies that I use for my project? Here is what I have in my **composer.json** file:

```json
"require": {
    "php": ">=7.0.5",
    "symfony/symfony": "3.0.*",
    "doctrine/orm": "^2.5",
    "doctrine/doctrine-bundle": "^1.6",
    "doctrine/doctrine-cache-bundle": "^1.2",
    "symfony/swiftmailer-bundle": "^2.3",
    "symfony/monolog-bundle": "^2.8",
    "sensio/distribution-bundle": "^5.0",
    "sensio/framework-extra-bundle": "^3.0.2",
    "incenteev/composer-parameter-handler": "^2.0",
    "friendsofsymfony/user-bundle": "~2.0@dev",
    "ornicar/gravatar-bundle": "^1.1",
    "hwi/oauth-bundle": "0.5.*@dev",
    "vich/uploader-bundle": "^1.0.1",
    "knplabs/doctrine-behaviors": "~1.1",
    "jms/security-extra-bundle": "dev-master",
    "excelwebzone/recaptcha-bundle": "^1.4"
}
```

I also confirm that it works as expected using PHP 5.6.20.

I've just tried again with PHP 7, but with no success, I had the same error. I can't have a proper stacktrace because this error spawns whatever the command that I run with *bin/console*. :'(

**Comment by Dragnucs** [comment]
Try having your project set up as it shows the error but only not loading the bundle in AppKernel.PHP. Also try visiting your project from the web browser. The exception handler is better there.

On May 11, 2016 4:06:53 PM GMT+01:00, Noxalus <notifications@github.com> wrote:
>It's related to this bundle, because if I disable it (remove the entry
>in `AppKernel.php` + `config.yml` files), there is no error. But if
>this bundle works for you with PHP 7, there is definitely something
>wrong with my project. Maybe it's related to one of the dependencies
>that I use for my project? Here is what I have in my **composer.json**
>file:
>
>```json
>"require": {
>    "php": ">=7.0.5",
>    "symfony/symfony": "3.0.*",
>    "doctrine/orm": "^2.5",
>    "doctrine/doctrine-bundle": "^1.6",
>    "doctrine/doctrine-cache-bundle": "^1.2",
>    "symfony/swiftmailer-bundle": "^2.3",
>    "symfony/monolog-bundle": "^2.8",
>    "sensio/distribution-bundle": "^5.0",
>    "sensio/framework-extra-bundle": "^3.0.2",
>    "incenteev/composer-parameter-handler": "^2.0",
>    "friendsofsymfony/user-bundle": "~2.0@dev",
>    "ornicar/gravatar-bundle": "^1.1",
>    "hwi/oauth-bundle": "0.5.*@dev",
>    "vich/uploader-bundle": "^1.0.1",
>    "knplabs/doctrine-behaviors": "~1.1",
>    "jms/security-extra-bundle": "dev-master",
>    "excelwebzone/recaptcha-bundle": "^1.4"
>}
>```
>
>I also confirm that it works as expected using PHP 5.6.20.
>
>I've just tried again with PHP 7, but with no success, I had the same
>error. I can't have a proper stacktrace because this error spawns
>whatever the command that I run with *bin/console*. :'(
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dustin10/VichUploaderBundle/issues/567#issuecomment-218488466

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Dragnucs** [comment]
@Noxalus Have you checked if your PHP 7 is configured and has the same extensions as your PHP 5?

**Comment by garak** [comment]
This could be related to anything, even to bugs in Symfony itself. Since this issue is a bit old, maybe such bugs could have been fixed meanwhile. By the way, I'm using this bundle with php 7.0 without problems.
Can you provide more informations?

**Comment by garak** [comment]
Closing for missing feedback.

**Comment by fatimaezzahra21** [comment]
**_-For those who are still looking for the solution to this problem- :_**

I had the same issue, while trying to run bin/console server:run I got : 

`[Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: unserialize(): Error at offset 0 of 95529 bytes`

I solved it by manually **deleting the cache** located at : **var/cache/dev**  and **var/cache/prod**. Hope this helps !
