### ISSUE TITLE
Confusing naming for yaml config files.

### ISSUE THREAD

**Issue by inet20** [dustin10/VichUploaderBundle#568]
When creating yaml-config for doctrine entities, local namespace are included into config file name.
For example for entity
`AppBundle/Entity/Catalog/Product.php`
config file would be
`/src/AppBundle/config/doctrine/Catalog.Product.orm.yml`

But VichUploader file locator, which looking for config file don't consider namespace at all.
And it will look for config file
`/src/AppBundle/config/vich_uploader/Product.orm.yml`
not
`/src/AppBundle/config/vich_uploader/Catalog.Product.orm.yml`

Don't know is it a bug, but i found it a bit confusing.

**Comment by garak** [comment]
There's no matching between mapping and entity name. You can name your yaml config file as you prefer, as long as you put the correct namespace for entity inside it
