### ISSUE TITLE
Name property null and Namer never called when multiple UploadableField

### ISSUE THREAD

**Issue by PeterFour** [dustin10/VichUploaderBundle#569]
I'm using more than on UploadableField inside an entity and only the first one declared is being properly used.

For the three field in my Entity, I have the correct name property field mapped out, but let's say when I want to add only one image on the second field the namer (`uniqid`) is not even called, which I can see by putting a dump on the `$mapping` var. In fact only the first declared uploadable field has its name called

Is there something specific to do ? By looking at #50 looks like you had to create a specific namer but it was back in 2012 so is it still the case (Because name method signature is now using `PropertyMapping`) ?

Thanks in advance for your help, I've been stuck all day on this

**After some research here is what I found :**
- This behaviour both failed for Fixtures or with Form
- It appears that the first field is correctly assigned the `UploadedFile` however for some bizarre reason the other field will be assigned the resulting File related to the first one (??) resulting in false being returned by `hasUploadedFile`

**Comment by garak** [comment]
Are you using 3 different mappings?

**Comment by garak** [comment]
Closing for missing feedback.
