### ISSUE TITLE
[Question] Is there a way to use this bundle with "image" content

### ISSUE THREAD

**Issue by aledeg** [dustin10/VichUploaderBundle#570]
**Background**
I am currently developping an API to upload pictures through an HTTP POST request with an "image/*" content-type. So I don't use forms thus, I don't have information in $_FILES and I can't use the class "UploadedFile".

**Question**
So I wonder if it's possible to do that with the uploader.
If so how do I do that?
If not please consider that as a feature request.

**Comment by Dragnucs** [comment]
If you have your information in a POST variable like `$_POST['image']` then you are all done and need no bundle. All you need is some few lines of code to save your data in a file.

Bundles like VichUploaderBundle are here to remove the hassle of having to create a form, managing the upload, where to write the files and have an accessible web path. You don't have any of these issues.

**Comment by aledeg** [comment]
Actually, I don't even have a POST variable. I just have the content being my image. I ended up doing what you are mentioning.
I liked the idea of using the bundle to manage the link between my entity and the real image without doing it myself.
Anyway, thank you.
