### ISSUE TITLE
Undefined index: category_image /DependencyInjection/Compiler/RegisterPropelModelsPass.php line 33

### ISSUE THREAD

**Issue by JarJak** [dustin10/VichUploaderBundle#572]
Undefined index: category_image /DependencyInjection/Compiler/RegisterPropelModelsPass.php line 33

'category_image' string does not even exist in my project, i cleared cache and nothing helps

**Comment by garak** [comment]
This should have been fixed in 0d517ec33c66dc3a507626900395dbfc902bb927.
Can you confirm?

**Comment by garak** [comment]
Closing for missing feedback.
