### ISSUE TITLE
Custom storage support

### ISSUE THREAD

**Issue by egeloen** [dustin10/VichUploaderBundle#573]
Hey!

I'm currently implementing a custom storage which will give me support for [Cloudinary](http://cloudinary.com/) but since 31b2900e2a0c2159e40ac48ad00f83a598c6a84d we are not able to put a custom service name as storage in the configuration (See [here](https://github.com/dustin10/VichUploaderBundle/blob/master/DependencyInjection/Configuration.php#L17) and [here](https://github.com/dustin10/VichUploaderBundle/blob/master/DependencyInjection/Configuration.php#L49-L52)).

I'm not sure if right now, it is supported to add custom storage since the configuration really restrict the allowed values. I have some solutions to propose but none which would not break BC...

What about dropping this validation in the configuration?

**Comment by K-Phoen** [comment]
Hi!

I would be in favor of supporting custom storage services but only if we can find a way to implement it without BC-breaks :)

Dropping the validation in the configuration could be a starting point but I'd like to still be able to display a meaningful error message if the configuration is incorrect.

Do you want to work on that? I'd be glad to review your PR :)

**Comment by egeloen** [comment]
I will work on it :)

**Comment by egeloen** [comment]
@K-Phoen PR ready! :)
