### ISSUE TITLE
update from 0.9.0 to 0.10.0 /  mapping name instead of a field name

### ISSUE THREAD

**Issue by kimwue** [dustin10/VichUploaderBundle#576]
> the resolvePath and resolveUri Storage methods now take a mapping name instead of a field name. The same goes for the UploaderExtension and UploaderHelper asset method.

I have been using fieldnames, like this:

`{{ vich_uploader_asset(abstract, 'originalFile') }}`

Now I get an error that the mapping is not found. What would be the procedure for me to upgrade to new "mapping" structure?

**Comment by kimwue** [comment]
We used to have something like this:

`    /**
     * @Assert\File(
     *      mimeTypes = {
     *          "application/pdf",
     *          "application/x-pdf"
     *      },
     *      mimeTypesMessage="nope"
     * )
     * @Vich\UploadableField(mapping="abstract_files", fileNameProperty="fileOne")
     */
    private $fileOne;

    /**
     * @Assert\File(
     *      mimeTypes = {
     *          "application/pdf",
     *          "application/x-pdf"
     *      },
     *      mimeTypesMessage="nope"
     * )
     * @Vich\UploadableField(mapping="abstract_files", fileNameProperty="fileTwo")
     */
    private $fileTwo;`

But now its not possible any longer to have the same mapping for two files, right?

**Comment by garak** [comment]
This changed again when migrating from `v0.12.0` to `v0.13.0`, so now you can (must) use field names again
