### ISSUE TITLE
get the folder where image is uploaded

### ISSUE THREAD

**Issue by NadaBen** [dustin10/VichUploaderBundle#578]
Hello, I'm using VichUploaderBundle to upload images, it works perfectly, but i want when the upload task is finished to get the folder where the current image is stored,  my upload destination is as follows:
`upload_destination: %upload_dir%/photos`

but each imge is stored in a new folder ; how can i know the current image uploaded:
![capture](https://cloud.githubusercontent.com/assets/11770242/15666304/63e8bade-2710-11e6-812d-15c9d6eef7d2.PNG)

**Comment by garak** [comment]
Your files should be placed directly under `photos` directory, unless you configured some additional options.

**Comment by garak** [comment]
Closing for missing feedback.
