### ISSUE TITLE
Label override?

### ISSUE THREAD

**Issue by clytemnestra** [dustin10/VichUploaderBundle#580]
A while ago there was a bug regarding labels https://github.com/dustin10/VichUploaderBundle/issues/369 that was fixed with https://github.com/dustin10/VichUploaderBundle/commit/3d091a43b8d90e1e71933ac32e2d94885356625a

The problem is that I don't see a way to add a label for this field now. A label is added, but it's not 'for the file input'. Anyone having the same issue?

```
{{ form_widget(form.file) }}
{{ form_label(form.file) }}
```

The label will not be FOR the form.file field. I observed this issue when I tried to style the label by giving it a class.

**Comment by garak** [comment]
As you can see in https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/views/Form/fields.html.twig#L6, the template for `vich_file` widget is not using a label for file input.
Just override that block in one of your themes and add `{{ form_label(form.file) }}` next to `{{ form_widget(form.file) }}`
