### ISSUE TITLE
Call to a member function getData() in VichFileType

### ISSUE THREAD

**Issue by n1c01a5** [dustin10/VichUploaderBundle#582]
I have this issue : 
```
Error: Call to a member function getData() on null 
```
in [VichFileType.php](https://github.com/dustin10/VichUploaderBundle/blob/master/Form/Type/VichFileType.php#L74).

The object ```$form->getParent()``` is load but the method ```getData()``` doesn't exist.

Any idea ?

**Comment by kunal-singh** [comment]
Hey,
 I am having the same trouble. How did you solve this?

**Comment by alexhoma** [comment]
@n1c01a5  Same error, how did you solved?
Thank you :)
