### ISSUE TITLE
making an image required inside a form

### ISSUE THREAD

**Issue by retosteffen** [dustin10/VichUploaderBundle#596]
I have an entity with
`/**
     *  @Assert\NotBlank(message="Please add the image.")
     *  @Assert\Image(
     *     maxSize="500K",
     *  maxSizeMessage="Image is too large - maximum size is 500K",
     * )
     * @Vich\UploadableField(mapping="image", fileNameProperty="imageName")
     * 
     * @var File
     */
    private $image;`

But the NotBlank assert never gets fired when creating a new entity. How do I make an image required ('required' html5 attribute not being enough)

**Comment by garak** [comment]
Try with `@Assert\NotNull`. Anyway, it's not related to this bundle.
