### ISSUE TITLE
FileNotFoundException in File.php line 37 when upload two files with vich upoader.

### ISSUE THREAD

**Issue by jink2005** [dustin10/VichUploaderBundle#597]
I met this issue when i try to upload two photos in an entity. Here are my conf:
// app/config/config.yml
`# VichUploaderBundle Configuration
vich_uploader:
    db_driver: orm

```
mappings:
    parking_map_image:
        uri_prefix: /upload/images/parkingMaps
        upload_destination: %kernel.root_dir%/../web/upload/images/parkingMaps
        namer: vich_uploader.namer_uniqid
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
    car_infraction_photo:
        uri_prefix: /upload/images/infractions
        upload_destination: %kernel.root_dir%/../web/upload/images/infractions
        namer: vich_uploader.namer_uniqid
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
```

`

// src/AppBundle/Resources/config/vich_uploader/CarInfraction.yml
`AppBundle\Entity\CarInfraction:
    photo1:
        mapping: car_infraction_photo
        filename_property: photoUrl1
    photo2:
        mapping: car_infraction_photo
        filename_property: photoUrl2
`

I test this with Postman, but get the following error message. I check the database and the upload folder, the record is inserted and files are there.

> FileNotFoundException in File.php line 37:
> The file "/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpAuLiP2" does not exist
> in File.php line 37
> at File->__construct('/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpAuLiP2', true) in UploadedFile.php line 96
> at UploadedFile->__construct('/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpAuLiP2', '8816210D779C9BDA11A43A4CEFA7A63D.jpg', 'image/jpeg', '42109', '0') in FileBag.php line 89
> at FileBag->convertFileInformation( array('name' => '8816210D779C9BDA11A43A4CEFA7A63D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpAuLiP2', 'error' => '0', 'size' => '42109')) in FileBag.php line 54
> at FileBag->set('photo1', array('name' => '8816210D779C9BDA11A43A4CEFA7A63D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpAuLiP2', 'error' => '0', 'size' => '42109')) in FileBag.php line 63
> at FileBag->add( array('photo1' => array('name' => '8816210D779C9BDA11A43A4CEFA7A63D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpAuLiP2', 'error' => '0', 'size' => '42109'), 'photo2' => array('name' => 'A476559A4AC6405CABB14A543C4E4D2D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpwEAJSd', 'error' => '0', 'size' => '44762'))) in FileBag.php line 42
> at FileBag->replace( array('photo1' => array('name' => '8816210D779C9BDA11A43A4CEFA7A63D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpAuLiP2', 'error' => '0', 'size' => '42109'), 'photo2' => array('name' => 'A476559A4AC6405CABB14A543C4E4D2D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpwEAJSd', 'error' => '0', 'size' => '44762'))) in FileBag.php line 33
> at FileBag->__construct( array('photo1' => array('name' => '8816210D779C9BDA11A43A4CEFA7A63D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpAuLiP2', 'error' => '0', 'size' => '42109'), 'photo2' => array('name' => 'A476559A4AC6405CABB14A543C4E4D2D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpwEAJSd', 'error' => '0', 'size' => '44762'))) in Request.php line 244
> at Request->initialize( array(), array('carPlate' => '苏A12345', 'address' => '金王府54栋门前'), array(), array(), array('photo1' => array('name' => '8816210D779C9BDA11A43A4CEFA7A63D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpAuLiP2', 'error' => '0', 'size' => '42109'), 'photo2' => array('name' => 'A476559A4AC6405CABB14A543C4E4D2D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpwEAJSd', 'error' => '0', 'size' => '44762')), array('DOCUMENT_ROOT' => '/Users/ares/Documents/Project/ParkingCloudServer/web', 'REMOTE_ADDR' => '127.0.0.1', 'REMOTE_PORT' => '49485', 'SERVER_SOFTWARE' => 'PHP 5.5.34 Development Server', 'SERVER_PROTOCOL' => 'HTTP/1.1', 'SERVER_NAME' => '127.0.0.1', 'SERVER_PORT' => '8000', 'REQUEST_URI' => '/api/v1/carInfraction/add', 'REQUEST_METHOD' => 'POST', 'SCRIPT_NAME' => '/app_dev.php', 'SCRIPT_FILENAME' => '/Users/ares/Documents/Project/ParkingCloudServer/web/app_dev.php', 'PHP_SELF' => '/app_dev.php', 'HTTP_HOST' => '127.0.0.1:8000', 'HTTP_CONNECTION' => 'keep-alive', 'HTTP_CONTENT_LENGTH' => '87469', 'HTTP_CACHE_CONTROL' => 'no-cache', 'HTTP_ORIGIN' => 'file://', 'HTTP_CONTENT_TYPE' => 'multipart/form-data; boundary=----WebKitFormBoundaryukyRKVG3SkIz4TZA', 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Postman/4.4.2 Chrome/51.0.2704.103 Electron/1.2.5 Safari/537.36', 'HTTP_POSTMAN_TOKEN' => '742519bc-d489-31c3-6fd7-54ae52eaae87', 'HTTP_ACCEPT' => '_/_', 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate', 'HTTP_ACCEPT_LANGUAGE' => 'en-US', 'REQUEST_TIME_FLOAT' => '1468803147.9047', 'REQUEST_TIME' => '1468803147', 'CONTENT_LENGTH' => '87469', 'CONTENT_TYPE' => 'multipart/form-data; boundary=----WebKitFormBoundaryukyRKVG3SkIz4TZA'), null) in Request.php line 222
> at Request->__construct( array(), array('carPlate' => '苏A12345', 'address' => '金王府54栋门前'), array(), array(), array('photo1' => array('name' => '8816210D779C9BDA11A43A4CEFA7A63D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpAuLiP2', 'error' => '0', 'size' => '42109'), 'photo2' => array('name' => 'A476559A4AC6405CABB14A543C4E4D2D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpwEAJSd', 'error' => '0', 'size' => '44762')), array('DOCUMENT_ROOT' => '/Users/ares/Documents/Project/ParkingCloudServer/web', 'REMOTE_ADDR' => '127.0.0.1', 'REMOTE_PORT' => '49485', 'SERVER_SOFTWARE' => 'PHP 5.5.34 Development Server', 'SERVER_PROTOCOL' => 'HTTP/1.1', 'SERVER_NAME' => '127.0.0.1', 'SERVER_PORT' => '8000', 'REQUEST_URI' => '/api/v1/carInfraction/add', 'REQUEST_METHOD' => 'POST', 'SCRIPT_NAME' => '/app_dev.php', 'SCRIPT_FILENAME' => '/Users/ares/Documents/Project/ParkingCloudServer/web/app_dev.php', 'PHP_SELF' => '/app_dev.php', 'HTTP_HOST' => '127.0.0.1:8000', 'HTTP_CONNECTION' => 'keep-alive', 'HTTP_CONTENT_LENGTH' => '87469', 'HTTP_CACHE_CONTROL' => 'no-cache', 'HTTP_ORIGIN' => 'file://', 'HTTP_CONTENT_TYPE' => 'multipart/form-data; boundary=----WebKitFormBoundaryukyRKVG3SkIz4TZA', 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Postman/4.4.2 Chrome/51.0.2704.103 Electron/1.2.5 Safari/537.36', 'HTTP_POSTMAN_TOKEN' => '742519bc-d489-31c3-6fd7-54ae52eaae87', 'HTTP_ACCEPT' => '_/_', 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate', 'HTTP_ACCEPT_LANGUAGE' => 'en-US', 'REQUEST_TIME_FLOAT' => '1468803147.9047', 'REQUEST_TIME' => '1468803147', 'CONTENT_LENGTH' => '87469', 'CONTENT_TYPE' => 'multipart/form-data; boundary=----WebKitFormBoundaryukyRKVG3SkIz4TZA'), null) in Request.php line 1913
> at Request::createRequestFromFactory( array(), array('carPlate' => '苏A12345', 'address' => '金王府54栋门前'), array(), array(), array('photo1' => array('name' => '8816210D779C9BDA11A43A4CEFA7A63D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpAuLiP2', 'error' => '0', 'size' => '42109'), 'photo2' => array('name' => 'A476559A4AC6405CABB14A543C4E4D2D.jpg', 'type' => 'image/jpeg', 'tmp_name' => '/private/var/folders/j7/mw_65t951zd5rhw3qfg2mdl40000gn/T/phpwEAJSd', 'error' => '0', 'size' => '44762')), array('DOCUMENT_ROOT' => '/Users/ares/Documents/Project/ParkingCloudServer/web', 'REMOTE_ADDR' => '127.0.0.1', 'REMOTE_PORT' => '49485', 'SERVER_SOFTWARE' => 'PHP 5.5.34 Development Server', 'SERVER_PROTOCOL' => 'HTTP/1.1', 'SERVER_NAME' => '127.0.0.1', 'SERVER_PORT' => '8000', 'REQUEST_URI' => '/api/v1/carInfraction/add', 'REQUEST_METHOD' => 'POST', 'SCRIPT_NAME' => '/app_dev.php', 'SCRIPT_FILENAME' => '/Users/ares/Documents/Project/ParkingCloudServer/web/app_dev.php', 'PHP_SELF' => '/app_dev.php', 'HTTP_HOST' => '127.0.0.1:8000', 'HTTP_CONNECTION' => 'keep-alive', 'HTTP_CONTENT_LENGTH' => '87469', 'HTTP_CACHE_CONTROL' => 'no-cache', 'HTTP_ORIGIN' => 'file://', 'HTTP_CONTENT_TYPE' => 'multipart/form-data; boundary=----WebKitFormBoundaryukyRKVG3SkIz4TZA', 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Postman/4.4.2 Chrome/51.0.2704.103 Electron/1.2.5 Safari/537.36', 'HTTP_POSTMAN_TOKEN' => '742519bc-d489-31c3-6fd7-54ae52eaae87', 'HTTP_ACCEPT' => '_/_', 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate', 'HTTP_ACCEPT_LANGUAGE' => 'en-US', 'REQUEST_TIME_FLOAT' => '1468803147.9047', 'REQUEST_TIME' => '1468803147', 'CONTENT_LENGTH' => '87469', 'CONTENT_TYPE' => 'multipart/form-data; boundary=----WebKitFormBoundaryukyRKVG3SkIz4TZA')) in Request.php line 281
> at Request::createFromGlobals() in AcmeExceptionListener.php line 15
> at AcmeExceptionListener->onKernelException( object( GetResponseForExceptionEvent), 'kernel.exception', object( TraceableEventDispatcher))
> at call_user_func( array( object( AcmeExceptionListener), 'onKernelException'), object( GetResponseForExceptionEvent), 'kernel.exception', object( TraceableEventDispatcher)) in WrappedListener.php line 61
> at WrappedListener->__invoke( object( GetResponseForExceptionEvent), 'kernel.exception', object( ContainerAwareEventDispatcher))
> at call_user_func( object( WrappedListener), object( GetResponseForExceptionEvent), 'kernel.exception', object( ContainerAwareEventDispatcher)) in classes.php line 1756
> at EventDispatcher->doDispatch( array( object( WrappedListener), object( WrappedListener), object( WrappedListener), object( WrappedListener)), 'kernel.exception', object( GetResponseForExceptionEvent)) in classes.php line 1671
> at EventDispatcher->dispatch('kernel.exception', object( GetResponseForExceptionEvent)) in TraceableEventDispatcher.php line 136
> at TraceableEventDispatcher->dispatch('kernel.exception', object( GetResponseForExceptionEvent)) in HttpKernel.php line 221
> at HttpKernel->handleException( object( FileNotFoundException), object( Request), '1') in HttpKernel.php line 75
> at HttpKernel->handle( object( Request), '1', true) in Kernel.php line 177
> at Kernel->handle( object( Request)) in app_dev.php line 30
> at require('/Users/ares/Documents/Project/ParkingCloudServer/web/app_dev.php') in router_dev.php line 40

**Comment by garak** [comment]
I can't find anything related to this bundle in your error stack trace. You need to provide more informations

**Comment by garak** [comment]
Closing for missing feedback. Feel free to re-open. Thanks.
