### ISSUE TITLE
New maintainer wanted

### ISSUE THREAD

**Issue by K-Phoen** [dustin10/VichUploaderBundle#609]
I have neither the time nor the will to properly maintain this project – which I don't even use anymore.

This project needs a new maintainer and I encourage anyone interested to contact me by replying to this issue or by sending me an email.

**Comment by Dragnucs** [comment]
The bundle is stable enough for you to take some rest without any worries.

**Comment by tgabi333** [comment]
I happily maintain the project if you think so.

**Comment by Koc** [comment]
I have some ideas how to improve the bundle (see my last PRs)

**Comment by edis2** [comment]
I think, I can maintain this project also

**Comment by xiranst** [comment]
i will use symfony in my project longtime and develop some customize function in my project. so, I can do this work. Thanks.

**Comment by kochen** [comment]
I'll be happy to help

**Comment by RezaSeyf** [comment]
I can help 👍

**Comment by m47730** [comment]
Could you abdicate and put someone else in control?
The message in the README It's quite scary and give a wrong impression; instead in few days you got some volunteers to continue this project. Long life to VichUploaderBundle!

**Comment by K-Phoen** [comment]
Starting today, @garak will be the one maintaining this bundle.

Thanks to him for his future work! :)
