### ISSUE TITLE
Can't customize form template

### ISSUE THREAD

**Issue by murtukov** [dustin10/VichUploaderBundle#611]
Hello,
i'm trying to customize appearance of simple form. I know how to extend twig templates and I have seen the issue #443. The problem is that I can't render the **upload** button and the **delete** checkbox separately, because they are renderd by **form_widget(form.file)**.
How can I put, let's say, the upload button in one "div" element and the checkbox in another?

**Comment by Dragnucs** [comment]
Override the whole template in your `app/` folder and customize them as you wish.

**Comment by eved42** [comment]
Hi, sorry to open back this ticket.

I edited the vich_image_widget and it works but I don't know how to custom the delete checkbox.
I want to add it the Bootstrap 4 classes.

I tried this :
```
// app/Resources/views/form/fields.html.twig

// [...]

{% if form.delete is defined %}
  {{ form_errors(form.delete) }}

  <div class="custom-control custom-checkbox">
    {{ form_widget(form.delete, {'attr': {'class' : 'custom-control-input'}}) }}
    {{ form_label(form.delete, {'attr': {'class' : 'custom-control-label'}}) }}
  </div>
{% endif %}
```

But I still have undesired classes from Vich (I suppose) :  div `form-check` shouldn't be here and the label has got the wrong class `form-check-label`.
```
<div class="custom-control custom-checkbox">
  <div class="form-check">
    <input type="checkbox" id="catalog_category_imageFile_delete" name="catalog_category[imageFile][delete]" class="custom-control-input form-check-input" value="1">
    <label class="form-check-label" for="catalog_category_imageFile_delete">Delete picture ?</label>
  </div>
</div>
```

Any idea ? Thank you.

**Comment by garak** [comment]
@eved42 your reference is https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/views/Form/fields.html.twig start from there and do your customizations

**Comment by eved42** [comment]
@garak Yes this is exactly what I did... I replaced lines 30 to 32.

**Comment by garak** [comment]
Then I'm afraid it's a matter Symfony templates.
