### ISSUE TITLE
URL Twig error 404

### ISSUE THREAD

**Issue by Cyr69** [dustin10/VichUploaderBundle#621]
Hi,

I have a small issue about url with twig.

my config :

`vich_uploader:
    db_driver: orm
    mappings:
        justificatif_document:
            uri_prefix:         /uploads/documents
            upload_destination: '%kernel.root_dir%/../app/Resources/uploads/documents'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid`

With that, i have an error 404...

However, i see in Issues : the uri_prefix and the upload_destination are the same. With my config, doesnt work :(

 Any idea ?

**Comment by omarsoufiane** [comment]
i had the same issue, i fixed it by changing th uri prefix  to "projectname/web/mymathtoimage/" but i think this has to do on wether you run symfony on a server like xpamp/mamp/wamp or the default symfony server with the console server:run, in production mode you should rename the uri again

**Comment by garak** [comment]
Your `upload_destionaton` must point to a public folder (e.g. to `web`, not to `app`)
