### ISSUE TITLE
Embedded VichImageType result in "Call to a member function getData() on null"

### ISSUE THREAD

**Issue by carere** [dustin10/VichUploaderBundle#627]
Hello,

First of all, thx for this bundle :). So all is explain in the question, for info this is the specific location where the error occurs:

```
            $translator = $this->translator;
            $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($options, $storage, $translator) {
                $form = $event->getForm();
/*THIS LINE*/ $object = $form->getParent()->getData();
                // no object or no uploaded file: no delete button
                if (null === $object || null === $storage->resolveUri($object, $form->getName())) {
```

This line is the 74 of the VichFileType.php

As the error indicate, the parent of the "$form" is null, i don't think that is normal because my form is embedded in another form.

Im using symfony 3.1, and easy-admin, i try to configure a 'collection' field with 'VichImageType' as 'entry_type'. Is there any configuration which could help me ?

**Comment by LamGui** [comment]
@carere Hi, have you solved this problem ? I encoutered the same with the same architecture

**Comment by carere** [comment]
@LamGui Hello, 

At the moment of my question, they were looking for new VichUploaderBundle's maintener, also Symfony 3 was releasing.
So the support for the new version of symfony wasn't there.

Now i suppose that, the problem will be solved very soon, since they have new mainteners :smile:

Anyway, i don't use embeded form to manage my images, i prefer to create a specific FormType which i bind to a JS module. Look for "multi-upload js" on Google :coffee:

Hope that help ;)

@garak Hello :) Should i close this issue ?

**Comment by garak** [comment]
@carere if it's working for you now, you can close this issue.
Thanks.
