### ISSUE TITLE
probleme for show my image path

### ISSUE THREAD

**Issue by rudak** [dustin10/VichUploaderBundle#628]
My upload is Ok, I use easyadmin and all works fine but in the front side, when I try to print the path of my image :
_An exception has been thrown during the rendering of a template ("Mapping not found for field "product_images"") in my view at line 666..._

here is my config
```
vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '/uploads'
            upload_destination: '%kernel.root_dir%/../web/uploads'
            namer: vich_uploader.namer_uniqid
```
here is my view.html.twig
`<p>Image path: {{ vich_uploader_asset(entity,'product_images') }}</p>`

can you explain me how to do, I dont understand :'(

**Comment by flo-sch** [comment]
Hi, it just happened to me, did you ensure to add the `@Vich\Uploadable` annotation to your entity global annotations?

    /**
     * User
     *
     * @ORM\Table(name="users")
     * @ORM\Entity(repositoryClass="...\UserRepository")
     * @ORM\HasLifecycleCallbacks()
     * @Vich\Uploadable
     */
    class User
    {

    }

**Comment by rudak** [comment]
Yes this annotation is added, the system automaticaly works with easyadminbundle, but not in front  :(

**Comment by rudak** [comment]
Solved with this thread
http://stackoverflow.com/questions/33943441/symfony-2-7-render-image-in-twig-with-vichuploaderbundle
grrrrrr!
