### ISSUE TITLE
Uploaded file lost upon form error

### ISSUE THREAD

**Issue by yashmika** [dustin10/VichUploaderBundle#631]
I have problem handling situation when I upload file, but other field does not meet validation criteria and user is directed to fix form errors. Then when I fix the problem and hit submit button, the file is no longer available and missing file error is displayed (file field is also compulsory). How to solve this issue?

**Comment by garak** [comment]
You can't.
See http://stackoverflow.com/questions/27726980/how-to-refill-file-input-after-form-submited-with-errors for some references
