### ISSUE TITLE
Image Update Not working

### ISSUE THREAD

**Issue by Siddharth22** [dustin10/VichUploaderBundle#634]
Hello,

I am using  vich_uploader with knp_gaufrette for image upload on amazonS3 with Sonata Admin.
Image upload is working perfect but when I want to update image then Image is not updating.
config.yml :- 

    knp_gaufrette:
    stream_wrapper: ~
    adapters:
        uploads:
            amazon_s3:                  
                amazon_s3_id: ct_file_store.s3
                bucket_name: xyz
                options:
                    create: true 
    filesystems:
        amazon_s3:
            adapter:    uploads

    vich_uploader:
        db_driver: orm
        #gaufrette: true
        storage: gaufrette
        mappings:
            logo:
                uri_prefix: https://s3.amazonaws.com/xyz
                upload_destination: amazon_s3
                namer: vich_uploader.namer_uniqid
                delete_on_remove: true
                delete_on_update: true

Entity:-

    <?php

     namespace ABC\Bundle\ABCBundle\Entity;

     use Doctrine\ORM\Mapping as ORM;
     use Symfony\Component\Validator\Constraints as Assert;
     use Symfony\Component\HttpFoundation\File\File;
     use Gedmo\Mapping\Annotation as Gedmo;
     use Vich\UploaderBundle\Mapping\Annotation as Vich;

    /**
     * Brand
     * @ORM\Entity
     * @Vich\Uploadable
     */
    class Brand
    {
	/**
	 * @var integer
	 *
	 * @ORM\Column(name="id", type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="logo", type="string", length=255, nullable=true)
	 */
	private $logo;

	/**
	 * @Assert\File(
	 *     maxSize="5M",
	 *     mimeTypes={"image/png", "image/jpeg", "image/pjpeg"}
	 * )
	 * @Vich\UploadableField(mapping="logo", fileNameProperty="logo")
	 *
	 * @var File $logo_virtual
	 *
	 * This is the virtual field that will populate logo with the resulting file.
	 */
	protected $logo_virtual;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set logo
     *
     * @param string $logo
     * @return Brand
     */
    public function setLogo($logo)
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * Get logo
     *
     * @return string 
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     */
    public function setLogoVirtual(File $image = null)
    {
    	$this->logo_virtual = $image;
    En
    	if ($image) {
    		// It is required that at least one field changes if you are using doctrine
    		// otherwise the event listeners won't be called and the file is lost
    		$this->updatedAt = new \DateTime('now');
    	}
    }
    
    /**
     * @return File
     */
    public function getLogoVirtual()
    {
    	return $this->logo_virtual;
    }

    }

Admin :- 

    <?php

    namespace ABC\Bundle\AdminBundle\Admin;

    use Sonata\AdminBundle\Admin\Admin;
    use Sonata\AdminBundle\Datagrid\DatagridMapper;
    use Sonata\AdminBundle\Datagrid\ListMapper;
    use Sonata\AdminBundle\Form\FormMapper;
    use Sonata\AdminBundle\Show\ShowMapper;

    class BrandAdmin extends Admin
    {

	protected function configureShowFields(ShowMapper $showMapper)
	{
		$showMapper
		->add('logo_virtual',null, array('label'=>'Image'))
		;
	}

	protected function configureListFields(ListMapper $listMapper)
	{
		$listMapper
		->addIdentifier('id')
		->add('logo_virtual', NULL, array('label'=>'Image',
    		'template' => 'ABCAdminBundle:Admin:list.html.twig'
			))
		->add('status',null,array('editable' => true));
	}

	protected function configureFormFields(FormMapper $formMapper)
	{
		$formMapper
		->add('logo_virtual', 'file', array('label'=>'Image'))
		;
	}
    }

Can Any one tell How I can fix this when User Update then Image upload update ???

**Comment by Koc** [comment]
You haven't `updatedAt` property and column

**Comment by Koc** [comment]
see #617 and related tickets
