### ISSUE TITLE
I'm trying to install

### ISSUE THREAD

**Issue by kibizu** [dustin10/VichUploaderBundle#635]
Hi,

I'm trying to install this bundle, but I get this error:

composer require vich/uploader-bundle

Using version ^1.3 for vich/uploader-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing ocramius/package-versions (1.1.1)
    Loading from cache

  - Installing jms/metadata (1.5.1)
    Loading from cache

  - Installing zendframework/zend-eventmanager (3.0.1)
    Loading from cache

  - Installing zendframework/zend-code (3.0.1)
    Loading from cache

  - Installing ocramius/proxy-manager (2.0.4)
    Loading from cache

  - Installing vich/uploader-bundle (1.3.1)
    Loading from cache

zendframework/zend-eventmanager suggests installing container-interop/container-
interop (^1.1.0, to use the lazy listeners feature)
zendframework/zend-eventmanager suggests installing zendframework/zend-stdlib (^
2.7.3 || ^3.0, to use the FilterChain feature)
zendframework/zend-code suggests installing zendframework/zend-stdlib (Zend\Stdl
ib component)
ocramius/proxy-manager suggests installing ocramius/generated-hydrator (To have
very fast object to array to object conversion for ghost objects)
ocramius/proxy-manager suggests installing zendframework/zend-xmlrpc (To have th
e XmlRpc adapter (Remote Object feature))
ocramius/proxy-manager suggests installing zendframework/zend-json (To have the
JsonRpc adapter (Remote Object feature))
ocramius/proxy-manager suggests installing zendframework/zend-soap (To have the
Soap adapter (Remote Object feature))
vich/uploader-bundle suggests installing doctrine/mongodb-odm-bundle (*)
vich/uploader-bundle suggests installing doctrine/phpcr-odm (~1.0)
vich/uploader-bundle suggests installing knplabs/knp-gaufrette-bundle (~0.3)
vich/uploader-bundle suggests installing willdurand/propel-eventdispatcher-bundl
e (~1.2)
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

  [Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined offset: 1

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handl
ing the post-update-cmd event terminated with an exception

Installation failed, reverting ./composer.json to its original content.

  [RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command:

    [Symfony\Component\Debug\Exception\ContextErrorException]
    Notice: Undefined offset: 1

Can you help me?

Thanks

**Comment by Koc** [comment]
try

```
composer require vich/uploader-bundle --no-scripts
php app/console cache:clear -vvv
```

and attach trace from `cache:clear`

**Comment by kibizu** [comment]
Thank you very much, this is the trace:

 // Clearing the cache for the dev environment with debug
 // true

 // Warming up cache...

[2016-11-14 13:35:27] php.INFO: The Symfony\Bundle\MonologBundle\DependencyInjec
tion\Compiler\DebugHandlerPass class is deprecated since version 2.12 and will b
e removed in 3.0. Use AddDebugLogProcessorPass in FrameworkBundle instead. {"typ
e":16384,"file":"C:\\Apache24\\htdocs\\StiFProject-00\\vendor\\symfony\\monolog-
bundle\\DependencyInjection\\Compiler\\DebugHandlerPass.php","line":14,"level":2
8928,"stack":[{"function":"handleError","class":"Symfony\\Component\\Debug\\Erro
rHandler","type":"->"},{"file":"C:\\Apache24\\htdocs\\StiFProject-00\\vendor\\sy
mfony\\monolog-bundle\\DependencyInjection\\Compiler\\DebugHandlerPass.php","lin
e":14,"function":"trigger_error"},{"file":"C:\\Apache24\\htdocs\\StiFProject-00\
\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Debug\\DebugClassLoader.php"
,"line":169,"args":["C:\\Apache24\\htdocs\\StiFProject-00\\vendor\\symfony\\mono
log-bundle\\DependencyInjection\\Compiler\\DebugHandlerPass.php"],"function":"re
quire_once"},{"function":"loadClass","class":"Symfony\\Component\\Debug\\DebugCl
assLoader","type":"->"},{"file":"C:\\Apache24\\htdocs\\StiFProject-00\\vendor\\s
ymfony\\monolog-bundle\\MonologBundle.php","line":38,"function":"spl_autoload_ca
ll"},{"file":"C:\\Apache24\\htdocs\\StiFProject-00\\vendor\\symfony\\symfony\\sr
c\\Symfony\\Component\\HttpKernel\\Kernel.php","line":626,"function":"build","cl
ass":"Symfony\\Bundle\\MonologBundle\\MonologBundle","type":"->"},{"file":"C:\\A
pache24\\htdocs\\StiFProject-00\\vendor\\symfony\\symfony\\src\\Symfony\\Compone
nt\\HttpKernel\\Kernel.php","line":595,"function":"prepareContainer","class":"Sy
mfony\\Component\\HttpKernel\\Kernel","type":"->"},{"file":"C:\\Apache24\\htdocs
\\StiFProject-00\\app\\cache\\de_\\kernel.tmp","line":29,"function":"buildContai
ner","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"},{"file":"C:\\
Apache24\\htdocs\\StiFProject-00\\vendor\\symfony\\symfony\\src\\Symfony\\Compon
ent\\HttpKernel\\Kernel.php","line":510,"function":"buildContainer","class":"App
Kerne_","type":"->"},{"file":"C:\\Apache24\\htdocs\\StiFProject-00\\vendor\\symf
ony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Kernel.php","line":133,"funct
ion":"initializeContainer","class":"Symfony\\Component\\HttpKernel\\Kernel","typ
e":"->"},{"file":"C:\\Apache24\\htdocs\\StiFProject-00\\vendor\\symfony\\symfony
\\src\\Symfony\\Bundle\\FrameworkBundle\\Command\\CacheClearCommand.php","line":
134,"function":"boot","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-
>"},{"file":"C:\\Apache24\\htdocs\\StiFProject-00\\vendor\\symfony\\symfony\\src
\\Symfony\\Bundle\\FrameworkBundle\\Command\\CacheClearCommand.php","line":96,"f
unction":"warmup","class":"Symfony\\Bundle\\FrameworkBundle\\Command\\CacheClear
Command","type":"->"},{"file":"C:\\Apache24\\htdocs\\StiFProject-00\\vendor\\sym
fony\\symfony\\src\\Symfony\\Component\\Console\\Command\\Command.php","line":25
9,"function":"execute","class":"Symfony\\Bundle\\FrameworkBundle\\Command\\Cache
ClearCommand","type":"->"},{"file":"C:\\Apache24\\htdocs\\StiFProject-00\\vendor
\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Application.php","line":86
6,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type
":"->"},{"file":"C:\\Apache24\\htdocs\\StiFProject-00\\vendor\\symfony\\symfony\
\src\\Symfony\\Component\\Console\\Application.php","line":193,"function":"doRun
Command","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file"
:"C:\\Apache24\\htdocs\\StiFProject-00\\vendor\\symfony\\symfony\\src\\Symfony\\
Bundle\\FrameworkBundle\\Console\\Application.php","line":92,"function":"doRun",
"class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"C:\\Apa
che24\\htdocs\\StiFProject-00\\vendor\\symfony\\symfony\\src\\Symfony\\Component
\\Console\\Application.php","line":124,"function":"doRun","class":"Symfony\\Bund
le\\FrameworkBundle\\Console\\Application","type":"->"},{"file":"C:\\Apache24\\h
tdocs\\StiFProject-00\\app\\console","line":29,"function":"run","class":"Symfony
\\Component\\Console\\Application","type":"->"}]}


  [Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined offset: 1


Exception trace:
 () at C:\Apache24\htdocs\StiFProject-00\vendor\zendframework\zend-code\src\Gene
rator\MethodGenerator.php:98
 Symfony\Component\Debug\ErrorHandler->handleError() at C:\Apache24\htdocs\StiFP
roject-00\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:98
 Zend\Code\Generator\MethodGenerator::clearBodyIndention() at C:\Apache24\htdocs
\StiFProject-00\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php
:77
 Zend\Code\Generator\MethodGenerator::fromReflection() at C:\Apache24\htdocs\Sti
FProject-00\vendor\ocramius\proxy-manager\src\ProxyManager\Generator\MethodGener
ator.php:39
 ProxyManager\Generator\MethodGenerator::fromReflection() at C:\Apache24\htdocs\
StiFProject-00\vendor\ocramius\proxy-manager\src\ProxyManager\ProxyGenerator\Laz
yLoadingValueHolder\MethodGenerator\LazyLoadingMethodInterceptor.php:48
 ProxyManager\ProxyGenerator\LazyLoadingValueHolder\MethodGenerator\LazyLoadingM
ethodInterceptor::generateMethod() at C:\Apache24\htdocs\StiFProject-00\vendor\o
cramius\proxy-manager\src\ProxyManager\ProxyGenerator\LazyLoadingValueHolderGene
rator.php:118
 ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->ProxyManager\Proxy
Generator\{closure}() at n/a:n/a
 array_map() at C:\Apache24\htdocs\StiFProject-00\vendor\ocramius\proxy-manager\
src\ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator.php:90
 ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->generate() at C:\A
pache24\htdocs\StiFProject-00\vendor\symfony\symfony\src\Symfony\Bridge\ProxyMan
ager\LazyProxy\PhpDumper\ProxyDumper.php:136
 Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->generateProxyClass
() at C:\Apache24\htdocs\StiFProject-00\vendor\symfony\symfony\src\Symfony\Bridg
e\ProxyManager\LazyProxy\PhpDumper\ProxyDumper.php:82
 Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->getProxyFactoryCod
e() at C:\Apache24\htdocs\StiFProject-00\vendor\symfony\symfony\src\Symfony\Comp
onent\DependencyInjection\Dumper\PhpDumper.php:661
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addService() at C:\Apac
he24\htdocs\StiFProject-00\vendor\symfony\symfony\src\Symfony\Component\Dependen
cyInjection\Dumper\PhpDumper.php:711
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->addServices() at C:\Apa
che24\htdocs\StiFProject-00\vendor\symfony\symfony\src\Symfony\Component\Depende
ncyInjection\Dumper\PhpDumper.php:153
 Symfony\Component\DependencyInjection\Dumper\PhpDumper->dump() at C:\Apache24\h
tdocs\StiFProject-00\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Ker
nel.php:666
 Symfony\Component\HttpKernel\Kernel->dumpContainer() at C:\Apache24\htdocs\StiF
Project-00\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:51
2
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at C:\Apache24\htdoc
s\StiFProject-00\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.
php:133
 Symfony\Component\HttpKernel\Kernel->boot() at C:\Apache24\htdocs\StiFProject-0
0\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Command\CacheClearCo
mmand.php:134
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at C:\Apache
24\htdocs\StiFProject-00\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBund
le\Command\CacheClearCommand.php:96
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at C:\Apach
e24\htdocs\StiFProject-00\vendor\symfony\symfony\src\Symfony\Component\Console\C
ommand\Command.php:259
 Symfony\Component\Console\Command\Command->run() at C:\Apache24\htdocs\StiFProj
ect-00\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:866
 Symfony\Component\Console\Application->doRunCommand() at C:\Apache24\htdocs\Sti
FProject-00\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php
:193
 Symfony\Component\Console\Application->doRun() at C:\Apache24\htdocs\StiFProjec
t-00\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Applicati
on.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\Apache24\htdo
cs\StiFProject-00\vendor\symfony\symfony\src\Symfony\Component\Console\Applicati
on.php:124
 Symfony\Component\Console\Application->run() at C:\Apache24\htdocs\StiFProject-
00\app\console:29

**Comment by garak** [comment]
It looks related to this [issue in zend-code](https://github.com/zendframework/zend-code/pull/63), that is closed now. Try againt, now it should work
