### ISSUE TITLE
Compiler pass is throwing exception in Symfony 3.2

### ISSUE THREAD

**Issue by PeterFour** [dustin10/VichUploaderBundle#637]
The call on `$container->get()` in the **RegisterPropelModelsPass.php** file cause a `ReflectionException`.

Looking at the Symfony 3.2 upgrade file, it's now deprectated to call a container get before the container is built.

**Comment by Koc** [comment]
related https://github.com/dustin10/VichUploaderBundle/pull/636

**Comment by garak** [comment]
#636 is merged, @PeterFour can you confirm that this issue is resolved? Unfortunately, I don't use Propel since many years and I can't verify myself.

**Comment by Koc** [comment]
I think that this issue solved only for users which used Symfony and not used Propel

**Comment by PeterFour** [comment]
Hi There, sorry I didn't get back sooner, but weird thing is I was not using Propel yet still add the error. However I just realised that I'm running 3.2.* without any issue and didn't even noticed it.
Not really sure what made this go away

**Comment by garak** [comment]
So, can I close this?

**Comment by PeterFour** [comment]
@garak Yes, I'll close it now
