### ISSUE TITLE
Fatal Error Exception after success install

### ISSUE THREAD

**Issue by drondar** [dustin10/VichUploaderBundle#640]
Hello. When I installed the bundle by the console, everything is correct, but when I open the url of the project it show me this error:  

> FatalErrorException in appDevDebugProjectContainer.php line 4687:
> Parse Error: syntax error, unexpected ':', expecting ';' or '{'

> in appDevDebugProjectContainer.php line 4687
> at Kernel->initializeContainer() in Kernel.php line 117
> at Kernel->boot() in Kernel.php line 166
> at Kernel->handle() in app_dev.php line 28
> at {main}() in app_dev.php line 0

I did not do anything else, only install the project by the console's command and it finished well.
I am working in my own localhost using wampserver. I have other projects and other bundles with no errors.
Thank you for any help.

**Comment by garak** [comment]
Can you paste relevant lines of your appDevDebugProjectContainer.php? I mean line 4687 and some lines before and after

**Comment by garak** [comment]
Closing for missing feedback. Feel free to re-open. Thanks.
