### ISSUE TITLE
uri_prefix not working for me

### ISSUE THREAD

**Issue by Zuhayer** [dustin10/VichUploaderBundle#641]
I followed the install procedure [https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/installation.md] but image not displaying on the page. 

My Project Dir: 
D:\wamp\www\[project]\web\uploads\images

My Config.yml
vich_uploader:
    db_driver:  orm
    mappings:
        user_image:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.root_dir%/../web/uploads/images'

My twig code:
{% if user.imageName %}
        <p>If:</p>
`        <img src="{{ vich_uploader_asset(user, 'imageFile') }}" alt="#">`
    {% endif %}

Twig template displays the alt="#" of the image but not the image.

**Comment by garak** [comment]
More info needed

**Comment by Zuhayer** [comment]
The issue was a typo in my code.
