### ISSUE TITLE
[Insight] Missing use statement should be avoided - in Metadata/Driver/ChainDriver.php, line 16

### ISSUE THREAD

**Issue by garak** [dustin10/VichUploaderBundle#645]
**[in Metadata/Driver/ChainDriver.php, line 16](https://github.com/dustin10/VichUploaderBundle/blob/c95d9419b9cbbf2047e3ebafcbed5f4b8bfa08a6/Metadata/Driver/ChainDriver.php#L16)**

> The `DriverInterface` type hint resolves to the following class: `Metadata\Driver\DriverInterface`.
Did you forget to add a corresponding use statement?

```php
    public function __construct(array $drivers = array())
    {
        $this->drivers = $drivers;
    }

    public function addDriver(DriverInterface $driver)
    {
        $this->drivers[] = $driver;
    }

    public function loadMetadataForClass(\ReflectionClass $class)
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/796872a3-72b8-46e7-87d2-65d2402189d5/analyses/1)_

**Comment by garak** [comment]
@K-Phoen any idea of what's happening here? I noticed that also `AnnotationDriver.php` is implemeting a `DriverInterface` that I can't find anywhere :disappointed:

**Comment by K-Phoen** [comment]
I think that the `DriverInterface` is this one: https://github.com/schmittjoh/metadata/blob/master/src/Metadata/Driver/DriverInterface.php (but the `use` statement appears to be missing)

I remember having to implement a few things to have Propel support working (especially in regard to class metadata) and this driver seem related to that. But it was almost 3 years ago and I don't remember well :/
