### ISSUE TITLE
[Insight] The Symfony Dependency Injection Container should not be passed as an argument - in Mapping/PropertyMappingFactory.php, line 49

### ISSUE THREAD

**Issue by garak** [dustin10/VichUploaderBundle#646]
**[in Mapping/PropertyMappingFactory.php, line 49](https://github.com/dustin10/VichUploaderBundle/blob/c95d9419b9cbbf2047e3ebafcbed5f4b8bfa08a6/Mapping/PropertyMappingFactory.php#L49)**

> A Symfony dependency injection container has been found as an argument.

```php
     * @param ContainerInterface $container                      The container.
     * @param MetadataReader     $metadata                       The mapping mapping.
     * @param array              $mappings                       The configured mappings.
     * @param string             $defaultFilenameAttributeSuffix The default suffix to be used if the fileNamePropertyPath isn't given for a mapping.
     */
    public function __construct(ContainerInterface $container, MetadataReader $metadata, array $mappings, $defaultFilenameAttributeSuffix = '_name')
    {
        $this->container = $container;
        $this->metadata = $metadata;
        $this->mappings = $mappings;
        $this->defaultFilenameAttributeSuffix = $defaultFilenameAttributeSuffix;
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/796872a3-72b8-46e7-87d2-65d2402189d5/analyses/1)_

**Comment by garak** [comment]
I see that we're using Container to get `$namerConfig['service']`, maybe we could inject that instead?

**Comment by Koc** [comment]
As I understand - this needed for lazy loading of the namers. We can create one service per mapping with injected namers (see #625) but anyway we also need getting this configured services lazy from container.

So this issue looks like wontfix

**Comment by Koc** [comment]
See also https://github.com/symfony/symfony/issues/20658 , https://github.com/symfony/symfony/issues/20875 but it all not merged/implemented yet and requires major minimum Symfony version bump
