### ISSUE TITLE
Content Based Filename hashing and Filename keeping

### ISSUE THREAD

**Issue by c33s** [dustin10/VichUploaderBundle#651]
as i wrote in #501 i think it is quite important to have the option to do content based filename hashing with [`hash_file()`][1] and also have the option to keep the filename.

`mypicture.jpg` 
->
`4/b/1/4b1e384ad74619bd212e236e52a5a174/mypicture.jpg`
or
`4/b/1/4b1e384ad74619bd212e236e52a5a174_mypicture.jpg`

the kept name is better for search engines and allow humans to debug uploads more easily. the content bases hashing allows better caching because uploads only have to be downloaded if the content is really changed -> more cache hits

[1]: https://secure.php.net/manual/en/function.hash-file.php

**Comment by garak** [comment]
You can implement your namer to achieve that.
Here's a small example:

```php
<?php

namespace AppBundle\Naming;

use Vich\UploaderBundle\Mapping\PropertyMapping;
use Vich\UploaderBundle\Naming\NamerInterface;

class SmartFileNamer implements NamerInterface
{
    /**
     * {@inheritdoc}
     */
    public function name($object, PropertyMapping $mapping)
    {
        $file = $mapping->getFile($object);
        $originalName = $file->getClientOriginalName();
        $originalExtension = pathinfo($originalName, PATHINFO_EXTENSION);
        $originalBasename = basename($originalName, '.'.$originalExtension);
        $originalBasename = str_replace(' ', '_', strtolower($originalBasename));

        return $originalBasename.'_'.uniqid().'.'.$originalExtension;
    }
}
```

**Comment by c33s** [comment]
@garak thanks for your support but my ticket ment to be to support this out of the box and making it configureable.
also your example doesn't support the content bases hashing, which, in my opinion, is very important. 

sidenote:
of course its not that difficult to create a custom namer that uses `hash_file` instead of `hash` but its quite expensive to hash two times. one time for the directory and one time for the filename.

this is the reason for requesting this to be solved in the official bundle, to support the multi subdirectory, contentbased hashed "path with filename strings".

**Comment by garak** [comment]
You can also use `DirectoryNamerInterface`. So, it's actually supported and configurable.

**Comment by c33s** [comment]
@garak thanks again. as i said i know how to do this but this ticket is not a question/support ticket but a request to add this namers to the bundle itself.

with supported and configurable i don't mean that every developer have to build its own solution and run into problems he/she hadn't thought about.

maybe even set it as default, because this prevents websites that are using your uploader as dropin solution and which had grown from the bad supprise of having 70k uploaded files in one directory.

also its about performance, because as i wrote in my comment above, that having both directory and file namer using the file_hash function is the double cost of cpu time.

**Comment by Koc** [comment]
How to deal with files which has identical content (and hash also)?

**Comment by garak** [comment]
@c33s is there anything left, that is not currently covered in eda23b8?

**Comment by c33s** [comment]
lets close this for now. i will reopen if needed (will test it on the next project where i implement upload)

**Comment by mkh01** [comment]
What if i want to keep the old name and just override the Image, do i have to make a namer?
let's say i habe the Image img-1.jpg this name i want it always to be the same and the new imgage gonna delete the old image and get the old name.

Every thing works okay in my function but i just need to solve this issue.

Any help?

**Comment by garak** [comment]
there's no control on file overwriting. You can do whatever you want
