### ISSUE TITLE
Error caused by ocramius

### ISSUE THREAD

**Issue by nachmo5** [dustin10/VichUploaderBundle#656]
Hello, when i install your bundle via composer, it installs automatically a bundle named ocramius, i guess it's necessary for yours to work.
But when i go to my website, it gives me an error, Configuration.php is in vendor/ocramius

![image](https://cloud.githubusercontent.com/assets/22916660/21600971/21bd9cf8-d17c-11e6-8297-a4a731b7cebe.png)

**Comment by garak** [comment]
PHP version?

**Comment by nachmo5** [comment]
5.6.25

**Comment by garak** [comment]
Unfortunately, that version is out of active support. You should upgrade to php 7.0 or 7.1

**Comment by nachmo5** [comment]
thank you very much

**Comment by garak** [comment]
You're welcome.
