### ISSUE TITLE
Syntax error after adding VichUploaderBundle to new project

### ISSUE THREAD

**Issue by Eversor1989** [dustin10/VichUploaderBundle#658]
As soon as I add the VichUploaderBundle to my symfony 3.2 project, I receive the following error:

> FatalErrorException in appDevDebugProjectContainer.php line 5944:
Parse Error: syntax error, unexpected ':', expecting ';' or '{'

Removing the bundle resolves the problem. The composer file for my project looks like the example below. Any thoughts?

> {
>     "name": "***",
>     "license": "proprietary",
>     "type": "project",
>     "autoload": {
>         "psr-4": {
>             "": "src/"
>         },
>         "classmap": [
>             "app/AppKernel.php",
>             "app/AppCache.php"
>         ]
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "Tests\\": "tests/"
>         }
>     },
>     "require": {
>         "php": ">=5.5.9",
>         "symfony/symfony": "3.2.*",
>         "doctrine/orm": "^2.5",
>         "doctrine/doctrine-bundle": "^1.6",
>         "doctrine/doctrine-cache-bundle": "^1.2",
>         "symfony/swiftmailer-bundle": "^2.3",
>         "symfony/monolog-bundle": "^3.0",
>         "symfony/polyfill-apcu": "^1.0",
>         "sensio/distribution-bundle": "^5.0",
>         "sensio/framework-extra-bundle": "^3.0.2",
>         "incenteev/composer-parameter-handler": "^2.0",
>         "stof/doctrine-extensions-bundle": "1.2.*",
>         "liip/imagine-bundle": "^1.3",
>         "symfony/assetic-bundle": "^2.8",
>         "vich/uploader-bundle": "1.4.0"
>     },
>     "require-dev": {
>         "sensio/generator-bundle": "^3.0",
>         "symfony/phpunit-bridge": "^3.0"
>     },
>     "scripts": {
>         "symfony-scripts": [
>             "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
>             "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
>             "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
>             "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
>             "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
>             "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
>         ],
>         "post-install-cmd": [
>             "@symfony-scripts"
>         ],
>         "post-update-cmd": [
>             "@symfony-scripts"
>         ]
>     },
>     "extra": {
>         "symfony-app-dir": "app",
>         "symfony-bin-dir": "bin",
>         "symfony-var-dir": "var",
>         "symfony-web-dir": "web",
>         "symfony-tests-dir": "tests",
>         "symfony-assets-install": "relative",
>         "incenteev-parameters": {
>             "file": "app/config/parameters.yml"
>         }
>     }
> }

**Comment by garak** [comment]
PHP version?

**Comment by Eversor1989** [comment]
7.0.14-2

**Comment by garak** [comment]
What is the content of line 5944?

**Comment by Eversor1989** [comment]
> public function initializeProxy() : bool

**Comment by garak** [comment]
That's looks good to me.
The only reason for an error `unexpected ':'` is using a version of PHP lower than 7.

**Comment by Eversor1989** [comment]
Yes, I figured the same. However, the machine IS running on 7.0.14-2, which seems alright?

**Comment by garak** [comment]
I see that your composer.json is requiring php `>=5.5.9`, not `>7.0`

**Comment by Eversor1989** [comment]
Turns out to be PEBCAK indeed: PHP7 was actually installed on the server and "php -v" showed me that the current installation was indeed 7.0.14. However, it was not loaded in Apache.

**Comment by garak** [comment]
So I guess you managed to resolve? Can we close this?
