### ISSUE TITLE
Documentation - Small update on YAML

### ISSUE THREAD

**Issue by BatsaxIV** [dustin10/VichUploaderBundle#659]
Hi,

I use this bundle with the YAML configuration and I think the [documentation](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/mapping/yaml.md) is a little bit unclear.
At first, I added the configuration regarding the uploaded fields directly in the mapping configuration of the entity and it is this [post](http://stackoverflow.com/questions/24658894/how-to-configure-vichuploader-in-entity-mapped-by-yml?answertab=votes#tab-top) that helped me understand that it needed a separate file only for the uploaded fiels.

A sentence like 

> To be automatically found, the mapping configuration MUST be in the Resources/config/vich_uploader

 can be confusing regarding where to put the configuration.

What do you think?

Jérémy.

**Comment by garak** [comment]
As others Symfony configuration (routing, doctrine, etc.), configuration can be put directly inside Entity (via annotation) or in a separate YAML/XML file.
What is unclear to you?

**Comment by BatsaxIV** [comment]
What is unclear to me is the fact that we have to create another file dedicated to the configuration of this bundle.
It is possible to think that this configuration has to be put inside the global yaml configuration of the entity, which does not work.

**Comment by garak** [comment]
That's exactly how mapping works for Doctrine: generic configuration in global config,yml, a mapping file per entity.

**Comment by BatsaxIV** [comment]
I think I'm unclear or maybe there's something I have not understand :)

Let's say I have my entity in : _Acme/AppBundle/Entity/Product.php_
My yaml mapping file in : _Acme/AppBundle/Resources/config/doctrine/Product.orm.yml_

What I was saying is that, it is possible to think that you have to add the configuration mentionned in the documentation in the _Product.orm.yml_ file, which does not work.
Then when I read the thread on stackoverflow, it was clear that I add to create a new file : 

> You need to create a src/Acme/DemoBundle/Resource/config/vich_uploader/Magazine.yml file with the following content

I know that the documentation indicate the file in _src/Acme/DemoBundle/Resources/config/vich_uploader/Product.yml_ which is not the mapping file, but it is possible to read not properly this part and to be confused by the sentence

>  the mapping configuration MUST be in the Resources/config/vich_uploader

Maybe it is just me, but I think adding something like the stackoverflow comment can dispel  the doubts :)

What's your opinion?

**Comment by garak** [comment]
> You need to create a src/Acme/DemoBundle/Resource/config/vich_uploader/Magazine.yml file with the following content

>  the mapping configuration MUST be in the Resources/config/vich_uploader of the bundle containing the entity

These two sentences are telling the same thing, but the first is mentioning the name of a bundle (a fictional one, indeed). I think that we'll keep the second one, that is more general.

Thanks for your suggession, anyway.
