### ISSUE TITLE
[Help Needed] How to Show Image in SonataAdmin ShowMapper?

### ISSUE THREAD

**Issue by Zuhayer** [dustin10/VichUploaderBundle#663]
![Image of my show mapper](https://cloud.githubusercontent.com/assets/5408155/21884270/6b17a9fc-d8d4-11e6-845b-127614ff3435.png)

After I upload Images using VichUploader, I am unable to show their preview in Sonata Admin ShowMapper.

I found this answer on stackoverflow, it seems promising, but as I am new to symfony I am unable to implement it properly. [StackOverFlow Answer](http://stackoverflow.com/questions/11366278/how-to-display-the-current-picture-above-the-upload-field-in-sonataadminbundle)

The stackoverflow answer mentions 'MyCompanyMyBundle:Form:mycompany_admin_fields.html.twig'. But in templating scenarios, I do not know where to place my twig file.

**Comment by garak** [comment]
`MyCompanyMyBundle:Form:mycompany_admin_fields.html.twig` should be placed under `src/MyCompanyBundle/Resources/views/Form/mycompany_admin_fields.html.twig` or under `app/Resources/MyCompanyBundle/views/Form/mycompany_admin_fields.html.twig`

**Comment by Zuhayer** [comment]
Thanks,

May I please get some more guidance regarding $this ...

My Admin Class:
```
protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
           ...
            ->add('logo', null, array('template' => 'SonataAdminBundle::custom_show_image.html.twig'))
            ...
        ;
    }
```
Entity:
```
    /**
     * @var string
     *
     * @Serializer\Expose()
     * @Groups({"partner"})
     * @ORM\Column(name="logo", type="string", nullable=true)
     */
    private $logo;
    
    /**
     * @Groups({"partner"})
     * @Vich\UploadableField(mapping="partner_logo", fileNameProperty="logo")
     */
    private $logoFile;
```

- How to i adapt the following code to suite my Entity?

The custom template is placed here (app/Resources/SonataAdminBundle/CRUD/custom_show_image.html.twig) . Code taken from [(StackoverFlow Answer):](http://stackoverflow.com/a/12696046/2870729)


> ```
> {% extends 'SonataAdminBundle:CRUD:base_show_field.html.twig' %}
> 
> {% block field %}
>     {% spaceless %}
>         {% set subject =  form.parent.vars.value %}
>         {% if subject.id and attribute(subject, logo) %}
>             <a href="{{ asset(vich_uploader_asset(subject, logo)) }}" target="_blank">
>                 <img src="{{ asset(vich_uploader_asset(subject, logo)) }}" width="200" />
>             </a><br/>
>         {% endif %}
>     {% endspaceless %}
> {% endblock %}
> ```

OR

```
 {% set subject =  form.parent.vars.value %}
        {% if subject.logo and attribute(subject, logoFile) %}
            <a href="{{ asset(vich_uploader_asset(subject, logoFile)) }}" target="_blank">
                <img src="{{ asset(vich_uploader_asset(subject, logoFile)) }}" width="200" />
            </a><br/>
        {% endif %}
```

Guidance will be very much appreciated.

Thanks.

**Comment by garak** [comment]
Sorry, I don't use Sonata.
I'm afraid that this support request gone too far. Please use other support channels.

**Comment by Zuhayer** [comment]
@garak 

I have almost got the code working, but there seems to be an issue.

![VichUploader logoFile is shows as Null value.](https://cloud.githubusercontent.com/assets/5408155/21892475/e4206f0e-d8f8-11e6-818d-1df6464a96c7.png)

Is this a bug, or am i missing something?

```
{% block field %}
    {% spaceless %}
        {% if object.logo %}
            {{ dump(object) }}
            <a href="{{ asset(vich_uploader_asset(object, logoFile)) }}" target="_blank">
                <img src="{{ vich_uploader_asset(object, logoFile) }}" width="200" />
            </a><br/>
        {% endif %}
    {% endspaceless %}
{% endblock %}
```
Error Shown:
```
Variable "logoFile" does not exist.
500 Internal Server Error - Twig_Error_Runtime

Stack Trace
in app\Resources\SonataAdminBundle\views\CRUD\custom_show_image.html.twig at line 8   -
        {% if object.logo %} 
            {{ dump(object) }} 
            {#<a href="{{ asset(vich_uploader_asset(object, logoFile)) }}" target="_blank">#} 
                <img src="{{ vich_uploader_asset(object, logoFile) }}" width="200" /> 
            {#</a><br/>#} 
        {% endif %} 

```

**Comment by garak** [comment]
You need to use `"logofile"` instead of `logofile`

**Comment by Zuhayer** [comment]
For anyone who might have the same issue:

1. First issue was my problem as vich_uploader_asset(object, logoFile) should have been vich_uploader_asset(object, 'logoFile').

2. Second cache needed clearing. 

@garak Thanks for the help.
