### ISSUE TITLE
vichuploadbundle with dropzone

### ISSUE THREAD

**Issue by fabirus** [dustin10/VichUploaderBundle#664]
hello, can integrate dropzonejs form with vichuploadbundle?

thanks

**Comment by garak** [comment]
Try this: http://stackoverflow.com/questions/18701684/multi-upload-symfony-2-3-with-dropzone

**Comment by garak** [comment]
Closing for missing feedback.

**Comment by bogdaniel** [comment]
@garak So the solution to his question would be to use the OneupUploaderBundle?

**Comment by garak** [comment]
That's a possible solution, yes
