### ISSUE TITLE
hook into fileSave or afterFileSave for running a custom postSave routine e.g. generate thumbnail 

### ISSUE THREAD

**Issue by kapitalo** [dustin10/VichUploaderBundle#665]
What is the best way to hook into VichUploader after a file (uploaded via vich_uploader) was uploaded and saved? I want to run a custom createThumbnail function, but don't see a configurable listener for this.  Is there a suggested way or hook point to do so or is it something i need to find completely on my own? thx.

**Comment by garak** [comment]
https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/events.md

it that enough for you?

**Comment by kapitalo** [comment]
bäm... indeed :)

**Comment by kapitalo** [comment]
doc example says:
`class FooListener
{
    public function onPreUpload(Event $event)
    {`

since i needed it for postUpload i concluded to to add this as my listener:

`class FooListener
{
    public function onPostUpload(Event $event)
    {`

but instead i needed to add this in order to get it working

`class FooListener
{
    public function onVichuploaderPostupload(Event $event)
    {`
