### ISSUE TITLE
Use with PHP templates

### ISSUE THREAD

**Issue by alexBelikoff** [dustin10/VichUploaderBundle#667]
Please, tell me, how can i use bundle with php templates?

**Comment by garak** [comment]
Try reading these docs:
* http://symfony.com/doc/current/templating/PHP.html
* https://symfony.com/doc/current/form/form_customization.html

Then, you should be able to re-create our [template](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/views/Form/fields.html.twig).

**Comment by alexBelikoff** [comment]
Thanks, I read this docs, I don't understand how to change this code
`<img src="{{ vich_uploader_asset(product, 'image') }}" alt="{{ product.name }}" />` for php template?

**Comment by garak** [comment]
`vich_uploader_asset()` is an helper. The doc linked above is explaining helpers in the section http://symfony.com/doc/current/templating/PHP.html#using-template-helpers

**Comment by alexBelikoff** [comment]
Sorry, it dawned on me). Thanks!
