### ISSUE TITLE
Fatal error: Allowed memory size

### ISSUE THREAD

**Issue by nansnans** [dustin10/VichUploaderBundle#668]
Hello,

After have done this : composer require vich/uploader-bundle

I've got this issue : 
Fatal error: Allowed memory size [..] in phar://C/ProgramData/composerSetup/bin/composer.phar/src/composer/DependencyResolver/Solver.php on line 214

I need your help, I don't know how to fix it

Thank you very much for your help

Nans

**Comment by garak** [comment]
I'm afraid this is not related to this bundle. Try asking help on [composer](https://github.com/composer/composer)
