### ISSUE TITLE
Handle upload in Embeddable

### ISSUE THREAD

**Issue by ama3ing** [dustin10/VichUploaderBundle#672]
There is way to crearte embedded objects in doctrine (See: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/embeddables.html). I really like this concept to extract reusable parts from entities. 

So what I am trying to achieve is to have some kind of AbstractImage which I can use in several entities.
```php
<?php

/**
 * @ORM\Embeddable
 * @Vich\Uploadable
 */
class Image
{
    /**
     * @var File
     * @Vich\UploadableField(mapping="upload", fileNameProperty="path")
     */
    private $file;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $path;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    private $uploadedAt;
// ...
}
```
However I guess that ```Uploadable``` annotation is skipped when saving entity which contain this embeddable.

Any ideas?

**Comment by garak** [comment]
See #350
