### ISSUE TITLE
Delete temporary files after upload?

### ISSUE THREAD

**Issue by polantis** [dustin10/VichUploaderBundle#675]
Hello,

Is it possible to delete temporary file after the file has been uploaded? 

I am uploading a zip with several files. My web servers are unzipping them in a folder. For each file, i am creating a UploadedFile object containing the file and attaching it to an entity. The upload is working well but i still have the files in my temporary folder. I tried to delete them with PostPersist/PostUpdate but files are not uploaded anymore. Should i try PostFlush or there is a special feature for it?

Thanks

**Comment by garak** [comment]
I think that temporary files cleaning is something the operating system should take care of.
