### ISSUE TITLE
Mongo db upload

### ISSUE THREAD

**Issue by licarigianluca** [dustin10/VichUploaderBundle#678]
Hi,
I cannot found in the documentation an example of configuration with mongo db odm. 
How can I upload a file with this bundle and store it in a collection?

Thx

**Comment by licarigianluca** [comment]
vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix:         /images/products
            upload_destination: %kernel.root_dir%/../web/images/products

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true



Is this the example?
How the fields uri_prefix and upload_destination have to be setted with mongoDB?

In the following example I set the fileNameProperty but I'd like to store the document's id retrieved from   Mongo db.Is it possible? I'm looking for a way to store a file in the Document Database and save the id of the document inside a field into a RDBMS's table.


/**
     * @var string
     *
     * @ORM\Column(name="idFile", type="string")
     *
     */
    private $idFile;


/**
     * @var File
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="idFile")
     *
     */
    private $file;

**Comment by garak** [comment]
the only relevant option is `db_driver`, everything else can stay untouched.
The saving of the id after file upload is something that you need to care about. You can take a look to events section in docs to get a clue.

**Comment by licarigianluca** [comment]
I have to know if for my problem this bundle is usefull.
I'll explain what i have to do.



I use doctrine as ORM and i have an entity Order( see example in doc http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/cookbook/blending-orm-and-mongodb-odm.html) and a  document called Product mapped in MongoDb using the DoctrineMongoDBBundle.

Can I use VichUploaderBundle to upload in a form a file which will be stored as an instance of Product in MongoDb and its id will be saved in a field of Order?

Which type of mapping inside config.yml I have to use?

I'm comfused.

**Comment by garak** [comment]
I dont' see any new detail that can change my previous answer.
Just use `db_driver: odm` and follow the docs for everything else

**Comment by licarigianluca** [comment]
# app/config/config.yml
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr


this is taken from the docs. Where is the ODM setting?

**Comment by garak** [comment]
sorry, it's `db_driver: mongodb`

**Comment by garak** [comment]
Closing for missing feedback
