### ISSUE TITLE
Download is not working : getMimeType on null

### ISSUE THREAD

**Issue by GCalmels** [dustin10/VichUploaderBundle#679]
Hey,
Since v1.5, I have the following error : `Call to a member function getMimeType() on null`

I get the $file with doctrine and I do `return $downloadHandler->downloadObject($file, $fileField = 'file', $objectClass = null, 'template.xlsx');`

Thanks

**Comment by garak** [comment]
Please try with `^1.6@dev` and see if it's OK

**Comment by GCalmels** [comment]
With `1.6@dev`, I don't have this error but the file downloaded is template.xlsx.html...

**Comment by garak** [comment]
Try now

**Comment by GCalmels** [comment]
👍 perfect!

Thank you

**Comment by garak** [comment]
I just released version `1.5.2`, so now you can use a stable requirement
