### ISSUE TITLE
probleme name and render.

### ISSUE THREAD

**Issue by xorgxx** [dustin10/VichUploaderBundle#680]
hi i try to use your bundle, and i get some trouble! all are working i suppose well but : this is the render final

![2017-03-08_08-31-40](https://cloud.githubusercontent.com/assets/7679725/23694351/bcbcb484-03d9-11e7-85ad-6fe72269bf3c.jpg)

I dont get any name file or image, it' normal ?

Symfony3.2.4,
in my type file : 
```            
->add("imageFile", VichFileType::class , [
                'required' => false,
                'allow_delete' => true, // not mandatory, default is true
                'download_link' => true, // not mandatory, default is true
            ])
```
config.yml : 
```
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
#        resources:  resources: ['bootstrap_3_layout.html.twig']
        - 'bootstrap_3_horizontal_layout.html.twig'
        - 'VichUploaderBundle:Form:fields.html.twig'
```
thank for your help

**Comment by garak** [comment]
As specified in documentation, you need to use `VichImageType`

**Comment by xorgxx** [comment]
ok my mistek !! i work now, but it can render only .jpg ... not pdf or any file  ?

**Comment by garak** [comment]
If you want to display current file name, you need to implement your own template.

**Comment by garak** [comment]
Closing for missing feedback

**Comment by xorgxx** [comment]
after time i get to this and it work well. thank 
![2017-03-16_13-15-24](https://cloud.githubusercontent.com/assets/7679725/23995676/e13cad7e-0a4a-11e7-9410-da6c6945eb18.jpg)
