### ISSUE TITLE
let us a way to (simply) choose the presentation of the image in the form theme

### ISSUE THREAD

**Issue by bruno-ds** [dustin10/VichUploaderBundle#685]
Hello,

It would be great to permit the customization of the rendering of the images, at least in order to define a max size for the image.
for example, you may : 
- add a block around the <img> tag so whe don't have to rewrite the whole `block vich_image_widget`
- add this kind of css class on the <img> tag : `class="vich_image_widget vich_image_widget-{{ form.vars.id }}"  `
- permit us to define a class and/or height/width properties in the config. file wich would be used by the template

it is not blocking since it is quite easy to overwrite the existing form theme.

PS : thank you for your great bundle!

**Comment by garak** [comment]
There's already a class in `<div class="vich-image">`, can't you just use that for your styles?

**Comment by bruno-ds** [comment]
Yes, you're right, I'll can use it, sorry.
