### ISSUE TITLE
Ajax and Vich

### ISSUE THREAD

**Issue by jMoulis** [dustin10/VichUploaderBundle#687]
Hi everyone,
I'm facing a trouble to persist my file via ajax? It seems that the upload service doesn't activate. The file is not uploaded neither the url saved in my database. Do you know any work around?

**Comment by garak** [comment]
Please provide a way to reproduce your problem

**Comment by jMoulis** [comment]
Actually, I think that it is more a pb with ajax, because the uploadable field is not in the Ajax request. it is Empty. So it's probably not a Vich issue... But my poor understanding of Ajax.

**Comment by Dragnucs** [comment]
@garak can you please provide a hint on the doc on how to use drag'n'rop or Ajax upload? This is recurrent and I myself do not know how to.

**Comment by garak** [comment]
Well, the drag andr drop is supported natively by any modern browser, just drag your file on the input and you're done.
The ajax, instead, is just a different way to handle the flow in your controllers, nothing changes in the logic of your entities or configuration
