### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by Haikuch** [dustin10/VichUploaderBundle#695]
I don't know if this is a general issue. But I had to change the config first, before running composer require. Otherwise I get an error.

Aside from that is there a mistake in the config:

```
# app/config/config.yml
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
```

yaml does not allow inline comments, so the `# or mongodb or propel or phpcr` leads to bad syntax

**Comment by garak** [comment]
Simply requiring a bundle has no effect on you application, until you add the bundle to your kernel

**Comment by garak** [comment]
Also, inline comments are considered valid by Symfony. See http://symfony.com/doc/master/components/yaml/yaml_format.html#comments

**Comment by Haikuch** [comment]
mh could not reproduce the error, maybe it was just because of an cache problem
