### ISSUE TITLE
use vich bundle without an entity or db_driver

### ISSUE THREAD

**Issue by fiburonsk** [dustin10/VichUploaderBundle#701]
I am working on a form building application in Symfony 3.2 which dynamically builds forms using the Symfony FormBuilder.  This bundle looks great but doesn't appear to fit my goal from what I can tell since I'm building my Symfony Forms from a data array instead of an Entity class.

I am saving the submission data as a document, but i'm not using mongodb. Each Record entity has a context field of type `json_array` where all of my data is saved after each revision.  For my database i'm just using Doctrine DBAL since all that is required is fetching each Record for a given uuid and merging each revision from first until last to get the final values.  Currently I save metadata in the field name value. Here is a sample record of a form that would have fields [name: text, pets: int, file_field: file].  The data in context is used for the Form data and running it through a transformer should not be a problem.

```
{
  "uuid": "...",
  "revision": 3,
  "form_id": "...",
  "form_revision": 4,
  "date": "2017-04-17 15:00:00 0500",
  "context": {
    "name": "waffles",
    "pets": 3,
    "file_field": {
      "mimetype" : "application/pdf",
      "name" : "instructions.pdf",
      "path" : "/http/var/uploads/8bd5ec85-31c5-4981-8f8e-c61ea2beac42",
      "pathName" : "2ed43e29-5976-4063-800e-13eeb3a6cca4",
  },
}
```
I would guess such a feature may be out of scope, but would it be possible to use this in a way that isn't dependent on using a database driver and an entity with mapping properties?  If this is already possible and I simply overlooked the potential configuration then even better.  thanks!

**Comment by garak** [comment]
You can try to implement an EvenListener, starting from the [existing ones](https://github.com/dustin10/VichUploaderBundle/tree/master/EventListener).
If you manage to do so, feel free to open a PR

**Comment by fiburonsk** [comment]
Thanks, I'll give that a try and see where it gets me.

**Comment by fiburonsk** [comment]
It looks like my pain point is `$storage->resolveUri(...)` in the VichFileType class.  I'll have to see if i can work around this with custom storage when I have more time.  In my case the FileSystemStorage needs more information than just the form data to determine which index in the array maps to a file field since there is no mapping metadata to read.

```
[1] RuntimeException: Impossible to determine the class name. Either specify it explicitly or give an object
    at n/a
        in /srv/http/project/vendor/vich/uploader-bundle/Mapping/PropertyMappingFactory.php line 203
```

**Comment by Koc** [comment]
Interesting usage of the bundle. Please open PR (documentaton recipe) if you got any success.

**Comment by fiburonsk** [comment]
I went ahead and wrote my own FileType and template from scratch utilizing file events the app was already firing.  The bundle ended up not being necessary.  I look forward to trying the bundle out maybe in my next project.  Thanks!
