### ISSUE TITLE
UploadHandler.php needs method getFile() in entity ?

### ISSUE THREAD

**Issue by hajika** [dustin10/VichUploaderBundle#702]
I had en error while uploading, that the method getFile() could not be found. The problem occured from line 118 in Uploadhandler.php

```
    protected function hasUploadedFile($obj, PropertyMapping $mapping)
    {
        $file = $mapping->getFile($obj);

        return $file !== null && $file instanceof UploadedFile;
    }
```

I didnt know, that it is necessary to declare a method getFile() in my Entity, in the documentation it is not explained like that (there it is called getImageFile()). Or is there a mistake on my side?

**Comment by garak** [comment]
The mentioned method is not related to your entity.
You probably did some mistake in your configuration: try to debug by puttin a stop in UploadHandler.php (or, as alternate and simpler debuggin strategy, try to `dump($mapping)` inside that file)

**Comment by hajika** [comment]
thats exactly what i did :) Putting a dump($mapping there). It did not look like my entity, true, but because I didn't know what to do else I just tried to add a method getFile() to my entity and voila it worked. 

```
public function getFile() {
        
        dump("boo"); die();
    }
```

And yes, it is called from within that above mentioned method. After that, I got a new error with acces property problems, so I added a method setFile() and it worked out, too. I guess it tried to set the $file constant within the class and thats why the error occured. With my new method setFIle() it took this one.

Iam also surprised, because the output of $mapping didn look like it could manage the getFile() method (even after I added it to my entity):

```
UploadHandler.php on line 117:
PropertyMapping {#607 ▼
  #namer: null
  #directoryNamer: null
  #mapping: array:8 [▶]
  #mappingName: "document_file"
  #filePropertyPath: "file"
  #fileNamePropertyPath: "name"
  #accessor: null
}
```

**Comment by hajika** [comment]
The `setFile()` method is called in `FileInjector.php()` on line 39:

```
public function injectFile($obj, PropertyMapping $mapping)
    {
        $path = $this->storage->resolvePath($obj, $mapping->getFilePropertyName());
        if ($path !== null) {
            $mapping->setFile($obj, new File($path, false));
        }
    }
```

**Comment by Koc** [comment]
it is calling `setFile` of `PropertyMapping` which can call `setFile` of your entity. Please show some the code of your entity

**Comment by garak** [comment]
Closing for missing feedback. Feel free to re-open
