### ISSUE TITLE
Make optional overriding files for Gaufrette storage 

### ISSUE THREAD

**Issue by bilel-noomene** [dustin10/VichUploaderBundle#703]
I think it will be interesting to make overriding optional when using Gaufrette storage. Currently, the parameter override is fixed to true in GaufretteStorage  service:
`$filesystem->write($path, file_get_contents($file->getPathname()), true);`

**Comment by garak** [comment]
Feel free to propose a PR

**Comment by Koc** [comment]
it is may be useful for all storages. Also imho this should be resolved by file namer.

**Comment by Koc** [comment]
can be considered as duplicate of #417
