### ISSUE TITLE
Conflict of two entities with the same name but different namespaces

### ISSUE THREAD

**Issue by igaponov** [dustin10/VichUploaderBundle#704]
Assume I have two entities like `Acme\DemoBundle\Entity\Product` and `Acme\DemoBundle\Entity\Order\Product` and I want to use yaml mapping. The only entity that has uploadable field is the first one, so I add a file `src/Acme/DemoBundle/Resources/config/vich_uploader/Product.yml`, but it doesn't work, because `\Vich\UploaderBundle\Metadata\Driver\FileLocator` uses `$class->getShortName()` and it returns "Product" for both entities. 

P.S. It's funny, that `\Metadata\Driver\FileLocator` from `jms/metadata` package (the `\Vich\...\FileLocator` file uses its interface) works fine, just need to change the name of metadata file to `.../vich_uploader/Entity.Product.yml` to avoid this conflict.

**Comment by Koc** [comment]
Class `\Vich\UploaderBundle\Metadata\Driver\FileLocator` has removed some time ago in #689. Can you recheck current behavior on `dev-master`?

**Comment by igaponov** [comment]
@Koc thanks, it works in `dev-master`. When do you plan to release it?

**Comment by Koc** [comment]
Let's ping @garak about tagging new release.

**Comment by garak** [comment]
There's no date for now, waiting for some PRs to be finished
