### ISSUE TITLE
directory namer like /web/images/{id}

### ISSUE THREAD

**Issue by jonibegoode** [dustin10/VichUploaderBundle#705]
Hi, 

I see in the doc it should be several directory namers but I can only see one.

I need a namer directory to be able to put files in the directory of the id (the foreign key) the file is in relation to (in a onetomany or onetoone relationship) for these reasons:
- One type of file I use absolutly need to be the only one of its kind to be able to work. Il will generate conflicts if 2 files of this kind are in the same directory.
- 2 files can have the same name.

Is there already a directory namer which put files in web/images/{id} or do I have to build a custom directory namer? As I am pretty new to php and symfony, could you give me some hints on how to do so? It would be greatly appreciated.

Regards

**Comment by garak** [comment]
Docs are pretty straightforward about writing a custom directory namer.

**Comment by jonibegoode** [comment]
Thank you. Docs are maybe too simple for novices (arguments needed for example are not presented) , but I've found examples somewhere else I've been able to use to make it work. 

Quick question before I close as I may not need  to open a new issue. What is, in your opinion, the best way to delete a file after it's been downloaded? Maybe something similar to"delete_on_remove" for downloads (like delete_on_download). 
Is it by serving the file from a controller?

**Comment by garak** [comment]
Of course, the best example for a custom namer is one of the namers already present in the code of this bundle.
The question about deleting a file after download is not related to this bundle. Anyway, best way is likely using an event listener

**Comment by jonibegoode** [comment]
Ok, I'll try to figure it out. Again, thank you very much.
