### ISSUE TITLE
Is there any slugger namer implementation?

### ISSUE THREAD

**Issue by roberto910907** [dustin10/VichUploaderBundle#709]
Somebody has implemented an slugify for the uploaded file name?

Thanks in advance.

**Comment by garak** [comment]
You can use [Transliterator](https://github.com/Behat/Transliterator/blob/HEAD/src/Behat/Transliterator/Transliterator.php) to transform your names into slugs, but handling clashing of names is up to you.
Of course, you should implement `NamerInterface`, as mentioned in docs

**Comment by Koc** [comment]
@roberto910907 for what? Use `HashNamer` and save original file name into database.

**Comment by roberto910907** [comment]
@Koc That's exactly what I was thinking, so what is the best way to save the original file name?, using @PrePersist or any other Lifecycle of doctrine, or directly inside `setImagenFile(File $imagen = null) method`?

**Comment by Koc** [comment]
https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/usage.md

> The UploadableField annotation has a few options. They are as follows:...
