### ISSUE TITLE
Viewing Security

### ISSUE THREAD

**Issue by jMoulis** [dustin10/VichUploaderBundle#712]
Hi,
I would like to know if there is a with vich to prevent direct file access?
For example: I use the generate url in an anchor tag then if you are not logged you can't generate any url, but if you are and then copy/paste the anchor href and send it to anyone, they will be able to see or download the file.
Have you got any tips?
Thx

**Comment by Koc** [comment]
You can store files outside document root (`web/` folder by default) and serving they by controller using download handler https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/downloads/serving_files_with_a_controller.md . And check permissions inside action.

One drawback is that serving files with php is not good idea - it may cause high load and memory usage. It should be done by xsendfle, but currently this bundle is not supports it. But for typical application it is ok.

**Comment by jMoulis** [comment]
Thanks for replying, but I think I'm too dumb... I don't get how serving files with controller works. I dump to see what is the response and I have StreamedResponse that don't know how to use.

**Comment by Koc** [comment]
Take a look at http://symfony.com/doc/current/controller.html . Your controller should return response object.

**Comment by jMoulis** [comment]
Thanks. Actually what I don't understand is how to use the StreamedResponse to provide an url to the anchor tag on my template, if the user is allowed
