### ISSUE TITLE
FileName in database become null when update object without update file 

### ISSUE THREAD

**Issue by haithemkdous** [dustin10/VichUploaderBundle#713]
I used vichUploaderBundle to upload a file, all works fine , but when i update the object without changing the input file , the fileName in the data base become null , why ?? 
this is some code from my entity.php

```php
    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $file
     *
     * @return Absence
     */
    public function setFichier(File $file = null)
    {
        $this->fichier = $file;
        if ($file instanceof UploadedFile) {
            $this->updatedAt =new \DateTime('now');
        }

        return $this;
    }
    /**
     * @return File|null
     */
    public function getFichier()
    {
        return $this->fichier;
    }
```

**Comment by Koc** [comment]
seems like bug, shouldn't override

https://github.com/dustin10/VichUploaderBundle/blob/master/Handler/UploadHandler.php#L85-L88

**Comment by Koc** [comment]
@haithemkdous can you reproduce bug on small code, like make fork of symfony-standard?

**Comment by Koc** [comment]
ping @haithemkdous

**Comment by garak** [comment]
Closing for missing feedback. Feel free to re-open.

**Comment by erwan-haquet** [comment]
Have the same problem here, if i resume : 
* I upload a file -> OK
* I update the entity, but i don't change the file -> NOT OK, the file property is set to `null`, but it should not be override.

I tried you'r fix @garak : 
> You should move $this->fichier = $file; inside your if

But if i do that, when i really want to delete the file, the setter will not trigger the `$this->fichier = $file;`. So the file is well removed from filesystem, but the field property is not changed.

**Comment by Koc** [comment]
@erwan-haquet please create fork of symfony-standard with env for reproduce this issue.

**Comment by erwan-haquet** [comment]
@Koc I've just realized (when creating the fork) that my issue was not linked to this one. 
I just did a mistake when creating entities, the `file` property was mapped to entity metadata, and i was looking to this field.
Thanx for your quick reply.
