### ISSUE TITLE
Use symfony-phpunit-bridge

### ISSUE THREAD

**Issue by Koc** [dustin10/VichUploaderBundle#716]
http://symfony.com/doc/current/components/phpunit_bridge.html

**Comment by garak** [comment]
I'm not sure that it's working with phpunit 6, unless using dev-master

**Comment by garak** [comment]
Now the bridge is stable, so we could use it.
What's the use case?

**Comment by Koc** [comment]
Trigger and check deprecations https://travis-ci.org/dustin10/VichUploaderBundle/jobs/243216587

**Comment by garak** [comment]
LGTM. Feel free to open a PR

**Comment by garak** [comment]
Done in #727
