### ISSUE TITLE
VichUploadType :  Variable "download_uri" does not exist.

### ISSUE THREAD

**Issue by pierre-robentz-cassion** [dustin10/VichUploaderBundle#719]
Hi everyone ,
I am trying to use vichuploadbundle . In my entityType , I use `        $builder
        ->add('imageFile', VichImageType::class,[
            'required' => false,
            'allow_delete' => true,
            'download_label' => '...',
            'download_uri' => true,
            'image_uri' => true,
            'imagine_pattern' => '...'
        ]);`
When I try to add or edit my entity , it gives me this error : **Variable "download_uri" does not exist.**
`            {% if image_uri %}
                <a href="{{ image_uri }}"><img src="{{ image_uri }}" alt="" /></a>
            {% endif %}
            {% if download_uri %}
                <a href="{{ download_uri }}">{{ translation_domain is same as(false) ? download_label : download_label|trans({}, translation_domain) }}</a>
            {% endif %}
        </div>`
. 
Please help me solve this issue.
Thanks in advance.

**Comment by Koc** [comment]
I see the bug, thanx, will open PR for fix it

**Comment by Koc** [comment]
@pierre-robentz-cassion please test with referenced PR

**Comment by pierre-robentz-cassion** [comment]
Ok I will do it

**Comment by pierre-robentz-cassion** [comment]
It works now @Koc . Thx a lot.
