### ISSUE TITLE
Yaml Config class name incorrect

### ISSUE THREAD

**Issue by harmstyler** [dustin10/VichUploaderBundle#721]
As of the latest release, 1.6.0, the Yaml upload mappings no longer work. It appears that the generated class name built by the bundle is no longer correct.

For example, running the following command in `bin/console vich:mapping:list-classes` returns different results depending tag I'm on.

1.5.3: `AppBundle\Entity\Avatar`
1.6.0: `AppBundle\Avatar`

I tried to track down the breaking change but the 1.6.0 release was rather large, and not entirely captured in the release docs. I believe, however, the offending change happened in this commit: e6706b22b98e3d52f8267d7b2e4095adc633dbac, though I'm not positive..

**Comment by Koc** [comment]
Referenced commit fixes another bug: #704. Can you create fork of symfony-standard edition with reproducible env for this bug?

**Comment by Koc** [comment]
Also this changes covered with new tests https://github.com/dustin10/VichUploaderBundle/commit/c40cdae8371044ebe010b2c25ad3f38525e1ee70 . Could you provide own fixtures and tests?

**Comment by flochntrl** [comment]
I have the same problem with Symfony 3.2.9

**Comment by Koc** [comment]
again, please, create small piece of reproducible code for this bug by forking symfony-standard

**Comment by Koc** [comment]
@harmstyler, @flochntrl can you check #728, does it solves your problem?

**Comment by flochntrl** [comment]
@Koc LGTM ! Thanks :+1:

**Comment by shairyar** [comment]
I am running into the same issue, I have provided more details [here](https://stackoverflow.com/questions/44653118/symfony-vichuploaderbundle-not-working-after-composer-update) incase it helps. This bundle seems to be a dependency of another bundle i am using `presta/image-bundle` its not listed in my composer.json file so how do i downgrade it to 1.5.3
