### ISSUE TITLE
Non required file leads to either an SQL insert error or a cascade persist error

### ISSUE THREAD

**Issue by florentdestremau** [dustin10/VichUploaderBundle#730]
Hi,

I want my form to present an optional logo field. So i have added a image type, but if i submit, i either get an sql error because doctrine tries to persist an image with no name, or if i remove the cascade persist i get an error too because cascading is not defined. The form can't ignore an empty file field it seems. What did I miss ?

**Comment by garak** [comment]
Are you using Vich image type?

**Comment by florentdestremau** [comment]
This is my setup:
```
// ImageType -> Image is a entity representing a Vich\Uploadable Image
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'imageFile',
                VichImageType::class,
                [
                    'label'         => false,
                    'download_link' => false,
                    'allow_delete'  => true,
                    'required'      => false,
                ]
            );
    }
```
```
// Image.php
 * @Vich\Uploadable()
class Image {
/**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="event_image", fileNameProperty="name")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;
}
```

```
// Company Type
            ->add('logo', ImageType::class)

```

**Comment by florentdestremau** [comment]
My objective is to allow people to upload OR NOT a logo when creating a company instance. So far so good when they do upload. But when I submit an empty field, I get the following error if I don't set any cascade behavior on `$logo`:
```
A new entity was found through the relationship 'AppBundle\Entity\Company#logo' that was not configured to cascade persist operations for entity: . To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).
```

And if I set cascade=persist I get this one:
```
An exception occurred while executing 'INSERT INTO image (id, name, updatedAt, standard_picture, thumbnail, event_id, category_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [5, null, null, null, null, null, null, null]:

SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "name" violates not-null constraint
DETAIL: Failing row contains (5, null, null, null, null, null, null, null).
```

**Comment by garak** [comment]
The form above is the form for Company or the form for Logo?

**Comment by florentdestremau** [comment]
The `CompanyType`:
```
$builder
            ->add(
                'name',
                null,
                ["required":true]
            )
            ->add(
                'website',
            )
            ->add(
                'address',
            )
            ->add('logo', ImageType::class)
            ->add('Enregistrer', SubmitType::class);
```

**Comment by garak** [comment]
So, you can't use ImageType directly like that. You need to define a LogoType with ImageType inside and use LogoType where you're currently usig ImageType

**Comment by florentdestremau** [comment]
What would the LogoType contain ? The whole purpose of the Image entity is to be an already configured object to be added to any entity.

**Comment by garak** [comment]
As I told you, LogoType should contain an ImageType, just because your image is inside Image entity and it's not inside Company entity.
If you want to use ImageType directly inside CompanyType, you need to remove Image entity and move vich-related fields inside Company entity

**Comment by florentdestremau** [comment]
I tried this, and now i get a
```
Expected argument of type "Symfony\Component\HttpFoundation\File\File or null", "AppBundle\Entity\Image" given
```

**Comment by florentdestremau** [comment]
I'm not sure this would be the solution. The real question is :
why can't vichuploaderbundle simply do nothing if the file is empty ? :thinking:

**Comment by garak** [comment]
You need to make your forms consistent with your model.
Otherwise, there's nothing this bundle (nor any other bundle) can do

**Comment by florentdestremau** [comment]
ended up doing an ImageTrait do add the image fields to my Company...
Works.

I still don't get why another intermediary form would solve my problem..
