### ISSUE TITLE
How have Image_id for change the name ?

### ISSUE THREAD

**Issue by razbounak** [dustin10/VichUploaderBundle#731]
Hello,

I have a custom namer and I want have the future id of my image for change the name.

`
    public function name($object, PropertyMapping $mapping)
    {
        $productId = $object->getProduct()->getId();
        $file = $object->getImageFile();
        $extension = $file->getExtension();

       // Here
        $imageId = ?;

        return $productId . '-' . $imageId  . '.' . $extension;
    }
`

Thanks for your help

**Comment by garak** [comment]
Duplicate of #14

**Comment by Koc** [comment]
Use hash namer :)
