### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by IvanVishanov** [dustin10/VichUploaderBundle#734]
Problem 1
    - Installation request for vich/uploader-bundle ^1.6 -> satisfiable by vich/uploader-bundle[1.6.0].
    - Conclusion: remove doctrine/annotations v1.2.7
    - Conclusion: don't install doctrine/annotations v1.2.7
    - vich/uploader-bundle 1.6.0 requires doctrine/annotations ^1.3 -> satisfiable by doctrine/annotations[v1.3.0, v1.3.1, v1.4
.0].
    - Can only install one of: doctrine/annotations[v1.3.0, v1.2.7].
    - Can only install one of: doctrine/annotations[v1.3.1, v1.2.7].
    - Can only install one of: doctrine/annotations[v1.4.0, v1.2.7].
    - Installation request for doctrine/annotations (locked at v1.2.7) -> satisfiable by doctrine/annotations[v1.2.7].

**Comment by garak** [comment]
So, do not lock doctrine/annotations to v1.2.7.
If that's not in your `require` section of composer.json, you can run `composer why doctrine/annotations`

**Comment by garak** [comment]
Hope you solved that. Otherwise, feel free to re-open
