### ISSUE TITLE
Allow Vich uploader to use files that aren't uploaded?

### ISSUE THREAD

**Issue by gonzalovilaseca** [dustin10/VichUploaderBundle#735]
We have a case where we want to use all of vich's behind the scenes magic with files that are already in the filesystem (for image import for example) eg:
```
...
$asset = New Asset();
$asset->setAssetFile(new UploadedFile($filepath, $image->getFilename()));
 $this->entityManager->persist($asset);
$this->entityManager->flush();
```
But it doesn't work as `/vich/uploader-bundle/Handler/UploadHandler.php` line 120 requires a `UploadedFile`, and then when moving the file, `UploadedFile` method `isValid` fails because we simulated an `UploadedFile`, it wasn't a real uploaded file.

Would it be good to have a flag to allow instances of `File` too? I can work on a PR for it.

**Comment by garak** [comment]
I think it could be simpler in your case to extend UploadHandler and to override `vich_uploader.upload_handler` service definition.
I don't think it could make sense to support non-uploaded files in a bundle named "Uploader"

**Comment by gonzalovilaseca** [comment]
Ok, will do that, thanks.
Thing is, it worked fine with gauffrette, but when we switched to Symfony's filesystem we got this issue, so in fact your bundle also works with non uploaded files in some cases.

**Comment by gonzalovilaseca** [comment]
I would also need to override `AbstractStorage` as it checks for `UploadedFile` there too..

**Comment by Koc** [comment]
Emulate `UploadedFile` using sixth parameter (`test=true`):

```php
$pathToTmpImageFile= copy('...', '...');
$imageObject = new UploadedFile($pathToTmpImageFile, $imageName, $mimeType, filesize($pathToTmpImageFile), null, true);

$entity->setUploadedFile($imageObject);

$em->persist($entity);
$em->flush();
```

**Comment by gonzalovilaseca** [comment]
Yes, that was another option but it felt wrong using a `test` flag in production...thanks!

**Comment by Koc** [comment]
It's ok for emulating file uploading.

**Comment by Koc** [comment]
@gonzalovilaseca feel free open PR with adding some howto section in docs https://github.com/dustin10/VichUploaderBundle/tree/master/Resources/doc which would help people solve issues like your.
