### ISSUE TITLE
Variable "download_uri" does not exist.

### ISSUE THREAD

**Issue by finkbg** [dustin10/VichUploaderBundle#737]
Cannot render form, because of this error. Form config:

`->add('cover', VichImageType::class, ['required' => false, 'label_attr' => ['class' => 'upload btn btn-sm btn-info fa fa-2x fa-picture-o float-xs-right'], 'label' => false, 'attr' => ['class' => 'btn btn-default btn-file hidden-xs-up']])`

**This happens with VichImageType only, it's ok with VichFileType.**

Even when I explicitly provide a 'download_uri' in formBuilder, the same error persists. Apparently, 'download_uri' is not passed for some reason.

**Comment by garak** [comment]
You should provide some more informations about your configuration

**Comment by garak** [comment]
Nice catch @davidgorges 
I'll try to see if I can release a new tag with the fix

**Comment by garak** [comment]
Done
