### ISSUE TITLE
Save EmbeddedFile properties into database

### ISSUE THREAD

**Issue by sebastianvirlan** [dustin10/VichUploaderBundle#739]
I tried to follow the documentation from here:

https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/usage.md

I implemented all the steps the file get uploaded, but in database it doesn't save all the file info:

![u9ugo](https://user-images.githubusercontent.com/179866/27823125-51a731e8-60a8-11e7-975d-243bb47ac56e.png)

So i have:

    /**
     * @Vich\UploadableField(mapping="feedback_files", fileNameProperty="embeddedFile.name", size="embeddedFile.size", mimeType="embeddedFile.mimeType", originalName="embeddedFile.originalName")
     * @var File $file
     */
    private $file;

    /**
     * @ORM\Embedded(class="Vich\UploaderBundle\Entity\File")
     *
     * @var EmbeddedFile
     */
    private $embeddedFile;

    /**
     * @param EmbeddedFile $embedded_file
     */
    public function setEmbeddedFile(EmbeddedFile $embedded_file)
    {
        $this->embedded_file = $embedded_file;
    }

    /**
     * @return EmbeddedFile
     */
    public function getEmbeddedFile()
    {
        // print_r($this->embedded_file);
        
        return $this->embedded_file;
    }

and in controller when I set the image:

    $feedback = new Feedback();
    $feedback->setTitle($title);
    ............................
    $feedbackFile = new FeedbackFile();
    $feedbackFile->setFile($file);
    $em->persist($feedbackFile);
    $feedback->setFile($feedbackFile);
    $em->persist($feedback);
    $em->flush();

Is there any other step that I am missing?
If I uncomment the `print_r` from `getEmbeddedFile` I get in console:

    Vich\UploaderBundle\Entity\File Object
    (
        [name:protected] => 
        [originalName:protected] => 
        [mimeType:protected] => 
        [size:protected] => 
    )
    Vich\UploaderBundle\Entity\File Object
    (
        [name:protected] => 595b4cd4b7e95492892222.jpg
        [originalName:protected] => 
        [mimeType:protected] => 
        [size:protected] => 
    )
    Vich\UploaderBundle\Entity\File Object
    (
        [name:protected] => 595b4cd4b7e95492892222.jpg
        [originalName:protected] => 
        [mimeType:protected] => 
        [size:protected] => 1363753
    )
    Vich\UploaderBundle\Entity\File Object
    (
        [name:protected] => 595b4cd4b7e95492892222.jpg
        [originalName:protected] => 
        [mimeType:protected] => image/jpeg
        [size:protected] => 1363753
    )
    Vich\UploaderBundle\Entity\File Object
    (
        [name:protected] => 595b4cd4b7e95492892222.jpg
        [originalName:protected] => island-wallpaper-7.jpg
        [mimeType:protected] => image/jpeg
        [size:protected] => 1363753
    )
and if I put a `print` in `setEmbeddedFile` it never get executed.
--------------------
Sorry was my fault, `private $embeddedFile;` => `private $embedded_file;`

**Comment by garak** [comment]
Did you add `@Vich\Uploadable` on both entities?

**Comment by sebastianvirlan** [comment]
Sorry @garak was my fault, I updated the post. Can be deleted or closed.

**Comment by garak** [comment]
No problem!
