### ISSUE TITLE
Encryption support?

### ISSUE THREAD

**Issue by Yippy** [dustin10/VichUploaderBundle#740]
I've already implemented "Serving files with a controller", but I would like to know if there is a built-in functionality for any uploaded files to be encrypted.

This will stop server admin\hackers browsing through files that does not relate to them, providing more security.

**Comment by garak** [comment]
I'm afraid that's a bit outside the scope of this bundle

**Comment by Yippy** [comment]
Thanks for the quick response, just thought I've asked
