### ISSUE TITLE
Twig_Error_Runtime: "Variable "download_uri" does not exist."

### ISSUE THREAD

**Issue by Zuhayer** [dustin10/VichUploaderBundle#741]
Symfony version 3.1.10
vich/uploader-bundle 1.6.0

I have getting this error in log:
[2017-07-04 11:30:27] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "Variable "download_uri" does not exist." at D:\wamp3\www\pp\vendor\vich\uploader-bundle\Resources\views\Form\fields.html.twig line 37 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"download_uri\" does not exist. at D:\\wamp3\\www\\pp\\vendor\\vich\\uploader-bundle\\Resources\\views\\Form\\fields.html.twig:37)"} []

    {% block vich_image_widget %}
        {% spaceless %}
        <div class="vich-image">
            {{ form_widget(form.file) }}
            {% if form.delete is defined %}
                {{ form_row(form.delete) }}
            {% endif %}

            {% if image_uri %}
                <a href="{{ image_uri }}"><img src="{{ image_uri }}" alt="" /></a>
            {% endif %}
    // Line 37 //        {% if download_uri %} 
                <a href="{{ download_uri }}">{{ translation_domain is same as(false) ? download_label : download_label|trans({}, translation_domain) }}</a>
            {% endif %}
        </div>
    {% endspaceless %}
    {% endblock %}`

Situation:
Project working fine on live server. 
I installed a new instance of WAMP server in dev environment, and after cloning the project again this error shown. 

Kindly let me know what could be the issue.

**Comment by garak** [comment]
Please upgrade bundle to `1.6.1`

**Comment by Koc** [comment]
@garak 1.6.1 not contains fix for this, looks like you created tag for some of earlier commits, not for current head

**Comment by garak** [comment]
I had to exclude some unrelated commits present in master. Anyway, [this](https://github.com/dustin10/VichUploaderBundle/commit/e7a1118c5f824e3c1cff7b2aea34ee394cc72dfa#diff-61cf138b1eea6444653e4ae361447fbdR59) should be the fix in 1.6.1

**Comment by Zuhayer** [comment]
Upgraded to 1.6.1; Fixed the issue; Thanks

**Comment by ZarakObama** [comment]
does upgrade resuire php >7 ?

**Comment by carteur007** [comment]
Hi! i have a same issue when i try to upload file whith VichUploaderundle this is  the message: Variable "image_uri" does not exist

**Comment by carteur007** [comment]
First scren
![twig_error01](https://user-images.githubusercontent.com/45242676/66240445-f6e72000-e6fc-11e9-9e5f-d1cb4360967b.png)

**Comment by carteur007** [comment]
Second  scren
![twig_error02](https://user-images.githubusercontent.com/45242676/66240510-24cc6480-e6fd-11e9-831a-e5e6f52eddd6.png)
My VichImageType Class:

**Comment by carteur007** [comment]
My VichImageType Class:
[v01.txt](https://github.com/dustin10/VichUploaderBundle/files/3692386/v01.txt)
My VichImage Class:
[v01.txt](https://github.com/dustin10/VichUploaderBundle/files/3692391/v01.txt)
My vich_uploader Config:

**Comment by carteur007** [comment]
My vich_uploader Config:
[v01.txt](https://github.com/dustin10/VichUploaderBundle/files/3692399/v01.txt)

**Comment by carteur007** [comment]
Please i need your help i have Upgraded to 1.6.1; But the issue is the same.
Help me to solve the issue; Thanks

**Comment by carteur007** [comment]
Thans i solve the issue by adding  'prototype' => false in my ProjectType Class

ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',TextType::class,[
                'attr'=>[
                    'style' => 'background-color:#212529;color:#fff;',
                ]
            ])
            ->add('durree')
            ->add('dateDebut',DateTimeType::class,[
                'widget' => 'single_text',
                'html5' => false,
            ])
            ->add('dateFin',DateTimeType::class,[
                'widget' => 'single_text',
                'html5' => false,
            ])
            ->add('description',TextType::class,[
                'attr'=>[
                    'style' => 'background-color:#212529;color:#fff;',
                ]
            ])
            ->add('cout')
            ->add('createurProject',EntityType::class,[
                'class' => User::class,
                'choice_label' => 'username',
                'multiple' => false,
                'expanded' => false,
                'attr'  =>
                    [
                        'class' => 'form-control',
                        'style' => 'width: 100%;',
                    ],
            ])
            ->add('vichImages',CollectionType::class,[
                'entry_type' => VichImageType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'prototype' => false,
                'by_reference' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}
VichImageTtype.php
<?php

namespace App\Form;

use App\Entity\Project;
use App\Entity\VichImage;
use Symfony\Bundle\FrameworkBundle\Routing\Router;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;

class VichImageType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //$router = new Router(Container::class,$this,null,null,null,null);
        $builder
            ->add('file',VichFileType::class,[
                'required' => false,
                'label' => 'Fichiers:',
                'allow_delete' => true,
                'by_reference' => false,
                'allow_file_upload' => true,
                'download_uri' => false,
                'image_uri' => true,
                'imagine_pattern' => null,
                'attr' =>[
                    'enctype' => 'multipart/form-data'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => \App\Entity\VichImage::class,
            'translation_domain' => 'forms'
        ]);
    }
}

VichImage.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @Vich\Uploadable
 * @ORM\Table(name="project_image")
 * @ORM\Entity(repositoryClass="App\Repository\VichImageRepository")
 *
 */
class VichImage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Project", inversedBy="vichImages")
     */
    private $project;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(max=255)
     * @var string
     */
    private $image;
    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="images", fileNameProperty="image")
     * @Assert\File(
     * maxSize="1000k",
     * maxSizeMessage="Le fichier excède 1000Ko.",
     * mimeTypes={"image/png", "image/jpeg", "image/jpg", "image/svg+xml", "image/gif"},
     * mimeTypesMessage= "formats autorisés: png, jpeg, jpg, svg, gif"
     * )
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $updateAt;
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tmpFile;
    /**
     * @return string
     */
    public function __toString(){
        return $this->image;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): self
    {
        $this->project = $project;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
     * @param string $image_name
     * @return VichImage
     */
    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
    /**
     * @return mixed
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $image
     * @return VichImage
     * @throws \Exception
     */
    public function setImageFile(?File $image = null):self
    {
        $this->imageFile = $image;

        if($image)/*instanceof UploadedFile && null !== $imageFile)*/{
            $this->updateAt = new \DateTime('now', new \DateTimeZone('ETC/UTC'));
        }

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->updateAt;
    }

    public function setUpdateAt(\DateTimeInterface $updateAt): self
    {
        $this->updateAt = $updateAt;

        return $this;
    }
    /*
    * Set tmpFile
    * @return Image
    */
    public function setTmpFile($tmpFile)
    {
        $this->tmpFile = $tmpFile;
        return $this;
    }

    /*
    * Get tmpFile
    * @return string
    */
    public function getTmpFile()
    {
        return $this->tmpFile;
    }
}

Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;
    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;
    /**
     * @ORM\Column(type="integer")
     */
    private $durree;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateDebut;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateFin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $cout;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="project")
     * @ORM\JoinColumn(nullable=false)
     */
    private $projectImages;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="projects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $createurProject;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tache", mappedBy="project", orphanRemoval=true)
     */
    private $taches;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\VichImage", mappedBy="project")
     */
    private $vichImages;



    public function __construct()
    {
        $this->projectImages = new ArrayCollection();
        $this->taches = new ArrayCollection();
        $this->vichImages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     * @return Project
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
        return $this;
    }

    public function getDurree(): ?int
    {
        return $this->durree;
    }

    public function setDurree(int $durree): self
    {
        $this->durree = $durree;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(?\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(?\DateTimeInterface $dateFin): self
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCout(): ?int
    {
        return $this->cout;
    }

    public function setCout(?int $cout): self
    {
        $this->cout = $cout;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getProjectImages(): Collection
    {
        return $this->projectImages;
    }

    public function addProjectImage(Image $projectImage): self
    {
        if (!$this->projectImages->contains($projectImage)) {
            $this->projectImages[] = $projectImage;
            $projectImage->setProject($this);
        }

        return $this;
    }

    public function removeProjectImage(Image $projectImage): self
    {
        if ($this->projectImages->contains($projectImage)) {
            $this->projectImages->removeElement($projectImage);
            // set the owning side to null (unless already changed)
            if ($projectImage->getProject() === $this) {
                $projectImage->setProject(null);
            }
        }

        return $this;
    }

    public function getCreateur(): ?User
    {
        return $this->createur;
    }

    public function setCreateur(User $createur): self
    {
        $this->createur = $createur;

        return $this;
    }

    public function getCreateurProject(): ?User
    {
        return $this->createurProject;
    }

    public function setCreateurProject(?User $createurProject): self
    {
        $this->createurProject = $createurProject;

        return $this;
    }

    /**
     * @return Collection|Tache[]
     */
    public function getTaches(): Collection
    {
        return $this->taches;
    }

    public function addTach(Tache $tach): self
    {
        if (!$this->taches->contains($tach)) {
            $this->taches[] = $tach;
            $tach->setProject($this);
        }

        return $this;
    }

    public function removeTach(Tache $tach): self
    {
        if ($this->taches->contains($tach)) {
            $this->taches->removeElement($tach);
            // set the owning side to null (unless already changed)
            if ($tach->getProject() === $this) {
                $tach->setProject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|VichImage[]
     */
    public function getVichImages(): Collection
    {
        return $this->vichImages;
    }

    public function addVichImage(VichImage $vichImage): self
    {
        if (!$this->vichImages->contains($vichImage)) {
            $this->vichImages[] = $vichImage;
            $vichImage->setProject($this);
        }

        return $this;
    }

    public function removeVichImage(VichImage $vichImage): self
    {
        if ($this->vichImages->contains($vichImage)) {
            $this->vichImages->removeElement($vichImage);
            // set the owning side to null (unless already changed)
            if ($vichImage->getProject() === $this) {
                $vichImage->setProject(null);
            }
        }

        return $this;
    }

}

**Comment by carteur007** [comment]
`Thans i solve the issue by adding 'prototype' => false in my ProjectType Class

ProjectType.php
-add('name',TextType::class,[ 'attr'=>[ 'style' => 'background-color:#212529;color:#fff;', ] ]) ->add('durree') ->add('dateDebut',DateTimeType::class,[ 'widget' => 'single_text', 'html5' => false, ]) ->add('dateFin',DateTimeType::class,[ 'widget' => 'single_text', 'html5' => false, ]) ->add('description',TextType::class,[ 'attr'=>[ 'style' => 'background-color:#212529;color:#fff;', ] ]) ->add('cout') ->add('createurProject',EntityType::class,[ 'class' => User::class, 'choice_label' => 'username', 'multiple' => false, 'expanded' => false, 'attr' => [ 'class' => 'form-control', 'style' => 'width: 100%;', ], ]) ->add('vichImages',CollectionType::class,[ 'entry_type' => VichImageType::class, 'allow_add' => true, 'allow_delete' => true, 'prototype' => false, 'by_reference' => false, ]) ; } public function configureOptions(OptionsResolver $resolver) { $resolver->setDefaults([ 'data_class' => Project::class, ]); } } VichImageTtype.php add('file',VichFileType::class,[ 'required' => false, 'label' => 'Fichiers:', 'allow_delete' => true, 'by_reference' => false, 'allow_file_upload' => true, 'download_uri' => false, 'image_uri' => true, 'imagine_pattern' => null, 'attr' =>[ 'enctype' => 'multipart/form-data' ] ]) ; } public function configureOptions(OptionsResolver $resolver) { $resolver->setDefaults([ 'data_class' => \App\Entity\VichImage::class, 'translation_domain' => 'forms' ]); } } VichImage.php image; } public function getId(): ?int { return $this->id; } public function getProject(): ?Project { return $this->project; } public function setProject(?Project $project): self { $this->project = $project; return $this; } public function getImage(): ?string { return $this->image; } /** * @param string $image_name * @return VichImage */ public function setImage(string $image): self { $this->image = $image; return $this; } /** * @return mixed */ public function getImageFile() { return $this->imageFile; } /** * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $image * @return VichImage * @throws \Exception */ public function setImageFile(?File $image = null):self { $this->imageFile = $image; if($image)/*instanceof UploadedFile && null !== $imageFile)*/{ $this->updateAt = new \DateTime('now', new \DateTimeZone('ETC/UTC')); } return $this; } public function getUpdateAt(): ?\DateTimeInterface { return $this->updateAt; } public function setUpdateAt(\DateTimeInterface $updateAt): self { $this->updateAt = $updateAt; return $this; } /* * Set tmpFile * @return Image */ public function setTmpFile($tmpFile) { $this->tmpFile = $tmpFile; return $this; } /* * Get tmpFile * @return string */ public function getTmpFile() { return $this->tmpFile; } } Project.php projectImages = new ArrayCollection(); $this->taches = new ArrayCollection(); $this->vichImages = new ArrayCollection(); } public function getId(): ?int { return $this->id; } public function getName(): ?string { return $this->name; } public function setName(string $name): self { $this->name = $name; return $this; } /** * @return mixed */ public function getSlug() { return $this->slug; } /** * @param mixed $slug * @return Project */ public function setSlug($slug) { $this->slug = $slug; return $this; } public function getDurree(): ?int { return $this->durree; } public function setDurree(int $durree): self { $this->durree = $durree; return $this; } public function getDateDebut(): ?\DateTimeInterface { return $this->dateDebut; } public function setDateDebut(?\DateTimeInterface $dateDebut): self { $this->dateDebut = $dateDebut; return $this; } public function getDateFin(): ?\DateTimeInterface { return $this->dateFin; } public function setDateFin(?\DateTimeInterface $dateFin): self { $this->dateFin = $dateFin; return $this; } public function getDescription(): ?string { return $this->description; } public function setDescription(string $description): self { $this->description = $description; return $this; } public function getCout(): ?int { return $this->cout; } public function setCout(?int $cout): self { $this->cout = $cout; return $this; } /** * @return Collection|Image[] */ public function getProjectImages(): Collection { return $this->projectImages; } public function addProjectImage(Image $projectImage): self { if (!$this->projectImages->contains($projectImage)) { $this->projectImages[] = $projectImage; $projectImage->setProject($this); } return $this; } public function removeProjectImage(Image $projectImage): self { if ($this->projectImages->contains($projectImage)) { $this->projectImages->removeElement($projectImage); // set the owning side to null (unless already changed) if ($projectImage->getProject() === $this) { $projectImage->setProject(null); } } return $this; } public function getCreateur(): ?User { return $this->createur; } public function setCreateur(User $createur): self { $this->createur = $createur; return $this; } public function getCreateurProject(): ?User { return $this->createurProject; } public function setCreateurProject(?User $createurProject): self { $this->createurProject = $createurProject; return $this; } /** * @return Collection|Tache[] */ public function getTaches(): Collection { return $this->taches; } public function addTach(Tache $tach): self { if (!$this->taches->contains($tach)) { $this->taches[] = $tach; $tach->setProject($this); } return $this; } public function removeTach(Tache $tach): self { if ($this->taches->contains($tach)) { $this->taches->removeElement($tach); // set the owning side to null (unless already changed) if ($tach->getProject() === $this) { $tach->setProject(null); } } return $this; } /** * @return Collection|VichImage[] */ public function getVichImages(): Collection { return $this->vichImages; } public function addVichImage(VichImage $vichImage): self { if (!$this->vichImages->contains($vichImage)) { $this->vichImages[] = $vichImage; $vichImage->setProject($this); } return $this; } public function removeVichImage(VichImage $vichImage): self { if ($this->vichImages->contains($vichImage)) { $this->vichImages->removeElement($vichImage); // set the owning side to null (unless already changed) if ($vichImage->getProject() === $this) { $vichImage->setProject(null); } } return $this; } } `

**Comment by carteur007** [comment]
`<h1>My</h1>`

**Comment by carteur007** [comment]
`Thans i solve the issue by adding 'prototype' => false in my ProjectType Class

ProjectType.php
-add('name',TextType::class,[ 'attr'=>[ 'style' => 'background-color:#212529;color:#fff;', ] ]) ->add('durree') ->add('dateDebut',DateTimeType::class,[ 'widget' => 'single_text', 'html5' => false, ]) ->add('dateFin',DateTimeType::class,[ 'widget' => 'single_text', 'html5' => false, ]) ->add('description',TextType::class,[ 'attr'=>[ 'style' => 'background-color:#212529;color:#fff;', ] ]) ->add('cout') ->add('createurProject',EntityType::class,[ 'class' => User::class, 'choice_label' => 'username', 'multiple' => false, 'expanded' => false, 'attr' => [ 'class' => 'form-control', 'style' => 'width: 100%;', ], ]) ->add('vichImages',CollectionType::class,[ 'entry_type' => VichImageType::class, 'allow_add' => true, 'allow_delete' => true, 'prototype' => false, 'by_reference' => false, ]) ; } public function configureOptions(OptionsResolver $resolver) { $resolver->setDefaults([ 'data_class' => Project::class, ]); } } VichImageTtype.php add('file',VichFileType::class,[ 'required' => false, 'label' => 'Fichiers:', 'allow_delete' => true, 'by_reference' => false, 'allow_file_upload' => true, 'download_uri' => false, 'image_uri' => true, 'imagine_pattern' => null, 'attr' =>[ 'enctype' => 'multipart/form-data' ] ]) ; } public function configureOptions(OptionsResolver $resolver) { $resolver->setDefaults([ 'data_class' => \App\Entity\VichImage::class, 'translation_domain' => 'forms' ]); } } VichImage.php image; } public function getId(): ?int { return $this->id; } public function getProject(): ?Project { return $this->project; } public function setProject(?Project $project): self { $this->project = $project; return $this; } public function getImage(): ?string { return $this->image; } /** * @param string $image_name * @return VichImage / public function setImage(string $image): self { $this->image = $image; return $this; } /* * @return mixed / public function getImageFile() { return $this->imageFile; } /* * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $image * @return VichImage * @throws \Exception / public function setImageFile(?File $image = null):self { $this->imageFile = $image; if($image)/instanceof UploadedFile && null !== $imageFile)/{ $this->updateAt = new \DateTime('now', new \DateTimeZone('ETC/UTC')); } return $this; } public function getUpdateAt(): ?\DateTimeInterface { return $this->updateAt; } public function setUpdateAt(\DateTimeInterface $updateAt): self { $this->updateAt = $updateAt; return $this; } / * Set tmpFile * @return Image / public function setTmpFile($tmpFile) { $this->tmpFile = $tmpFile; return $this; } / * Get tmpFile * @return string / public function getTmpFile() { return $this->tmpFile; } } Project.php projectImages = new ArrayCollection(); $this->taches = new ArrayCollection(); $this->vichImages = new ArrayCollection(); } public function getId(): ?int { return $this->id; } public function getName(): ?string { return $this->name; } public function setName(string $name): self { $this->name = $name; return $this; } /* * @return mixed / public function getSlug() { return $this->slug; } /* * @param mixed $slug * @return Project / public function setSlug($slug) { $this->slug = $slug; return $this; } public function getDurree(): ?int { return $this->durree; } public function setDurree(int $durree): self { $this->durree = $durree; return $this; } public function getDateDebut(): ?\DateTimeInterface { return $this->dateDebut; } public function setDateDebut(?\DateTimeInterface $dateDebut): self { $this->dateDebut = $dateDebut; return $this; } public function getDateFin(): ?\DateTimeInterface { return $this->dateFin; } public function setDateFin(?\DateTimeInterface $dateFin): self { $this->dateFin = $dateFin; return $this; } public function getDescription(): ?string { return $this->description; } public function setDescription(string $description): self { $this->description = $description; return $this; } public function getCout(): ?int { return $this->cout; } public function setCout(?int $cout): self { $this->cout = $cout; return $this; } /* * @return Collection|Image[] / public function getProjectImages(): Collection { return $this->projectImages; } public function addProjectImage(Image $projectImage): self { if (!$this->projectImages->contains($projectImage)) { $this->projectImages[] = $projectImage; $projectImage->setProject($this); } return $this; } public function removeProjectImage(Image $projectImage): self { if ($this->projectImages->contains($projectImage)) { $this->projectImages->removeElement($projectImage); // set the owning side to null (unless already changed) if ($projectImage->getProject() === $this) { $projectImage->setProject(null); } } return $this; } public function getCreateur(): ?User { return $this->createur; } public function setCreateur(User $createur): self { $this->createur = $createur; return $this; } public function getCreateurProject(): ?User { return $this->createurProject; } public function setCreateurProject(?User $createurProject): self { $this->createurProject = $createurProject; return $this; } /* * @return Collection|Tache[] / public function getTaches(): Collection { return $this->taches; } public function addTach(Tache $tach): self { if (!$this->taches->contains($tach)) { $this->taches[] = $tach; $tach->setProject($this); } return $this; } public function removeTach(Tache $tach): self { if ($this->taches->contains($tach)) { $this->taches->removeElement($tach); // set the owning side to null (unless already changed) if ($tach->getProject() === $this) { $tach->setProject(null); } } return $this; } /* * @return Collection|VichImage[] */ public function getVichImages(): Collection { return $this->vichImages; } public function addVichImage(VichImage $vichImage): self { if (!$this->vichImages->contains($vichImage)) { $this->vichImages[] = $vichImage; $vichImage->setProject($this); } return $this; } public function removeVichImage(VichImage $vichImage): self { if ($this->vichImages->contains($vichImage)) { $this->vichImages->removeElement($vichImage); // set the owning side to null (unless already changed) if ($vichImage->getProject() === $this) { $vichImage->setProject(null); } } return $this; } }
