### ISSUE TITLE
InvalidArgumentException @  PropertyAccessor ->setValue

### ISSUE THREAD

**Issue by andrewSeldenrust** [dustin10/VichUploaderBundle#745]
Howdy, 

I am working on a Symfony 3 app and when attempting to delete a Vich\Uploadable() Entity I got an "'InvalidArgumentException' Expected argument of type "integer", "NULL" given."

This was triggered on the 'objectSize' field (even when set to Doctrine Nullable).  It looks like the bundle has a remove listener that iterates through the entity fields and sets them to null.  Is that normal?  It seems to be a bit strange to me and I cannot figure out a way around it.  I have not been able to find anything similar in other issues. I realize this may be caused by something else.  Thoughts?  I am thankful for anything.

Thanks again,
Andrew

**Comment by garak** [comment]
I'm not sure what the "objectSize" field is.

**Comment by andrewSeldenrust** [comment]
The size of the object being stored.  In my case it is a csv file.  
<img width="934" alt="screen shot 2017-07-07 at 10 03 40 am" src="https://user-images.githubusercontent.com/25235489/27963799-b212d08c-62fb-11e7-8817-edae2101f0ad.png">

**Comment by garak** [comment]
Can you provide the stack trace of your exception?

**Comment by andrewSeldenrust** [comment]
Sure, here it is: 

<img width="488" alt="screen shot 2017-07-07 at 2 42 12 pm" src="https://user-images.githubusercontent.com/25235489/27974194-90e1674e-6322-11e7-9204-514854ede352.png">
<img width="483" alt="screen shot 2017-07-07 at 2 42 20 pm" src="https://user-images.githubusercontent.com/25235489/27974195-90e6a7fe-6322-11e7-8859-396b6804a983.png">
<img width="480" alt="screen shot 2017-07-07 at 2 42 28 pm" src="https://user-images.githubusercontent.com/25235489/27974196-90e6fcf4-6322-11e7-804d-a24db69eac39.png">

**Comment by garak** [comment]
So, it looks like the problem is in your AppBundle

**Comment by andrewSeldenrust** [comment]
Wow - I see it now.  Idiot.  Thanks!  Coding problems late at night.
