### ISSUE TITLE
FIleException -> RuntimeException 

### ISSUE THREAD

**Issue by flim** [dustin10/VichUploaderBundle#747]
When I upload an image with an exceeded size (upload_max_filesize), I got the FileException that I handle via try / catch.

But there is another exception I cant manage, which is

    (1/1) RuntimeException
    --
    stream_socket_sendto(): Broken pipe
    --
    in ServerLogHandler.php (line 57)
    at stream_socket_sendto(resource, 'YTo3Ontz...xO319')in ServerLogHandler.php (line 57)

Its seems to happen only when the fileException occur.

How can I abord the upload to avoid the RuntimeException to occur ?

Thanks

**Comment by garak** [comment]
Being ServerLogHandler outside this bundle, I can't see how we can help you here.

**Comment by KoenPasman** [comment]
We were experiencing the exact same scenario. Important detail is that this happens in Symfony 3.3. 

This only occurs when using the built-in Symfony Webserver. When running on a 'normal' LAMP-stack, this does not happen. It looks like a weird side-effect after they tried to speed up performance of the built-in server on Windows: https://github.com/symfony/symfony/issues/22712
