### ISSUE TITLE
upload destination not working on cpanel linux uploading

### ISSUE THREAD

**Issue by sanribadu** [dustin10/VichUploaderBundle#751]
i have deployed my symfony project on shared hosting. i am using this bundle to handle my image uploading but it is not uploading image file to the server. the image name is saved to the database. i have tried changing upload_destination to linux path like this: "/home/kaftanhu/public_html/images/" thanks

**Comment by garak** [comment]
It looks like you don't even know the reason of your failed upload.
I'm afraid there's nothing we can do to help you.
