### ISSUE TITLE
RegisterPropelModelPass is failing on SF2.8

### ISSUE THREAD

**Issue by jkabat** [dustin10/VichUploaderBundle#753]
PHP: 7.1.6
Bundle: 1.6.2

YAML configurations renamed as suggested.

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getParent" of class "Symfony\Component\DependencyInjection\Definition". in /vendor
  /vich/uploader-bundle/DependencyInjection/Compiler/RegisterPropelModelsPass.php:63
```

**Comment by nibsirahsieu** [comment]
The error comes from here

`$container->addCompilerPass(new RegisterPropelModelsPass(), PassConfig::TYPE_BEFORE_REMOVING);`

It work If i remove the second parameter (PassConfig::TYPE_BEFORE_REMOVING). I dunno the effect of removing those parameter.

**Comment by garak** [comment]
Hey, since this is an OLD issue and we had to remove Propel support in latest version, I'd like to know if this issue is still relevant, and especially if you're able to propose a fix for an older branch.
Otherwise, this issue will be closed without resolution.
