### ISSUE TITLE
The options "download_uri" does not exist !!!

### ISSUE THREAD

**Issue by bhss** [dustin10/VichUploaderBundle#754]
Any idea how to show a link for downloading the file ??
this is my form : 

> ->add('imageFile',VichFileType::class, [
>             'required' => false,
>           'download_link' => true,
>             'label' => false, 
>         ]);

**Comment by garak** [comment]
Bundle version?

**Comment by bhss** [comment]
"vich/uploader-bundle": "^1.4"

**Comment by garak** [comment]
That's your composer.json constraint, you should run `composer show | grep vich` and report your output

**Comment by bhss** [comment]
1.4.2

**Comment by garak** [comment]
The option is `download_link`, not `download_uri`.
There's nothing much I can say without more informations

**Comment by Koc** [comment]
@garak the problem is: 1.6.x versions requires php 7.0. By default Symfony standards hardcores composer.config.platform = php 5.5.9. So anybody who installs our bundle will get 1.4.x version of it.

**Comment by garak** [comment]
That's not a problem, we can support anyway version 1.4.
Anyway, I would recommend anyone to upgrade to an actively supported php version.
