### ISSUE TITLE
Remove file with soft delete Doctrine extension behaviour

### ISSUE THREAD

**Issue by davidromani** [dustin10/VichUploaderBundle#757]
Hi.

Is working "delete_on_remove" flag set to true with soft delete Doctrine extension? Which has to be the right behaviour?

**Comment by garak** [comment]
Do not use soft delete.

**Comment by davidromani** [comment]
@garak why? it's a projetc requirement that I must follow...

**Comment by garak** [comment]
Because it's an anti-pattern. https://www.google.it/search?q=soft+delete+anti+pattern

**Comment by davidromani** [comment]
thx @garak
