### ISSUE TITLE
Class Vich\UploaderBundle\Entity\File does not exists, or could not be auto-loaded.

### ISSUE THREAD

**Issue by traczewskim** [dustin10/VichUploaderBundle#760]
Fresh instance of project. Composer install and when I run: console doctrine:schema:validate I'm getting this error: 

> The annotation "@Doctrine\ORM\Mapping\Embeddable" in class Vich\UploaderBundle\Entity\File does not exist, or could not be auto-loaded.

File exists in vendor/ folder but I have no clue where to look for solution.

**Comment by garak** [comment]
Check your version of doctrine/orm.
As you can see in composer.json, suggested version is `^2.5`.

**Comment by traczewskim** [comment]
Damn. That was easy... Works perfect. Thank you.
