### ISSUE TITLE
Entity not uploadable error with yaml

### ISSUE THREAD

**Issue by benIT** [dustin10/VichUploaderBundle#763]
Hi,
I am encountering the following error with a doctrine entity described in yaml and using vich mapping in yaml file: 

> The class "AppBundle\Entity\Video" is not uploadable. If you use annotations to configure VichUploaderBundle, you probably just forgot to add `@Vich\Uploadable` on top of your entity. If you don't use annotations, check that the configuration files are in the right place. In both cases, clearing the cache can also solve the issue.

I follow these steps:

-  [setup vich mapping](https://github.com/benIT/sf3-video-app/blob/vich-upload-issue/app/config/bundles/vich_uploader.yml)
-  [add entity fields](https://github.com/benIT/sf3-video-app/blob/vich-upload-issue/src/AppBundle/Entity/Video.php)
-  [setup doctrine entity mapping](https://github.com/benIT/sf3-video-app/blob/vich-upload-issue/src/AppBundle/Resources/config/doctrine/Video.orm.yml)
-  [setup vich entity mapping](https://github.com/benIT/sf3-video-app/blob/vich-upload-issue/src/AppBundle/Resources/config/vich_uploader/Entity.Video.yml)
-  [setup formtype](https://github.com/benIT/sf3-video-app/blob/vich-upload-issue/src/AppBundle/Form/VideoType.php)
- clear cache

**Comment by benIT** [comment]
Hi,
it seems to be a file naming issue, my entity vich mapping file was named `Resources/config/vich_uploader/Entity.Video.yml` according to the [documentation](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/mapping/yaml.md).
I renamed it `Resources/config/vich_uploader/Video.yml`, cleared cache and this is now running fine.

**Comment by Sander-Toonen** [comment]
The change in the documentation is due to a BC-break in 1.6.0 (It should therefore really have been 2.0.0 i.m.h.o.)

Before 1.6.0:
``Resources/config/vich_uploader/Video.yml``

1.6.0 and later:
``Resources/config/vich_uploader/Entity.Video.yml``
or ``Resources/config/vich_uploader/Document.Video.yml``
depending on whether you are using ORM or ODM.
