### ISSUE TITLE
File duplication

### ISSUE THREAD

**Issue by akeeman** [dustin10/VichUploaderBundle#766]
Hi @garak,

My project requires me to occasionally clone an entity that contains a file. I use the delete_on_update and delete_on_remove functionality, and so simply cloning the image references clearly makes these do undesirable things. Because this bundle manages the file, it feels logical to also handle duplication of the file here.

Before wringing a pr I want to check up if this sounds like a good idea to you guys.

The general structure I was thinking of is to add a `duplicate` flag to the PropertyMapping that stores whether the current file should be duplicated. UploadHandler::upload should check whether there's a file and it should be duplicated. If so, it instructs the storage to duplicate the file, using an added duplication method. Also, there should be an in-memory mapping cache instead of recreating the MappingProperties object every time, so that the duplicate property state gets preserved.

Are you guys in for such a feature, or should I save the effort?

**Comment by garak** [comment]
It looks like a really specific requirement to me.
Are you sure you can't resolve it inside your application?

**Comment by akeeman** [comment]
It surely can be done, but it'll be quite nasty. Most of the infrastructure and configuration has to be done twice, as it should work on the same field with the same namers (or at least the naming logic), use the same storage, and hooks into the same lifecycle as the upload part. Also it should produce an updated `Vich\UploaderBundle\Entity\File` object.

Also extending the bundle is quite hard and I find it less desirable, because it has to keep up with future changes.

**Comment by garak** [comment]
What if you inject the VichUploaderBundle services you need  inside your own service? You can inject the handler, the namer, etc. and so you won't need to duplicate any configuration

**Comment by akeeman** [comment]
That would leave me with a way to flag a file for duplication, requires a separate event listener, and extension of the storage. So I think that would be quite hard, still, and then extending the whole bundle would provide a higher degree of integration, because parts can and must be overridden.
Or am I just looking at the problem the wrong way? Thanks for thinking with me, by the way!

**Comment by colinodell** [comment]
I need this feature for the same reasons.  And I agree with @akeeman that this is not currently feasible.

One approach I investigated was injecting `UploadHandler` into my service so I could manually "upload" a copy of the existing file.  There are two challenges with this, though:

1. **The file must exist locally**.  The handler only works with `UploadedFile` or `ReplacingFile` instances.  But I'm using Flysystem storage.  My service therefore has to read/download the original file into a temporary location first.  This is not ideal.
2. **I must specify each field name explicitly**. `MetadataReader` knows all the field names but it's an `@internal` class so I shouldn't rely on it.  I therefore have to maintain hard-coded strings of each field name and keep those in sync with my entity metadata.  And I must do this for every field on every entity that needs to support this.

## Alternate Suggestion 1

If the proposal to support a `duplicate` flag is not ideal for any reason, I have an alternate suggestion:  **Add a new `DuplicatingFile` class.**  This would work similarly to `ReplacingFile`, except it would signal that the existing file is already located in the storage (which may be local or remote).  `UploadHandler::upload()` (or perhaps `StorageInterface::upload()`) would detect this and invoke a newly-added duplication/copy method on the underlying storage to create that copy without needing to download and re-upload the data.

End users like myself would then leverage this with code like this:

```
public function __clone()
{
    $this->setFile(new DuplicatingFile($this->getPath()); // Similar to use `ReplacingFile`
}
```

It's definitely not as pretty as an automated approach though, but I think it should work.  WDYT?

**Comment by garak** [comment]
@colinodell I think you should not inject directly the UploaderHandler, but instead use your specific service for this purpose (and inject UploaderHandler in it). This way you can isolate your logic.
Again, it seems to me a very specific feature, which I'd prefer to avoid to maintain in this bundle.
