### ISSUE TITLE
OneToMany - Expected value of type "Doctrine\Common\Collections\Collection|array" for association field "ClassifiedsBundle\Entity\Product#$images", got "array" instead.

### ISSUE THREAD

**Issue by Pixellone** [dustin10/VichUploaderBundle#767]
I got this error when I try to save a new Product.

```
class Product
{
  /**
   * @ORM\Id
   * @ORM\Column(type="integer")
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  protected $id;
  
  /**
   * @ORM\ManyToOne(targetEntity="Category", inversedBy="products")
   * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
   */
  protected $category;
  
  /**
   * @ORM\ManyToOne(targetEntity="Condition", inversedBy="products")
   * @ORM\JoinColumn(name="condition_id", referencedColumnName="id")
   */
  protected $condition;
  
  /**
   * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User", inversedBy="products")
   * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
   */
  protected $user;
  
  /**
   * @ORM\Column(type="string", length=100)
   */
  protected $title;
  
  /**
   * @ORM\Column(type="float")
   */
  protected $price;
  
  /**
   * @ORM\Column(type="text")
   */
  protected $description;
  
  /**
   * @ORM\OneToMany(targetEntity="ProductImage", mappedBy="product")
   */
  protected $images;
  
  /**
   * @ORM\ManyToMany(targetEntity="UserBundle\Entity\User", mappedBy="subscribed_products")
   */
  private $subscribers;
  
  /**
   * @ORM\Column(type="datetime")
   */
  protected $created_at;
  
  /**
   * @ORM\Column(type="datetime")
   */
  protected $updated_at;
}
```

```
class ProductImage
{
  /**
   * @ORM\Id
   * @ORM\Column(type="integer")
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  protected $id;
  
  /**
   * @ORM\ManyToOne(targetEntity="Product", inversedBy="images")
   * @ORM\JoinColumn(name="product_id", referencedColumnName="id")
   */
  protected $product;
  
  /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName", size="imageSize")
     * 
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer")
     *
     * @var integer
     */
    private $imageSize;
}
```

```
class ProductType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    $builder
      ->add('title', TextType::class)
      ->add('category', EntityType::class, array(
        'class' => 'ClassifiedsBundle:Category',
        'label' => 'Categoria'
      ))
      ->add('description', TextareaType::class, array(
        'label' => 'Descrizione'
      ))
      ->add('condition', EntityType::class, array(
        'class' => 'ClassifiedsBundle:Condition',
        'label' => 'Condizione'
      ))
      ->add('price', MoneyType::class, array(
        'scale' => 2
      ))
      ->add('images', CollectionType::class, array(
        'entry_type' => ProductImageType::class,
        'entry_options' => array('label' => false),
        'allow_add' => true,
        'by_reference' => false,
      ))
    ;
  }
}
```

```
class ProductImageType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    $builder->add('imageFile', VichImageType::class, [
      'required' => true,
      'allow_delete' => true,
    ]);
  }
}
```

I need help... please

**Comment by StanThall** [comment]
Hi,
I got same issue on my side, my code looks almost same. Short code extract : 
Part of **Entity MachandiseImages** :
`class UtMarchandiseImages
{
    /**
     * @var integer
     */
    private $miId;

    /**
     * @var string
     */
    private $miFilename;

	/**
	 * @var File $miFilename_file
	 */
	protected $miFilename_file;

    /**
     * @var \DateTime
     */
    private $miCreationDatetime;

    /**
     * @var \Acme\Test\Entity\UtMarchandise
     */
    private $utMarchandise;
...`

Part of **Entity Marchandise** :
`/**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $utMarchandiseImages;


    /**
     * Add utMarchandiseImage
     *
     * @param \Acme\Test\Entity\utMarchandiseImages $utMarchandiseImage
     *
     * @return UtMarchandise
     */
    public function addUtMarchandiseImage(\Acme\Test\Entity\utMarchandiseImages $utMarchandiseImage)
    {
        $this->utMarchandiseImages[] = $utMarchandiseImage;

        return $this;
    }

    /**
     * Remove utMarchandiseImage
     *
     * @param \Acme\Test\Entity\utMarchandiseImages $utMarchandiseImage
     */
    public function removeUtMarchandiseImage(\Acme\Test\Entity\utMarchandiseImages $utMarchandiseImage)
    {
        $this->utMarchandiseImages->removeElement($utMarchandiseImage);
    }

    /**
     * Get utMarchandiseImages
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUtMarchandiseImages()
    {
        return $this->utMarchandiseImages;
    }`

Part of **MarchandiseAdmin** (I'm using Sonata Admin):
`->add('utMarchandiseImages', 'sonata_type_native_collection', array(
				'label' => "Illustrations du produit",
				'entry_type' => MarchandiseImagesType::class,
				'allow_add'     => true,
				'allow_delete'  => true,
				'entry_options' => [
					'by_reference'  => false,
					'label' => false
					]
				)`

Part of **MarchandiseImageType** :
`class MarchandiseImagesType extends AbstractType
{
		/**
	 * @param FormBuilderInterface $builder
	 * @param array                $options
	 */
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		return $builder
			->add('miFilename_file', VichImageType::class , [
				'required' => false,
				'download_uri' => true,
				'image_uri' => true,
			]);
	}


	public function setDefaultOptions(OptionsResolverInterface $resolver)
	{
		$resolver->setDefaults([
			'data_class' => 'Acme\Test\Entity\UtMarchandiseImages',
		]
		);
	}`
Any guess what are we doing wrong ?

Thanks a lot.

**Comment by StanThall** [comment]
@Pixellone I've found out one issue I made.

Since Symfony 2.7, setDefaultOptions is deprecated and has been remove since Symfony 3.
We should use configureOptions in place of, like this :
Part of **MarchandiseImageType.php**
```
use Symfony\Component\OptionsResolver\OptionsResolver;

class MarchandiseImagesType extends AbstractType
{
		/**
	 * @param FormBuilderInterface $builder
	 * @param array                $options
	 */
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		return $builder
			->add('miFilename_file', VichImageType::class , [
				'required' => false,
				'download_uri' => true,
				'image_uri' => true,
			]);
	}


	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults([
			'data_class' => 'ACME\Test\Entity\UtMarchandiseImages',
		]
		);
	}

	/**
	 * @return string
	 */
	public function getName()
	{
		return 'marchandise_images';
	}
}
```
Hope it will help you.

**Comment by garak** [comment]
Is this solved?

**Comment by StanThall** [comment]
On my side, yes it is.

**Comment by chrisVdd** [comment]
Hi there!

I'm trying to do exactly the same thing but it doesn't work.
In fact, if I go to the add a post page, my form is displayed, except for the field dedicated to adding an image. Only the label is displayed.
If I go to the browser console, I can see the generated code.

This is the visual rendering:

![screenshot_20171104_121424](https://user-images.githubusercontent.com/3304456/32404867-c4346660-c159-11e7-9a83-7854f90d944d.png)

Help would be welcome, I'm having trouble understanding the problem.
Thanks!

**Comment by StanThall** [comment]
Please have a look to following :

```
->add('utMarchandiseImages', 'sonata_type_native_collection', array(
				'label' => "Illustrations du produit",
				'entry_type' => MarchandiseImagesType::class,
				'allow_add'     => true,
				'allow_delete'  => true,
				'entry_options' => [
					'by_reference'  => false,
					'label' => false
					]
				) 
```

Have you set 'allow_add'     => true ?
