### ISSUE TITLE
Tutorial on how to use VichUploader in a ManyToOne relation/Collection

### ISSUE THREAD

**Issue by picks44** [dustin10/VichUploaderBundle#781]
Hi all,

I've tried to use the VichUplader bundle to manage multiple images likes to one article (to create a gallery), but I'm struggling, specially when editing the Article entity (I'm also using the [symfony-collection bundle](https://github.com/ninsuo/symfony-collection)).

Can we get a clear and tested way of doing this? I've seen many threads but I can't get it to work myself.

With the create/edit/remove controllers also, that would be appreciated.

Thanks!

**Comment by skornev** [comment]
picks44. Please check https://github.com/skornev/vichbundle-sandbox-not-cp-symfony3.3
Though it's about demonstrating  a bug, it's also a basic app mostly related to your question.

**Comment by picks44** [comment]
thanks @skornev

**Comment by rigecko** [comment]
Hello
Well, I have the same problem on Symfony 2.7. edit is not creating any new file. 
I coded the delete by going through images with a null filename after handling the request!

Any guidance apprecaited

**Comment by skornev** [comment]
@rigecko Please read https://github.com/dustin10/VichUploaderBundle/issues/776

**Comment by skornev** [comment]
Also please update Symfony to the latest one

**Comment by rigecko** [comment]
Well the problem is slightly different as  I keep the previously submitted values. I'll try to add a field in the entity. But I can't update symfony because of compatibilities on My server (many project need old php version not compatible with symfony3.3 ; So since all project will not be migrated I'll keep 2.7! thanks for yor help anyway
