### ISSUE TITLE
Setting an image name to the slug of the entity not working?

### ISSUE THREAD

**Issue by DBarkz** [dustin10/VichUploaderBundle#782]
Hi

I am trying to set the slug of both my retailer_image and product_image to the slug property of the entity so I set my retailer_image to use the namer with a property if slug and it worked fine:

```
retailer_image:
            uri_prefix:         /images/retailers
            upload_destination: '%kernel.root_dir%/../web/images/retailers'
            namer:
                service: vich_uploader.namer_property
                options: { property: 'slug'}
```
However, when I also added the namer to my product_image:

```
product_image:
            uri_prefix:         /images/products
            upload_destination: '%kernel.root_dir%/../web/images/products'
            namer:
                service: vich_uploader.namer_property
                options: { property: 'slug'}
    
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false
```

I get an error of "File name could not be generated: property slug is empty." whenever I try and create a new entity...

It does work however if I edit an existing entity, any idea why this is and how to fix it?

Thanks

**Comment by DBarkz** [comment]
This can be removed, it was an error on my part, sorry.

**Comment by garak** [comment]
Likely the slug is set too late.
You can try to force the slug generation in your namer

**Comment by garak** [comment]
Closing for missing feedback
