### ISSUE TITLE
Symfony3 how to retrieve a JsonResponse via AJAX

### ISSUE THREAD

**Issue by thierrybou** [dustin10/VichUploaderBundle#783]
In my controller I retrieve a query result wich I store in the `$articles` variable. 
I wish send this variable toward AJAX with a `JsonRESPONSE()` function. 
But when I retrieve the data in AJAX, it's an array of empty objects while when I debug the `$articles` variable in my PHP controller the data is well present.

Here is my controller :

    /**
     * @Route("/ajax/request", options={"expose"=true}, name="ajax_request")
     * @Method({"POST"})
     */
    public function ajaxRequestAction(Request $request)
    {
          if ($request->isMethod('post')) {
            $brands = $request->request->get('brand');

            $repository = $this->getDoctrine()->getRepository('ArticleBundle:Article');

            /* I retrieve my query result */
            $articles = $repository->getBrandsByFilter($brands);

            /* And send it toward Ajax */
            $response = new JsonResponse();
            return $response->setData(array('data' => $articles));
        }
    }

Here is my AJAX code :

    $('#submitFilter').click(function () {

        $.ajax({
            type: 'POST',
            url: Routing.generate("ajax_request"),
            data: { brand: selectedBrand },
            dataType: 'json'
        })
            // HERE I WANT RETRIEVE MY JsonRESPONSE
            .done(function( data ) {
                console.log(data);

                for ( var i = 0; i < data.length; i++ ) {
                    Object.keys(data[i]).forEach(function (key) {
                        var propertyData = data[i][key];
                        //console.log(key);
                        //
                    })
                }
            });
    })

Here is the debug of the `$articles` in PHP :

    array:8 [▼
      0 => Article {#612 ▼
        -id: 203
        -fosUserId: null
        -name: "article 1"
        -category: "sous-vêtements"
        -brand: "caporal"
        -model: "running"
        -gender: "unisex"
      1 => Article {#610 ▶}
      2 => Article {#631 ▶}
      3 => Article {#619 ▶}
      4 => Article {#657 ▶}
      5 => Article {#635 ▶}
      6 => Article {#695 ▶}
      7 => Article {#633 ▶}
    ]

And here the debug of the data what I retrieve in AJAX :

    data: Array(8)
        0: {} 
        1: {}
        2: {}
        3: {}
        4: {}
        5: {}
        6: {}
        7: {}  

If you have an idea why I retrieve empty data in AJAX it will help me a lot :)

**Comment by garak** [comment]
How is this related to VichUploaderBundle?

**Comment by thierrybou** [comment]
Yes sorry for that I did not know where put it. I can delete it or close it ?

**Comment by garak** [comment]
I suggest you [Stackoverflow](https://stackoverflow.com/)
