### ISSUE TITLE
Mapping not found after an installation on another machine

### ISSUE THREAD

**Issue by rigecko** [dustin10/VichUploaderBundle#789]
Hello, I'm starting usng this bundle and manage to create a table to manage multi image linked to my table.
It is working on a PC. I pushed everything using git.
Pulled on another PC, making the composer install..... and I got a mapping error when viewing, but event the file_name field in my table is NULL while it is filed correctly on another.
I(m using symfony 2.7 and vich 1.4.2 .
There are no differences between the composedr.lock on both PC. 

My mapping file is:
```
InventoryBundle\Entity\MaterielImages:
    doc:
        mapping:           materiel_docs
        filename_property: file_name
```

I can't figure out what the problem is. 
Help appreciated

**Comment by rigecko** [comment]
PB Found, not where expected. In fact I had no annotation on my entity @Vich\UploadableField 
i thought the file in config/vich_uploader was enough. On my former PC the cache was not cleared, so It was continuing to work.
So the question is becoming: Why the annotation is mandatory as the inforations seems to be the same as in the file?
regards

**Comment by garak** [comment]
You can use console commands in `vich:mapping` namespace to debug your configuration
