### ISSUE TITLE
Allow to Put @Vich\UploadableField Annotation into a Parent Class

### ISSUE THREAD

**Issue by HSteeb** [dustin10/VichUploaderBundle#793]
Using the `@Vich\UploadableField` annotation in a parent class (`@ORM\MappedSuperclass`) does not work, since the annotation driver only checks the class itself for the `UploadableField` annotation.

So you have to clone the `UploadableField` and its methods into each derivation class.

The following modification in the AnnotationDriver.php loadMetadataForClass() helps:

old code: 

`foreach ($class->getProperties() as $property) {`

new code:

~~~
$classes = array();
do {
    $classes[] = $class;
    $class = $class->getParentClass();
} while (false !== $class);
$classes = array_reverse($classes, false);
$properties = array();
foreach ($classes as $class) {
    $properties = array_merge($properties, $class->getProperties());
}
foreach ($properties as $property) {
~~~
Note:
- loop borrowed from `vendor/jms/metadata/src/Metadata/MetadataFactory.php::getClassHierarchy`
- Actually the code can be optimized to avoid using two loops.
- I'm referring to version `1.4.2`, the code has changed on trunk on github but has still the  same behavior.

**Comment by etshy** [comment]
This could be good to have this (if not already, I didn't try it yet).

**Comment by garak** [comment]
Feel free to provide a PR

**Comment by etshy** [comment]
I started a PR and have question about the tests.
I saw a `DummyEntity` at the root of the `tests/` folder and there are also entities in a `tests/fixtures/...` folder.

As I have to add some Entities, I'd like to know if it's good to add them in the `fixtures` folder.

For now I just took the code proposed by HSteeb, and i'll see if it needs some changes after running tests.

**Comment by garak** [comment]
`Tests/Fixtures/` folder contains an entire application used in tests, while `DummyEntity` is just an entity used directly in tests.
