### ISSUE TITLE
Data Transformers return null

### ISSUE THREAD

**Issue by imsheng** [dustin10/VichUploaderBundle#796]
`
$builder
	->add('imageFile', 'Vich\UploaderBundle\Form\Type\VichImageType', [
		'allow_delete' => true,
		'download_uri' => true,
	]);
$builder->get('imageFile')
	->addModelTransformer(new CallbackTransformer(
		function ($file) {
		},
		function ($file) {
			dump($file);
		}
	));
`

"imageFile" is Base64 data  ,I submitted Base64 data，data transformers return null

**Comment by garak** [comment]
Well, you're using a custom transformer instead of the one provided by the bundle. I'm afraid you're on your own

**Comment by imsheng** [comment]
$builder
            ->add('imageFile', VichImageType::class, [
                'required' => false,
                'allow_delete' => true, // not mandatory, default is true
                'download_uri' => true, // not mandatory, default is true
            ]);
        $builder->get('imageFile')
            ->addModelTransformer(new CallbackTransformer(
                function ($file) {
                },
                function ($file) {
                   // before composer update , $file return base64
                    if ($file instanceof UploadedFile) {
                        return $file;
                    }
                    if ($file != null) {
                        $base64 = explode(',', $file)[1];
                        $path = trim(ini_get("upload_tmp_dir")) == '' ? sys_get_temp_dir() : ini_get("upload_tmp_dir");

                        $temp_file = tempnam($path, 'tmp');
                        file_put_contents($temp_file, base64_decode($base64));

                        return new UploadedFile($temp_file, null, null, null, null, true);
                    }
                }
            ));
but it return base64 before `composer update`
it's normal before `composer update`

**Comment by garak** [comment]
I'm sorry but I cant' help you if I don't understand you.
Please state something clear. "Composer update" is not something clear

**Comment by imsheng** [comment]
I found it return the data in symfony 3.3.10 ，so it can save the file.
Since I upgraded to symfony 3.3.13, it returned to null.

**Comment by garak** [comment]
My advice on possible solutions:
* go back to Symfony 3.3.10
* open an issue on Symfony repository

**Comment by imsheng** [comment]
thank you.
