### ISSUE TITLE
Mapping not found when using MappedSuperClass

### ISSUE THREAD

**Issue by nikophil** [dustin10/VichUploaderBundle#797]
Hello,

i got a "Mapping not found" error when i try to upload a file.
Actually, i'm using a doctrine mappedSuperClass : when the upload field is in the base class, it is working, but it is not when it's in the child class.

Any workaround please ?

thank you.

**Comment by garak** [comment]
Did you check your mapped entities using provided commands?

**Comment by nikophil** [comment]
hi, thanks for your answer,
i tried, and when the field is in the child class, the command vich:mapping:debug-class doesn't find the field

**Comment by nikophil** [comment]
I got a BaseUser class and a User that extends it

when the field is in User, the command can't find it
but it's ok when it is in BaseUser

**Comment by garak** [comment]
Try to map User too

**Comment by nikophil** [comment]
What do you mean?
I can provide some code if needed...

**Comment by garak** [comment]
I mean that mapping the superclass is not enough, you need to map every child too

**Comment by nikophil** [comment]
okay, i've found my mistake, indeed i've forgotten to put the @Uploadable annotation on the child class...
thanks for helping.
