### ISSUE TITLE
Error when installing on Symfony 4.

### ISSUE THREAD

**Issue by phpeek** [dustin10/VichUploaderBundle#800]
This is what I'm getting when installing `vich/uploader-bundle` at `1.7^`.

```php
PHP Fatal error:  Class 'Symfony\Component\Templating\Helper\Helper' not found in [...]/vendor/vich/uploader-bundle/Templating/Helper/UploaderHelper.php on line 13
```

Is it possible that `symfony/templating` should now be listed as a `require` dependency in `composer.json` ?

**Comment by phpeek** [comment]
There's also missing depedency on `symfony/form` ?

Steps to reproduce:

```sh
composer create-project symfony/skeleton foo
cd foo
composer require vich/uploader-bundle
```

finishes with

```sh
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 32:
!!                                                                                 
!!    The service "vich_uploader.namer_directory_property" has a dependency on a   
!!    non-existent service "form.property_accessor".                               
!!                                                                                 
!!  
!!  
```

**Comment by jawish** [comment]
Can confirm. Both `symfony/form` and `symfony/templating` are needed as dependencies for Symfony 4 Flex skeleton based projects for this bundle to work.

**Comment by garak** [comment]
Thanks for reporting guys. This is fixed in latest `1.7.1` tag.

**Comment by timotheemoulin** [comment]
I just installed 1.7.1 in a Symfony 3.3.15 and the problem of the missing service is still there.

> The service "vich_uploader.namer_directory_property" has a dependency on a non-existent service "form.property_accessor".

Should I add something else in my config file?

```yaml
vich_uploader:
  db_driver: orm
  mappings:
    product_image:
      uri_prefix: /images/products
      upload_destination: '%kernel.root_dir%/../web/assets/products/images'
      namer: vich_uploader.namer_uniqid```

**Comment by rbaarsma** [comment]
Solved by enabling form:

```yaml
framework:
    form: { enabled: true }
```

For me it would be nice if this bundle didn't require the form, because I need to specifically enable it for this bundle..
