### ISSUE TITLE
Validate mapping  (enhancement)

### ISSUE THREAD

**Issue by skornev** [dustin10/VichUploaderBundle#805]
`@Vich\UploadableField(mapping="attachment"...)`
It would be great  if mappings are validated for existing in mapping config.

Currently it's allowed to map not existing mapping e.g.  
`@Vich\UploadableField(mapping="attachment_not_existing_mapping"...)`
Now this mapping throws no error.

**Comment by garak** [comment]
Not found mapping are throwing `MappingNotFoundException`

**Comment by skornev** [comment]
Hm... I am using 1.7.1. It does throw exception during render of a template which uses attachments. 
`An exception has been thrown during the rendering of a template ("Mapping "attachment_not_existing_mapping" does not exist`
But  it does not raise any error when  entity is created or saved, only doctrine error occurs when trying to save with file null 

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'file_name' cannot be null`
