### ISSUE TITLE
BC break when serving files

### ISSUE THREAD

**Issue by fabienlem** [dustin10/VichUploaderBundle#809]
Hello,

I'm experiencing a BC break when updgrading from VichUploaderBundle 1.7.1 to 1.8.0 (with Symfony 3.4.3, I use vich + flysystem).

My controller that serve files doesn't work anymore as it serve empty files.

Here is my controller's code : 
```
use Vich\UploaderBundle\Handler\DownloadHandler;

/**
 * @Route("/storage")
 */
class StorageController extends Controller
{

    /**
     * @Route("/attachment/{fileName}", name="serve_attachment")
     * @Security("is_granted('download', attachment)")
     */
    public function serveAction(Attachment $attachment, DownloadHandler $downloadHandler)
    {
        return $downloadHandler->downloadObject($attachment, 'file');
    }

}
```

```
# services.yml

services:
    Vich\UploaderBundle\Handler\DownloadHandler: '@vich_uploader.download_handler'

```

Do you have any hint of what I'm doing wrong?

Thank you!

Fabien

**Comment by garak** [comment]
Sorry, I just tried but I can't reproduce

**Comment by fabienlem** [comment]
Ok, thank you for your quick reply.

I'll try to gather further information and keep you updated.

Fabien

**Comment by Koc** [comment]
Please create fork of symfony standard or symfony skeleton to reproduce this issue on our env.

**Comment by TerjeBr** [comment]
Is this issue related to using a `FlysystemStorage`? If so it might be related to #814
