### ISSUE TITLE
Add aliases for services

### ISSUE THREAD

**Issue by garak** [dustin10/VichUploaderBundle#810]
I think it could be nice if we add aliases that map services class names to services names.
Example: we currently expose a service named `vich_uploader.download_handler` that points to `Vich\UploaderBundle\Handler\DownloadHandler` (and it's pubilc)
We could add an alias like this:

```xml
 <service id="Vich\UploaderBundle\Handler\DownloadHandler" alias="vich_uploader.download_handler" public="false"/>
```

in this way, users are not forced to declare their own aliases to use such services in controllers.
Furthermore, we could deprecate public services, so in next major release we'll be able to remove then (and replace them with the aliases)

What do you think?

**Comment by garak** [comment]
Ping @Koc

**Comment by Koc** [comment]
+1 for download handler. And maybe create interface for it.

Storage also requires in some cases.

**Comment by Koc** [comment]
Can we reopen it until https://github.com/dustin10/VichUploaderBundle/commit/aad4ccceb5bc6d832f27a025334334b159073f80#r27021884 comment not resolved? I'm afraid that we forgot about it.

**Comment by garak** [comment]
It's already solved, see https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/config/storage.xml#L11
