### ISSUE TITLE
Symfony 3.4 - Profiler with VichImageType never loads

### ISSUE THREAD

**Issue by Sydney-o9** [dustin10/VichUploaderBundle#811]
The profiler doesn't load in dev mode:

![image](https://user-images.githubusercontent.com/1480617/34802967-a549b642-f6c4-11e7-922d-250348f82fed.png)

If needed, the implementation I have is extremely simple:

```php
$builder
            ->add('profileImgFile', VichImageType::class, [
                'label' => 'form.profile.chooseProfileImage',
                'translation_domain' => 'forms',
                'download_uri' => false,
                'required' => false
            ])
```

Removing the image fixes the issue.

**Comment by garak** [comment]
We need to be able to reproduce this. Please provide more informations.
Ideally, provide a full Symfony project where the issue is reproducible

**Comment by garak** [comment]
See if this is fixing: https://github.com/symfony/symfony/issues/11015#issuecomment-244596933

**Comment by Sydney-o9** [comment]
@garak, this is very surprising, I only have this with Vich form types. I have increased both `max_execution_time` and `memory_limit`. 

Ok, I understand it would be better to have a full Symfony project where we can reproduce this issue.
