### ISSUE TITLE
Delete checkbox next to file field in the fom doesn't work

### ISSUE THREAD

**Issue by velkony** [dustin10/VichUploaderBundle#813]
I just installed VichUploaderBundel 1.8 for Symfony 4 and to avoid writing a manual delete script I want to use sometimes the delete checkbox when I update the form.
However, when I select the Delete checkbox and press on Update (I am updating the entity with a ManyToOne relation with Attachment) then I got the following error.

An exception occurred while executing 'UPDATE attachment SET image_name = ?, image_size = ? WHERE id = ?' with params [null, null, 2]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'image_name' cannot be null

======================================================
EmailType:

->add('attachments', AttachmentType::class)
=======================================================
AttachmentsType:

$builder->add('imageFile', VichImageType::class, [
            'required' => false,
            'allow_delete' => true,
            'download_label' => true,
            'download_uri' => true,
            'image_uri' => true,
            'imagine_pattern' => 'my_thumb'
        ]);
======================================================
EmailEntity:

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Attachment", cascade={"persist"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $attachments;
=======================================================
vich_uploader.yaml

vich_uploader:
    db_driver: orm
    mappings:
        settings_image:
            uri_prefix: public/uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid

======================================================

/**
 * Attachment Entity
 *
 * @ORM\Table(name="attachment")
 * @ORM\Entity
 * @Vich\Uploadable
 */
class Attachment
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    // ... other fields

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="settings_image", fileNameProperty="imageName", size="imageSize")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer")
     *
     * @var integer
     */
    private $imageSize;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     */
    public function setImageFile(?File $image = null): void
    {
        $this->imageFile = $image;

        if (null !== $image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

How I can solve this problem?

**Comment by garak** [comment]
Set your property to be nullable

**Comment by velkony** [comment]
Hi,
what exactly do you have in mind?

**Comment by garak** [comment]
If your image can be null, keeping field not nullable does not make sense.

**Comment by velkony** [comment]
I tried but it does not work for me.

**Comment by garak** [comment]
Sadly, "it does not work" does not tell anything to us

**Comment by velkony** [comment]
It gives me the same error:
``` Doctrine\DBAL\Exception\NotNullConstraintViolationException:
An exception occurred while executing 'UPDATE image_entity SET image_name = ? WHERE id = ?' with params [null, 2]:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'image_name' cannot be null
  at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:118
  at Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception occurred while executing \'UPDATE image_entity SET image_name = ? WHERE id = ?\' with params [null, 2]:SQLSTATE[23000]: Integrity constraint violation: 1048 Column \'image_name\' cannot be null', object(PDOException))
     (vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:176)
  at Doctrine\DBAL\DBALException::wrapException(object(Driver), object(PDOException), 'An exception occurred while executing \'UPDATE image_entity SET image_name = ? WHERE id = ?\' with params [null, 2]:SQLSTATE[23000]: Integrity constraint violation: 1048 Column \'image_name\' cannot be null')
     (vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:150)
  at Doctrine\DBAL\DBALException::driverExceptionDuringQuery(object(Driver), object(PDOException), 'UPDATE image_entity SET image_name = ? WHERE id = ?', array(null, 2))
     (vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1065)
  at Doctrine\DBAL\Connection->executeUpdate('UPDATE image_entity SET image_name = ? WHERE id = ?', array(null, 2), array('string', 'integer'))
     (vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:499)
  at Doctrine\ORM\Persisters\Entity\BasicEntityPersister->updateTable(object(ImageEntity), 'image_entity', array('image_name' => null), null)
```
the problem comes from Flashing

**Comment by velkony** [comment]
otherwise, upload and delete features work well just the problem is update with Delete checkbox

**Comment by garak** [comment]
It looks like you didn't change the nullability of "image_name".

**Comment by velkony** [comment]
```
/**
     * @ORM\Column(type="string", length=255, name="image_name", nullable=true)
     *
     * @var string $imageName
     */
    protected $imageName = null;
```

**Comment by garak** [comment]
You need to update your schema after that

**Comment by velkony** [comment]
Hi @garak ,
You're right. Thank you so much.
I forgot to update the database.
It works.
Would you recommend me a filter for preview of an image?
I'm currently using LiipImagineBundle.
But unfortunately it still does not work well on Symfony 4.

**Comment by garak** [comment]
You're welcome.
About LiipImagineBundle, all we can do for now is voting for the issues/PRs that support Symfony 4. I already did it.
