### ISSUE TITLE
resolveStream does not work when storage is Flysystem

### ISSUE THREAD

**Issue by TerjeBr** [dustin10/VichUploaderBundle#814]
Hi.

In the class `Vich\UploaderBundle\Storage\FlysystemStorage` you have this method:
```
public function resolveStream($obj, string $fieldName, string $className = null): ?string
    {
        $path = $this->resolvePath($obj, $fieldName, $className);

        if (empty($path)) {
            return null;
        }

        $mapping = $this->factory->fromField($obj, $fieldName, $className);
        $fs = $this->getFilesystem($mapping);

        return (string) $fs->readStream($path);
    }
```

This makes any streams returned by the Flysystem to be converted to a string, and not work.

The correct thing to do here would be to return a resource (the stream as it is) and not try to return a string.

**Comment by TerjeBr** [comment]
Also, another bug in this part of the code is that the line
```
$path = $this->resolvePath($obj, $fieldName, $className);
```

should rather be:
```
$path = $this->resolvePath($obj, $fieldName, $className, true);
```

It is very inefficient to resovle the path to an absolute path before passing it on to `readstream`.

**Comment by garak** [comment]
@TerjeBr please check if master is OK now. If so, we'll release a new tag.

**Comment by TerjeBr** [comment]
Yes, now it looks ok. Thank you for the quick fix.
