### ISSUE TITLE
Namer for 2 different property in same entity

### ISSUE THREAD

**Issue by aanthraxx** [dustin10/VichUploaderBundle#816]
Hi, i want to implement a namer that can change filename of two different property

for example:

i have these columns
file1, file2

then a FileNamer service

i want to set the filename of File1 to amazing-file1.pdf
and to File2 to awesome-file2.pdf

but i end up both fields have the same filenames.

**Comment by garak** [comment]
You can use this bundle to handle a single file related to a single object of yours.
If you need something different, you're on your own.

**Comment by aanthraxx** [comment]
right now i'm using it with EasyAdminBundle, can help how can I start building a namer per property?

**Comment by garak** [comment]
You can create a namer that create a **single** name taking informations from **two** properties.
You can't get two different names, because there just one file.
