### ISSUE TITLE
Show Videos not working

### ISSUE THREAD

**Issue by mkh01** [dustin10/VichUploaderBundle#817]
I'm using VichUploader to show some videos added in database Manual. I don't need create function cuz they are only 2 or 3 videos. is it the right way to show videos using VichUploader?

```
 {% for video in videos %}
     <video width="400" controls>
           <source src="{{ vich_uploader_asset(video, 'videoFile') }}" type="video/mp4">
     </video>
{% endfor %}
```

My database: 

``
    /**
     * @var string
     */
    private $videoName;

        /**
     * 
     * @Assert\File(
     *     mimeTypes = {"video/mp4", "video/quicktime", "video/avi"},
     *     mimeTypesMessage = "Wrong file type (mp4,mov,avi)"
     * )
     * @Vich\UploadableField(mapping="slider_video", fileNameProperty="videoName", size="videoSize")
     * 
     * @var File
     */
    private $videoFile;

 /**
     * Get videoName.
     *
     * @return string
     */
    public function getvideoName()
    {
        return $this->videoName;
    }

    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $video
     *
     * @return SliderVideo
     */
    public function setVideoFile(File $video = null)
    {
        $this->videoFile = $video;

        if ($video) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
        
        return $this;
    }

    /**
     * @return File|null
     */
    public function getVideoFile()
    {
        return $this->videoFile;
    }

    
    /**
     * @param integer $videoSize
     *
     * @return SliderVideo
     */
    public function setVideoSize($videoSize)
    {
        $this->videoSize = $videoSize;
        
        return $this;
    }
``

Any Help would be appreciated.

**Comment by garak** [comment]
What is the output of `{{ vich_uploader_asset(video, 'videoFile') }}`?

**Comment by mkh01** [comment]
It is Empty it shows only the Videos Controls, see the picture pls.

![videos](https://user-images.githubusercontent.com/24636291/34996808-05140c3e-fadb-11e7-9fe2-1c9c3e89f67d.PNG)

When i try to go directly to the real path it works right : 

<source src="{{ asset('uploads/videos/slider-vedios/slider.mp4')}}" type="video/mp4">

**Comment by garak** [comment]
What is the **HTML** output of {{ vich_uploader_asset(video, 'videoFile') }}?

**Comment by mkh01** [comment]
It is 

` <video width="400" controls="">
      <source src="/uploads/videos/slider-video/slider.mp4" type="video/mp4">
  </video>`

**Comment by garak** [comment]
It looks like that's the expected output.

**Comment by mkh01** [comment]
Yes it is but it shows no thing.  I don't know where the Problem could be. i used VichUploader many Times for Images before. But this is my first Time using it for Videos. Do you have Any Example for using it with videos?

**Comment by garak** [comment]
I'm afraid that HTML specs are out of the scope of this bundle. I'm sure that you'll find support on other channels, like stackoverflow

**Comment by mkh01** [comment]
Ok thank you any way.
