### ISSUE TITLE
VichFileType widget does not allow setting custom id attribute in Twig

### ISSUE THREAD

**Issue by Spunc** [dustin10/VichUploaderBundle#821]
Usually, I can assign a custom id attribute for a form_widget within in a Twig as follows:
```
{{ form_widget(form.fieldName, {'id': 'myCustomId'}) }}
```
But this does not work, if the field to be rendered is a VichFileType.

I would like the VichFileType form type to be more consistent to Symfony's build-in form types. Allowing to assign a custom id would also be of great benefit, because it eases to access the field by JavaScript in order to do some validation.

**Comment by cadavre** [comment]
Same with other attributes, like `{'attr': {'custom': 'value'}`.

**Comment by elvismdev** [comment]
Same here, I can't do this:

`{{ form_widget(adForm.imageFile1, {'attr': {'class': form_errors(adForm.imageFile1) == '' ? 'form-control-file' : 'form-control-file is-invalid'}}) }}`

No class attribute is rendered.

**Comment by kalyashka** [comment]
Quick fix using form theme:
```twig
{%- block vich_file_widget -%}
    <div class="vich-file">
        {{- form_widget(form.file, {'attr': attr}) -}}
        {%- if form.delete is defined -%}
            {{- form_row(form.delete) -}}
        {%- endif -%}

        {%- if download_uri -%}
            <a href="{{ asset_helper is same as(true) ? asset(download_uri) : download_uri }}">{{ translation_domain is same as(false) ? download_label : download_label|trans({}, translation_domain) }}</a>
        {%- endif -%}
    </div>
{%- endblock -%}
```

**Comment by garak** [comment]
I just tried and found these results:

1) `attr` option is working as expected. You can use `$builder->add('pic', VichImageType::class, ['attr' => ['class' => 'ciao', 'accept' => 'image/*'])` and get such attributes on your input field.

2) `id` option is not working. You can't pass `id` as `attr`. But it's the same for other Symfony types.

**Comment by garak** [comment]
Closing for missing feedback

**Comment by Coffee2CodeNL** [comment]
I suffer from this issue as well.

**Comment by garak** [comment]
> I suffer from this issue as well.

suffer no more:

> So, in the end you're still able to customize your field directly. If you need further customization, you still get the option of overriding template, as pointed above (even without id)

**Comment by butteredptarmigan** [comment]
I feel like this enhancement should be implemented (especially given the fact that it is a matter of one-liner that already has a pull request from @Coffee2CodeNL). Most of the time, the ability to specify form's/field's HTML attributes in both places – inside the class and in the template – is not just a matter of convenience, but also a huge boost to separation of concerns. For example, I don't think that a person who only does front-end/template design wants to interfere with back-end region on daily basis just to define HTML classes serving aesthetical purposes.
