### ISSUE TITLE
[BC-BREAK] Use >= 1.6.* without doctrine/annotation

### ISSUE THREAD

**Issue by sdespont** [dustin10/VichUploaderBundle#823]
Hello,

I am using this bundle for 3 years now, and it is very useful. Thanks.

I recently upgraded from Symfony 2.7 to Symfony 2.8 and therefore moved from version 1.4.* to 1.7.*. From this time, the bundle is longer working anymore : the entity is not handled by the bundle to process the uploaded file.

From your doc :

> First, annotate your class with the Uploadable annotation. This is really like a flag indicating that the entity contains uploadable fields.

The reason is that I am **NOT** using the Doctrine annotation for my project. I read from the 1.6.0 release note that  `doctrine/annotation`  is now a hard dependency https://github.com/dustin10/VichUploaderBundle/pull/711, but I don't know really why (new meta data? embeddable entity file?)

From the Symfony [doc](https://symfony.com/doc/2.8/doctrine.html) :

> A bundle can accept only one metadata definition format. For example, it's not possible to mix YAML metadata definitions with annotated PHP entity class definitions.

My question is : as `annotation` and `YAML` cannot be used at the same time on the same project, is there a way to use this bundle >= 1.6.* only with YAML or am I stuck to version 1.5.3?

Best regards

**Comment by sdespont** [comment]
I think you should add a notice about this in your [UPGRADE.md](https://github.com/dustin10/VichUploaderBundle/blob/master/UPGRADE.md) file

**Comment by garak** [comment]
I guess you already read UPGRADE and performed changes in your yaml filenames

**Comment by sdespont** [comment]
@garak thanks for your reply.

Yes, the yaml files have been renamed has requested `Entity.MyEntity.yml` in the `vich_uploader `folder. But it doesn't change anything. The configuration is like ignored.

**Comment by garak** [comment]
Did you clear cache? Not just running command, but deleting anything inside cache dir

**Comment by sdespont** [comment]
@garak Yes I swear. Are you saying that I should be work without using annotation in version >= 1.6?

FYI, I tried v1.6.0, 1.7.0 and 1.7.1 (in the reverse order because I was trying to find the last working version for me).

**Comment by garak** [comment]
I'm using this bundle with yaml only myself. Did you try to run vich debug commands?

**Comment by sdespont** [comment]
Oh that is a good news! No I didn't try to run this command.

How can I use it? Something like `php app/console vich:mapping:debug global_template`? 

It shows the same with v1.5.3 and 1.7.1:

```
> php app/console vich:mapping:debug global_template                                                                                                          
[2018-01-19 14:49:42] event.DEBUG: Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
[2018-01-19 14:49:42] event.DEBUG: Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DumpListener::configure".         
[2018-01-19 14:49:42] event.DEBUG: Notified event "console.command" to listener "Symfony\Bridge\Monolog\Handler\ConsoleHandler::onCommand".                   
Debug information for mapping global_template                                                                                                                 
uri_prefix: '/../../template'                                                                                                                                 
upload_destination: 'app/../../template'                                                         
namer: array (                                                                                                                                                
  'service' => 'tools.property_file_namer.global_template',                                                                                          
  'options' =>                                                                                                                                                
  array (                                                                                                                                                     
  ),                                                                                                                                                          
)                                                                                                                                                             
directory_namer: array (                                                                                                                                      
  'service' => 'tools.property_directory_namer',                                                                                                     
  'options' =>                                                                                                                                                
  array (                                                                                                                                                     
  ),                                                                                                                                                          
)                                                                                                                                                             
inject_on_load: false                                                                                                                                         
delete_on_update: true                                                                                                                                        
delete_on_remove: true                                                                                                                                        
db_driver: 'orm'           
```

**Comment by garak** [comment]
The other command

**Comment by sdespont** [comment]
Thanks @garak, the commands help me a lot.

After clearing the cache (delete the directory), the command `php app/console vich:mapping:list-classes` returns the wrong entities paths (without "entity" folder). Then, rerun this command lists the rights entity path.

I really don't know why the command must be run twice?! Perhaps it is related to my environment : Windows => vagrant box (ubuntu 16.04).

When the rights entities paths are displayed, everything works fine.

**Comment by garak** [comment]
So, can we close this?

**Comment by sdespont** [comment]
Yes, we can. Thanks for your time.
