### ISSUE TITLE
Directory not removed

### ISSUE THREAD

**Issue by olaviivask** [dustin10/VichUploaderBundle#825]
I'm using file namer and directory namer. After deleting file, file is removed, but directory still exists.

`      

product_files:

        uri_prefix: %app.path.product_files%

        upload_destination: %kernel.root_dir%/../web/uploads/products/files

        directory_namer:

          service: vich_uploader.directory_namer_subdir

          options: {chars_per_dir: 6, dirs: 1}

        namer:

          service: vich_uploader.namer_hash`

**Comment by garak** [comment]
Why do you expect directory is removed?

**Comment by Koc** [comment]
This is correct behavior
