### ISSUE TITLE
BC-Break inside StorageInterface

### ISSUE THREAD

**Issue by Koc** [dustin10/VichUploaderBundle#829]
https://github.com/dustin10/VichUploaderBundle/commit/2a39e12d078fb108a937f054b3b617c3a14f3a49#diff-eee6d060bc362bdd76df8851458b4595

Method signature change inside interface is BC-break. Is it not? http://symfony.com/doc/current/contributing/code/bc.html#changing-interfaces "Add type hint to an argument - change not allowed".

**Comment by garak** [comment]
In theory it is, but such interface is meant mainly for internal use.
Even a possible implementation for a custom storage system should follow the intended types (that are the ones now hinted)

**Comment by Koc** [comment]
Clear. But better do not do this kind of changes in minor versions. Can you add upgrade note https://github.com/dustin10/VichUploaderBundle/blob/master/UPGRADE.md ? (I cann't do this because don't know what also you have changed)
