### ISSUE TITLE
Image doesn't update

### ISSUE THREAD

**Issue by sonjadeissenboeck** [dustin10/VichUploaderBundle#832]
I've read through all the issues so far, but haven't found one that actually helped me solving my problem, so I'd like to open a new one and would be very thankful for your help!

I  have four pictures on my homepage banner and I'd like to be able to update them every now and then using a Symfony form.

I set up an Image Entity exactly as described in the Vich Uploader documentation (with updated At-Entity and everything)

```
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
* Image
*
* @ORM\Table(name="app_image")
* @ORM\Entity
* @Vich\Uploadable
*/
class Image {

  /**
   * @var integer
   *
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;

  /**
   * @Vich\UploadableField(mapping="dashboard", fileNameProperty="imageName", size="imageSize")
   *
   * @var File
   */
  private $imageFile;

  /**
    * @ORM\Column(type="integer")
    *
    * @var integer
    */
   private $imageSize;

   /**
    * @var string
    * @ORM\Column(type="string", nullable=false)
    */
   private $imageName;

   /**
   * @ORM\Column(type="datetime")
   *
   * @var \DateTime
   */
  private $updatedAt;

      /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     */
    public function setImageFile(?File $image = null): void
    {
        $this->imageFile = $image;

        if (null !== $image) {

            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return Image
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }
}
```

Since the four images already exist, I only added an action to update the images to my Controller

```
  /**
  * @Route("/uploadImage/{id}", name="appBundle_upload_image", requirements={"id" = "\d+"})
  * @Security("is_granted('ROLE_ATTACHEMENT_ADMIN')")
  */
  public function uploadAction(Request $request, $id){
    $repository = $this->getDoctrine()->getRepository('AppBundle:Image');
    $em = $this->getDoctrine ()->getManager ();
    $image = $repository->findOneById($id);
    $form = $this->createForm(UploadImageType::class, $image);
    $form->handleRequest($request);
    if ($form->isValid() ) {
      $em->flush();
      return $this->redirectToRoute('index');
    }
    return $this->render('AppBundle:Image:upload.html.twig', array(
      'form' => $form->createView(),
      'image' => $image,
    ));
  }
```

I already have some pictures in my database table, so I can access the route to my controller action, the form that gets rendered contains simply this:

```
  public function buildForm(FormBuilderInterface $builder, array $options): void
{

    $builder->add('imageFile', VichImageType::class, [
        'required' => false,
        'allow_delete' => false,
        'download_label' => '...',
        'download_uri' => true,
        'image_uri' => true,
    ]);
}
```

So as you can see, I didn't change a lot yet from the basic documentation. Anyway, when going to that route with e.g. ID 7, picture 7 is displayed under the download_uri and when dumping imageName or UpdatedAt, it's the same data as shown in my database table. But when I then try to upload a new picture which should replace the old one, I get an error saying

Entity AppBundle\Entity\Image@0000000075aa1d6c00000000789d890b is not managed. An entity is managed if its fetched from the database or registered as new through EntityManager#persist
or sometimes it goes through like a miracle and I get redirected, but nothing's changed in my database table, so the old picture didn't get replaced or anything.

As I said, I've searched a lot and found a lot of solutions for the Entity not managed error, or not updating because no property changed. But none of them actually solved my problem.

Do you see anything in my code that could cause the problem?

**Comment by sonjadeissenboeck** [comment]
nobody?

**Comment by garak** [comment]
It looks like your problem is more about Doctrine mapping than VichuploaderBundle. You should resolve by adding a "cascade-persist" option under your "one-to-many" mapping

**Comment by sonjadeissenboeck** [comment]
@garak  I don\t have a one-to-many mapping?

**Comment by garak** [comment]
So you're trying to persist the wrong entity

**Comment by garak** [comment]
You said you have four pictures, so you have four entities

**Comment by sonjadeissenboeck** [comment]
Hm, these four pictures are supposed to be entries in my Image entity. ID 1-4 and then I'd like to update them every now and them

**Comment by sonjadeissenboeck** [comment]
weirdly, the $imageFile property is always null.. do you know why?
@garak

**Comment by sonjadeissenboeck** [comment]
@garak are you still following? sorry, I'm really lost!

**Comment by garak** [comment]
Our current docs are wrong in some details. See PR #794

**Comment by sonjadeissenboeck** [comment]
All right, thanks for letting me know! Since I'm not really familiar with Pull requests etc. how can I proceed to solve my problem? :) @garak

**Comment by garak** [comment]
Just read the content of PR and adapt your code accordingly

**Comment by sonjadeissenboeck** [comment]
I read the content, but I am using $imageFile everywhere? and I'm also using the same setter e.g.? @garak

**Comment by sonjadeissenboeck** [comment]
@garak could you give me a hint what I should change? or somebody else I could ask?

**Comment by garak** [comment]
Please provide a full project where your issue is reproduceable

**Comment by sjuvonen** [comment]
This is kinda old but I'll answer anyway. The upload handler is implemented in a Doctrine event listener and if none of the mapped (Doctrine) fields change, the Vich update listener is not triggered. 
One solution would be to e.g. call $entity->setImageName(null) on upload to trigger the upload handler.
