### ISSUE TITLE
Service alias doesn't exist

### ISSUE THREAD

**Issue by mzmgh** [dustin10/VichUploaderBundle#833]
I'm using Symfony 3.4 and Vich Uploader 1.8.1.
This is `composer.lock` file of my project:
`...
"name": "vich/uploader-bundle",
"version": "1.8.1",
...
`
And this is `namer.xml` of bundle
<?xml version="1.0" encoding="UTF-8" ?>
<container xmlns="http://symfony.com/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <services>
        <service id="vich_uploader.namer_uniqid" class="Vich\UploaderBundle\Naming\UniqidNamer" public="true" />
        <service id="vich_uploader.namer_property" class="Vich\UploaderBundle\Naming\PropertyNamer" public="true" />
        <service id="vich_uploader.namer_origname" class="Vich\UploaderBundle\Naming\OrignameNamer" public="true" />
        <service id="vich_uploader.namer_hash" class="Vich\UploaderBundle\Naming\HashNamer" public="true" />
        <service id="vich_uploader.namer_base64" class="Vich\UploaderBundle\Naming\Base64Namer" public="true" />

        <service id="vich_uploader.directory_namer_subdir" class="Vich\UploaderBundle\Naming\SubdirDirectoryNamer" public="true" />
        <service id="vich_uploader.namer_directory_property" class="Vich\UploaderBundle\Naming\PropertyDirectoryNamer" public="true">
            <argument type="service" id="form.property_accessor" />
        </service>
    </services>
</container>
But I don't have aliases. Why?

**Comment by garak** [comment]
Where are you're looking for aliases?

**Comment by mzmgh** [comment]
@garak 
I looking in `vendor\vich\uploader-bundle\Resources\config\namer.xml`

**Comment by garak** [comment]
We need to release a new tag. Meanwhile, you can require `1.8*@dev` version

**Comment by mzmgh** [comment]
@garak 
I get `dev-master` and now it is ok.

**Comment by garak** [comment]
Don't do it: you're risking to get next major version and break your project. It's safer to rely con current branch-alias

**Comment by mzmgh** [comment]
@garak 
But I got an error when I require `1.8*@dev` I think the right version is `1.8.*@dev`.

**Comment by garak** [comment]
It is, my bad

**Comment by mzmgh** [comment]
Is `1.8.*@dev` safe for using in project?

**Comment by garak** [comment]
Absolutely
