### ISSUE TITLE
ImageFile is null after upload

### ISSUE THREAD

**Issue by sonjadeissenboeck** [dustin10/VichUploaderBundle#836]
When I upload an Image with the Vich Uploader Bundle, the image name, updatedAt and size is set correctly and also stored in my database table. However, the imageFile property is always NULL.

I've read the documentation, advising to be cautious with the ImageFile Setter when using doctrine but I can't figure what to do to get it working.

Here is my Entity:

```
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
* Image
*
* @ORM\Table(name="app_image")
* @ORM\Entity
* @Vich\Uploadable
*/
class Image {

  /**
   * @var integer
   *
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;

  /**
   * @Vich\UploadableField(mapping="carousel", fileNameProperty="imageName", size="imageSize")
   *
   * @var File
   */
  private $imageFile;

  /**
    * @ORM\Column(type="integer")
    *
    * @var integer
    */
   private $imageSize;

   /**
    * @var string
    * @ORM\Column(type="string", nullable=false)
    */
   private $imageName;

   /**
   * @ORM\Column(type="datetime")
   *
   * @var \DateTime
   */
  private $updatedAt;

   public function getImageFile(){
     return $this->imageFile;
   }

    /**
  *
  * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image

  */
    public function setImageFile(File $image = null)
    {
      $this->imageFile = $image;
      if ($image instanceof File) {
        $this->updatedAt = new \DateTime();
      }

    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return Image
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set imageSize
     *
     * @param integer $imageSize
     *
     * @return Image
     */
    public function setImageSize($imageSize)
    {
        $this->imageSize = $imageSize;

        return $this;
    }

    /**
     * Get imageSize
     *
     * @return integer
     */
    public function getImageSize()
    {
        return $this->imageSize;
    }

    /**
     * Set imageName
     *
     * @param string $imageName
     *
     * @return Image
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * Get imageName
     *
     * @return string
     */
    public function getImageName()
    {
        return $this->imageName;
    } 
}
```
I've also tried this way for the setter, but it didn't work either:

```
 /*
 * @param File|UploadedFile $image
 */
public function setImageFile(File $image = null)
{
    $this->imageFile = $image;

    if (null !== $image) {
        $this->updatedAt = new \DateTimeImmutable();
    }
}
```
Here is my mapping:

```
carousel:
        uri_prefix: %non_public_upload_dir%/carousel
        upload_destination: "%non_public_upload_dir%/carousel"
        namer: vich_uploader.namer_origname

        # lifecycle events
        inject_on_load:     false
        delete_on_update:   true
        delete_on_remove:   true
```
Any ideas where my problem is?

**Comment by sonjadeissenboeck** [comment]
Noone?

**Comment by stevechilds** [comment]
I've got the same issue :(

As far I can see I've done everything as per the instructions and likewise, the property is always null after upload.

**Comment by stevechilds** [comment]
LOL, how typical is that. I immediately realise what's missing - the enctype on the form, it wasn't set to "multipart/form-data".

**Comment by marcharding** [comment]
Did you use the VichFileType (NOT the symfony FileType) in your FormType?

**Comment by ewasos** [comment]
I have near the same issue! And I have no more idea to resolve it !  I can't  store in my database table the path of my uploaded file !! the **image**  and **imageSize** properties are always NULL in my database..

HELP 

Here is my Entity:

`
/**
 * News
 *
 * @ORM\Table(name="news")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\NewsRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable
 */
class News
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="titre", type="string", length=255)
     */
    private $titre;

    
    /**
     * @var string
     *
     * @ORM\Column(name="contenu", type="string", length=255)
     */
    private $contenu;

	
	/**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="news_images", fileNameProperty="image", size="imageSize", nullable=true)
     * @var File $imageFile
     */
    private $imageFile;
	
	 /**
     * @ORM\Column(type="integer", nullable=true)
     *
     * @var integer
     */
    private $imageSize;


    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime
     */
    private $updatedAt;
	
    /**
	 *
     * @var \DateTime
     *
     * @ORM\Column(name="created_on", type="date", nullable=true)
     */
    private $createdOn;

	public function __construct() {
		$this->createdOn = new \DateTime();
		$this->updatedAt = new \DateTime();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set titre
     *
     * @param string $titre
     *
     * @return News
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;

        return $this;
    }

    /**
     * Get titre
     *
     * @return string
     */
    public function getTitre()
    {
        return $this->titre;
    }

   
    /**
     * Set contenu
     *
     * @param string $contenu
     *
     * @return News
     */
    public function setContenu($contenu)
    {
        $this->contenu = $contenu;

        return $this;
    }

    /**
     * Get contenu
     *
     * @return string
     */
    public function getContenu()
    {
        return $this->contenu;
    }

    /**
     * Set createdOn
     *
     * @param \DateTime $createdOn
     *
     * @return News
     */
    public function setCreatedOn($createdOn)
    {
        $this->createdOn = $createdOn;

        return $this;
    }

    /**
     * Get createdOn
     *
     * @return \DateTime
     */
    public function getCreatedOn()
    {
        return $this->createdOn;
    }
	
	/**
     * Set image
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     */
	public function setImageFile(?File $image = null): void
    {
        $this->imageFile = $image;

        if (null !== $image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
		
    }
	
	/**
     * Get imageFile
     *
     * @return File
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

	/**
     * Set image
     *
     * @param string $image
     *
     */
    public function setImage(?string $image):void
    {
        $this->image = $image;
    }

	 /**
     * Get image
     *
     * @return string
     */
    public function getImage(): ?string
    {
        return $this->image;
    }
	
	/**
     * Set imageSize
     *
     * @param integer $imageSize
     *
     * @return News
     */
	 public function setImageSize(?int $imageSize) :void
    {
        $this->imageSize = $imageSize;
    }

	/**
     * Get imageSize
     *
     * @return integer
     */
    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    
	

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return News
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }
}

`
And Here is my mapping:
`
parameters:
    news_directory: '%kernel.project_dir%/web/uploads/news'
    app.news_image.path: /uploads/images/news

vich_uploader:
    db_driver: orm  
    mappings:
        news_images:
            uri_prefix: '%app.news_image.path%'
            upload_destination: '%kernel.root_dir%/../web/uploads/news'
            namer: vich_uploader.namer_origname
            # lifecycle events
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
`

and NewType.php

`....
$builder
		->add('titre', TextareaType::class, array(
				'label' => "Titre de l'article :",
				'required' => false
				))
		->add('imageFile', VichFileType::class, array(
				'required' => false,
				'allow_delete' => true,
				'download_link' => true
				))
		->add('contenu', TextareaType::class, array(
				'label' => "Texte Article - le contenu :",
				'required' => false
				))
		;
...

`

Please

**Comment by giorgiopagnoni** [comment]
This somehow started to happen in a easy_admin backend where I last successfully used Vich in June. The site hasn't been updated since then, but now that I have to upload a few pictures, it doesn't work anymore. The only thing that I think has changed is that I had updated symfony/flex. I'll post the code here anyway...

```
Picture:
    class: App\Entity\Picture
    form:
          fields:
               - { property: 'imageFile', type: 'vich_image' }
               - caption
               - activity
```

```
vich_uploader:
    db_driver: orm

    mappings:
        activities:
            uri_prefix: /uploads/activities
            upload_destination: '%kernel.project_dir%/public/uploads/activities'
```

```
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="activities", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $updatedAt;

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime();
        }
    }
```

**Comment by berengergermain** [comment]
> 
> 
> LOL, how typical is that. I immediately realise what's missing - the enctype on the form, it wasn't set to "multipart/form-data".

THANK YOU ! After 1 hour searching around why my form doesn't submit the file, you save my day :)

I explain quickly : I have a form which contains one dynamic field, understand one field that could be a text or an image depending on previous fields values (The magic is done with SF form event and ajax request, as recommended in the doc). When I update the form with JS I use to forget to set the enctype when I change the field from text to file, so the form submit well without any errors but no file were uploaded.
