### ISSUE TITLE
Compile Error after Symfony 3.4 update

### ISSUE THREAD

**Issue by aguidis** [dustin10/VichUploaderBundle#837]
I decided to update the framework version to `^3.4` and update the VichUploaderBundle to `^1.8` but 

> the script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception:

```
 Compile Error: Declaration of VichUploaderBundleStorageGaufretteStorage_000
  000006f5edc2e00000000405312f0210405bc69a384c828e00d0899e7e146::upload($obj,
   Vich\UploaderBundle\Mapping\PropertyMapping $mapping) must be compatible w
  ith Vich\UploaderBundle\Storage\StorageInterface::upload($obj, Vich\Uploade
  rBundle\Mapping\PropertyMapping $mapping): void
```

Any idea ?

**Comment by garak** [comment]
Clear your cache

**Comment by aguidis** [comment]
Thanks for your fast answer. I deleted all the cache directories and then it worked.

Sorry for this inconvenience.
