### ISSUE TITLE
DownloadHandler dont work with stream

### ISSUE THREAD

**Issue by piotrantosik** [dustin10/VichUploaderBundle#841]
File object has invalid path if storage is Flysystem or Gaufrette.

https://github.com/dustin10/VichUploaderBundle/blob/19686dd8822e79634d668b2301b2ae3f3ba4bcf4/Handler/DownloadHandler.php#L42

**Comment by garak** [comment]
Please provide more informations

**Comment by piotrantosik** [comment]
Ok, i try explain :)
I use VichUploader with flysystem with local adapter, in config i set `inject_on_load: true`
Entity has injected file in FileInjector:
https://github.com/dustin10/VichUploaderBundle/blob/master/Injector/FileInjector.php#L31
but path passed to the file object is just a file name - so it is created with `checkPath` as false
And now, i try use `DownloadHandler` on this entity and i get a error on line:
https://github.com/dustin10/VichUploaderBundle/blob/master/Handler/DownloadHandler.php#L47
`MimeTypeGuesser` try guest mimetype but it does not know the correct file location and throw exception
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/File/MimeType/MimeTypeGuesser.php#L121

I think VichUploader should't use `File` class if storage is not a local file system.

**Comment by garak** [comment]
So, what's you proposed solution?

**Comment by garak** [comment]
I checked the code and `File` should be a valid file even when the path is not checked, so it should be not throw exception when mime type is guessed.
Can you try to debug or dump the value of your file and see what type is it?

**Comment by garak** [comment]
Closing for missing feedback
