### ISSUE TITLE
Removing files in Embedded Collection Form doesn't work

### ISSUE THREAD

**Issue by eco3** [dustin10/VichUploaderBundle#842]
I'm working a form with an embedded collection form to upload multiple files of the same type. [This](https://github.com/skornev/vichbundle-sandbox-not-cp-symfony3.3) describes my main build. Just set [this](https://github.com/skornev/vichbundle-sandbox-not-cp-symfony3.3/blob/master/src/AppBundle/Form/InvoiceAttachmentType.php#L31) here to true.

Now I'm trying to add an option to let the user be able to remove uploaded files. However as soon, as the user edits an existing entity and checks the "Delete this" checkbox, Symfony tries to update the attribute fileName to NULL, which is forbidden in the InvoiceAttachment. After setting fileName to nullable=true and trying to delete a file again, it updates the database entry and sets it fileName to NULL and removes the file from the disk. However the database entry stays. So I have a unsynchronized state: file was removed but database not updated.

**Comment by frostieDE** [comment]
I can confirm that when working with a One-To-Many relationship (in which the Many-entity is the uploadable entity) deletion is not working properly. 

Expectation: the entity is removed from the database.

First symptom: properties related to the uploadable stuff are set to `null`. Why does the `PropertyMapping::erase` method need to set those values to `null`? The entity needs to be removed from the underlying database instead.

Second symptom: after allowing the `PropertyMapping` to set the described values to `null`, the entity is not removed from the relationship. Instead it is persisted to the database and thus still exists even thouth the file was already removed from the filesystem.

**Comment by frostieDE** [comment]
BTW: Manually removing the using a separate listener (which subscribes to the `postRemove` event provided by the VichUploaderBundle does not work either. The entity is removed from the database, but somehow Symfony adds a new one which is completely empty:

```
An exception occurred while executing 'INSERT INTO document_attachment (filename, size, updated_at, document_id) VALUES (?, ?, ?, ?)' with params [null, null, "2019-05-09 20:29:47", 6]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'filename' cannot be null
```

**Comment by garak** [comment]
First of all, the `fileName` property must be nullable.
Second, your expectation that entity should be removed from database is wrong. The file is deleted from the entity, and this bundle can't know that your entity is useless without a file.
To be clear: you must take care of entity deletion on your own.
@frostieDE please open your issue and provide a working project when this happens
