### ISSUE TITLE
VichImageType with "download_uri" and "image_uri" not working in production environment

### ISSUE THREAD

**Issue by sonjadeissenboeck** [dustin10/VichUploaderBundle#843]
I'm using both, vichImageType and vichFileType in my project. In testing environment, on my local machine everything is working. Yesterday I pushed my code to the production server and suddenly I get the error message:

> The options "download_uri", "image_uri" do not exist. Defined options are: "action", "allow_delete", "allow_extra_fields", "attr", "auto_initialize", "block_name" ....

Has that happened before to anyone else?
Test and Production environment are both on the same vich/uploader-bundle version so this can't really make the difference..

I'm happy to provide more code wherever needed. Just let me know which parts!

**Comment by garak** [comment]
How did you find installed version of bundle?
Try with `composer show | grep vich`

**Comment by sonjadeissenboeck** [comment]
It's 1.7.1 :)

**Comment by garak** [comment]
It's a problem on your side. Double check your production environment

**Comment by sonjadeissenboeck** [comment]
I understand that and I fixed it with simply not mentioning download_uri and image_uri. 
But now, there is an error saying 'image_size' can't be null. Everything else is set correctly but the image size is always null. Do you know where that problem might lay? Same thing, working on test but not on production. I understand that's a problem on my side but you are more into the topic and probably heard more issues than i did so you would know rather know where to look for my problem?
