### ISSUE TITLE
Please respect Semver

### ISSUE THREAD

**Issue by Nyholm** [dustin10/VichUploaderBundle#847]
I see that 1.8 has added return types on many places. And as you say in the [upgrade docs](https://github.com/dustin10/VichUploaderBundle/blob/master/UPGRADE.md#upgrading-from-v160-to-180): 

> we enforced, via type-hinting, as many parameters and return values as we can. This is formally a BC break, but likely you don't need to change anything in your code

Yes it is *formally* a BC break. That is why you cannot do a minor release. You have to do a major one. No matter how "likely" you think it is that I need to change anything. 

I suggest removing the BC break and release 1.8.1. Then, optionally, re-add them again and release 2.0. 

Im sorry if I sound aggressive, that is not my intention. But this is a major issue.

**Comment by garak** [comment]
We agree that is _formally_ a BC break, question is if it is _actually_ a BC break.
Did you get a compatibility issue while upgrading?

**Comment by Nyholm** [comment]
Hehe. Yes it actually breaks BC. :)

 I implemented the NamerInterface. And now I have to update my implementation because of the new signature. I’ve also overridden some protected functions.

**Comment by garak** [comment]
OK, but did you get a real compatibility issue? Not something you can solve by just adding a return type

**Comment by Nyholm** [comment]
Yes I got a "real compatibility issue". When I ran composer install a bunch of errors were thrown in my face. 

And yes, I solved it by updating the method signature, but that is irrelevant. You should not be afraid of using a new major version. I mean, you just broke BC and that is far more scary.

**Comment by garak** [comment]
Well, the BC break already happened and I can't change that.
I can't even remove the changes that caused such break without breaking again.
So, I'm afraid we'll need to live with that

**Comment by Nyholm** [comment]
>  I can't even remove the changes that caused such break without breaking again.

Oh, that is right... Okey. We have to make sure we are more careful in the future then.

**Comment by garak** [comment]
Thanks for understanding. I'm sorry about your problem with BC-break and I promise I'll be super careful in next releases
