### ISSUE TITLE
How to log missing images

### ISSUE THREAD

**Issue by benr77** [dustin10/VichUploaderBundle#849]
Is there any mechanism to log 404's to images using the URL resolver?

Say I'm using `vich_uploader_asset` in a Twig template, and the images are hosted on Amazon S3 via a Flysystem filesystem, is there a way to log (e.g. with monolog) any broken images?

There does not appear to be any support for this via Flysystem itself.

I'm also using LiipImagine to resize images so perhaps that is an alternative location to try and detect this?

Any suggestions appreciated. Thanks.

**Comment by garak** [comment]
https://symfony.com/doc/current/reference/events.html#kernel-exception

**Comment by benr77** [comment]
Ah I see thanks. In my case LiipImagine is throwing the exceptions so I've just created a listener for those exceptions and then log it to a dedicated log channel.
