### ISSUE TITLE
logout (FOSUserBundle) after submit edit form if file doesn't exist

### ISSUE THREAD

**Issue by LanmanGroup** [dustin10/VichUploaderBundle#850]

**Comment by garak** [comment]
Please provide more informations

**Comment by LanmanGroup** [comment]
I have an admin area with access_control managed by FOSUserBundle.
Example entity: **Team**
VichUploaderBundle works good and I'm able to upload/edit/delete the profile pic.
If I manually delete the uploaded image from filesystem when I try to edit the entity (ex route: /admin/team/1/edit), after submit form I'm signed out 
`security.INFO: Populated the TokenStorage with an anonymous Token. [] []`
This happens ONLY If the file doesn't exist in file system.

**Comment by garak** [comment]
I guess you should open an issue on FOSUserBundle then

**Comment by garak** [comment]
Closing for missing feebdack
