### ISSUE TITLE
Bind vich upload to fields added by javascript

### ISSUE THREAD

**Issue by Ashallar** [dustin10/VichUploaderBundle#851]
Hi there,

i have a solution running Symfony 3

I have my `Trainer` entity, which has a reference to `User` (which contains generic information about users, id, registrationDate ..) entity and in `User` entity i have a reference to Documents which is a list of `Document` entity. Each `Document` entity contains all the informations for an uploaded document (Type of document, name, upload date, extension and so on) bound to the `User`.

In my `Trainer` creation view(so the trainer entity isn't yet created), i have a page that allow the `Trainer` to upload and attach documents to his profile, so i allow the trainer to click on a button that dynamically inject HTML fields to type the name of the document, the type, and upload the file (via Vich uploader).

My problem is that i don't really know if it's possible to bind vichuploader to dynamically added html fields, to display the filepicker, keep it, and then create a Document that i bound to my User entity in my newly created Trainer entity.

Is that even possible ? Or is it just that my approach of the problematic isn't a good approach for symfony in general ?

(I don't know if i should post the issue there also, if not, sorry about that..)

**Comment by garak** [comment]
This bundle is mainly about mapping files with entities. It doesn't matter how you "attach" your instance of UploadedFile to your entity, as long as entity is correctly mapped (and VichUploaderBundle correctly configured).
So, form is an implementation detail that is left to the developer. We include some examples in thins bundle just to help in the "classic" Symfony form approach, but you're not limited to it
