### ISSUE TITLE
SplFileInfo::getSize(): stat failed for D:\xampp\tmp\php4B14.tmp

### ISSUE THREAD

**Issue by WassabiVl** [dustin10/VichUploaderBundle#853]
Hi all:

I am Facing a small problem using the bundle. we have  special use-case that doesn't allow us to delete or update a File/Document. so every time a file is uploaded, a new entity has to be created in the database with the new file linked to it. the document table is on its own, and has a OntToOne relationship to the other Table entity

the method I'm using is to call the form after submitting and crate a new document file entity, but i am always getting the error stated above. here is a screenshot of the problem 
![image](https://user-images.githubusercontent.com/26925021/37350112-41d82df2-26d8-11e8-9acd-6ba4917fbc8d.png)

the code on the controller is as follows
```
 public function uploadAction(OrderedProductCategory $orderedProductCategory, Request $request){
        $em = $this->getDoctrine()->getManager();
        $previousDocVersion = $orderedProductCategory->getADRDocument();
        $document = new Document();
        $document->setPreviousVersion($previousDocVersion);
        $document->setDocType('ADR');
        $form = $this->createForm(CarrierDocumentFormType::class, $document);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($document);
            $orderedProductCategory->setADRDocument($document);
            $em->persist($orderedProductCategory);
            $em->flush();
            return $this->redirectToRoute('carrier_dashboard');
        }
        return $this->render('user_dashboard/common_dashboard/upload.html.twig', array('form'=>$form->createView()));
    }
```

and this is the Entity class
```
<?php
/**
 * Created by PhpStorm.
 * User: giese
 * Date: 25.10.2017
 * Time: 12:37
 *
 * This needs a lifecycle...doooiinnggggg
 * http://symfony.com/doc/2.2/cookbook/doctrine/file_uploads.html
 * https://symfony.com/doc/3.4/controller/upload_file.html
 */
namespace AppBundle\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity
 * @ORM\Table(name="document")
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks()
 */
class Document
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    protected $id;
    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $name;

    /**
     * @ORM\OneToOne(targetEntity="Document", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="previous_version", referencedColumnName="id", nullable=true)
     * @var Document
     */
    private $previousVersion;
    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     * @var datetime
     */
    private $dateUploaded;
    /**
     * @ORM\Column(type="string", columnDefinition="ENUM('UG','Bill','OrderConfirmation', 'ADR')")
     */
    private $docType;

    /**
     * @Vich\UploadableField(mapping="document_file", fileNameProperty="name")
     * @var File
     */
    private $documentFile;

    public function __toString() {
        return $this->name;
    }


    /**
     * @return string
     */
    public function getDocType()
    {
        return $this->docType;
    }

    /**
     * @param string $docType
     */
    public function setDocType($docType)
    {
        $this->docType = $docType;
    }

    /**
     * @return \DateTime
     */
    public function getDateUploaded()
    {
        return $this->dateUploaded;
    }

    /**
     * @param mixed $dateUploaded
     */
    public function setDateUploaded($dateUploaded)
    {
        $this->dateUploaded = $dateUploaded;
    }

    /**
     * @return string|null
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return void
     */
    public function setName($name): void
    {
        $this-> name = $name;
    }


    /**
     * @return Document
     */
    public function getPreviousVersion()
    {
        return $this->previousVersion;
    }

    /**
     * @param Document $previousVersion
     */
    public function setPreviousVersion($previousVersion)
    {
        $this->previousVersion = $previousVersion;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }
    

    /**
     * @return File
     */
    public function getDocumentFile(): ?File
    {
        return $this->documentFile;
    }

    /**
     * * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     *
     * @param File|UploadedFile $documentFile
     * @return void
     */
    public function setDocumentFile(?File $documentFile = null): void
    {
        $this->documentFile = $documentFile;
        if (null !== $documentFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->dateUploaded = new \DateTimeImmutable();
        }
    }


}
```

is there a use case for this method or is there a workaround?

**Comment by WassabiVl** [comment]
I actually found the solution.
i created an event listener and created a whole new entity onVichUploaderPreUpload.
the problem was trying to read the temp file as it was being processed. 

I hope some others may benefit form this.

**Comment by Ragash** [comment]
@WassabiVl mind sharing the solution?

it will help newbie (like me) who encountered the same problem

**Comment by WassabiVl** [comment]
The Problem came as a two fold, the first, is that we have a special use case so a controller was needed to handle the upload, the second problem is that this bundle needs a SAL (Storage Abstraction Layer) to handle the temp file as it is being moved around. I used FlySystem. well the controller is a bad practice (it should be an event listener, but here is the code 

```php
public function persistFile($file, Document $previousVersion = null, $docType =null): Document
    {
        $document = new Document();
        $document->setDocumentFile($file);
        $document->setPreviousVersion($previousVersion);
        $document->setDocType($docType);
        return $document;

    }
```

**Comment by vishal-iwd** [comment]
public function genernalupdate(Request $request){
		$request->validate([
			'site_name' => 'required|max:255',
			'site_email' => 'required|email',
		]);
		if($request->hasFile('site_logo')) {
			$request->validate([
				'site_logo' => 'mimes:jpeg,jpg,png,gif|required|max:10000',
            ]);
		}
		$all_post  			= $request->all();
		if($all_post){
			foreach($all_post as $key=>$row){
				if($key!='_token'){
					if($key =='site_logo'){
						$count 		= Setting::where('setting_key',$key)->count();
						if ($files = $request->file('site_logo')) {
							$destinationPath 	= public_path().'/uploads/logoimages/'; // upload path
							$logoImg 			= time() . "." . $files->getClientOriginalExtension();
							
						}
						if($count > 0){
							$setting 	= Setting::where('setting_key',$key)->firstOrFail();
							$image_path = public_path().'/uploads/logoimages/'.$setting->setting_value;
							if(file_exists($image_path)){
								unlink($image_path);
							}
							$setting_value 			 = $logoImg;
							Setting::where('setting_key', $key)->update(array('setting_value' => $setting_value));
						}
						else{
							$setting 				= new Setting;
							$setting->setting_key 	= $key;
							$setting->setting_value = $logoImg;
							$setting->setting_tab 	= 'general';
							$setting->save();
							$files->move($destinationPath, $logoImg);
						}
					}
					else{
						$setting_value = $row;
						Setting::where('setting_key', $key)->update(array('setting_value' => $setting_value));
					}
					
					
				}
			}
		}
		
		Session::flash('message', 'General setting update successfully!'); 
		Session::flash('alert-class', 'alert-success'); 
		return redirect('/setting/general'); 
	}
