### ISSUE TITLE
Eror return value 

### ISSUE THREAD

**Issue by fyher** [dustin10/VichUploaderBundle#855]
i have this 
Type error: Return value of Vich\UploaderBundle\Vich  
  UploaderBundle::build() must be an instance of Vich\UploaderBundle\void, none returned

do you have the idea ? 

thanks

**Comment by garak** [comment]
Upgrade to php 7.1 (or 7.2)

**Comment by fyher** [comment]
think yes on the dev server I have php 7.1 and in prod 7.0

**Comment by garak** [comment]
https://getcomposer.org/doc/06-config.md#platform

**Comment by paul-mesnilgrente** [comment]
I had the same on my production server.

Here is my configuration:

```text
4.4.0-124-generic #148-Ubuntu (Ubuntu server 16.04)
PHP 7.2.5-1+ubuntu16.04.1+deb.sury.org+1
Apache2.4
```

**Note:** I have insalled the newest version of php with this ppa `ondrej/php`.

Do you know where it can come from?

**Comment by garak** [comment]
@paul-mesnilgrente you're messing something. There's no way you can get such error on php 7.2

**Comment by paul-mesnilgrente** [comment]
@garak thanks for this affirmation, you were totally right. After the upgrade to PHP 7.2, I didn't know that I had to add it to the apache2 configuration by running `a2enmod php7.2`. It works now. Thank you very much!
