### ISSUE TITLE
How to add class to the delete checkbox?

### ISSUE THREAD

**Issue by crabnky** [dustin10/VichUploaderBundle#856]
Hi,
How can I add css classes to the delete checkbox?
Thanks.

**Comment by garak** [comment]
You can override bundle's templates

**Comment by crabnky** [comment]
Yeah, trying, but probably doing something wrong. Here is a part for delete checkbox:
```
{% if form.delete is defined %}
    <div class="column is-narrow">
        {{ form_label(form.delete) }}
        <div class="is-choice">
            {% set attr = {'class': 'switch is-medium is-rounded'} %}
            {{ form_widget(form.delete) }}
        </div>
    </div>
{% endif %}
```
attr does not work as this is compound widget, right? How can I pass attr to the checkbox?

**Comment by garak** [comment]
try with
`{{ form_widget(form.delete, {attr: {class: 'foobar'}}) }}`

**Comment by crabnky** [comment]
Hah, of course, shame on me - how come I did not think of the simplest way. :|
Thanks much!
