### ISSUE TITLE
SplFileInfo::getSize(): stat failed for C:\Bitnami\wappstack\php\tmp\php2AB6.tmp

### ISSUE THREAD

**Issue by methodeprog** [dustin10/VichUploaderBundle#857]
| Q                          | A
| -------------------------- | -----
| Bug report?                | yes
| Feature request?           | no
| BC Break report?           | no
| Symfony version            | 4.0.6
| VichUploaderBundle version | ^1.7

**Comment by garak** [comment]
You should provide some more informations...

**Comment by methodeprog** [comment]
My main form is 

class DirectoryType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('logoFile', VichFileType::class, [
                'required' => false,
                'allow_delete' => true,
                'download_uri' => '...',
                'download_label' => '...',
            ])
            ->add('brochureFile', VichFileType::class, [
                'required' => false,
                'allow_delete' => true,
                'download_uri' => '...',
                'download_label' => '...',
            ])

//////////////////////////////////////////////

And related form are

use Symfony\Component\Form\Extension\Core\Type\FileType;

class LogoType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    $builder
    ->add('logoFile', FileType::class, [
        'multiple' => 'false',
        'label' => false,
        'required' => false,
    ])
    ;
  }

///////////////////////////////////////////////////////////

And

use Vich\UploaderBundle\Form\Type\VichFileType;


class BrochureType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options)
  {

    $builder
        ->add('brochureFile', VichFileType::class, [
            'required' => false,
            'allow_delete' => true,
            'download_uri' => '...',
            'download_label' => '...',
        ]);
  }

**Comment by garak** [comment]
Other informations needed:
* when the error occurs
* a full stack of error

**Comment by methodeprog** [comment]
![image](https://user-images.githubusercontent.com/18600282/37722481-0557a6d0-2d24-11e8-96c5-1684b5fa5173.png)

**Comment by methodeprog** [comment]
![image](https://user-images.githubusercontent.com/18600282/37722507-18e3997a-2d24-11e8-9716-77c93fe9a034.png)

**Comment by garak** [comment]
Still missing the "when"

**Comment by garak** [comment]
Please update bundle version to reflect your actual installed version, and provide your template/controller code

**Comment by methodeprog** [comment]
My template controller
////////////////////////////////////////
                         <div class="form-group">
                                          <label class="col-md-3 control-label" for="demo-text-input">
                                          {{ form_label(form.logoFile) }}
                                          </label>
                                          <div class="col-md-6">
                                          {{ form_widget(form.logoFile, {'attr': {'class':'pull-left btn btn-primary btn-file' }}) }}
                                      </div>
                                      </div>


                         <div class="form-group">
                                          <label class="col-md-3 control-label" for="demo-text-input">
                                          {{ form_label(form.brochureFile) }}
                                          </label>
                                          <div class="col-md-6">
                                          {{ form_widget(form.brochureFile, {'attr': {'class':'pull-left btn btn-primary btn-file' }}) }}
                                      </div>

**Comment by methodeprog** [comment]
My template file 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////

                                      <div class="form-group">
                                          <label class="col-md-3 control-label" for="demo-text-input">
                                          {{ form_label(form.logoFile) }}
                                          </label>
                                          <div class="col-md-6">
                                 {{ form_widget(form.logoFile, {'attr': {'class':'pull-left btn btn-primary btn-file'  }}) }}
                                      </div>
                                      </div>
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                      <div class="form-group">
                                          <label class="col-md-3 control-label" for="demo-text-input">
                                          {{ form_label(form.brochureFile) }}
                                          </label>
                                          <div class="col-md-6">
                        {{ form_widget(form.brochureFile, {'attr': {'class':'pull-left btn btn-primary btn-file' }}) }}
                                      </div>

**Comment by methodeprog** [comment]
My Controller


    /**
     * @Route("/new", name="directory_new" )
     *
     */
    public function newAction(Request $request)
    {
        $user = $this->getUser();

        $directory = new Directory();

        $directory->setUser($this->getUser());

        $form = $this->createForm(DirectoryType::class, $directory);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $em = $this->getDoctrine()->getManager();
            $em->persist($directory);
            $em->flush();

            $request->getSession()->getFlashbag()
                ->add('success','Registration is success ! You can add more enterprises ! And its free ! ');
            return $this->redirectToRoute('directory_index');
        }

        return $this->render('directory/new.html.twig', array(
            'user' => $user,
            'directory' => $directory,
            'form' => $form->createView(),
        ));
    }

**Comment by garak** [comment]
template is incomplete

**Comment by methodeprog** [comment]
Just to be short,

{{ form_start(form, {'attr': {'class':'panel-body form-horizontal form-padding' }}) }}


                                  <div class="form-group">
                                      <label class="col-md-3 control-label" for="demo-text-input">
                                      {{ form_label(form.logoFile) }}
                                      </label>
                                      <div class="col-md-6">
                     {{ form_widget(form.logoFile, {'attr': {'class':'pull-left btn btn-primary btn-file'  }}) }}
                                  </div>
                                  </div>
                                  <div class="form-group">
                                      <label class="col-md-3 control-label" for="demo-text-input">
                                      {{ form_label(form.brochureFile) }}
                                      </label>
                                      <div class="col-md-6">
                    {{ form_widget(form.brochureFile, {'attr': {'class':'pull-left btn btn-primary btn-file' }}) }}
                                  </div>

                  <div class="form-group">
                                            <div class="col-sm-9 col-sm-offset-3">
                  <button class="btn btn-mint" type="submit">Add your Enterprise</button>
                 <button class="btn btn-mint" type="submit">Add your Enterprise</button>
                 <button class="btn btn-warning" type="reset">Reset</button>
                                            </div>
                                            </div>

            	{{ form_end(form) }}

**Comment by garak** [comment]
Configuration?

**Comment by methodeprog** [comment]
vich_uploader:
    db_driver: orm
    templating: true        # set to false to disable templating integration
    twig:       true        # set to false to disable twig integration (requires templating)
    form:       true        # set to false to disable form integration
    metadata:
        auto_detection: true
        cache: file
    mappings:
        logo_file:
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
            uri_prefix: /directory/logos
            upload_destination: '%kernel.project_dir%/files/directory/logos'
            namer: vich_uploader.namer_origname
        brochure_file:
            uri_prefix: /directory/brochures
            upload_destination: '%kernel.project_dir%/files/directory/brochures'
            namer: vich_uploader.namer_origname

**Comment by garak** [comment]
What about permissions of `files` dir (and its subdirs)?

**Comment by methodeprog** [comment]
I work on local, with the left click on the Files folder, it said Read Only

**Comment by garak** [comment]
So there's nothing this bundle can do for you. The folder needs to be writable.

**Comment by methodeprog** [comment]
Ok i will be back in a few
