### ISSUE TITLE
Bug when uploading some image/* content 

### ISSUE THREAD

**Issue by noccy80** [dustin10/VichUploaderBundle#860]
| Q                          | A
| -------------------------- | -----
| Bug report?                | yes
| Feature request?           | no
| BC Break report?           | no
| Symfony version            | 3.4.6
| VichUploaderBundle version | 1.8.2

The `Storage\AbstractStorage#upload` method (L44-47) checks the size of image files but doesn't handle errors. Anything with a content type matching `image/*` that can't be properly parsed by `getimagesize` will give an error when trying to splice the boolean false.

        if (false !== strpos($file->getMimeType(), 'image/') && 'image/svg+xml' !== $file->getMimeType()) {
            $dimensions = getimagesize($file);
            $mapping->writeProperty($obj, 'dimensions', array_splice($dimensions, 0, 2));
        }

Probably better to test all `image/*` uploads, but only write the property if the call to `getimagesize` succeeds.

**Comment by garak** [comment]
Better now?

**Comment by noccy80** [comment]
Perfect :) Thank you for the quick fix!

**Comment by noccy80** [comment]
Quick follow-up question: When will this make it into an release? Have had the library pinned at dev-master since, which feels like a bad idea :)

**Comment by garak** [comment]
It is bad. You should point to our alias instead, `^1.8@dev`

**Comment by garak** [comment]
Just released `1.8.3` :rocket:

**Comment by noccy80** [comment]
Thank you for the update, I've swapped out the alias for the stable :) :+1:
