### ISSUE TITLE
Download link not visible

### ISSUE THREAD

**Issue by matdev** [dustin10/VichUploaderBundle#863]
I'd like to display a link to download a file previously uploaded with the VichUploader bundle.  
I've added the following line in my Form's buildForm() function:  
->add('theFile', VichFileType::class, array(
                'required' => false,
                'allow_delete' => true,
                'download_link' => true)

But no link is displayed on the form.
I'm using version 1.4 of the bundle because I use php 5.6 and cannot upgrade it.

| Q                          | A
| Symfony version            | 2.8.38
| VichUploaderBundle version | 1.4

**Comment by vieweg** [comment]
Yes, i too

and parameters 
'download_label', 'download_uri' cause exceptions 

HTTP 500 Internal Server Error
The options "download_label", "download_uri" do not exist.

Symfony : 3.4.6
VichUploaderBundle: 1.4.2

**Comment by garak** [comment]
You can refer to https://github.com/dustin10/VichUploaderBundle/blob/1.4.2/Resources/doc/index.md
