### ISSUE TITLE
Store files in Mongo DB

### ISSUE THREAD

**Issue by etshy** [dustin10/VichUploaderBundle#869]
|    Q        |   A
|--------   | -----
| Version  | 1.8

I'd  like to know if it's possible to store file in Mongo DB using MongoGridFS ?

As I have some problem handling upload by myself (symfony make upload quite difficult compared to what I did with ZF2 years ago ....) I search for a bundle to manage it.

The doc here : https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/usage.md
says that the File field is not meant to be stored in DB but in my case I want my files in DB instead of System FS.
In my case I also don't need 2 fields (one for name and one for the file) but only one for the file.

**Comment by etshy** [comment]
Hmm I don't know how create a Custom Storage.
I'll do some test during the week.

**Comment by garak** [comment]
>Hmm I don't know how create a Custom Storage.

That's what the doc is for
