### ISSUE TITLE
The class 'Doctrine\ORM\UnitOfWork' was not found

### ISSUE THREAD

**Issue by wyllyjon** [dustin10/VichUploaderBundle#872]
Hello ! 

In my form, I have added a `CollectionType` of `PhotoType` and `PhotoType` has one field : a `VichImageType`

Normal case : I fill my form without forgetting anything, and add some photos. Everything works fine, I go the to the next step and I do have my photos saved.

Buggy case : I fill my form forgetting something and I add some photos. I submit. The form page is shown again because I have forgotten something. I fill it and submit again. Then, I have this error : 

```request.CRITICAL: Uncaught PHP Exception Doctrine\Common\Persistence\Mapping\MappingException: "The class 'Doctrine\ORM\UnitOfWork' was not found in the chain configured namespaces AppBundle\Entity, AnnoncesBundle\Entity, FOS\UserBundle\Model" at /home/www/beta/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php line 37 {"exception":"[object] (Doctrine\\Common\\Persistence\\Mapping\\MappingException(code: 0): The class 'Doctrine\\ORM\\UnitOfWork' was not found in the chain configured namespaces AppBundle\\Entity, AnnoncesBundle\\Entity, FOS\\UserBundle\\Model at /home/www/beta/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:37)"} []```

I don't have this error if I do the same thing without adding photos. So, I assume that the problem comes with the photos use.

Any idea of the problem ? 

Thanks a lot !

**Comment by garak** [comment]
Try to re-run composer update

**Comment by wyllyjon** [comment]
Same problem

**Comment by garak** [comment]
I'm closing this because it looks unrelated to bundle (and old)
