### ISSUE TITLE
service or alias has been removed

### ISSUE THREAD

**Issue by WassabiVl** [dustin10/VichUploaderBundle#877]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.8.3

#### Summary

Trying to call PropertyDirectoryNamer breaks the page, same with Vich\UploaderBundle\Naming\SubdirDirectoryNamer

#### Current behavior

Symfony throws the following error:
``` 
Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "The "Vich\UploaderBundle\Naming\PropertyDirectoryNamer" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead." at D:\radiopharma\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Container.php line 337
 ``` 

#### How to reproduce

enabling the Directory namer in the config.yml file while running Symfony version 3.4.11

##### Current config.yml
![image](https://user-images.githubusercontent.com/26925021/41295923-008e4bee-6e5c-11e8-9bae-9da3d0764444.png)

#### Expected behavior

either PropertyDirectoryName is given public access or there is another method, not stated in the documentations, to inject the service

**Comment by garak** [comment]
@WassabiVl did you solve with above suggestion?

**Comment by garak** [comment]
Closing for missing feedback
