### ISSUE TITLE
Can't unlink cache file

### ISSUE THREAD

**Issue by petrixs** [dustin10/VichUploaderBundle#884]
### Bug Report

Sometimes I see next error at my API response:

Warning: unlink(/path/var/cache/dev/vich_uploader/App-Entity-Document.cache.php): No such file or directory.

file': '/var/www/verivication/testing/vendor/jms/metadata/src/Metadata/Cache/FileCache.php', 'line': 80

Check that file exists before unlink.

**Comment by garak** [comment]
What is `var/cache/dev/vich_uploader/App-Entity-Document.cache.php`?

**Comment by petrixs** [comment]
<?php return unserialize('C:42:"Vich\\UploaderBundle\\Metadata\\ClassMetadata":381:{a:2:{i:0;a:1:{s:13:"document_file";a:7:{s:7:"mapping";s:14:"documents_file";s:12:"propertyName";s:13:"document_file";s:16:"fileNameProperty";s:4:"path";s:4:"size";N;s:8:"mimeType";N;s:12:"originalName";N;s:10:"dimensions";N;}}i:1;s:141:"a:5:{i:0;s:19:"App\\Entity\\Document";i:1;a:0:{}i:2;a:0:{}i:3;a:1:{i:0;s:45:"/var/www/verification/src/Entity/Document.php";}i:4;i:1530603274;}";}}');

**Comment by petrixs** [comment]
> <?php return unserialize('C:42:"Vich\\UploaderBundle\\Metadata\\ClassMetadata":381:{a:2:{i:0;a:1:{s:13:"document_file";a:7:{s:7:"mapping";s:14:"documents_file";s:12:"propertyName";s:13:"document_file";s:16:"fileNameProperty";s:4:"path";s:4:"size";N;s:8:"mimeType";N;s:12:"originalName";N;s:10:"dimensions";N;}}i:1;s:141:"a:5:{i:0;s:19:"App\\Entity\\Document";i:1;a:0:{}i:2;a:0:{}i:3;a:1:{i:0;s:45:"/var/www/verification/src/Entity/Document.php";}i:4;i:1530603274;}";}}');

**Comment by petrixs** [comment]
`<?php return unserialize('C:42:"Vich\\UploaderBundle\\Metadata\\ClassMetadata":381:{a:2:{i:0;a:1:{s:13:"document_file";a:7:{s:7:"mapping";s:14:"documents_file";s:12:"propertyName";s:13:"document_file";s:16:"fileNameProperty";s:4:"path";s:4:"size";N;s:8:"mimeType";N;s:12:"originalName";N;s:10:"dimensions";N;}}i:1;s:141:"a:5:{i:0;s:19:"App\\Entity\\Document";i:1;a:0:{}i:2;a:0:{}i:3;a:1:{i:0;s:45:"/var/www/verification/src/Entity/Document.php";}i:4;i:1530603274;}";}}');`

**Comment by petrixs** [comment]
`
{
'error':{
'code':500,
'message':'Internal Server Error',
'exception':[
{
'message':'Warning: unlink(path/var/cache/dev/vich_uploader/App-Entity-Document.cache.php): No such file or directory',
'class':'ErrorException',
'trace':[
{
'namespace':'',
'short_class':'',
'class<span class="code-quote">':'',
                  'type':'',
                  'function':'',
                  'file':'path/vendor/jms/metadata/src/Metadata/Cache/FileCache.php',
                  'line':80,
                  'args':[  

                  ]
               },
               {  
                  'namespace':'Metadata\\Cache',
                  'short_class':'FileCache',
                  'class<span class="code-quote">':'Metadata\\Cache\\FileCache',
                  'type':'->',
                  'function':'evictClassMetadataFromCache',
                  'file':'path/vendor/jms/metadata/src/Metadata/MetadataFactory.php',
                  'line':93,
                  'args':[  
                     [  
                        'object',
                        'ReflectionClass'
                     ]
                  ]
               },
               {  
                  'namespace':'Metadata',
                  'short_class':'MetadataFactory',
                  'class<span class="code-quote">':'Metadata\\MetadataFactory',
                  'type':'->',
                  'function':'getMetadataForClass',
                  'file':'path/vendor/vich/uploader-bundle/Metadata/MetadataReader.php',
                  'line':44,
                  'args':[  
                     [  
                        'string',
                        'App\\Entity\\Document'
                     ]
                  ]
               },
               {  
                  'namespace':'Vich\\UploaderBundle\\Metadata',
                  'short_class':'MetadataReader',
                  'class<span class="code-quote">':'Vich\\UploaderBundle\\Metadata\\MetadataReader',
                  'type':'->',
                  'function':'isUploadable',
                  'file':'path/vendor/vich/uploader-bundle/EventListener/Doctrine/BaseListener.php',
                  'line':55,
                  'args':[  
                     [  
                        'string',
                        'App\\Entity\\Document'
                     ],
                     [  
                        'string',
                        'documents_file'
                     ]
                  ]
               },
               {  
                  'namespace':'Vich\\UploaderBundle\\EventListener\\Doctrine',
                  'short_class':'BaseListener',
                  'class<span class="code-quote">':'Vich\\UploaderBundle\\EventListener\\Doctrine\\BaseListener',
                  'type':'->',
                  'function':'isUploadable',
                  'file':'path/vendor/vich/uploader-bundle/EventListener/Doctrine/UploadListener.php',
                  'line':38,
                  'args':[  
                     [  
                        'object',
                        'App\\Entity\\Document'
                     ]
                  ]
               },
               {  
                  'namespace':'Vich\\UploaderBundle\\EventListener\\Doctrine',
                  'short_class':'UploadListener',
                  'class<span class="code-quote">':'Vich\\UploaderBundle\\EventListener\\Doctrine\\UploadListener',
                  'type':'->',
                  'function':'prePersist',
                  'file':'path/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php',
                  'line':61,
                  'args':[  
                     [  
                        'object',
                        'Doctrine\\ORM\\Event\\LifecycleEventArgs'
                     ]
                  ]
               },
               {  
                  'namespace':'Symfony\\Bridge\\Doctrine',
                  'short_class':'ContainerAwareEventManager',
                  'class<span class="code-quote">':'Symfony\\Bridge\\Doctrine\\ContainerAwareEventManager',
                  'type':'->',
                  'function':'dispatchEvent',
                  'file':'path/vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php',
                  'line':117,
                  'args':[  
                     [  
                        'string',
                        'prePersist'
                     ],
                     [  
                        'object',
                        'Doctrine\\ORM\\Event\\LifecycleEventArgs'
                     ]
                  ]
               },
               {  
                  'namespace':'Doctrine\\ORM\\Event',
                  'short_class':'ListenersInvoker',
                  'class<span class="code-quote">':'Doctrine\\ORM\\Event\\ListenersInvoker',
                  'type':'->',
                  'function':'invoke',
                  'file':'path/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php',
                  'line':929,
                  'args':[  
                     [  
                        'object',
                        'Doctrine\\ORM\\Mapping\\ClassMetadata'
                     ],
                     [  
                        'string',
                        'prePersist'
                     ],
                     [  
                        'object',
                        'App\\Entity\\Document'
                     ],
                     [  
                        'object',
                        'Doctrine\\ORM\\Event\\LifecycleEventArgs'
                     ],
                     [  
                        'integer',
                        4
                     ]
                  ]
               },
               {  
                  'namespace':'Doctrine\\ORM',
                  'short_class':'UnitOfWork',
                  'class<span class="code-quote">':'Doctrine\\ORM\\UnitOfWork',
                  'type':'->',
                  'function':'persistNew',
                  'file':'path/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php',
                  'line':1766,
                  'args':[  
                     [  
                        'object',
                        'Doctrine\\ORM\\Mapping\\ClassMetadata'
                     ],
                     [  
                        'object',
                        'App\\Entity\\Document'
                     ]
                  ]
               },
               {  
                  'namespace':'Doctrine\\ORM',
                  'short_class':'UnitOfWork',
                  'class<span class="code-quote">':'Doctrine\\ORM\\UnitOfWork',
                  'type':'->',
                  'function':'doPersist',
                  'file':'path/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php',
                  'line':1722,
                  'args':[  
                     [  
                        'object',
                        'App\\Entity\\Document'
                     ],
                     [  
                        'array',
                        {  
                           '000000007bd5bf0000000000675b3ec3':[  
                              'object',
                              'App\\Entity\\Document'
                           ]
                        }
                     ]
                  ]
               },
               {  
                  'namespace':'Doctrine\\ORM',
                  'short_class':'UnitOfWork',
                  'class<span class="code-quote">':'Doctrine\\ORM\\UnitOfWork',
                  'type':'->',
                  'function':'persist',
                  'file':'path/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php',
                  'line':594,
                  'args':[  
                     [  
                        'object',
                        'App\\Entity\\Document'
                     ]
                  ]
               },
               {  
                  'namespace':'Doctrine\\ORM',
                  'short_class':'EntityManager',
                  'class<span class="code-quote">':'Doctrine\\ORM\\EntityManager',
                  'type':'->',
                  'function':'persist',
                  'file':'path/src/Controller/DocumentsController.php',
                  'line':268,
                  'args':[  
                     [  
                        'object',
                        'App\\Entity\\Document'
                     ]
                  ]
               },
               {  
                  'namespace':'App\\Controller',
                  'short_class':'DocumentsController',
                  'class<span class="code-quote">':'App\\Controller\\DocumentsController',
                  'type':'->',
                  'function':'postAction',
                  'file':'path/vendor/symfony/http-kernel/HttpKernel.php',
                  'line':149,
                  'args':[  
                     [  
                        'object',
                        'Symfony\\Component\\HttpFoundation\\Request'
                     ],
                     [  
                        'object',
                        'Symfony\\Component\\Validator\\Validator\\TraceableValidator'
                     ]
                  ]
               },
               {  
                  'namespace':'Symfony\\Component\\HttpKernel',
                  'short_class':'HttpKernel',
                  'class<span class="code-quote">':'Symfony\\Component\\HttpKernel\\HttpKernel',
                  'type':'->',
                  'function':'handleRaw',
                  'file':'path/vendor/symfony/http-kernel/HttpKernel.php',
                  'line':66,
                  'args':[  
                     [  
                        'object',
                        'Symfony\\Component\\HttpFoundation\\Request'
                     ],
                     [  
                        'integer',
                        1
                     ]
                  ]
               },
               {  
                  'namespace':'Symfony\\Component\\HttpKernel',
                  'short_class':'HttpKernel',
                  'class<span class="code-quote">':'Symfony\\Component\\HttpKernel\\HttpKernel',
                  'type':'->',
                  'function':'handle',
                  'file':'path/vendor/symfony/http-kernel/Kernel.php',
                  'line':188,
                  'args':[  
                     [  
                        'object',
                        'Symfony\\Component\\HttpFoundation\\Request'
                     ],
                     [  
                        'integer',
                        1
                     ],
                     [  
                        'boolean',
                        True
                     ]
                  ]
               },
               {  
                  'namespace':'Symfony\\Component\\HttpKernel',
                  'short_class':'Kernel',
                  'class<span class="code-quote">':'Symfony\\Component\\HttpKernel\\Kernel',
                  'type':'->',
                  'function':'handle',
                  'file':'path/public/index.php',
                  'line':37,
                  'args':[  
                     [  
                        'object',
                        'Symfony\\Component\\HttpFoundation\\Request'
                     ]
                  ]
               }
            ]
         }
      ]
   }
}
`

**Comment by garak** [comment]
It looks like problem is in https://github.com/schmittjoh/metadata/blob/1.6.0/src/Metadata/Cache/FileCache.php#L80
Try to open an issue with them
