### ISSUE TITLE
imagine_pattern bug ?

### ISSUE THREAD

**Issue by NicolasDW** [dustin10/VichUploaderBundle#889]
Hi everyone,

I'm using Symfony 4.1 with EasyAdmin bundle and I'm not able to use imagine_pattern option in the vichImageType.
I define my filter, call it in the formType but nothing happens : no resize, no file created in media/cache (I use default values for paths).

So, what the purpose of this option ? It seems to be use for resizing after upload but I'm not really sure. Or is it a bug ?

Thanks

PS: sorry for my english

**Comment by garak** [comment]
What is the "image_pattern" option?

**Comment by NicolasDW** [comment]
Imagine_pattern, sorry.

From the doc :
![capture](https://user-images.githubusercontent.com/5811644/42616176-8e7e2dd0-85ad-11e8-8914-f081722b823d.JPG)

**Comment by garak** [comment]
Please provide your configuration

**Comment by NicolasDW** [comment]
Here is my configuration :
Symfony v4.1
Liip Imagine v2.1
VichUploaderBundle v1.8
EasyAdmin v1.17

The website runs on a local LAMP Server.

Thanks for your help

**Comment by garak** [comment]
Please provide your **Symfony** configuration

**Comment by NicolasDW** [comment]
Here is my code,

imagine.yaml
`liip_imagine:
    driver: "gd"
    
    filter_sets:

        zoom:
            jpeg_quality:          85
            png_compression_level: 8
            
            filters:
                            
                auto_rotate: ~

                strip: ~

                thumbnail:
                    size:          [1200, 1200]
                    mode:          outbound
                    allow_upscale: true`

**Comment by NicolasDW** [comment]
Ok, I think I've got it

In VichImageType.php
```
public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        $object = $form->getParent()->getData();
        $view->vars['object'] = $object;
        $view->vars['image_uri'] = null;
        $view->vars['download_uri'] = null;

        if (null !== $object) {
            if ($options['imagine_pattern']) {
                if (null === $this->cacheManager) {
                    throw new \RuntimeException('LiipImagineBundle must be installed and configured for using "imagine_pattern" option.');
                }

                $path = $this->storage->resolvePath($object, $form->getName(), null, true);
                if (null !== $path) {
                    $view->vars['image_uri'] = $this->cacheManager->getBrowserPath($path, $options['imagine_pattern']);
                }
            } else {
                $view->vars['image_uri'] = $this->resolveUriOption($options['image_uri'], $object, $form);
            }

            $view->vars = array_replace(
                $view->vars,
                $this->resolveDownloadLabel($options['download_label'], $object, $form)
            );

            $view->vars['download_uri'] = $this->resolveUriOption($options['download_uri'], $object, $form);
        }
        // required for BC
        // TODO: remove for 2.0
        $view->vars['show_download_link'] = !empty($view->vars['download_uri']);
    }
```
The imagine_pattern option just replace the original path by the path of the image generated by LiipImagine (and i think getBrowserPath create the resized image). 

I think the issue is located here :
```
$path = $this->storage->resolvePath($object, $form->getName(), null, true);
                if (null !== $path) {
                    $view->vars['image_uri'] = $this->cacheManager->getBrowserPath($path, $options['imagine_pattern']);
                }
```
When i want to store a new image, the first line always return null, and the imagine pattern is never applied. 
And if i want to update it to apply the filter (in this case, $path is not null), getBrowserPath seems to return a wrong link :
- /media/cache/resolve/zoom/5b470886ef5c8515716121.JPG

**Comment by garak** [comment]
See #858

**Comment by NicolasDW** [comment]
Thanks, after reading #858, I understand the problem of the getBrowserPath and how it works.

But in the "new" case, 
```
$path = $this->storage->resolvePath($object, $form->getName(), null, true);
```
still returns null, because there is no name for the image.

I'm maybe wrong, but i think this function would be launch in an event (PRE or POST_UPLOAD) to get the file name and make the right path, no ?

To go further, i have to explain my case : I save images of 10 Mo on my website (4000x3000) with vich_uploader, but I never use it, I always use Liip filters (the biggest size is 1500x1000).
But if I upload 100 images of this weight, I have 1 Go of file never used.

Do you think it's a good idea to apply the filter to the image and save it instead of the original file ?
I found a link in stackoverflow (I don't test the code) : https://stackoverflow.com/questions/15047281/use-liipimaginebundle-to-resize-image-after-upload

I'll be glad to test it myself if you could tell me where to work.

I hope it's understandable.

**Comment by garak** [comment]
About resizing image after upload: it's outside the scope of this bundle.
About problem with `getBrowserPath`, please contribute to existing issue (and possibly close this one)

**Comment by NicolasDW** [comment]
Thanks, I understand.

I'll do my best with getBrowserPath issue !
