### ISSUE TITLE
404 response in encoded URLs

### ISSUE THREAD

**Issue by davidromani** [dustin10/VichUploaderBundle#893]
|    Q        |   A
|------------ | -----
| Version     | 1.7.1

### Support Question

I'm migrating a Symfony 2 based webapp to a new webserver. All is working fine excepting this problem... In the old server the img src URLs are not encoded, but in the new server they are encoded. When the URL is encoded I'm getting a **404 response** for that resource.

Check the uploaded images, are the same inspected HTML code in both servers.

What can I do? It's a bundle problem? Or maybe is related with Apache config?

<img width="1622" alt="url_encoded" src="https://user-images.githubusercontent.com/698779/43519117-7c0f044e-958e-11e8-8ec9-b95df60a3a7b.png">
<img width="1619" alt="url_not_encoded" src="https://user-images.githubusercontent.com/698779/43519118-7c28444a-958e-11e8-92b4-dc7a1d5de7d0.png">

**Comment by davidromani** [comment]
Please, any hint will be welcome. Thank you.

**Comment by garak** [comment]
Did you keep your vendor versions? E.g. your composer.lock is the same in two servers? If so, it can't be a bundle problem and you need to check and compare server configurations

**Comment by davidromani** [comment]
@garak yes I think so because I executed `composer install` command in both servers during the deployment process.

**Comment by davidromani** [comment]
@garak can you explain a little bit which PHP functions are involved to build the src path?

**Comment by garak** [comment]
https://github.com/dustin10/VichUploaderBundle/blob/master/Twig/Extension/UploaderExtension.php#L40

**Comment by garak** [comment]
Is this still relevant?
