### ISSUE TITLE
vichuploadbundle and KnpLabs/DoctrineBehaviors (translatable)

### ISSUE THREAD

**Issue by alex83130** [dustin10/VichUploaderBundle#894]
|    Q        |   A
|------------ | -----
| Version     | 1.4.2

### Support Question

I use the bundle KnpLabs/DoctrineBehaviors (translatable) for to manage my translation.

I use also the bundle vichuploadbundle to manage my img.

I have an entity that must have different images depending on languages, so I placed my img field and the annotation Vich\UploadField in my entityTranslatable entity. But I can't display the image on Twig... I have an error because the mapping of my image field is not found... How mapping this ? Because my image field is'nt in my Creation entity but in my CreationTranslation entity ?

![capture](https://user-images.githubusercontent.com/15250423/43647147-14cfae6e-9737-11e8-8db5-8fb9a8564699.PNG)

Thank you in advance !

**Comment by garak** [comment]
I'm not sure to understand where you're trying to add your mapping

**Comment by garak** [comment]
Closing for missing feedback.
