### ISSUE TITLE
Blanck Picture zone on production

### ISSUE THREAD

**Issue by methodeprog** [dustin10/VichUploaderBundle#895]
|    Q        |   A
|------------ | -----
| Version     | 1.8.3

### Support Question

Hi 
On local, i can diplay on a page a picture i upload, but 
On production, on Heroku, things are differents.
Once the file is upload it appear on a page, but after a hour, page become blank, the picture zone remain in place, and the picture doesnt appear.
That the issue i face.
If you could help.
Many thanks

**Comment by garak** [comment]
I guess you need to ask to Heroku

**Comment by methodeprog** [comment]
Ok cool
