### ISSUE TITLE
Use the bundle without the local storage

### ISSUE THREAD

**Issue by gchanteloube** [dustin10/VichUploaderBundle#905]
Good evening, everyone,
Is it possible to use the bundle by disabling local storage? Indeed, I use the Amazon SDK to backup my files remotely, but the files are always store locally. This bundle works perfectly for uploading files + saving to database, but my use is a little particular...

Thank you all,
Guillaume

**Comment by gchanteloube** [comment]
Thank @garak, but I've this error : The service "vich_uploader.download_handler" has a dependency on a non-existent service "app\storage\digitaloceanstorage".

=> src/Storage/DigitalOceanStorage.php
`namespace App\Storage;
[...]
class DigitalOceanStorage extends AbstractStorage {
    protected function doUpload(PropertyMapping $mapping, UploadedFile $file, ?string $dir, string $name) {
[...]
`

`vich_uploader:
    db_driver: orm
    storage: '@App\Storage\DigitalOceanStorage'
`
Any ideas?
Thanks again

**Comment by garak** [comment]
You need to ensure that your service is correctly defined

**Comment by gchanteloube** [comment]
Hum, is it not automatic with default autowire service configuration?
I've added
`    vich_uploader.download_handler:
        class: App\Storage\DigitalOceanStorage`
but I must add too 'upload_handler', 'form.type.file', 'form.type.image', 'templating.helper.uploader_helper'?
Thank @garak for your helping. You know where I can find an configration example?
Guillaume

**Comment by garak** [comment]
it is automatic at some extent. You need anyway to check if your service is defined, using one of symfony console commands available for such purpose.
All configuration examples needed in this bundle are provided in docs

**Comment by garak** [comment]
Can we close this?
