### ISSUE TITLE
Image upload in OneToOne relation

### ISSUE THREAD

**Issue by ElGecko76** [dustin10/VichUploaderBundle#906]
Hi,

I would like to make a simple upload thanks to VichUploaderBundle and EasyAdminBundle in Symfony 4. 

I wish to separate my Image entity and my Article entity because I think it's cleaner to do this rather than putting everything into the Article entity. 

An article may have one image and an image can be used only in one article, so I would like use OneToOne relation between my entities. 

I looked into the documentation and forums but this relationship OneToOne is never used.. 

How can I do this? 

Thanks in advance

**Comment by gilsondelrei** [comment]
I think that sample on site is enought for your requirements. The sample
lack when using multiple filés (one to many) if you have any problems
implementing it you can post here for help.
Cheers

Em ter, 2 de out de 2018 18:24, Valentin Harrang <notifications@github.com>
escreveu:

**Comment by ElGecko76** [comment]
Thank you for your answer. Actually it works in OneToMany but not in OneToOne. It would not be worth doing a OneToMany if I only need a OneToOne.

**Comment by ElGecko76** [comment]
I have this error : 

> The class "App\Entity\Article" is not uploadable. If you use annotations to configure VichUploaderBundle, you probably just forgot to add `@Vich\Uploadable` on top of your entity. If you don't use annotations, check that the configuration files are in the right place. In both cases, clearing the cache can also solve the issue.

My Article entity : 

`<?php

declare(strict_types = 1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Article
 *
 * @package App\Entity
 *
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", options={"unsigned":true})
     *
     * @var int
     */
    protected $id;

    /**
     * @ORM\OneToOne(targetEntity="Image", mappedBy="article", cascade={"persist", "remove"}, orphanRemoval=true)
     *
     * @Assert\Valid()
     *
     * @var null|Image
     */
    protected $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): void
    {
        $this->id = $id;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): void
    {
        $this->image = $image;
    }

    public function __toString(): ?string
    {
        return $this->titre;
    }
}`

Image : 

`<?php

declare(strict_types = 1);

namespace App\Entity;

use App\Entity\Traits\TimestampableTrait;
use DateTime;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Class Image
 *
 * @ORM\Entity
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    use TimestampableTrait;

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     * @var int
     */
    protected $id;

    /**
     * @Vich\UploadableField(mapping="article_image", fileNameProperty="fileName", originalName="originalName", mimeType="mimeType", size="size")
     *
     * @var File
     */
    protected $file;

    /**
     * @ORM\Column(name="size", type="integer", nullable=true)
     *
     * @var int
     */
    protected $size;

    /**
     * @ORM\Column(nullable=true)
     *
     * @var string
     */
    protected $mimeType;

    /**
     * @ORM\Column(nullable=true)
     *
     * @var string
     */
    protected $originalName;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    protected $fileName;

    /**
     * @ORM\OneToOne(targetEntity="Article", inversedBy="image")
     * @ORM\JoinColumn(nullable=false)
     *
     * @var Article
     */
    protected $article;

    public function __construct()
    {
        $this->updatedAt = new DateTime();
    }

    public function getId() : int
    {
        return $this->id;
    }

    public function getSize() : int
    {
        return $this->size;
    }

    public function setSize($size) : void
    {
        $this->size = $size;
    }

    public function getMimeType() : string
    {
        return $this->mimeType;
    }

    public function setMimeType($mimeType) : void
    {
        $this->mimeType = $mimeType;
    }

    public function getOriginalName(): string
    {
        return $this->originalName;
    }

    public function setOriginalName($originalName): void
    {
        $this->originalName = $originalName;
    }

    public function getFile() : File
    {
        return $this->file;
    }

    public function setFile(File $file = null): void
    {
        $this->file = $file;
        if ($file) {
            $this->updatedAt = new DateTimeImmutable();
        }
    }

    public function getFileName() : string
    {
        return $this->fileName;
    }

    public function setFileName($fileName): void
    {
        $this->fileName = $fileName;
    }

    public function getArticle(): Article
    {
        return $this->article;
    }

    public function setArticle(Article $article): void
    {
        $this->article = $article;
    }
}`

easy_admin.yaml : 

`- { property: 'image', type: 'vich_image'}`

vich_uploader.yaml : 

`vich_uploader:
    db_driver: orm
    mappings:
        article_image:
            uri_prefix: uploads/images/articles
            upload_destination: '%app.destination.images_articles%'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
`

**Comment by garak** [comment]
As stated in the error you get, `Article` is not uploadable. You need to set is as Uploadable

**Comment by ElGecko76** [comment]
Yes, but I would like separate my Article entity and my Image entity because it's cleaner. It's not possible ?

**Comment by garak** [comment]
It should be possible.

**Comment by ElGecko76** [comment]
I can't find any solution. Do you know how I can do that?

**Comment by garak** [comment]
Configure `Article` as Uploadable

**Comment by ElGecko76** [comment]
> Mapping not found for field "image"

**Comment by garak** [comment]
I see that your mapped field is "$file"

**Comment by ElGecko76** [comment]
Yes but my mapped field is in Image entity, not in Article entity

**Comment by garak** [comment]
So, you're pointing your form to image, but image is not a field of Article, it's an Image object. It can't be working like that. You need to point your form field to the entity property that is mapped by Vich ("file", in your case)

**Comment by ElGecko76** [comment]
Like that in my easy_admin.yaml ?

> - { property: 'image', type: 'vich_image', type_options: { entry_type: 'App\Form\ImageType', by_reference: false, allow_add: true, allow_delete: true }}

**Comment by garak** [comment]
Sorry, I don't know what easy_admin.yaml is.
I can only help you with VichUploaderBundle.

**Comment by ElGecko76** [comment]
I need to create an ImageType form with a VichImageType field and ArticleType form must have the ImageType field ?

**Comment by garak** [comment]
Try that

**Comment by ElGecko76** [comment]
The upload field HTML is displayed but I have this error when I submit the form :

> Return value of App\Entity\Image::getFile() must be an instance of Symfony\Component\HttpFoundation\File\File, null returned

**Comment by garak** [comment]
use `?File` as return type

**Comment by garak** [comment]
That depends on you (and your code).
This bundle is not responsible of putting a value in your File property during form submission.

**Comment by ElGecko76** [comment]
When I submit the form, all values ​​of the Image entity are null (even article_id)

**Comment by garak** [comment]
That's a good starting point to investigate

**Comment by ElGecko76** [comment]
I still have not succeeded, I think it's not possible..
