### ISSUE TITLE
Folders are not removed after file entity is removed in version 1.4

### ISSUE THREAD

**Issue by st0at** [dustin10/VichUploaderBundle#909]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 1.4

#### Summary

Folders are not removed after file entity is removed.

#### Current behavior

When directory namer is used and entity is removed, entity file is deleted but directory is left empty.

#### How to reproduce

PHP version 5.6, Symfony version 2.8, integration with Doctrine.

configuration:
vich_uploader:
    db_driver: orm
    mappings:
        file:
            uri_prefix: /path_to_files
            upload_destination: 'absolute_path_to_files'
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'some_entity_property' }

Upload file, create entity with that file. Then remove entity.

#### Expected behavior

Delete directory if entity's file is the last one in that directory and it is deleted.

**Comment by garak** [comment]
So, why do you expect such behavior?

**Comment by st0at** [comment]
> So, why do you expect such behavior?

I assume that it would be a proper full directory namer feature - creating directory when new entity is created and also deleting it when no entities files are left.

**Comment by garak** [comment]
It's not the same thing: creating directory is necessary in order to create files inside it. Deleting is not.

**Comment by st0at** [comment]
Can I make a PR to implement this feature? On entity removal check if there are no files left in created directory/subdirectories and delete them when such case occurs?

**Comment by garak** [comment]
Can't you just add your own listener? Just listen to `vich_uploader.post_remove` and do whatever you want.
Personally, I see little if not zero value in deleting an empty directory.

**Comment by st0at** [comment]
> Can't you just add your own listener? Just listen to `vich_uploader.post_remove` and do whatever you want.
> Personally, I see little if not zero value in deleting an empty directory.

I did. Anyway thank you for this library!

**Comment by MLDMoritz** [comment]
I thought about this too, however - keep in mind: There can be files in the directory which you try to delete (aaaab and aaaac in same directory aa/).
