### ISSUE TITLE
YAML mapping file name extension

### ISSUE THREAD

**Issue by benr77** [dustin10/VichUploaderBundle#912]
If using a Yaml mapping file, it appears that the file extension of the mapping file needs to be `.yml` (see MetaData/YamlDriver.php line 53).

What with Symfony 4 best practices stating that Yaml files should have the extension `.yaml`, I feel it would be an improvement to support both extensions, as currently I have a mix of .yml and .yaml extensions in my project which feels untidy.

**Comment by garak** [comment]
Duplicate of #807
