### ISSUE TITLE
GaufretteStorage PHP7 imcompatible

### ISSUE THREAD

**Issue by wuestkamp** [dustin10/VichUploaderBundle#926]
### Bug Report

```
"php": ">=7",
"vich/uploader-bundle": "1.8.4",
"knplabs/gaufrette": "^0.5",
"knplabs/knp-gaufrette-bundle": "^0.5",
"symfony/symfony": "3.4.*",
```

I'm getting this error:

```
Fatal error: Declaration of GaufretteStorage_f99e4b3::upload($obj, Vich\UploaderBundle\Mapping\PropertyMapping $mapping) must be compatible with Vich\UploaderBundle\Storage\AbstractStorage::upload($obj, Vich\UploaderBundle\Mapping\PropertyMapping $mapping): void in   
  /project/var/cache/dev/ContainerVwqwlax/GaufretteStorage_f99e4b3.php on line 3 
```

I did clear the cache like described in #837 but didn't affect. Any ideas?

**Comment by garak** [comment]
your php version?

**Comment by wuestkamp** [comment]
PHP 7.2.9

**Comment by garak** [comment]
Did you clear your cache by removing all files manually? If so, I don't know what else it could be.

**Comment by wuestkamp** [comment]
I created a simple test project and can't reproduce this, so it must be some other bundle or extension in our application.

**Comment by lushc** [comment]
In our case it was because we had [ocramius/proxy-manager](https://packagist.org/packages/ocramius/proxy-manager) locked to 1.x – removing that allowed 2.x to be fulfilled by another package, fixing the issue.
