### ISSUE TITLE
Display an Upload File from Google Cloud Storage

### ISSUE THREAD

**Issue by methodeprog** [dustin10/VichUploaderBundle#935]
|    Q        |   A
|------------ | -----
| Version     | 1.8.5

### Support Question
Hi value team member !
Is there something i missed ?

Ive upload a file in google file storage, and i get a blank page for my picture.
**The distant file source code**
style="background-image: url('//picture.png')

On local 
**The local file source code**
style="background-image: url('/picture.png')

So distant file could not appear and cloud storage, also ACL  are set on AllUsers access !
Many thanks for help !

**Comment by garak** [comment]
Your configuration and the way you retrieve file could be useful to add some context

**Comment by methodeprog** [comment]
Here is the config
/////////////////////////////////////
oneup_flysystem:
    adapters:
        google_adapter:
            googlecloudstorage:
                client: top.google_storage_client
                bucket: top.google_storage_bucket
    filesystems:
        google_filesystem:
            adapter: google_adapter
            alias: google_filesystem
            mount: google_filesystem
            visibility: public

///////////////////////////////////////////
vich_uploader:
    db_driver: orm
    form: true
    twig:  true
    storage: flysystem
    mappings:
        front_banners:
            uri_prefix: /
            upload_destination: google_filesystem
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_origname

///////////////////////////
Twig template
                {% for tops in tops %}
                
                <div class="carousel-item active" style="background-image: url('{{ asset(vich_uploader_asset(tops, 'imageFile')) }}')">
                </div>
                {% endfor %}

That's where i am !

**Comment by garak** [comment]
So you're using Flysystem, please refer to issue #493
