### ISSUE TITLE
Requesting a cookbook for basic usage

### ISSUE THREAD

**Issue by gundamftw** [dustin10/VichUploaderBundle#936]
I'm new to this package and trying to get it working with symfony 4. But I couldn't find any document about the basic to run it from the controller. Like what do I do after the form validation? Do I just flush it? I was kind of lost.

**Comment by garak** [comment]
Documentation in this bundle shows only specific topics related to bundle itself.
You need to read Symfony documentation **before** using this bundle.
For example, [this](https://symfony.com/doc/current/forms.html#building-the-form) could be a good starting point.

**Comment by gundamftw** [comment]
I have already looked at that article as well as this one about [uploading file](https://symfony.com/doc/current/controller/upload_file.html), I did the entityManager->persist and flush but nothing happened, there's a no error. I mean there should be at least some example of the basic workflow in the document for people to troubleshoot themselves,  I have no idea where I messed up right now.

**Comment by garak** [comment]
If you think something is missing in documentation, feel free to propose a PR.
For your issue, you need to provide code where we can reproduce the problem

**Comment by gundamftw** [comment]
I did found out my problem, it was that I haven't update my doctrine schema to the database after the added the changes in my entities.

What I'm requesting is a more thorough basic usage documentation, right now the document has nothing that talks about how to use the bundle in the controller. Why not add it so that newcomer like me doesn't have to flip through documents from the internet if something went wrong.

**Comment by garak** [comment]
So, it looks like duplicating Symfony documentation here would not be useful in case where problem is in the model and not in the controller.
