### ISSUE TITLE
Upload file and store filename in serialized entity.

### ISSUE THREAD

**Issue by RubixR4** [dustin10/VichUploaderBundle#938]
### Bug Report

Impossible to upload images on serialized entity.

|    Q        |   A
|------------ | ------
| BC Break    | No
| Version     | 1.8

#### Summary

I have an main entity with an attribute which contains another entity. For specific reasons, the child entity is stored as an object type in doctrine. The child entity contains a uploaded file attribute and a string attribute used to store the file name as explained in the bundle installation documentation. I would like to serialize the filename (and ignore the file attribute of course) but when I submit my form, the field is null.

#### Current behavior

The attribute is stored as null is the database.
` i:2;N; `

#### How to reproduce

Create a main entity, a child entity and reference it as an object field for doctrine.
In the child entity, create an uploadable field as explained in the bundle installation.
`     * @ORM\Column(name="other_fields", type="object", nullable=true)`

#### Expected behavior

I would like to store the image as usual and serialize the filename in my serialized field.

**Comment by RubixR4** [comment]
**Page.php file**

```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Page
 * 
 * @ORM\Table(name="cc_page")
 * @ORM\Entity(repositoryClass="App\Repository\PageRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Page extends Datable
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var array
     *
     * @ORM\Column(name="other_fields", type="object", nullable=true)
     */
    private $otherFields;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Page
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set otherFields
     *
     * @param \Object $otherFields
     *
     * @return Page
     */
    public function setOtherFields($otherFields)
    {
        $this->otherFields = $otherFields;

        return $this;
    }

    /**
     * Get otherFields
     *
     * @return \Object
     */
    public function getOtherFields()
    {
        return $this->otherFields;
    }
}
```

**HomeFields.php file** (store in otherFields attribute)

```
<?php

namespace App\Entity;

use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * HomeFields
 *
 * @Vich\Uploadable
 */
class HomeFields implements \Serializable
{
    /**
     * @var string
     */
    private $main1Title;

    /**
     * @Vich\UploadableField(mapping="home_banner", fileNameProperty="bannerFileName")
     * 
     * @var File
     */
    private $bannerFile;

    /**
     * @var string
     */
    private $bannerFileName;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set main1Title
     *
     * @param string $main1Title
     *
     * @return HomeFields
     */
    public function setMain1Title($main1Title)
    {
        $this->main1Title = $main1Title;

        return $this;
    }

    /**
     * Get main1Title
     *
     * @return string
     */
    public function getMain1Title()
    {
        return $this->main1Title;
    }

    /**
     * Set bannerFile
     *
     * @param \File $bannerFile
     *
     * @return HomeFields
     */
    public function setBannerFile($bannerFile)
    {
        $this->bannerFile = $bannerFile;

        return $this;
    }

    /**
     * Get bannerFile
     *
     * @return File
     */
    public function getBannerFile()
    {
        return $this->bannerFile;
    }

    /**
     * Set bannerFileName
     *
     * @param string $bannerFileName
     *
     * @return HomeFields
     */
    public function setBannerFileName($bannerFileName)
    {
        $this->bannerFileName = $bannerFileName;
    }

    /**
     * Get bannerFileName
     *
     * @return string
     */
    public function getBannerFileName()
    {
        return $this->bannerFileName;
    }

    /**
     * Serialize
     *
     * @return string
     */
    public function serialize()
    {
        return serialize(array(
            $this->main1Title,
            $this->bannerFileName
        ));
    }

    /**
     * Unserialize
     *
     * @return void
     */
    public function unserialize($serialized)
    {
        list (
            $this->main1Title,
            $this->bannerFileName
        ) = unserialize($serialized);
    }
}
````

**Comment by garak** [comment]
Try this https://stackoverflow.com/questions/45154697/serialization-of-uploadedfile-is-not-allowed

**Comment by RubixR4** [comment]
Actually, this isn't enought. I already make a copy of the child object each time I update it because doctrine cannot detect changes on a object attribute as it only checks if it points to the same object in memory. (https://stackoverflow.com/questions/30193351/how-to-update-doctrine-object-type-field) And even at the entity creation, the filename is null.

I guess it should be because I have no ORM annotation on the filename attribute but I cannot have one as the whole object is stored as a single field and not in a table.

**Comment by garak** [comment]
If you can propose a solution, feel free to open a PR.
Otherwise, you should use a custom implementation instead of this bundle

**Comment by RubixR4** [comment]
I checked the bundle structure, everything is handled with doctrine listeners.
As the field in the parent entity is not mapped with the Vich annotation, the bundle does not detect that he must also check the child entity. I think the simpler solution is to use a custom implementation indeed.

Thank you for your time !
