### ISSUE TITLE
Namer : user service instead of namespace

### ISSUE THREAD

**Issue by takali** [dustin10/VichUploaderBundle#940]
#### Summary

Hi was following [the documentation on Namer](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/namers.md), i used the UniqidNamer like in the doc : 
`namer: Vich\UploaderBundle\Naming\UniqidNamer`

Then i get a 500 : 

> Service "Vich\UploaderBundle\Naming\UniqidNamer.image_slide_desktop": Parent definition "Vich\UploaderBundle\Naming\UniqidNamer" does not exist.

I fixed it by using the service : 
`namer: vich_uploader.namer_uniqid`

Symfony Version : v3.4.14
EasyAdmin : v1.17.14

**Comment by garak** [comment]
bundle version?

**Comment by takali** [comment]
@garak : 
`
"name": "vich/uploader-bundle",
"version": "1.7.1",
`

**Comment by garak** [comment]
So, you should read [your version documentation](https://github.com/dustin10/VichUploaderBundle/blob/1.7.1/Resources/doc/namers.md), not to latest one.
