### ISSUE TITLE
Directory Namer services use wrong aliases

### ISSUE THREAD

**Issue by fyrye** [dustin10/VichUploaderBundle#942]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | commit [dbcd1a5deb9f19f4a7507a24508cfa667fe91bcb](https://github.com/dustin10/VichUploaderBundle/commit/dbcd1a5deb9f19f4a7507a24508cfa667fe91bcb#diff-f95a36bc6c3729133991b59501ab6870)

#### Summary

The [`PropertyDirectoryNamer`](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/config/namer.xml#L30) service class is specified as `vich_uploader.namer_directory_property` but the service is aliased from service `vich_uploader.namer_property` which is the `PropertyNamer` service.

The `SubdirDirectoryNamer` class service is specified as `vich_uploader.directory_namer_subdir` but the service is aliased from service `vich_uploader.namer_subdir` which doesn't exist.

#### Expected:

```xml
<!-- Create initial service definitions -->
<service id="vich_uploader.directory_namer_subdir" class="Vich\UploaderBundle\Naming\SubdirDirectoryNamer" public="true" />
<service id="vich_uploader.namer_directory_property" class="Vich\UploaderBundle\Naming\PropertyDirectoryNamer" public="true">
    <argument type="service" id="form.property_accessor" on-invalid="null" />
</service>

<!-- Create alias of initial service definitions for Dependency Injections -->
<service id="Vich\UploaderBundle\Naming\SubdirDirectoryNamer" alias="vich_uploader.directory_namer_subdir" public="false"/>
<service id="Vich\UploaderBundle\Naming\PropertyDirectoryNamer" alias="vich_uploader.namer_directory_property" public="false"/>
```

**Comment by garak** [comment]
Can you provide a PR? Thanks
