### ISSUE TITLE
vichuploader not working on prod version

### ISSUE THREAD

**Issue by mystimkg** [dustin10/VichUploaderBundle#944]
In my Symfony 3.4 project (vich/uploader-bundle: "^1.4"), I need to upload 3 kinds of files and for two of them it's work, but for the third even if i use the same process it doesn't work...? When the form is submitted, i get this exception:

**SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'document_name' cannot be null**

In local everything work fine. In production i get this exception only with one of them. I have all permission on server.

I followed the documentation, read many tuto, ask question on stackverflow, cleared cache and updated doctrine schema many times, tried many things...

when i dumped, i can see that my Setter "vichuploader document name" not work and can't persisted.

This is the context:
- Everythings is ok on my local version...Files are uploaded but on my production version it's doesn't work.
- I have one Entity (NoteFrais) with OneToOne relation with another Entity (Justificatif). 
- The Justificatif entity has the @vich\uploadable annotation.

****************Here is my config:**************

`parameters:
    locale: fr
    app.path.logos: /uploads/logos
    app.path.imports: /uploads/imports
    app.path.documents: /uploads/documents

vich_uploader:
db_driver: orm
mappings:
    logo:
        uri_prefix: '%app.path.logos%'
        upload_destination: '%kernel.root_dir%/../web%app.path.logos%' //========IT'S WORK FINE FOR THIS ONE==========//
        namer: vich_uploader.namer_uniqid
        inject_on_load:     false
        delete_on_update:   true
        delete_on_remove:   true

    import:
        uri_prefix: '%app.path.imports%'
        upload_destination: '%kernel.root_dir%/../web%app.path.imports%' //=========IT'S WORK FINE THIS ONE=========//
        namer: vich_uploader.namer_uniqid
        inject_on_load:     false
        delete_on_update:   true
        delete_on_remove:   true

    document:
        uri_prefix: '%app.path.documents%'
        upload_destination: '%kernel.root_dir%/../web%app.path.documents%'
        namer: vich_uploader.namer_uniqid
        inject_on_load:     false
        delete_on_update:   true
        delete_on_remove:   true`

***********forms:**********************

`public function buildForm(FormBuilderInterface $builder, array $options)
{
$builder->add('justificatifFile', FileType::class, array( //========= I TRIED WITH FILETYPE OR VICHFILETYPE =======//
    //'data_class' => null,                      //======== NOTE:USALLY I USE TO FILETYPE AND IT'S WORK FINE ==============//
    'label' => false,
    'required' => true,
    'attr' => array(
        'class' => 'NoteFraisBootstrapFileInput',
        'type' => 'file',
        'placeholder' => 'Selectionner un justificatif (jpeg, png, jpg, pdf)',
        'data-preview-file-type' => 'text',
        'data-allowed-file-extensions' => '["jpeg", "png", "jpg", "pdf"]',
    )
));
}`

`public function buildForm(FormBuilderInterface $builder, array $options)
{
$builder
    //=======OTHERS FIELDS===========//
    ->add('justificatif', JustificatifType::class, array(
        'required' => false));
}`

*******justificatif.php (Entity)**********
`use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
  * Justificatif
  *
  * @ORM\Table(name="justificatif")
  * @ORM\Entity(repositoryClass="MKG\MystiBundle\Repository\JustificatifRepository")
 * @vich\Uploadable
 */
class Justificatif
{
/**
 * @var int
 *
 * @ORM\Column(name="id", type="integer")
 * @ORM\Id
 * @ORM\GeneratedValue(strategy="AUTO")
 */
private $id;

/**
 * NOTE: This is not a mapped field of entity metadata, just a simple property.
 *
 * @Vich\UploadableField(mapping="document", fileNameProperty="documentName")
 *
 * @var File
 */
private $justificatifFile;

/**
 * @ORM\Column(type="string", length=255)
 *
 * @var string
 */
private $documentName;

/**
 * @ORM\Column(type="datetime")
 *
 * @var \DateTime
 */
private $updatedAt;

/**
 * Constructor
 */
public function __construct()
{
    $this->updatedAt = new \DateTime();
}

/**
 * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
 * of 'UploadedFile' is injected into this setter to trigger the  update. If this
 * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
 * must be able to accept an instance of 'File' as the bundle will inject one here
 * during Doctrine hydration.
 *
 * @param File|UploadedFile $justificatif
 */
public function setJustificatifFile(File $justificatif = null)
{
    $this->justificatifFile = $justificatif;

    if ($justificatif) {
        $this->updatedAt =  new \DateTime('now');
    }

}

/**
 * @return File|null
 */
public function getJustificatifFile()
{
    return $this->justificatifFile;
}

/**
 *
 * @param $documentName
 *
 * @return $this
 */
public function setDocumentName($documentName)
{
    $this->documentName = $documentName;

    return $this;
}

/**
 * @return string|null
 */
public function getDocumentName()
{
    return $this->documentName;
}

/**
 * Set updatedAt
 *
 * @param \DateTime $updatedAt
 *
 * @return Justificatif
 */
public function setUpdatedAt($updatedAt)
{
    $this->updatedAt = $updatedAt;

    return $this;
}

/**
 * Get updatedAt
 *
 * @return \DateTime
 */
public function getUpdatedAt()
{
    return $this->updatedAt;
}

/**
 * Get id
 *
 * @return int
 */
public function getId()
{
    return $this->id;
}
}`

************NoteFrais.php (Entity)***************
`   use Doctrine\ORM\Mapping as ORM;
    use Doctrine\Common\Persistence\ObjectManager;
    use Symfony\Component\HttpFoundation\File\File;
    use Symfony\Component\HttpFoundation\File\UploadedFile;
    use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * NoteFrais
 *
 * @ORM\Table(name="note_frais")
 * @ORM\Entity(repositoryClass="MKG\MystiBundle\Repository\NoteFraisRepository")
 */
class NoteFrais
{
/**
 * @var int
 *
 * @ORM\Column(name="id", type="integer")
 * @ORM\Id
 * @ORM\GeneratedValue(strategy="AUTO")
 */
private $id;

/**
 * @ORM\ManyToOne(targetEntity="MKG\MystiBundle\Entity\Mission", cascade={"persist"})
 * @ORM\JoinColumn(name="mission_id", referencedColumnName="id", onDelete="CASCADE", nullable=true)
 */
private $mission;

/**
 * @ORM\ManyToOne(targetEntity="MKG\MystiBundle\Entity\CodeComptable", cascade={"persist"})
 * @ORM\JoinColumn(name="compte_comptable_id", referencedColumnName="id", onDelete="SET NULL", nullable=true)
 */
private $compteComptable;

/**
 * @var string
 *
 * @ORM\Column(name="montant_defraiement_max", type="string", length=255, nullable=false)
 */
private $montantDefraiementMax;

/**
 * @var string
 *
 * @ORM\Column(name="refacturation_client", type="string", length=255, nullable=true)
 */
private $refacturationClient;

/**
 * @var string
 *
 * @ORM\Column(name="total_defraiement", type="string", length=255, nullable=true)
 */
private $totalDefraiement;

/**
 * @var string
 *
 * @ORM\Column(name="total_refacturation", type="string", length=255, nullable=true)
 */
private $totalRefacturation;

/**
 * @var string
 *
 * @ORM\Column(name="compte_avances_et_acomptes", type="string", length=255, nullable=true)
 */
private $compteAvancesEtAcomptes;

/**
 * @var string
 *
 * @ORM\Column(name="admin_current_user", type="string", length=255, nullable=true)
 */
private $currentUser;

/**
 * @var string
 *
 * @ORM\Column(name="code_affaire", type="string", length=255, nullable=true)
 */
private $codeAffaire;

/**
 * @var string
 *
 * @ORM\Column(name="etat", type="string", length=255, nullable=true)
 */
private $etat;

/**
 * @ORM\OneToOne(targetEntity="Justificatif", cascade={"persist"})
 * @ORM\JoinColumn(name="justificatif_id", referencedColumnName="id", onDelete="CASCADE", nullable=true)
 */
private $justificatif;

/**
 * @var \DateTime
 *
 * @ORM\Column(name="dateCreation", type="datetime")
 */
private $dateCreation;

public function __construct() {

    $this->dateCreation = new \DateTime;
    $this->etat = "0";
}

/**
 * Get id
 *
 * @return integer
 */
public function getId()
{
    return $this->id;
}

/**
 * Set montantDefraiementMax
 *
 * @param string $montantDefraiementMax
 *
 * @return NoteFrais
 */
public function setMontantDefraiementMax($montantDefraiementMax)
{
    $this->montantDefraiementMax = $montantDefraiementMax;

    return $this;
}

/**
 * Get montantDefraiementMax
 *
 * @return string
 */
public function getMontantDefraiementMax()
{
    return $this->montantDefraiementMax;
}

/**
 * Set refacturationClient
 *
 * @param string $refacturationClient
 *
 * @return NoteFrais
 */
public function setRefacturationClient($refacturationClient)
{
    $this->refacturationClient = $refacturationClient;

    return $this;
}

/**
 * Get refacturationClient
 *
 * @return string
 */
public function getRefacturationClient()
{
    return $this->refacturationClient;
}

/**
 * Set compteAvancesEtAcomptes
 *
 * @param string $compteAvancesEtAcomptes
 *
 * @return NoteFrais
 */
public function setCompteAvancesEtAcomptes($compteAvancesEtAcomptes)
{
    $this->compteAvancesEtAcomptes = $compteAvancesEtAcomptes;

    return $this;
}

/**
 * Get compteAvancesEtAcomptes
 *
 * @return string
 */
public function getCompteAvancesEtAcomptes()
{
    return $this->compteAvancesEtAcomptes;
}

/**
 * Set currentUser
 *
 * @param string $currentUser
 *
 * @return NoteFrais
 */
public function setCurrentUser($currentUser)
{
    $this->currentUser = $currentUser;

    return $this;
}

/**
 * Get currentUser
 *
 * @return string
 */
public function getCurrentUser()
{
    return $this->currentUser;
}

/**
 * Set codeAffaire
 *
 * @param string $codeAffaire
 *
 * @return NoteFrais
 */
public function setCodeAffaire($codeAffaire)
{
    $this->codeAffaire = $codeAffaire;

    return $this;
}

/**
 * Get codeAffaire
 *
 * @return string
 */
public function getCodeAffaire()
{
    return $this->codeAffaire;
}

/**
 * Set etat
 *
 * @param string $etat
 *
 * @return NoteFrais
 */
public function setEtat($etat)
{
    $this->etat = $etat;

    return $this;
}

/**
 * Get etat
 *
 * @return string
 */
public function getEtat()
{
    return $this->etat;
}

/**
 * Set dateCreation
 *
 * @param \DateTime $dateCreation
 *
 * @return NoteFrais
 */
public function setDateCreation($dateCreation)
{
    $this->dateCreation = $dateCreation;

    return $this;
}

/**
 * Get dateCreation
 *
 * @return \DateTime
 */
public function getDateCreation()
{
    return $this->dateCreation;
}

/**
 * Set mission
 *
 * @param \MKG\MystiBundle\Entity\Mission $mission
 *
 * @return NoteFrais
 */
public function setMission(\MKG\MystiBundle\Entity\Mission $mission = null)
{
    $this->mission = $mission;

    return $this;
}

/**
 * Get mission
 *
 * @return \MKG\MystiBundle\Entity\Mission
 */
public function getMission()
{
    return $this->mission;
}

/**
 * Set compteComptable
 *
 * @param \MKG\MystiBundle\Entity\CodeComptable $compteComptable
 *
 * @return NoteFrais
 */
public function setCompteComptable(\MKG\MystiBundle\Entity\CodeComptable $compteComptable = null)
{
    $this->compteComptable = $compteComptable;

    return $this;
}

/**
 * Get compteComptable
 *
 * @return \MKG\MystiBundle\Entity\CodeComptable
 */
public function getCompteComptable()
{
    return $this->compteComptable;
}

/**
 * Set justificatif
 *
 * @param \MKG\MystiBundle\Entity\Justificatif $justificatif
 *
 * @return NoteFrais
 */
public function setJustificatif(\MKG\MystiBundle\Entity\Justificatif $justificatif = null)
{
    $this->justificatif = $justificatif;

    return $this;
}

/**
 * @return File
 */
public function getJustificatif()
{
    return $this->justificatif;
}

/**
 * Set totalDefraiement
 *
 * @param string $totalDefraiement
 *
 * @return NoteFrais
 */
public function setTotalDefraiement($totalDefraiement)
{
    $this->totalDefraiement = $totalDefraiement;

    return $this;
}

/**
 * Get totalDefraiement
 *
 * @return string
 */
public function getTotalDefraiement()
{
    return $this->totalDefraiement;
}

/**
 * Set totalRefacturation
 *
 * @param string $totalRefacturation
 *
 * @return NoteFrais
 */
public function setTotalRefacturation($totalRefacturation)
{
    $this->totalRefacturation = $totalRefacturation;

    return $this;
}

/**
 * Get totalRefacturation
 *
 * @return string
 */
public function getTotalRefacturation()
{
    return $this->totalRefacturation;
}
}`

********* newAction in NoteFraisController *********

`
public function newAction(Request $request)
{
    // === RECUPERE LA MISSION
    $em = $this->getDoctrine()->getManager();
    $mission = $em->getRepository('MKGMystiBundle:Mission')->findOneBy(array('id' => $request->get('idMission')));
    $lignesNoteFrais = $em->getRepository('MKGMystiBundle:NoteFrais')->findBy(array('mission' => $mission->getId()));

    $noteFrais = new Notefrais();
    $form = $this->createForm('MKG\MystiBundle\Form\NoteFraisType', $noteFrais);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {

        //$noteFrais->setMission($mission);
        $em = $this->getDoctrine()->getManager();
        $em->persist($noteFrais);
        //dump($noteFrais);die();
        $em->flush();

        $this->addFlash('notice', 'Une ligne a été ajouté à la note de frais!');
        return $this->redirect($request->getUri());
    }

    return $this->render('@MKGMysti/Notefrais/new.html.twig', array(
        'lignesNoteFrais' => $lignesNoteFrais,
        'mission' => $mission,
        'noteFrais' => $noteFrais,
        'form' => $form->createView(),
    ));
}`

Thank you very much your time!!!!

**Comment by garak** [comment]
Try to set your mapped property as nullable

**Comment by monoulou** [comment]
Thank you! I reviewed my code and check it line by line and I noticed something strange... If I replace the mapping name in my vichuploable entity by another existing one. Everything work fine. So my is question why only 2 of 3 mappings work fine. What's wrong with my third mapping (document).

**Comment by monoulou** [comment]
Thank you! I reviewed my code and check it line by line and I noticed
something strange... If I replace the mapping name in my vichuploable
entity by another existing one. Everything work fine. So my is question why
only 2 of 3 mappings work fine. What's wrong with my third mapping
(document)???

**Comment by garak** [comment]
Again, we can't answer such questions. Unless, of course, you provide a repository with code where is possible to reproduce such problem (one workling mapping and one non-working mapping)

**Comment by mystimkg** [comment]
I have finally solved this problem! In fact, it was very stupid ... The problem only concerns the prod environment, which means that the configuration used must be registered from the config_prod.yml file and it was not my case! Most of the time, i am in dev environment , so I ended to ignoring the existence of this file ... Thank you to everyone who tried to help me!
