### ISSUE TITLE
JMS/metadata dependency is outdated

### ISSUE THREAD

**Issue by iCodr8** [dustin10/VichUploaderBundle#945]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    |no
| Version     | 1.8.x

#### Summary

Can not install JMS Serializer, because the JMS/metadata dependency of this bundle is still on 1.6. The current version for symfony 4 is 2.0 and should be supported from this bundle.

#### How to reproduce

`composer require jms/serializer`

#### Expected behavior

Change the dependency `jms/metadata` to `^2.0`

**Comment by garak** [comment]
Feel free to partecipate in PR #918
