### ISSUE TITLE
I can't have more more than 2 vichuploader mappings

### ISSUE THREAD

**Issue by mystimkg** [dustin10/VichUploaderBundle#946]
I try to upload a file with vichuploaderBundle...but it doesn't work?? the image_name attribute is never set so the file is never uploaded??

Here is my configuration:

parameters:
locale: fr
app.path.logos: /uploads/logos
app.path.imports: /uploads/imports
app.path.documents: /uploads/documents

vich_uploader:
db_driver: orm
mappings:
    logo:
        uri_prefix: '%app.path.logos%'
        upload_destination: '%kernel.root_dir%/../web%app.path.logos%'
        namer: vich_uploader.namer_uniqid
        inject_on_load:     false
        delete_on_update:   true
        delete_on_remove:   true
    import:
        uri_prefix: '%app.path.imports%'
        upload_destination: '%kernel.root_dir%/../web%app.path.imports%'
        namer: vich_uploader.namer_uniqid
        inject_on_load:     false
        delete_on_update:   true
        delete_on_remove:   true
    document:
        uri_prefix: '%app.path.documents%'
        upload_destination: '%kernel.root_dir%/../web%app.path.documents%'
        namer: vich_uploader.namer_uniqid
        inject_on_load:     false
        delete_on_update:   true
        delete_on_remove:   true

I have a OneToOne relationship between 2 entities.
Here is my first entity:

@ORM\Table(name="justificatif")
* @ORM\Entity(repositoryClass="MKG\MystiBundle\Repository\JustificatifRepository")
* @vich\Uploadable
 */
class Justificatif
{
/**
 * NOTE: This is not a mapped field of entity metadata, just a simple property.
 * @Vich\UploadableField(mapping="document", fileNameProperty="documentName")
 * @var File
 */
private $justificatifFile;

/**
 * @ORM\Column(type="string", length=255)
 * @var string
 */
private $documentName;

//...............................//
/**
 * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
 * of 'UploadedFile' is injected into this setter to trigger the  update. If this
 * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
 * must be able to accept an instance of 'File' as the bundle will inject one here
 * during Doctrine hydration.
 *
 * @param File|UploadedFile $justificatif
 */
public function setJustificatifFile(File $justificatif = null)
{
    $this->justificatifFile = $justificatif;

    if ($justificatif) {
        $this->updatedAt =  new \DateTime('now');
    }
}
//...............................//
}

Here is my second entity:

/**
 * NoteFrais
 *
 * @ORM\Table(name="note_frais")
 * @ORM\Entity(repositoryClass="MKG\MystiBundle\Repository\NoteFraisRepository")
 * @Vich\Uploadable
 */
 class NoteFrais
{
/**
 * @ORM\OneToOne(targetEntity="Justificatif", cascade={"persist"})
 * @ORM\JoinColumn(name="justificatif_id", referencedColumnName="id", onDelete="CASCADE", nullable=true)
 */
private $justificatif;
//.............................//
}

I tried a lot of things, revised my code, read pages and pages of forum ...

For information:

-I have the right rights on the destination folders on the server.
-I have tried several times to change the name of the problematic mapping ...
- I cleaned the cache so much (acquired, ordered ...)

On the other hand:

I noticed that I'm pointing my Justificatif entity to another existing mapping, everything works perfectly ??? Awesome ... But that's not what I want ... I want to keep 3 different matches and I want to understand why this 3rd mapping is ignored.

Thank you for your help!

**Comment by garak** [comment]
Please do not open new bugs while your current one is still open.
