### ISSUE TITLE
Mandatory parameter 'fieldName'

### ISSUE THREAD

**Issue by svinohod** [dustin10/VichUploaderBundle#947]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

Version of VichUploaderBundle: 1.8.5 

#### Summary

Methods
```
helper->asset()
vich_uploader_asset()
storage->resolvePath()
```
expectds parameter `fieldName` with Entity field name with Annotation @Vich\UploadableField
Can you please make this parameter not mandatory?

**Comment by garak** [comment]
Just to be clear, do you expect to get mapping for a single field automatically?

**Comment by svinohod** [comment]
1. I implemented my entity class and setting up one field as `@Vich\UploadableField`, as you described here https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/usage.md#step-2-link-the-upload-mapping-to-an-entity

2. I use method `vich_uploader_asset()` in my twig template to display my uploaded file, as you described here https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/generating_urls.md#generating-a-url-in-a-twig-template

My Question: why I have to pass in `vich_uploader_asset()` fieldName, although I already setting it up in my step 1. ?

**Comment by garak** [comment]
Because current implementation doesn't make any assumption on the number of your mapped fields.
In this case you got a single mapped field, but you could get more than one.

**Comment by svinohod** [comment]
@garak 
I think, that single `@Vich\UploadableField` per Entity is a default case and is most use case, as you described here https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/usage.md#step-2-link-the-upload-mapping-to-an-entity

I think, you could make parameter `fieldName` optional.

**Comment by garak** [comment]
I'm afraid that assuming that as a "most use case" is arbitrary, unless you're able to provide some data.
But making `fieldName` parameter optional is possible.
Feel free to propose a PR.

**Comment by garak** [comment]
Fixed
