### ISSUE TITLE
material-dashboard class viche_file

### ISSUE THREAD

**Issue by smerouane** [dustin10/VichUploaderBundle#949]
I am on a project symfony4 and I have material-dashboard for the utlisé and I used vichuploaderBundle for my profits but I have a problem at the level of the viche_file class on my form.

I'm sorry for my english

**Comment by smerouane** [comment]
I have conflict at the class vich_file and class_file of my material dashboard, so the input is not displayed correctly

**Comment by garak** [comment]
It looks like your problem is in your material dashboard (whatever it is), not in this bundle
