### ISSUE TITLE
preUpdate not call after setFile

### ISSUE THREAD

**Issue by GCalmels** [dustin10/VichUploaderBundle#951]
### Bug Report

When I create an object with a `$file`, it is persisted (via the `UploadListener`)
but if I add a file after a persist and before a flush, the `onUpdate` in `UploadListener` is never called... It is **not** a well known issue because the object is updated : `createdAt != updatedAt` and an other field changed as well...

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.8.5

**Comment by garak** [comment]
I'm not sure to understand your use case.
Maybe an example could be useful

**Comment by GCalmels** [comment]
@garak yes of course !
This snippet works as expected, the `prePersist` from `UploadListener` is called : 
```
$invoice = new Invoice();
$invoice->setFile(new UploadedFile($file, 'invoice.pdf'));
$em->persist($invoice);
```
but if the invoice is already persist without a file, `preUpdate` is never called :
```
$invoice->setFile(new UploadedFile($file, 'invoice.pdf'));
$em->flush();
```

In `setFile`, I update `updatedAt`...

**Comment by GCalmels** [comment]
Yes, I agree but the changeset is not empty ... some changes are pushed to the database but not the file...
I added a dump in `onUpdate` in `UploaderListener` but it is never displayed. An other `dump` is displayed in `onPersist`

**Comment by garak** [comment]
So, your changeset is not empty and the listener is not called.
It looks like a bug in Doctrine

**Comment by GCalmels** [comment]
There is a little detail : the object is updated, a field and the `updatedAt` change but without the `UploadListener` so the file will not be add...

**Comment by garak** [comment]
Your object is updated because you are changing its properties.

**Comment by GCalmels** [comment]
Thank you for your help ! 👍
