### ISSUE TITLE
CroppieJS Blob result, pass it to Symfony Controller, use setImage and persist

### ISSUE THREAD

**Issue by powerfulsheron** [dustin10/VichUploaderBundle#953]
|    Q        |   A
|------------ | -----
| Version     | Last

### Support Question

I have a small symfony 4 application with a cropper using CroppieJS. When i crop and hit the save button, croppie sends me a base64 image :

   `$( "#cropSave" ).click(function() {
    basic.croppie('result','canvas'
    ).then(function (result) {}`

how to send this result to my controller and persist the image with VichUploader and Doctrine ?

Here is my controller :

    public function updateProfilePicture(Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->getUser();
        $entityManager = $this->getDoctrine()->getManager();
        $user->setImageFile($request->files->get('image'));
        $entityManager->flush();
        return new Response("ok");
    }

I tried a lot of things but I must lack experience because it don't work :
https://ourcodeworld.com/articles/read/322/how-to-convert-a-base64-image-into-a-image-file-and-upload-it-with-an-asynchronous-form-using-jquery
https://stackoverflow.com/questions/35940290/how-to-convert-base64-string-to-javascript-file-object-like-as-from-file-input-f

I was thinking maybe "Simulate" a file upload in JS from the base64 using VichUploader formType input field, but I want to know if there are simpler ways.

Thanks

**Comment by garak** [comment]
You can try to create an instance of UploadedFile from your string, then pass it to your setter method

**Comment by powerfulsheron** [comment]
I tried but the problem is that creating a instance of UploadedFile requires a realPath and since i'm passing either a base64 string or a blob, I don't have this.

I managed a workaround : 

https://stackoverflow.com/questions/54352608/vichuploader-and-croppiejs-how-to-send-a-base64-cropped-image-to-persist-in-sy/54362349#54362349

Maybe not the best solution but eh, it works. I will try to improve this code if I got the time. Thanks for your help

**Comment by garak** [comment]
You need to create a temporary file, that is what PHP does for your when you upload a file.

**Comment by powerfulsheron** [comment]
Yeah I though about that too, but it was too complicated to get the application base path without more and more bundles and confs, manage writting rights, etc etc

**Comment by garak** [comment]
Just write it to a `tmpfile()`

**Comment by powerfulsheron** [comment]
Here's my code : 

 `try {
            $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
            $user = $this->getUser();
            $entityManager = $this->getDoctrine()->getManager();
            $output_file = tmpfile();
            $ifp = fopen( $output_file, 'wb' );
            $data = explode( ',', $request->get('image') );
            fwrite( $ifp, base64_decode( $data[ 1 ] ) );
            fclose( $ifp );
            $file =  new UploadedFile($output_file, $user->getid().'.jpg', 'image/jpeg',null,null,true);
            $user->setImageFile($file);
            $entityManager->flush();
        }
        catch (exception $e) {

        }`

here is the error : `Warning: fopen() expects parameter 1 to be a valid path, resource given`
