### ISSUE TITLE
Service or alias has been removed or inlined when the container was compiled

### ISSUE THREAD

**Issue by pdias** [dustin10/VichUploaderBundle#954]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | master

#### Summary

Since yesterday's update i have this error:

> An exception has been thrown during the rendering of a template ("The "vich_uploader.namer_uniqid.client_photo" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.").

#### How to reproduce

The error occurs when i call "**vich_uploader_asset**" in my twig.

`<img src="{{ vich_uploader_asset(output.client, 'photoFile') }}" class="img-offline img-responsive img-profile" alt="" />
`
#### Solution/Patch

In service.yml:

```
    vich_uploader.namer_uniqid.client_photo:
        class: Vich\UploaderBundle\Naming\UniqidNamer
        public: true
```

Thanks.

**Comment by garak** [comment]
@pdias can you try if last commit fixed it? Thanks

**Comment by pdias** [comment]
Yes, is fixed. Thanks.
