### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by PaddyLock** [dustin10/VichUploaderBundle#956]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.8.6

#### Summary

Your requirements could not be resolved to an installable set of packages

#### Current behavior

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.2.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install vich/uploader-bundle 1.8.6
    - Conclusion: don't install vich/uploader-bundle 1.8.5
    - Conclusion: don't install vich/uploader-bundle 1.8.4
    - Conclusion: don't install vich/uploader-bundle 1.8.3
    - Conclusion: don't install vich/uploader-bundle 1.8.2
    - Conclusion: don't install vich/uploader-bundle 1.8.1
    - Conclusion: remove jms/metadata 2.0.0
    - Installation request for vich/uploader-bundle ^1.8 -> satisfiable by vich/uploader-bundle[1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6].
    - Conclusion: don't install jms/metadata 2.0.0
    - vich/uploader-bundle 1.8.0 requires jms/metadata ^1.6 -> satisfiable by jms/metadata[1.6.0, 1.7.0].
    - Can only install one of: jms/metadata[1.6.0, 2.0.0].
    - Can only install one of: jms/metadata[1.7.0, 2.0.0].
    - Installation request for jms/metadata (locked at 2.0.0) -> satisfiable by jms/metadata[2.0.0].

Installation failed, reverting ./composer.json to its original content.

#### How to reproduce
first install jms/serializer-bundle which requires jms/metadata ^2.0
`composer require jms/serializer-bundle`

then try and install vich/uploader-bundle

`composer require vich/uploader-bundle`

#### Expected behavior

Can vich/uploader-bundle require latest  jms/serializer-bundle ^2.0

**Comment by PaddyLock** [comment]
Sorry, I see I made a duplicate of #941 is this being looked at yet please?

**Comment by garak** [comment]
You can refer to PR #918
