### ISSUE TITLE
Add Content-Length header

### ISSUE THREAD

**Issue by abrgitlab** [dustin10/VichUploaderBundle#957]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I want to set Content-Length header when download file via DownloadHandler. 
Only one way to get file size is use fstat in createDownloadResponse, but cannot use it in the controller. Please, add method, which will set 'Content-Length' header if needed.

**Comment by garak** [comment]
I'm not sure to understand your need.
Anyway, you can manipulate the Response object returned by DownloadHandler as you want.
I suggest you to create a service, inject DownloadHandler into it, and add your logic. Then use such object in your controller instead of using directly DownloadHandler

**Comment by abrgitlab** [comment]
There's problem is that browser doesn't know available size of downloading file without Content-Length header. But file gets from storage inside this bundle. I cannot get size of downloading file except by cloninig DownloadHandler or fork all the bundle. I created this issue to resolve problem with getting size of downloadable file.
If there's some ways to get this value, please tell me.

**Comment by garak** [comment]
So, what's the point in DownloadHandler you need to alter?
Can you provide the needed changes?

**Comment by abrgitlab** [comment]
Should I create pull request to show my point of view on this issue?

**Comment by garak** [comment]
Yes, please

**Comment by abrgitlab** [comment]
https://github.com/dustin10/VichUploaderBundle/pull/958
