### ISSUE TITLE
An error occurred while loading the web debug toolbar after upgrade to 1.9.0 

### ISSUE THREAD

**Issue by diabl0** [dustin10/VichUploaderBundle#961]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.9.0

#### Summary

While using latest Symfony 4.2.3 after upgrading to 1.9.0 web debug toolbbar stops working:
`An error occurred while loading the web debug toolbar.`

#### Current behavior

After upgrading to 1.9.0 web debug toolbbar stops working:
`An error occurred while loading the web debug toolbar.`

while accessing _wdt directly i have exception:

`The profiler template "VichUploaderBundle::Collector/mapping_collector.html.twig" for data collector "vich_uploader.mapping_collector" does not exist.`
at vendor/symfony/web-profiler-bundle/Profiler/TemplateManager.php line 90

Same happens when trying to access profiler directly

#### How to reproduce

Upgrade bundle from 1.8.6 to 1.9.0

#### Expected behavior

working web debug toolbar

**Comment by garak** [comment]
That's weird, since the file is [present](https://github.com/dustin10/VichUploaderBundle/blob/1.9.0/Resources/views/Collector/mapping_collector.html.twig).
Can you find such file in your vendor dir?
