### ISSUE TITLE
file per language

### ISSUE THREAD

**Issue by NicolasDW** [dustin10/VichUploaderBundle#964]
|    Q        |   A
|------------ | -----
| Version     | 1.8

### Support Question

Hi everyone,

Is there any way to upload a file per language with VichUploaderBundle ? Especially with Knp Doctrine Behaviors.

Thanks

**Comment by garak** [comment]
Question is not really clear.
You can upload any number of file

**Comment by garak** [comment]
Closing for missing feedback
