### ISSUE TITLE
Make bundle compatible to twig/twig:^2.7.0

### ISSUE THREAD

**Issue by Lyhl** [dustin10/VichUploaderBundle#968]
Due to a security issue in twig/twig:2.6.2 and earlier versions, we had to update to twig/twig:^2.7.0 - see https://symfony.com/blog/twig-sandbox-information-disclosure for more details. 

Unfortunately after updating to twig 2.7.2 we see deprecation warnings caused by using this bundle. 

Can you please fix the deprecation warnings and provide a version that's fully compatible with twig/twig:^2.7.0

**Comment by garak** [comment]
Can you report you deprecations?
I just tried to upgrade a project of mine, I can't find any twig-related deprecations caused by VichUploaderBundle

**Comment by Lyhl** [comment]
Thank you for your quick answer. 

The deprecation notice "The spaceless tag is deprecated since Twig 2.7, use the spaceless filter instead." occurs on rendering a form using the VichImageType. 
I guess that in https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/views/Form/fields.html.twig is the responsible code / spaceless tag. 
Using {% filter spaceless %} instead should solve the deprecation as mentioned in https://twig.symfony.com/doc/2.x/deprecated.html#tags. Please check if there are any other deprecations that should be solved in VichUploaderBundle.

Thx and regards,
Andreas
