### ISSUE TITLE
Unable to handle files with special characters

### ISSUE THREAD

**Issue by gnat42** [dustin10/VichUploaderBundle#973]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.8.6

#### Summary

If the file has a 'special' character such as a % the vich_uploader_asset twig helper doesn't urlencode it. Thus the file is unable to be downloaded.

In FileSystemStorage.php
#### Current behavior

Suppose filename TaxCertificate-85%.pdf.
vich_uploader_asset(document,'field') outputs 

http://project.local/documents/93a61cf5d3e004af359b4406a391de907190ef9a/contracts/BEDNAR-0002/TaxCertificate-85%.pdf

#### How to reproduce

Use a file with a special character needing escaping in a url.

#### Expected behavior

I would expect the output to be.

http://project.local/documents/93a61cf5d3e004af359b4406a391de907190ef9a/contracts/BEDNAR-0002/TaxCertificate-85%25.pdf

To fix it in my particular case FileSystemStorage.php needs a small change:

from
```
return sprintf('%s/%s', $mapping->getUriPrefix(), $uploadDir.$name);
```
to
```
return sprintf('%s/%s', $mapping->getUriPrefix(), $uploadDir.urlencode($name));
```

**Comment by gnat42** [comment]
See PR #974 for what fixes it for my particular use case. I wasn't as sure how it worked for other storage systems and whether they're required.

**Comment by garak** [comment]
A way to go around this problem has been highlighted in related PR.
