### ISSUE TITLE
Symfony 3.4 vichUploaderBundle existing file in Edit form

### ISSUE THREAD

**Issue by kiuega** [dustin10/VichUploaderBundle#977]
Hello, I've a problem with my edit-form with my edit-form using VichUploader.

![edit-form](https://user-images.githubusercontent.com/48760851/54747037-11790200-4bce-11e9-9da8-90b5e0c2b11f.PNG)

I don't understand why I've "form.label.delete" checkbox.

And more important: I would like the form to show me the two files I already upload. Because the form acts as if I did not upload anything before editing. Thus, if I validate my form without touching the "File" fields, it asks me to enter a file.

This is my code:

**Controler.php**

![controller_edit](https://user-images.githubusercontent.com/48760851/54747305-cad7d780-4bce-11e9-94ee-fbaeb39e79a0.PNG)

**My "a href" to the edit-page in the index.html.twig:**

![twig edit](https://user-images.githubusercontent.com/48760851/54747313-d1fee580-4bce-11e9-8d70-679e502507b0.PNG)

**My edit-page (edit.html.twig)**

![form twig edit](https://user-images.githubusercontent.com/48760851/54747333-e0e59800-4bce-11e9-9b29-34653ce15435.PNG)

**My formType:**

![formType](https://user-images.githubusercontent.com/48760851/54747335-e347f200-4bce-11e9-971d-9a0a0da35b3e.PNG)

Thanks !

**Comment by garak** [comment]
It looks like you're missing the basic knowledge of this bundle.
Please read the documentation, then if you're still in trouble feel free to open another issue
