### ISSUE TITLE
Symfony 3.4 Vichuploader how show existing file in a form

### ISSUE THREAD

**Issue by kiuega** [dustin10/VichUploaderBundle#978]
Hello
Following my recent post on the same subject, I consulted the documentation of the bundle vichuploader.

I was able to remove the form.delete.label.

Only, I still can not understand what I can do to make this happen:

1. I am in the list of my entity rows.
2. I click on a line to update it.
3. I want my update form to show me my files if they exist instead of nulling them.

I want the form to show me if I already have files for this line.

For the moment, everything is updated. If I do not select another file, it keeps the old ones that I had. But from an aesthetic point of view I still want to know if the line already contains files

Even with the documentation I do not understand how to do it.

I am under Symfony 3.4 and PHP 5.6

![edit-form](https://user-images.githubusercontent.com/48760851/54752272-c4049100-4bdd-11e9-9d8e-3b4c49fec4ca.PNG)

Thanks for your help

**Comment by garak** [comment]
See https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/form/vich_file_type.md
Anyway, that depends on the object tied to your form. Such object is controlled by you, so this bundle can't display anything in the case of you "Parquet file" is null when editing.

Also, you're using a version of PHP that is out of support (and, as a consequence, a version of this bundle that is out of support). Feel free to open another issue when using supported versions.
