### ISSUE TITLE
why cannot I delete my image entity ?

### ISSUE THREAD

**Issue by 12rambau** [dustin10/VichUploaderBundle#980]
|    Q        |   A
|------------ | -----
| Version     | 1.10

### Support Question

I work with Symphony 4 and Doctrine And i'm using vinchUploader to manage my images. 

I create an entity image and when I use this entity to add new images it works like a charm but when I want to delete it with my controller : 
```php
    public function delete(Image $image):Response
    {
        $em = $this->getDoctrine()->getEntityManager();
        $em->remove($image);
        $em->flush();

        return new RedirectResponse($this->generateUrl('image-index'));
    }
```

I get the strangest error : 
```
Expected argument of type "string", "NULL" given at property path "fileName".
```

with `filename being as such in my Image entity : 

```php
     /** 
     * @Vich\UploadableField(mapping="picture", fileNameProperty="fileName")
     * @var File
     */
    private $imageFile;

    /**
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string|null
     */
    private $fileName;
```

The same behavior appear when dealing with editing the entity. Do you see anything that I did wrong ? Or is it a bug ?

This question have been posted few weeks ago on SO [here](https://stackoverflow.com/questions/55109410/why-cannot-i-delete-my-image-entity-using-vichuploader) so if you find it inappropriate here feel free to remove the issue

**Comment by garak** [comment]
Use a nullable type hinting (also replied on SO)
