### ISSUE TITLE
VichUploader Serving files with a controller

### ISSUE THREAD

**Issue by kiuega** [dustin10/VichUploaderBundle#981]
Hello,
I would like, when clicking on a URL that downloads the file, to make a change in my database.

![indexVich](https://user-images.githubusercontent.com/48760851/54919836-11e10800-4f02-11e9-8407-607a9eeb6a87.PNG)

Is this the DownloadHander.php file that I must edit ?

![downloadVich](https://user-images.githubusercontent.com/48760851/54919867-22917e00-4f02-11e9-895e-aa7d4addafd0.PNG)

If yes, will there be any repercussions on the rest of the bundle's features?

Thanks !

**Comment by garak** [comment]
Please take a look to [serving_files_with_a_controller](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/downloads/serving_files_with_a_controller.md) guide.

**Comment by kiuega** [comment]
Hello,

I edited my code.

I have on my **index.html.twig** the line : 

` <td><a href="{{ path('paquet_file', { 'id': uneInfo.id}) }}"</a>{{ uneInfo.urlPaquet }} </td>`

On my controller : 

```
`namespace Site\PagesBundle\Controller;

use Site\PagesBundle\Entity\Paquet;
use Site\PagesBundle\Entity\TypeUser;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Vich\UploaderBundle\Handler\DownloadHandler;

//........
```

```
/** 
     * Serves an uploaded file.
     *
     * @Route("/{id}/file", name="paquet_file")
     */
    public function fileAction(Paquet $paquet)
    {   
        $downloadHandler = $this->get('vich_uploader.download_handler');

        return $downloadHandler->downloadObject($paquet, $fileField = 'paquetFile', Paquet::class, true);
    }
```

But when I click on the URL file : 

![vich](https://user-images.githubusercontent.com/48760851/55143351-db440100-513e-11e9-9c52-db0465fefc09.PNG)

I have this file : 

![DDLfileVich](https://user-images.githubusercontent.com/48760851/55143362-e434d280-513e-11e9-872b-7b4349792306.PNG)


Thanks for your help

**Comment by garak** [comment]
I'm not sure to understand what you get when you click

**Comment by kiuega** [comment]
In the example, I am supposed to get the file "commande composer.txt". 

But instead I get this very weird file.

![DDLfileVich](https://user-images.githubusercontent.com/48760851/55145162-886c4880-5142-11e9-8fa6-0f3e0152946b.PNG)

And when I open it with the block noten I am very surprised because it is neither more nor less than my configuration of the file "sftp config" of my project. I don't understand

**Comment by garak** [comment]
Still, I don't get your image. Sorry but I don't use windows.
Anyway, you can open your profiler and see what happened there

**Comment by kiuega** [comment]
I do not understand either what this represents or even why this file contains the STFP configuration parameters of my project. I am a great beginner in Symfony, and I do not know all the vocabulary of this framework, I really do not know what to do

**Comment by kiuega** [comment]
The problem can only come from my code because when I use the file by twig, it is downloaded. But using it from the controller is a problem

**Comment by garak** [comment]
Follow these steps:
- on any page, click on the green "200"
- on upper left corner, click on "Last 10"
- click on any result you found. The one you want to inspect
- see all the informations Symfony provides you on your request, response, etc.

Also, you can debug your application using xdebug, a debugger and some stop points.

Anyway, I'm afraid that this is more about general programming, general PHP, or general Symfony.
Since here we're focused on this bundle, you should probably use one of the many tools that Symfony ecosystem offers for supporting developers

Thank you

**Comment by kiuega** [comment]
I will directly modify the asset that handles the download to incorporate the lines related to the database processing. Because there my situation is really blocked. Quit having to serve the download link from the twig file, as much to perform the processing from the asset, right?

What would be the file to edit in this case?

**Comment by garak** [comment]
You can't edit a vendor file

**Comment by kiuega** [comment]
Wow, guess what ... I changed this line:

`return $downloadHandler->downloadObject($paquet, $fileField = 'paquetFile', Paquet::class, true);
`
by that :

And now, it works. It's great, but why does it work by passing the filename to null?

`return $downloadHandler->downloadObject($paquet, $fileField = 'paquetFile', Paquet::class, null);`
