### ISSUE TITLE
Empty vish mapping toolbar

### ISSUE THREAD

**Issue by ahmed-bhs** [dustin10/VichUploaderBundle#983]
|    Q        |   A
|------------ | -----
| Version     | 1.9.1

### Support Question

I just installed vishuploader bundle. This is my current config:

```
vich_uploader:
    db_driver: orm
    mappings:
        contact_form:
            uri_prefix:         '%app.path.form_contact%'
            upload_destination: '%kernel.root_dir%/../web%app.path.form_contact%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer:              vich_uploader.namer_uniqid

```

My question why I'm not seeing any thing under the Vish Mappings toolbar . It's empty??

<img src="https://i.imgur.com/4bvUb2p.png"/>
<img src="https://i.imgur.com/mxjljLX.png"/>
Any explanation would be appreciated.

**Comment by garak** [comment]
It's only working if you use XML/yaml mapping

**Comment by fyrye** [comment]
@ahmed-bhs What garak is referring to is the [non-annotation entity based metadata mappings](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/mapping/yaml.md), not the `vich_uploader.mappings` config.
