### ISSUE TITLE
Remove form type 'file' name from the form

### ISSUE THREAD

**Issue by ahmed-bhs** [dustin10/VichUploaderBundle#984]
|    Q        |   A
|------------ | -----
| Version     | 1.9.1

I'm working on an upload file form using <a href="https://github.com/dustin10/VichUploaderBundle">VichUploaderBundle</a>. This the buildForm part of my form Type:
```
class AssistanceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       $builder->add('file1', VichFileType::class)
    }
    ...

```
Unfortunately, **VichFileType** is generating an **input name** that's end always with `file` : `<input type="file" id="file1_file" name="file1[file]" required="required" class="form-control-file">`
Why: Because if we look inside <a href="https://github.com/dustin10/VichUploaderBundle/blob/master/Form/Type/VichFileType.php#L95" >VichFileType</a> code, we gonna find an `->add('file')`

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('file', Type\FileType::class, [
            'required' => $options['required'],
            'label' => $options['label'],
            'attr' => $options['attr'],
            'translation_domain' => $options['translation_domain'],
        ]);
    ...

    }

So i need to submit every-time an array: `[ 'file1' => ['file' => the file object ] ] ` This is not really clean.<br>
Does, there any way where I can remove that `file` suffix from the name of the input to looks like this : <br>
`<input type="file" id="file1" name="file1" required="required" class="form-control-file">`

I tried `createNamed(null,...` and `getBlockPrefix() with return ''` But nothing changed. Any help would be appreciated. Thanks.

**Comment by garak** [comment]
You can create you own FileType and use the name you prefer

**Comment by ahmed-bhs** [comment]
Hey garak thank you for your answer. Ther's no kind of option !! Could you provide me more information about the FileType that I should create!

**Comment by garak** [comment]
A class copied from VichFileType

**Comment by ahmed-bhs** [comment]
But I want to remove the suffix, not chnage it to another name.

**Comment by garak** [comment]
In your own class you can do whatever you want. For example, using directly a file field instead of adding it from the builder. Of course, you would need to replicate the functionalities offered by VichFileType.
