### ISSUE TITLE
PropertyDirectoryNamer with more one property

### ISSUE THREAD

**Issue by theodelhomme** [dustin10/VichUploaderBundle#986]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

Is it possible to have several property of entity or object to name directories like :

directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'marque', 'category', 'sub-category' etc}

**Comment by garak** [comment]
Of course. Take a look to [docs](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/directory_namer/howto/create_a_custom_directory_namer.md)

**Comment by theodelhomme** [comment]
> Of course. Take a look to [docs](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/directory_namer/howto/create_a_custom_directory_namer.md)

**Comment by theodelhomme** [comment]
@garak it's not exactly what i want to do :

What I want is to create directories and subdirectories with the properties of my Resource entity according to the data sent from the form...

**Comment by garak** [comment]
You need to pass such data to your object. The namer needs to get information not only at update time, but also when showing the file.

**Comment by theodelhomme** [comment]
of course but, i want directories and subdirectories structure  with the data of the form class not only one directoryname...

**Comment by garak** [comment]
The data of your form class need to be in your obect.
After the file is saved, there is no form anymore

**Comment by theodelhomme** [comment]
of course but, but how to make directories and subdirecotories with these data ?

**Comment by garak** [comment]
That's up to you

**Comment by Padam87** [comment]
@garak This is why my old PR would have been useful. 90% of the time a custom namer is totally overkill, and could be replaced with a simple callback.

https://github.com/dustin10/VichUploaderBundle/pull/892
