### ISSUE TITLE
Serialization of 'Symfony\Component\HttpFoundation\File\File' is not allowed

### ISSUE THREAD

**Issue by kiuega** [dustin10/VichUploaderBundle#987]
|    Symfony |   PHP
|------------ | -----
|      3.4        | 5.6

### Support Question

I am working on a site that allows users to download packages.

I have a Packages entity that contains attributes (title, comment, ...) and File attributes. These files are uploaded thanks to VichUploaderBundle.

I also have two User tables. One for those who connect to the site locally (login form on the site) and a CAS authentication.

When I authenticate in CAS and I want to access the page presenting the packages to download, I come across this error:

> Serialization of 'Symfony\Component\HttpFoundation\File\File' is not
> allowed

Yet, when I connect locally, there is no such problem. I do not understand why I have this error.

This is my code :

**CAS authentication: success :**

    /**
         * Traitement personnalisé après récupération du token
         * 
         * Il est possible d'enrichir le token (attributs...) ou d'effectuer des contrôles supplémentaire
         * 
         * @param $token 
         *      Token d'authification généré
         * 
         * @return null
         */
        public function onSuccess($token){
    
            $mail = $this->ai->getMail();
            $nomComplet = $this->ai->getCompletName();
            $rne = $this->ai->getRne();
    
            $token->setAttribute('mail', $mail);
            $token->setAttribute('nomComplet', $nomComplet);
            $token->setAttribute('rne', $rne);   
            $token->setAttribute('typeAuth','cas');
    
            $user = $this->checkBDD($mail); //I retrieve the user object
    
            $token->setAttribute('user',$user);
    
    
        }

The User object is placed as an attribute in the token.

He goes to his profile, which must contain his information, as well as a table representing the packages he has already downloaded.

    /**
     * @Route ("/profile", name="user_profile")
     */
    public function profileAction()
    {
        $token = $this->get('security.token_storage')->getToken();
        //dump($token->getAttribute('nomComplet'));
        $user = $token->getAttribute('user');
    
    
        return $this->render('@Pages/cas/profile.html.twig');
    }

Profile.html.twig:

    {% extends "base.html.twig" %}
    {% block body %}
    
    {% set user = app.getToken().getAttribute('user') %}
    {% dump(user) %}
    
    {% dump(app.getToken().getAttribute('nomComplet')) %}
    <div class="container">
        <h1><u>{{ user.mail }}</u></h1><br/>
        
        <h2>Profil</h2>
        
        <br/>
        
        <table class="table">
            <tbody>
                <tr>
                    <th scope="row">Nom d'utilisateur</th>
                    <td>{{app.user.username}}</td>
                </tr>
                <tr>
                    <th scope="row">Email</th>
                    <td>{{user.mail}}</td>
                </tr>
                <tr>
                    <th scope="row">Téléchargements restants</th>
                    <td>4</td>
                </tr>
            </tbody>
        </table>
        
        <br/><br/><br/>
        
        <h3> Liste des packages téléchargés </h3> <br/>
        <table class="table table-stripped">
            <thead>
                <tr>
                    <th>Titre</th>
                    <th>Package</th>
                    <th>Notice</th>
                    <th>Commentaire</th>
                </tr>
            </thead>
            <tbody>
                    {% for unPackage in user.packages %}
                <tr>
                    <td> {{unPackage.titre}} </td>
                    <td> {{unPackage.urlPaquet}} </td>
                    <td> {{unPackage.urlNotice}} </td>
                    <td> {{unPackage.commentaire}} </td>
                </tr>
                    {% endfor %}
            </tbody>
        </table>
        
        <a href="{{path('connexion_index')}}" class="btn btn-primary">Retour à l'accueil</a>
        <a href="{{ path('deconnexion') }}" class="btn btn-primary">Déconnexion</a><br/><br/><br/><br/>
        </div>

in twig, we retrieve the User attribute that was in the token and we display its information, including its packages. (The user has a packages attribute that is an ArrayCollection and is associated in ManyToMany with the Package entity)

**My User entity :**

    <?php
    
    namespace Site\PagesBundle\Entity;
    
    use Doctrine\ORM\Mapping as ORM;
    use Doctrine\Common\Collections\Collection;
    use Site\PagesBundle\Security\Traits\traitUser;
    use Doctrine\Common\Collections\ArrayCollection;
    use Symfony\Component\Security\Core\User\UserInterface;
    use Symfony\Component\Validator\Constraints as Assert;
    use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
    
    /**
     * UserCas
     *
     * @ORM\Table(name="user_cas")
     * @ORM\Entity(repositoryClass="Site\PagesBundle\Repository\UserCasRepository")
     * @UniqueEntity("mail")
     */
    class UserCas
    {
    
        use traitUser;
    
        
        /**
         * @var int
         *
         * @ORM\Column(name="id", type="integer")
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="AUTO")
         */
        private $id;
    
        /**
         * @var int
         *
         * @ORM\Column(name="nbTelechargementsAuto", type="integer", nullable=true)
         */
        private $nbTelechargementsAuto;
    
        /**
         * @var bool
         *
         * @ORM\Column(name="enabled", type="boolean")
         */
        private $enabled;
    
    
        /**
         * @ORM\Column(name="mail", type="string")
         */
        private $mail;
    
        /**  
         * @var \Doctrine\Common\Collections\Collection
         * @ORM\ManyToMany(targetEntity="Paquet")  
         * @ORM\JoinTable(name="paquetsDDLUserCas") 
         * @ORM\JoinColumn(nullable=false)
         */  
        private $packages;
    
        /**
         * Constructor
         */
        public function __construct()
        {
            $this->packages = new ArrayCollection();
            $this->setEnabled(true);
    
        }
    
    
    
    
        /**
         * Get id
         *
         * @return int
         */
        public function getId()
        {
            return $this->id;
        }
    
    
        /**
         * @return string
         */
        public function getMail()
        {
            return $this->mail;
        }
    
        public function setMail($mail)
        {
            $this->mail = $mail;
        }
    
        
        /**
         * Set enabled
         *
         * @param boolean $enabled
         *
         * @return UserCas
         */
        public function setEnabled($enabled)
        {
            $this->enabled = $enabled;
    
            return $this;
        }
    
        public function isEnabled()
        {
            return $this->enabled;
        }
    
    }

**My Package entity :**

    <?php
    
    namespace Site\PagesBundle\Entity;
    
    use DateTimeImmutable;
    use Doctrine\ORM\Mapping as ORM;
    use Site\PagesBundle\Entity\Paquet;
    use Site\PagesBundle\Entity\TypeUser;
    use Symfony\Component\HttpFoundation\File\File;
    use Doctrine\Common\Collections\ArrayCollection;
    use Vich\UploaderBundle\Mapping\Annotation as Vich;
    use Symfony\Component\HttpFoundation\File\UploadedFile;
    use Symfony\Component\Validator\Constraints as Assert;
    
    /**
     * Paquet
     *
     * @ORM\Table(name="paquet")
     * @ORM\Entity(repositoryClass="Site\PagesBundle\Repository\PaquetRepository")
     * @Vich\Uploadable
     */
    class Paquet
    {
        /**
         * @var int
         *
         * @ORM\Column(name="id", type="integer")
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="AUTO")
         */
        private $id;
    
    
        /**  
         * @var \Doctrine\Common\Collections\Collection
         * @ORM\ManyToMany(targetEntity="TypeUser")  
         * @ORM\JoinTable(name="Packages_des_TypesUser") 
         * @ORM\JoinColumn(nullable=false)
         */  
        private $typeUser;
    
        public function __construct()
        {
            $this->typeUser = new ArrayCollection();
        }
    
        /** 
         * Get TypeUser 
         * 
         * @return Site\PagesBundle\Entity\TypeUser 
         */ 
        public function getTypeUser() 
        { 
            return $this->typeUser; 
        }
    
        public function deleteTypeFromTypesUser(TypeUser $type)
        {
            $this->typeUser->removeElement($type);
        }
    
    
    
        /**
         * Set typeUser
         *
         * @param Site\PagesBundle\Entity\TypeUser $typeUser
         *
         * @return Paquet
         */
        public function setTypeUser(Site\PagesBundle\Entity\TypeUser $typeUser)
        {
            $this->typeUser = $typeUser;
    
            return $this;
        }
    
    
        /**
         * @var string
         *
         * @ORM\Column(name="titre", type="string", length=255)
         * @Assert\Length(min=5, max=255, minMessage="Le titre doit comporter au minimum 5 caractères")
         */
        private $titre;
    
        /**
         * @var string
         *
         * @ORM\Column(name="urlPaquet", type="string", length=255)
         */
        private $urlPaquet;
    
        /**
         * @Vich\UploadableField(mapping="paquet", fileNameProperty="urlPaquet")
         * @var File
         */
        private $paquetFile;
    
        /**
         * @ORM\Column(type="datetime")
         *
         * @var \DateTime
        */
        private $updatedAt;
    
        /**
     * @param File|UploadedFile $unPaquetFile
     *
     * @return Paquet
    */
    public function setPaquetFile(File $unPaquetFile = null)
    {
        $this->paquetFile = $unPaquetFile;
    
        if ($unPaquetFile) 
        {
            $this->updatedAt = new \DateTimeImmutable();
        }
            
        
        return $this;
    }
    
        /**
         * Set updatedAt
         *
         * @param \DateTime $updatedAt
         *
         * @return Paquet
         */
        public function setUpdatedAt($updatedAt)
        {
            $this->updatedAt = $updatedAt;
    
            return $this;
        }
    
        /**
         * Get updatedAt
         *
         * @return \DateTime
         */
        public function getUpdatedAt()
        {
            return $this->updatedAt;
        }
    
    /**
     * @return File|null
     */
    public function getPaquetFile()
    {
        return $this->paquetFile;
    }
    
    
        /**
         * @var string
         *
         * @ORM\Column(name="urlNotice", type="string", length=255,nullable=true)
         */
        private $urlNotice;
    
        /**
         * @Vich\UploadableField(mapping="notice", fileNameProperty="urlNotice",nullable=true)
         * @var File
         */
        private $noticeFile;
    
        /**
         * @var string
         *
         * @ORM\Column(name="commentaire", type="text")
         */
        private $commentaire;
    
    
        /**
         * Get id
         *
         * @return int
         */
        public function getId()
        {
            return $this->id;
        }
    
        /**
         * Set titre
         *
         * @param string $titre
         *
         * @return Paquet
         */
        public function setTitre($titre)
        {
            $this->titre = $titre;
    
            return $this;
        }
    
        /**
         * Get titre
         *
         * @return string
         */
        public function getTitre()
        {
            return $this->titre;
        }
    
        /**
         * Set urlPaquet
         *
         * @param string $urlPaquet
         *
         * @return Paquet
         */
        public function setUrlPaquet($urlPaquet)
        {
            $this->urlPaquet = $urlPaquet;
    
            return $this;
        }
    
        /**
         * Get urlPaquet
         *
         * @return string|null
         */
        public function getUrlPaquet()
        {
            return $this->urlPaquet;
        }
    
        /**
         * @return File|null
         */
        public function getNoticeFile()
        {
            return $this->noticeFile;
        }
    
            /**
         * @param File|UploadedFile $uneNoticeFile
         *
         * @return Paquet
        */
        public function setNoticeFile(File $uneNoticeFile = null)
        {
            $this->noticeFile = $uneNoticeFile;
    
            if ($uneNoticeFile) 
            {
                $this->updatedAt = new \DateTimeImmutable();
            }
            
        
            return $this;
    }
    
        /**
         * Set urlNotice
         *
         * @param string $urlNotice
         *
         * @return Paquet
         */
        public function setUrlNotice($urlNotice)
        {
            $this->urlNotice = $urlNotice;
    
            return $this;
        }
    
        /**
         * Get urlNotice
         *
         * @return string
         */
        public function getUrlNotice()
        {
            return $this->urlNotice;
        }
    
        /**
         * Set commentaire
         *
         * @param string $commentaire
         *
         * @return Paquet
         */
        public function setCommentaire($commentaire)
        {
            $this->commentaire = $commentaire;
    
            return $this;
        }
    
        /**
         * Get commentaire
         *
         * @return string
         */
        public function getCommentaire()
        {
            return $this->commentaire;
        }
    }

That's it, I think I put all the information that was needed. And I repeat that when I authenticate locally (and not in CAS), I do not have this problem. And I should not have to serialize any file normally, right?

Since when I use a local connection (with a User entity that uses FOSUserBundle and can use its methods), it works. And so it would seem that there is no need to do this serialization job within the Package entity. The difference is with the UserCas entity (which is the entity for users who authenticate in CAS), this entity does not use FOSUserBundle , and therefore does not have some methods, which might be useful ?

--------------------------------------------------------------------------------

So, what I did ?

In Paquet.php, I've implemented \Serializable, and two methods :

      /** @see \Serializable::serialize() */
      public function serialize()
      {
          return serialize(array(
              $this->id,
              $this->noticeFile,
              $this->paquetFile,
          
          ));
      }
      
      /** @see \Serializable::unserialize() */
      public function unserialize($serialized)
      {
          list (
              $this->id,
              $this->noticeFile,
              $this->paquetFile,
          ) = unserialize($serialized, array('allowed_classes' => false));
      }

Same error, my methods are they good ?

**Comment by garak** [comment]
Try to implement Serializable on your user class too

**Comment by kiuega** [comment]
Yes, I've added two functions on my UserCas.php entity :

`    public function serialize()
    {
        return serialize($this->id);
    }

    public function unserialize($serialized)
    {
       $this->id = unserialize($serialized);

    }`

It works better, thx

**Comment by Morisf** [comment]
symfony 5 fix

```
public function __serialize(): array
    {
        return [
            'id' => $this->id,
            'email' => $this->email,
            //......
        ];
    }

public function __unserialize(array $serialized): User
{
    $this->id = $serialized['id'];
    $this->email = $serialized['email'];
    // .....
    return $this;
}
```

**Comment by ph1823** [comment]
> public function __serialize(): array
>     {
>         return [
>             'id' => $this->id,
>             'email' => $this->email,
>             //......
>         ];
>     }
> 
> public function __unserialize(array $serialized): User
> {
>     $this->id = $serialized['id'];
>     $this->email = $serialized['email'];
>     // .....
>     return $this;
> }

Did work for symfony 5.2, i get this message: Serialization of 'Symfony\Component\HttpFoundation\File\File' is not allowed

**Comment by Dieu-Merci-Kambale** [comment]
WhenI try to submite a form register Users. I see this error

Serialization of 'Symfony\Component\HttpFoundation\File\File' is not allowed


Please help me if you now this error

**Comment by lpredova** [comment]
Got the same error, solution seems to be:

extend user class with \Serializable

```php
class User implements UserInterface, \Serializable
```

And add serialization part:
```php
public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
        ));
    }

    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->email,
            $this->password,
        ) = unserialize($serialized);
    }
```

**Comment by madxmind** [comment]
Hi,

It works with implementation of  \Serializable !

Do I need to put all properties of User entity in serialize() and unserialize() methods ?

Thanks for advance

**Comment by garak** [comment]
> Do I need to put all properties of User entity in serialize() and unserialize() methods ?

You can put only the properties needed to construct the User object.

**Comment by thommyhh** [comment]
The question is, which properties are actually required for making the security system work. It seems the `id`, the username property (`email` in my case) and the password is needed. My implementation looks like this:

```php

    /**
     * Return only the security relevant data
     *
     * @return array
     */
    public function __serialize(): array
    {
        return [
            'id' => $this->id,
            'email' => $this->email,
            'password' => $this->password,
        ];
    }

    /**
     * Restore security relevant data
     *
     * @param array $data
     */
    public function __unserialize(array $data): void
    {
        $this->id = $data['id'];
        $this->email = $data['email'];
        $this->password = $data['password'];
    }
```

I hope, this helps others running into this problem.

**Comment by garak** [comment]
> The question is, which properties are actually required for making the security system work. It seems the `id`, the username property (`email` in my case) and the password is needed.

The security system doesn't need anything but a valid instance. For sure, it doesn't need a password, since the password should be used only when checking the login, and it must be not stored in session.

**Comment by BenhammadiGhassen** [comment]
it work for me with serialize() and unserialize() 
public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
            $this->lastName,
        ));
    }

    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->email,
            $this->password,
            $this->lastName,
        ) = unserialize($serialized);
    }
I hope, this helps others running into this problem

**Comment by Ghassenbenhammadi** [comment]
it work for me with serialize() and unserialize()
public function serialize()
{
return serialize(array(
$this->id,
$this->email,
$this->password,
$this->lastName,
));
}

public function unserialize($serialized)
{
    list(
        $this->id,
        $this->email,
        $this->password,
        $this->lastName,
    ) = unserialize($serialized);
}
I hope, this helps others running into this problem
