### ISSUE TITLE
Bad render with VichImageType in Form

### ISSUE THREAD

**Issue by alacroixAskin** [dustin10/VichUploaderBundle#988]
Hello,

I'm using VichImageType In a Symfony Form. But the image isn't rendered because the link is wrong.

I have this form :

```
protected function configureFormFields(FormMapper $formMapper)
{
        $formMapper->add('presentationImageFile', VichImageType::class,
                    [
                        'label' => 'Image',
                        'required' => false,
                        'download_uri' => true,
                        'imagine_pattern' => 'photocall_presentation',
                    ]);
}
```

Vich configuration :

`
vich_uploader:
    db_driver: orm

    mappings:
    photocall_presentation:
            uri_prefix: /images/photocall/presentation
            upload_destination: '%kernel.project_dir%/public/images/photocall/presentation'
            namer: vich_uploader.namer_origname
`

And in my entity :

```
    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $presentationImage;

    /**
     * @Vich\UploadableField(mapping="photocall_presentation", fileNameProperty="presentationImage")
     * @Assert\Image()
     * @var File
     */
    private $presentationImageFile;
```

The link generated is : 
"https://localhost:8443/media/cache/photocall_presentation/5ca61f6750b11_vienna-reyes-616736-unsplash.jpg"

The correct link should be :
"https://localhost:8443/media/cache/photocall_presentation/images/photocall/presentation/5ca61f6750b11_vienna-reyes-616736-unsplash.jpg"

So it misses the **uri_prefix (/images/photocall/presentation)** from the configuration mapping...

Does anyone already had this issue ?

Thanks in advance for your help

**Comment by garak** [comment]
Did you try to remove `imagine_pattern` option?

**Comment by alacroixAskin** [comment]
Yes, as you can see in the form, there is an option `imagine_pattern`

**Comment by garak** [comment]
I see the option. I'm asking you if you tried without it

**Comment by alacroixAskin** [comment]
Oh sorry, no I didn't tried. I just try and the image is displaying. It doesn't use the cache but no problem.

Thank you for your help garak !
