### ISSUE TITLE
Directory name not found if data is array

### ISSUE THREAD

**Issue by stevro** [dustin10/VichUploaderBundle#989]
|    Q        |   A
|------------ | -----
| Version     | 1.9

### Support Question

I configured the directory name to vich_uploader.namer_directory_property and I'm using a stateless "directoryName" attribute from my entity. This attribute is persisted in the database.

When I want to render the url to the image, and I pass an array not the entity itself I get the following exception:

> An exception has been thrown during the rendering of a template ("Directory name could not be generated: property directoryName does not exist.").

The array contains the "directoryName" key.
If I pass the entity everything works fine.

Any help on this matter is appreciated. Thanks.

The array I'm using
`array:10 [▼
      "id" => 40
      "name" => "81c4e7ba1834a110844c03a4c94a2087706e144b.jpg"
      "size" => 71957
      "directoryName" => "1eaa260fddcc15e3c1f09453b8d5bd92"
      "mimeType" => "image/jpeg"
      "extension" => "jpg"
      "status" => 0
      "isProfileImage" => false
      "position" => 0
      "likesCount" => 0
    ]`

How I'm calling the helper in twig:
`<img src="{{ vich_uploader_asset(image , 'file', 'App\\Entity\\ProfileMedia') }}"/>`

**Comment by garak** [comment]
How can you think that an array could work?

**Comment by stevro** [comment]
The same way it finds the "name" attribute it should find the "directoryName" attribute.

**Comment by garak** [comment]
I can't see any reason to support such use case. Just use entities

**Comment by stevro** [comment]
Entities are expensive to hydrate. If you have an e-commerce with multiple image galleries on same page it can get quickly slow to hydrate entities.

Moreover, you might cache the data in Redis or ApacheLucene, and you will cache only the class,name and directory for each image. It's pointless to hydrate everything again just to display the images.

**Comment by garak** [comment]
Well, I don't know.
The value is retrieved via Symfony PropertyAccess component. With debug enabled, you should be able to seet the related exception, that is passed to bundle's `NameGenerationException`

**Comment by stevro** [comment]
Sorry for bothering you, after a few cache:clear and a composer update it's working. Probably it was something incorrect in the cache.
