### ISSUE TITLE
How cancel removing entity, if remove file is failed?

### ISSUE THREAD

**Issue by nickicool** [dustin10/VichUploaderBundle#994]
Hi!

I need cancel delete entity, if filesystem cant delete file. Similarly, when updating an entity.

Bundle controled `delete_on_remove` and `delete_on_update` behaviors. But how cancel operation, if we cant delete file or update (For example, there are not enough permissions for a file).

**Comment by garak** [comment]
You should never find yourself in such situation. If file can't be deleted, you should throw an exception

**Comment by nickicool** [comment]
Yes it is a non-standard and rare situation which can happen at the wrong configured server. But we have to think about such cases too.

To cancel the deletion of the entity through Doctrine events. For example so:

    class ImageEntityEventListener
    {
        private $filesystem;
    
        public function __construct(Filesystem $filesystem)
        {
            $this->filesystem = $filesystem;
        }
    
        public function preRemove(LifecycleEventArgs $args)
        {
            /** @var $entity Image */
            $entity = $args->getEntity();
            if (!$entity instanceof Image) {
                return;
            }
    
            if (! $this->filesystem->delete($entity->getImageName())) {
                // Cancel removal
                throw new IOException(sprintf('Failed to remove file "%s".', $entity->getImageName()));
            }
        }
    }

But using Doctrine events is additional code. The logic of the control file will be blurred between the Doctrine and VichUploaderBundle. This is wrong. If VichUploaderBundle controls the deletion of a file when an entity is deleted, it should throw an exception.
 
Is it possible to do this by means of the bundle itself?

**Comment by garak** [comment]
The purpose of bundle is not covering 100% of cases, but only providing a common base.
If you need to cover your non-standard super-edge case, you're covered with listeners

**Comment by garak** [comment]
I think that this case is already covered in #756
