### ISSUE TITLE
Switch to local adapter if DEV env

### ISSUE THREAD

**Issue by asuri0n** [dustin10/VichUploaderBundle#995]
|    Q        |   A
|------------ | -----
| Version     | 1.9

### Support Question
Is there any way to switch to a local adapter (knp_gaufrette), if environement is dev and use other adapter (ex. aws s3) if prod ?

**Comment by garak** [comment]
Of course, just use different configurations

**Comment by asuri0n** [comment]
Hum yes but i'm using `@Vich\UploadedField` like that : 
```
/**
   * @var File
   * @Vich\UploadableField(mapping="image", fileNameProperty="imageName", size="imageSize")
   */
  private $imageFile;
```
So i'm always using `image` mappings with AWS S3 adapter.

**Comment by garak** [comment]
You can redefine your mappings in different environments, as any other Symfony configurations.
Configurations are merged.

**Comment by asuri0n** [comment]
Of course ... I feel stupid :D Sorry for the inconveniance
