### ISSUE TITLE
The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "vich_uploader" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.

### ISSUE THREAD

**Issue by romaricp** [dustin10/VichUploaderBundle#999]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.9.0

#### Summary

After updated my Symfony project, I have got this deprecated message : 
`
The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "vich_uploader" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.
`
#### Current behavior

The problem is just here : 

```
#Vich\UploaderBundle\DependencyInjection\Configuration.php L.21

    public function getConfigTreeBuilder(): TreeBuilder
    {
        if (Kernel::VERSION_ID >= 40200) {
            $builder = new TreeBuilder('vich_uploader');
        } else {
            $builder = new TreeBuilder();
        }
        $root = $builder->root('vich_uploader');
        $this->addGeneralSection($root);
        $this->addMetadataSection($root);
        $this->addMappingsSection($root);

        return $builder;
    }
```

#### Expected behavior

Should be : 

```
#Vich\UploaderBundle\DependencyInjection\Configuration.php L.21

    public function getConfigTreeBuilder(): TreeBuilder
    {
        if (Kernel::VERSION_ID >= 40200) {
            $root = new TreeBuilder('vich_uploader');
        } else {
            $builder = new TreeBuilder();
            $root = $builder->root('vich_uploader');
        }
        
        $this->addGeneralSection($root);
        $this->addMetadataSection($root);
        $this->addMappingsSection($root);

        return $builder;
    }
```

**Comment by garak** [comment]
It's fixed in 1.9.1

**Comment by MKalinin1997** [comment]
1.9.1 version of which?

**Comment by garak** [comment]
@MKalinin1997 1.9.1 version of this bundle

**Comment by romaricp** [comment]
@garak are you sure it's ok ? 
Because I have got always this deprecated message : 

![image](https://user-images.githubusercontent.com/2545417/58882752-3ebd5280-86dd-11e9-8147-ba803f8f3456.png)

I'm right now with Symfony 4.3 (last version) with your package : 
```
...
"vich/uploader-bundle": "^1.9.1"
```

**Comment by garak** [comment]
My bad: it's fixed in 1.9.2

**Comment by romaricp** [comment]
Hi, 

Thanks for your reply, but I just try again with v1.9.2 and I have got the same message. 

![image](https://user-images.githubusercontent.com/2545417/58940674-63b3d300-877a-11e9-8537-8471880aaaaa.png)

@garak are you sure it's ok after test for you ? May be, it's due of my config. 
Thx,

**Comment by picks44** [comment]
+1 here, i have the issue and running 1.9.2

**Comment by garak** [comment]
@picks44 try with 1.10@dev

**Comment by romaricp** [comment]
@garak it's good ! 
Thx, can't wait for the new release's tag :)
